Repository hannibal002/SkyHanni, pull requests merged in 2023-09, with the labels that each got.

#464 Feature: gui scaling
  src/main/java/at/hannibal2/skyhanni/config/core/config/Position.java
  src/main/java/at/hannibal2/skyhanni/config/core/config/gui/GuiPositionEditor.kt
  src/main/java/at/hannibal2/skyhanni/config/features/GUIConfig.java
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderLineTooltips.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: New Feature

#461 Fix: One area in the zealot hideout showing as The End
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
Labels: Bug Fix

#469 Fix + Backend: Sack Save
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
Labels: Backend Change, Bug Fix

#420 Fix + Backend: Config migration and also more atomic config saves
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/Features.java
  src/main/java/at/hannibal2/skyhanni/config/features/AshfangConfig.java
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangFreezeCooldown.kt
Labels: Backend Change, Bug Fix

#462 Fix: Rare sea creature detection
  src/main/java/at/hannibal2/skyhanni/features/damageindicator/MobFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/SeaCreatureFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerMiniBossFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
Labels: Bug Fix

#422 Feature: Trevor tracker and other small stuff
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/Storage.java
  src/main/java/at/hannibal2/skyhanni/config/features/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/FrozenTreasureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/CurrentMobArea.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorSolver.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorTracker.kt
Labels: New Feature

#441 Fix + Feature: Fixed inconsistencies with arachne brood highlighting and add countdown for arachne spawn
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/CombatConfig.java
  src/main/java/at/hannibal2/skyhanni/features/mobs/MobHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/mobs/SpawnTimers.kt
Labels: New Feature, Bug Fix

#489 Backend: more efficient implementation of String.removeColor() method (StringUtils.kt:)
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Backend Change

#491 Fix: Crimson Reputation Helper doesn't count trophy fish when sacks exist
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
Labels: Bug Fix

#481 Fix: Dicer error when switching away from dicer during farmer
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
Labels: Bug Fix

#482 Backend: Chat Component and LorenzChatEvent Stuff
  src/main/java/at/hannibal2/skyhanni/events/LorenzChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/Translator.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HighlightBonzoMasks.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/AccessorChatComponentText.java
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/main/resources/mixins.skyhanni.json
Labels: Backend Change

#480 Fix: Compensate for mage ability cooldown reduction while in dungeons
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonData.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbility.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbilityCooldown.kt
Labels: Bug Fix

#429 Feature + Fix: Rich Presence Dynamic Priority Box and Dungeons
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/Storage.java
  src/main/java/at/hannibal2/skyhanni/config/features/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/damageindicator/MobFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonBossHideDamageSplash.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonBossMessages.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonCleanEnd.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHighlightClickedBlocks.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonLividFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbility.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ParticleHider.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: New Feature, Bug Fix

#477 Fix: Improve performance for tooltips and item ability cooldown feature (fixes item cooldown flickering)
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/ToolTooltipTweaks.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbilityCooldown.kt
Labels: Bug Fix

#427 Feature: Armor drops to $/hr
  src/main/java/at/hannibal2/skyhanni/config/features/GardenConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/CropType.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingArmorDrops.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/jsonobjects/ArmorDropsJson.java
Labels: New Feature

#502 hotfix for elias watchdogshelper: prevent accidental roman numeral conversion of skill names
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
Labels: Bug Fix
