Repository hannibal002/SkyHanni, pull requests merged in 2024-04, with the labels that each got.

#1328 Fix: Fixed "Hide Empty Numbers" not hiding empty coop banks (Custom Scoreboard)
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
Labels: Bug Fix - Sooner than Very Soon

#1332 Fix: Fixed "No Power" showing "No" in Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
Labels: Bug Fix - Sooner than Very Soon

#1185 Feature: Open Contest on elitebot.dev
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/JacobFarmingContestConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/FarmingContestAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobFarmingContestsInventory.kt
Labels: Soon

#1315 Improvement: Added support for ct inquisitorchecker
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
Labels: Soon

#1264 Backend: Less fixed rate timer
  CONTRIBUTING.md
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/FixedRateTimerManager.kt
  src/main/java/at/hannibal2/skyhanni/events/SecondPassedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonMilestonesDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/event/jerry/frozentreasure/FrozenTreasureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/winter/JyrreTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
Labels: Soon, Backend

#1322 Backend: Removed Old TimeMark
  src/main/java/at/hannibal2/skyhanni/features/event/anniversary/Year300RaffleEvent.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeMark.kt
Labels: Soon

#1336 Fix: Friend Detection from Chat
  src/main/java/at/hannibal2/skyhanni/data/FriendAPI.kt
Labels: Soon, Bug Fix - Sooner than Very Soon

#1343 Backend: Typo in code
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#1340 Fix: All Names Party Tab
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyCommands.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/tabcomplete/PlayerTabComplete.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
Labels: Soon, Bug Fix - Sooner than Very Soon

#1330 Fix: Farming Fortune Display
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#1342 Fix: Tick event being called twice a tick
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/MinecraftData.kt
  src/main/java/at/hannibal2/skyhanni/events/LorenzTickEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/playerchat/PlayerChatModifier.kt
  src/main/java/at/hannibal2/skyhanni/features/chroma/ChromaShader.kt
  src/main/java/at/hannibal2/skyhanni/features/cosmetics/ArrowTrail.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonDeathCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonLividFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonMilestonesDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinPetWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/ArmorDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropSpeedMeter.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/SprayDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/ChickenHeadTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/KingTalismanHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/TabListReader.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/ShyCruxWarnings.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/motes/ShowMotesNpcSellPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/BlazeSlayerFirePitsWarning.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
Labels: Bug Fix - Sooner than Very Soon

#712 Backend: Mob Detection
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugMobConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.java
  src/main/java/at/hannibal2/skyhanni/data/ClickType.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobData.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDebug.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFactories.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
  src/main/java/at/hannibal2/skyhanni/events/MobEvent.kt
  src/main/java/at/hannibal2/skyhanni/test/command/CopyNearbyEntitiesCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
  src/main/java/at/hannibal2/skyhanni/utils/MobUtils.kt
Labels: Soon, Backend

#1321 Feature: Pest Profit Tracker
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestProfitTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
Labels: Soon

#888 Backend: Renderable advanced Strings
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Soon

#1209 Backend: KuudraAPI
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/events/KuudraCompleteEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/KuudraEnterEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/KuudraAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/CrimsonIsleReputationHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailykuudra/KuudraTier.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/quest/KuudraQuest.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/kuudra/DailyKuudraBossHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon, Backend

#1349 Fix: Hilight -> Highlight
  src/main/java/at/hannibal2/skyhanni/config/features/mining/DeepCavernsParkourConfig.java
Labels: Bug Fix - Sooner than Very Soon

#1348 Backend: code cleanup
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/kuudra/KuudraAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/kuudra/KuudraTier.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/quest/KuudraQuest.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/kuudra/DailyKuudraBossHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon, Backend

#1357 Fix: Pest Tp Delay
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1286 Feature: No Bits Warning
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/Storage.java
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
  src/main/java/at/hannibal2/skyhanni/events/BitsUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/NoBitsWarning.kt
Labels: Soon

#1118 Improvement: Anita and SkyMart highlight
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/ChestValueConfig.java
  src/main/java/at/hannibal2/skyhanni/data/HighlightOnHoverSlot.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/AnitaMedalProfit.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/SkyMartCopperPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/motes/ShowMotesNpcSellPrice.kt
  src/main/java/at/hannibal2/skyhanni/utils/DisplayTableEntry.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Soon

#1299 Backend: error manager only for beta users
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon, Backend

#1353 Backend: matchFirst function for lists of strings
  src/main/java/at/hannibal2/skyhanni/api/CollectionAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/GardenCropMilestones.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/ProfileStorageData.kt
  src/main/java/at/hannibal2/skyhanni/data/PurseAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/winter/UniqueGiftCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenCropMilestoneFix.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenLevelDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterInventoryNumbers.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/FarmingContestAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/GardenInventoryNumbers.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/AuctionsHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/DojoRankDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/MaxPurseItems.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/StatsTuning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarCancelledBuyOrderClipboard.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CurrentPetDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ServerRestartTitle.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/AuctionHouseCopyUnderbidPrice.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Soon, Backend

#1350 Improvement: Use SkyblockArea.skyblockAreaWithSymbol for Custom Scoreboard Area
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPattern.kt
Labels: Soon

#1287 Add: Visitor's Logbook stats
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/LogBookStats.kt
Labels: Soon

#1356 Backend: Add option to copy raw scoreboard
  src/main/java/at/hannibal2/skyhanni/test/command/CopyScoreboardCommand.kt
Labels: Soon, Backend

#1361 Fix: Dojo npe
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFactories.kt
Labels: Bug Fix - Sooner than Very Soon

#1354 Improvement: Add /trade to tab complete commands
  src/main/java/at/hannibal2/skyhanni/features/commands/tabcomplete/PlayerTabComplete.kt
Labels: Soon

#1327 Improvement: Get Magical Power from Maxwell
  src/main/java/at/hannibal2/skyhanni/data/MaxwellAPI.kt
Labels: Soon

#1184 Backend: Use only one inventory close event
  src/main/java/at/hannibal2/skyhanni/data/ItemAddManager.kt
  src/main/java/at/hannibal2/skyhanni/data/OtherInventoryData.kt
  src/main/java/at/hannibal2/skyhanni/data/OwnInventoryData.kt
  src/main/java/at/hannibal2/skyhanni/events/InventoryCloseEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/FarmingContestAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/WildStrawberryDyeNotification.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/LogBookStats.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/PowerStoneGuideFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SkyblockGuideHighlightFeature.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionCollectLogic.kt
Labels: Soon, Backend

#1333 Backend: Improved Scoreboard Line joining with special formatting codes
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
Labels: Soon, Backend

#1362 Fix: Impossible Pest Counts
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1366 Fix: Not showing MP when no power
  src/main/java/at/hannibal2/skyhanni/data/MaxwellAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1363 Improvement: Kills since last inquis
  src/main/java/at/hannibal2/skyhanni/features/event/diana/MythologicalCreatureTracker.kt
Labels: Soon

#1292 Improvement: Cookie Buff Timer
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/utils/SimpleTimeMark.kt
Labels: Soon, Backend

#1367 Fix: M7 Mob Detection
  src/main/java/at/hannibal2/skyhanni/data/mob/MobData.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1359 Improvement: Added support for ct inquisitorchecker (v2)
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
Labels: Soon

#581 Backend: Add feature toggle adapter to automatically turn on features
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/FeatureTogglesByDefaultAdapter.kt
Labels: Soon, Backend

#852 Feature: Shadow Assassin Jump Notification
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/DungeonConfig.java
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonShadowAssassinNotification.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/AccessorWorldBoarderPacket.java
Labels: Soon

#1370 Fix: Bingo Card Row
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardTips.kt
Labels: Bug Fix - Sooner than Very Soon

#1266 Feature: Crystal Hollow Area Walls
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/AreaWallsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsWalls.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon

#1374 Fix: Don't tell player to enter boss room in Entrance
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonCopilot.kt
Labels: Bug Fix - Sooner than Very Soon

#1302 Backend: Mayor Overwrite
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/diana/DianaConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
  src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/Mayors.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropSpeed.kt
Labels: Soon, Backend

#1227 Backend: Change stuff around with chat messages
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/events/LorenzChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/WikiManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
Labels: Soon, Backend

#1178 Feature: Clear plot sprays when Portable Washer is used
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenPlotAPI.kt
Labels: Soon

#1316 Improvement: Allow receiving inquisitor information from all chat
  src/main/java/at/hannibal2/skyhanni/config/features/event/diana/InquisitorSharingConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon

#731 Backend: HolographicEntities
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/AccessorRender.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/AccessorRendererLivingEntity.java
  src/main/java/at/hannibal2/skyhanni/utils/HolographicEntities.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
Labels: Soon, Backend

#822 Backend: Renderable table
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
Labels: Soon, Backend

#1371 Backend: Remove a lot of deprecated code
  src/main/java/at/hannibal2/skyhanni/data/QuiverAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/SacksJson.java
  src/main/java/at/hannibal2/skyhanni/events/SecondPassedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/WikiManager.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishFillet.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FortuneUpgrade.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FortuneUpgrades.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/UpgradePage.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbility.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/InGameDateDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/stillgorechateau/RiftBloodEffigies.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/EnigmaSoulWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/RiftTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerBossSpawnSoon.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerRngMeterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/TestCopyRngMeterValues.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/NumberUtil.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
Labels: Soon, Backend

#1318 Backend: Renderable Vertical Container
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Soon, Backend

#1380 Backend: Sack Display Cleanup
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
Labels: Soon, Backend

#1377 Fix: Fixed Objective Lines never being shown in Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
Labels: Bug Fix - Sooner than Very Soon

#1379 Improvement: Mob Detection logEvents to file
  src/main/java/at/hannibal2/skyhanni/data/mob/MobData.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDebug.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
Labels: Soon, Backend

#1383 Add hud element config links.
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/core/config/Position.java
  src/main/java/at/hannibal2/skyhanni/config/core/config/gui/GuiPositionEditor.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/composter/ComposterConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/SprayConfig.java
  src/main/java/at/hannibal2/skyhanni/events/LorenzEvent.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Waiting on Dependency PR

#1394 Fix: Fixed Double Objective in Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#1390 Fix/Backend: Renderable.itemStack itemScale
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/SkyMartConfig.java
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/AnitaMedalProfit.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/SkyMartCopperPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/motes/ShowMotesNpcSellPrice.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Bug Fix - Sooner than Very Soon

#1387 Fix: Duplicate Custom Keybinds
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCustomKeybinds.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1389 Fix: Fixed Crystal Hollows Island size
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
Labels: Bug Fix - Sooner than Very Soon

#1386 Fix: Pest Count Issues v2
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1395 Improvement: Add @ConfigLink to many garden guis
  src/main/java/at/hannibal2/skyhanni/config/features/garden/ArmorDropTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/EliteFarmingWeightConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/FarmingFortuneConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenLevelConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/MoneyPerHourConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/NextJacobContestConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/cropmilestones/CropMilestonesConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/cropmilestones/NextConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/optimalspeed/OptimalSpeedConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestTimerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/TimerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/GUIConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/CustomScoreboardConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/pets/PetConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
Labels: Soon

#1411 Bump Moulconfig
  gradle/libs.versions.toml
Labels: Bug Fix - Sooner than Very Soon

#1392 Updated /ff
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFGuideGUI.kt
Labels: Soon

#1384 Improvement: Mark Museum donated items as unsalvageable
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
Labels: Soon

#1413 Fix: Item Scale in Skill Progress Display
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
Labels: Bug Fix - Sooner than Very Soon

#1131 Improvement + Fix: Added atmospheric display + fixed typo
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/enums/OutsideSbFeature.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/AtmosphericFilterDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/AtmosphericFilterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobContestTimeNeeded.kt
Labels: Soon

#1414 Fix: Fixed Powder not being shown in the Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#1378 Backend: Switch from LorenzUtils.inDungeons to DungeonAPI.inDungeon()
  src/main/java/at/hannibal2/skyhanni/data/MaxwellAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/ArrowTypeJson.java
  src/main/java/at/hannibal2/skyhanni/features/chat/PlayerDeathMessages.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/MobFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonBossHideDamageSplash.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonBossMessages.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonCleanEnd.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonCopilot.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonDeathCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHideItems.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHighlightClickedBlocks.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonLividFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonMilestonesDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonRankTabListColor.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonShadowAssassinNotification.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonTeammateOutlines.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/HighlightDungeonDeathmite.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/TerracottaPhase.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/ReminderUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/SeaCreatureFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvents.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbility.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/NonGodPotEffectDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ParticleHider.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/PartyMemberOutlines.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/AdvancedPlayerList.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerMiniBossFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/JsonUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon, Backend

#890 Backend: Renderable.renderInsideRoundedRect
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Soon

#1416 Add: New Gemstones to ModifierUtils
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
Labels: Soon

#1418 Fix: Crystall Hollows Area Walls wrong offset
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsWalls.kt
Labels: Bug Fix - Sooner than Very Soon

#1324 Feature: Stereo Harmony Display
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/StereoHarmonyConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestType.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/StereoHarmonyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/VinylType.kt
Labels: Soon

#1423 Fix: Color Code escape in getGemstones()'s debug messages
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1427 Feature: Fossil Excavator
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/FossilExcavatorConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsWalls.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/FossilExcavator.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/FossilExcavatorSolver.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/FossilMutation.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/FossilShape.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/FossilTile.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/FossilType.kt
Labels: Soon

#1431 Backend: Fossil Excavator API
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/FossilExcavatorAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilExcavator.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilExcavatorSolver.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilMutation.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilShape.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilTile.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilType.kt
Labels: Soon, Backend

#1421 Fix: Clear SkyBlock area on world change
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/easter/EasterEggWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1425 Fix + Improvement: No Bits Warning
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/NoBitsWarningConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
  src/main/java/at/hannibal2/skyhanni/events/BitsUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/NoBitsWarning.kt
Labels: Bug Fix - Sooner than Very Soon

#1422 Improvement: Discord Rich Presence Glacite Tunnels
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordLocationKey.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
Labels: Soon

#1308 Backend: Update farming weight api links and format
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/EliteBotJson.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestType.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Soon, Backend

#1191 Backend: Remove Neu Constant
  .github/workflows/illegal-imports.txt
  src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/NeuRNGScore.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/NeuReforgeStoneJson.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/NeuSacksJson.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/NeuSkillLevelJson.kt
  src/main/java/at/hannibal2/skyhanni/events/NeuRepositoryReloadEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillUtil.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerRngMeterDisplay.kt
Labels: Merge Conflicts, Soon, Backend

#1433 Add party chat commands
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/PartyCommandsConfig.java
  src/main/java/at/hannibal2/skyhanni/data/PartyAPI.kt
  src/main/java/at/hannibal2/skyhanni/events/PartyChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyChatCommands.kt
Labels: Soon

#1429 Feature: Mining Notifications
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningNotificationsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/mining/MiningNotifications.kt
Labels: Soon

#1213 Improvement: More pet drop messages
  src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
Labels: Soon

#1432 New Feature: Excavation Profit Tracker
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/ExcavatorProfitTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/FossilExcavatorConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/FossilExcavatorSolverConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/events/mining/FossilExcavationEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/FossilExcavatorAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilMutation.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilShape.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilSolver.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilSolverDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilTile.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilType.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
Labels: Soon

#1430 Improvements: Hide non clickable items mining v3
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
Labels: Soon

#1420 Improvement: Added More Mining v3 content to Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvents.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Soon

#1436 Fix: Item Size in Crop Milestones GUI
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
Labels: Bug Fix - Sooner than Very Soon

#1391 Improvement: Enchanted Book Bundle Name
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Soon

#1446 Fix skill issue
  build.gradle.kts
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinXPInformation.java
  src/main/java/at/hannibal2/skyhanni/utils/CombatUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1445 Improvement: Code cleanup, bug fix and new functions
  src/main/java/at/hannibal2/skyhanni/data/ChatClickActionManager.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/AtmosphericFilterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/DelayedRun.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
  src/main/java/at/hannibal2/skyhanni/utils/MinecraftConsoleFilter.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyblockSeason.kt
Labels: Bug Fix - Sooner than Very Soon

#1449 Fix: Fixed Totem of Corruption Overlay not getting cleared on disable
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/TotemOfCorruptionConfig.java
  src/main/java/at/hannibal2/skyhanni/features/fishing/TotemOfCorruption.kt
Labels: Bug Fix - Sooner than Very Soon

#1450 Fix: Fixed Fame Rankup not updating the rank
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1381 Improvement: Sack Display Update
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/SackDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
Labels: Soon, Backend

#1439 New Feature: Profit Per Excavation
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/FossilExcavatorConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/FossilExcavatorAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ProfitPerExcavation.kt
Labels: Soon

#1426 Backend: Adding Hypixel Mod API v0.1.6
  build.gradle.kts
Labels: Soon, Backend

#1428 Improvementt: Add Dungeon Room Id to Lobby Code
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
Labels: Soon

#1412 Improvement: Add all remaining config links
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/features/combat/QuiverDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/crimsonisle/ReputationHelperConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/bingo/BingoCardConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/bingo/BingoConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/StereoHarmonyConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/ChestValueConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/SackDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/skillprogress/SkillProgressConfig.java
Labels: Soon

#1405 Backend: isKeyClicked
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
Labels: Soon, Backend

#1373 Improvement: Added Linebreaks functionality for Custom Scoreboard Title/Footer
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/TitleAndFooterConfig.java
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
Labels: Soon

#1407 Backend: MultiClickable
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Soon, Backend

#1453 Improvement: Add Fortunate Freezing Bonus to Mining Events in Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvents.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Soon

#1452 Fix: Bazaar Copy null
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarCancelledBuyOrderClipboard.kt
Labels: Bug Fix - Sooner than Very Soon

#1451 Improvement: Farming Fortune Display
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
Labels: Soon

#1347 Feature: Different color for Zealots holding Chests
  src/main/java/at/hannibal2/skyhanni/config/features/combat/MobsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/MobHighlight.kt
Labels: Soon

#1455 Backend: Crash in dev env for @ConfigLink
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
Labels: Soon, Backend

#1457 Feature: Vermin Highlight
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/westvillage/VerminHighlightConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/westvillage/WestVillageConfig.java
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminHighlighter.kt
Labels: Soon

#1458 Feature: Glacite Powder as stack size in Fossil Excavator
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/FossilExcavatorConfig.java
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/GlacitePowderFeatures.kt
Labels: Soon

#1466 Feature: Highlight own Golden/Diamond Goblin
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/GoldenGoblinHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/MiningNotifications.kt
Labels: Soon

#1459 Improvement: Match Kat order in Vermin Tracker
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminTracker.kt
Labels: Soon

#1388 FIx: Pest Profit Tracker Items
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
Labels: Bug Fix - Sooner than Very Soon

#1468 Fix: Gemstones item query
  src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemNameResolver.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1465 Fix: Stop rendering an empty string on every item
  src/main/java/at/hannibal2/skyhanni/events/RenderItemTipEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#1462 Fix: Catch correct error type on alpha 27
  src/main/java/at/hannibal2/skyhanni/utils/CombatUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1406 Fix: Pest Count (again)
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1355 Backend: Make TablistFooterUpdateEvent and cleanup TabListData
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/events/TablistFooterUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/TabListReader.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/TabListRenderer.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
Labels: Soon, Backend

#1173 Feature: Visitor Super Craft
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/ShoppingListConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorSupercraft.kt
Labels: Soon

#1438 Feature: Cold Overlay
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/ColdOverlayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
  src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
  src/main/java/at/hannibal2/skyhanni/events/ColdUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/RenderBackground.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/ColdOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/MiningNotifications.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/resources/assets/skyhanni/cold_overlay.png
Labels: Soon

#1478 Fix: hotkey name crash in vistior
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorRewardWarning.kt
Labels: Bug Fix - Sooner than Very Soon

#1476 Improvement: Patcher Coords Color and Duration
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/PatcherCoordsWaypointConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/PatcherSendCoordinates.kt
Labels: Soon

#1481 Fix: NPE in visitor reward warning
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorRewardWarning.kt
Labels: Bug Fix - Sooner than Very Soon

#1474 FIx: bazaar cancelled buy order v2
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarCancelledBuyOrderClipboard.kt
Labels: Bug Fix - Sooner than Very Soon

#1475 Fix: Shift click visitor buttons
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorRewardWarning.kt
Labels: Bug Fix - Sooner than Very Soon

#1487 Feature: Bits Gained Chat Message
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/BitsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/NoBitsWarningConfig.java
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/NoBitsWarning.kt
Labels: Soon

#1479 Improvelemt: RNG Meter slayer menu reading
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerRngMeterDisplay.kt
Labels: Soon

#1485 Cleanup
  src/main/java/at/hannibal2/skyhanni/config/core/config/gui/GuiPositionEditor.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/PlotMenuHighlightingConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/RewardWarningConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningNotificationsConfig.java
  src/main/java/at/hannibal2/skyhanni/data/ClickType.kt
  src/main/java/at/hannibal2/skyhanni/data/FriendAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/PurseAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/QuiverAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobData.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
  src/main/java/at/hannibal2/skyhanni/events/GuiContainerEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/PacketEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/mining/FossilExcavationEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/easter/EasterEggWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/easter/EggEntrances.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/TotemOfCorruption.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/OdgerWaypoint.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenCropMilestoneFix.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenPlotAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/SensitivityReducer.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFGuideGUI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFTypes.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FarmingItems.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestSpawn.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/StereoHarmonyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorSupercraft.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorListener.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorRewardWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MovementSpeedDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/AdvancedPlayerList.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/limbo/LimboTimeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/teleportpad/TeleportPadCompactName.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/VisualWordGui.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/SulphurSkitterBox.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/AccessorRendererLivingEntity.java
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ConfigUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/HolographicEntities.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
  src/main/java/at/hannibal2/skyhanni/utils/NumberUtil.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Backend

#1488 Fix: Fix pet error with discord rich presence
  src/main/java/at/hannibal2/skyhanni/data/PetAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1434 Feature: Stuff for chocolate factory and hoppity event
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/EventConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/HoppityEggLocationsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/event/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/chocolatefactory/ChocolateFactoryBarnManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/chocolatefactory/ChocolateFactoryInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/event/chocolatefactory/ChocolateFactoryStats.kt
  src/main/java/at/hannibal2/skyhanni/features/event/chocolatefactory/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/chocolatefactory/HoppityEggType.kt
  src/main/java/at/hannibal2/skyhanni/features/event/chocolatefactory/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/chocolatefactory/HoppityEggsShared.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
Labels: Soon

#1483 Feature + Fix: Player Chat Rework
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatSymbols.java
  src/main/java/at/hannibal2/skyhanni/config/features/chat/PlayerMessagesConfig.java
  src/main/java/at/hannibal2/skyhanni/data/PartyAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerNameFormatter.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/event/AbstractChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/event/GuildChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/event/NpcChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/event/PartyChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/event/PlayerAllChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/event/PlayerShowItemChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/event/PrivateMessageChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/event/SystemMessageEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/PartyChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/BingoAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/Translator.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/playerchat/PlayerChatModifier.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyChatCommands.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MarkedPlayerManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/PlayerChatSymbols.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/AdvancedPlayerList.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/TabListReader.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Soon

#1491 Fix: Memory leak in ItemRenderBackground
  src/main/java/at/hannibal2/skyhanni/data/ItemRenderBackground.kt
Labels: Bug Fix - Sooner than Very Soon

#1490 Fix: paleontologist in fossil excavator
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/FossilExcavatorAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1456 Backend: Add unimined build system
  .gitignore
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/AutoMixinDiscovery.kt
  buildSrc/src/EnvFile.kt
  gradle.properties
  gradle/libs.versions.toml
  log4j2.xml
  settings.gradle.kts
  src/main/java/at/hannibal2/skyhanni/mixins/init/SkyhanniMixinPlugin.java
  src/main/java/at/hannibal2/skyhanni/utils/MinecraftConsoleFilter.kt
Labels: Soon

#1494 Fix: Rift NPC shops not using Motes
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
Labels: Bug Fix - Sooner than Very Soon

#1493 [Feature] Added support for calculations in gfs
  src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
Labels: Soon

#1489 Backend: Display in-world the locations of sounds for TrackSoundsCommand
  src/main/java/at/hannibal2/skyhanni/test/command/TrackSoundsCommand.kt
Labels: Soon

#1498 Fix: No more jline
  .github/workflows/illegal-imports.txt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
Labels: Bug Fix - Sooner than Very Soon

#1509 Fix: Visitor Reward Spelling
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/RewardWarningConfig.java
Labels: Bug Fix - Sooner than Very Soon

#1507 Fix: Pet Rarity Message
  src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
Labels: Bug Fix - Sooner than Very Soon

#1503 Fix: Fixed Bits Gained Chat Messages randomly being send
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
  src/main/java/at/hannibal2/skyhanni/events/BitsUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/NoBitsWarning.kt
Labels: Bug Fix - Sooner than Very Soon

#1495 Fix: Wierd default Armorstand value
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
  src/main/java/at/hannibal2/skyhanni/utils/MobUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1499 Fix: Use recalculating value for all egglocator
  src/main/java/at/hannibal2/skyhanni/features/event/chocolatefactory/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/chocolatefactory/HoppityEggsManager.kt
Labels: Soon, Backend

#1512 Add component regex matcher API
  src/main/java/at/hannibal2/skyhanni/utils/ComponentMatcherUtils.kt
  src/test/java/at/hannibal2/skyhanni/test/ComponentSpanTest.kt
Labels: Soon

#1501 Add percent to hoppity display
  src/main/java/at/hannibal2/skyhanni/features/event/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/chocolatefactory/ChocolateFactoryStats.kt
Labels: Soon

#1519 Backend: Add ContributorManager
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/compacttablist/AdvancedPlayerListConfig.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/ContributorListJson.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/ContributorsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ContributorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/AdvancedPlayerList.kt
Labels: Soon

#1520 Fix: Maxwell Power not updating when unlocking a new Power
  src/main/java/at/hannibal2/skyhanni/data/MaxwellAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1496 Fix: f7 bosses in Mob Detection
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
Labels: Bug Fix - Sooner than Very Soon

#1197 Feature: Architect Notifications when puzzle fails
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/DungeonConfig.java
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonArchitectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonCopilot.kt
Labels: Soon

#1505 Fixed transfer command
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/event/PartyChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyChatCommands.kt
Labels: Bug Fix - Sooner than Very Soon

#1369 Improvement: Infested Plots Display Customization
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestFinderConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestFinder.kt
Labels: Soon

#1331 Backend: Tooltip Event without forge
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/data/ToolTipData.kt
  src/main/java/at/hannibal2/skyhanni/events/LorenzToolTipEvent.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinItemStack.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiContainer.java
Labels: Soon

#1523 Add Funny
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/ContributorsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ContributorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/AdvancedPlayerList.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/RendererLivingEntityHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinContributorRendererEntityLiving.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinRendererLivingEntityHookSBA.java
Labels: Soon

#1464 Feature: Allow party members to request allinvite to be enabled
  src/main/java/at/hannibal2/skyhanni/config/features/misc/PartyCommandsConfig.java
  src/main/java/at/hannibal2/skyhanni/data/PartyAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyChatCommands.kt
Labels: Soon

#1528 Fix: gfs error with 0
  src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
  src/main/java/at/hannibal2/skyhanni/utils/NumberUtil.kt
Labels: Bug Fix - Sooner than Very Soon
