Repository hannibal002/SkyHanni, pull requests merged in 2024-06, with the labels that each got.

#1969 Fix: Bumped Custom Scoreboard Error Time to 2 seconds
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
Labels: Bug Fix - Sooner than Very Soon

#1967 Fix: Skymall Titanium Pattern
  src/main/java/at/hannibal2/skyhanni/api/HotmAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1970 Change: getByNameOrNull using simpleName of Crop
  src/main/java/at/hannibal2/skyhanni/features/garden/CropType.kt
Labels: Bug Fix - Sooner than Very Soon

#1913 Improvement + Fix: Sound for special stray rabbit
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryRabbitWarningConfig.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/HoppityEggLocationsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
Labels: Bug Fix - Sooner than Very Soon

#1962 Feature: Hide Useless Armorstands
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/FixGhostEntities.kt
Labels: Soon

#1955 Fix: Estimated item value not working in pv
  src/main/java/at/hannibal2/skyhanni/data/ToolTipData.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinItemStack.java
Labels: Bug Fix - Sooner than Very Soon

#1965 Fix: Movable hotbar messing with some other mods
  src/main/java/at/hannibal2/skyhanni/features/gui/MovableHotBar.kt
Labels: Bug Fix - Sooner than Very Soon

#1973 Fix: Gui editor opening when not intended to
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
Labels: Bug Fix - Sooner than Very Soon

#1500 Feature: Glacite Mineshafts QOL
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/CorpseLocatorConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/GlaciteMineshaftConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MineshaftWaypointsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
  src/main/java/at/hannibal2/skyhanni/events/mining/CorpseLootedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/MineshaftWaypoint.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/MineshaftWaypointType.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/MineshaftWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/mineshaft/CorpseAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/mineshaft/CorpseType.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
Labels: Soon

#1971 Improvement: Move all SkyMall message hiding to the same toggle
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Soon

#1735 Improvement: Compact Dicer Tracker
  src/main/java/at/hannibal2/skyhanni/config/features/garden/DicerRngDropTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/DicerRngDropTracker.kt
Labels: Soon

#1733 Backend: RepoPattern Exclusive Group & RepoPattern List
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/CommonPatternInfo.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPattern.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternExclusiveGroup.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternExclusiveGroupInfo.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternGroup.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternGui.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternImpl.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternKeyOwner.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternList.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternListImpl.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
  src/main/resources/assets/skyhanni/gui/regexes.xml
  src/test/java/at/hannibal2/skyhanni/test/RepoPatternTest.kt
Labels: Soon, Backend

#1824 Backend: Keep visual formatting appearance with CharSequence.removeColor(keepFormatting=true)
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/test/java/at/hannibal2/skyhanni/test/RemoveColorTest.kt
Labels: Soon, Backend

#1904 Backend: Auto load annotation
  CONTRIBUTING.md
  annotation-processors/build.gradle.kts
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProcessor.kt
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProvider.kt
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/SkyHanniModule.kt
  annotation-processors/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
  build.gradle.kts
  gradle.properties
  settings.gradle.kts
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
Labels: Soon, Backend

#1901 Feature: Beacon Power Display
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/GUIConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/gui/BeaconPower.kt
Labels: Soon

#1975 Fix: wrong api name conversion for Fish the Rabbit
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionData.kt
Labels: Bug Fix - Sooner than Very Soon

#1976 Fix: Visitor Drop Statistics new data
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
Labels: Bug Fix - Sooner than Very Soon

#1687 Improvement: Contributor nametag
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.java
  src/main/java/at/hannibal2/skyhanni/data/EntityData.kt
  src/main/java/at/hannibal2/skyhanni/events/entity/EntityDisplayNameEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ContributorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/AdvancedPlayerList.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntity.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntityPlayer.java
Labels: Soon

#1980 Fix: No longer hide boss bars by accident
  src/main/java/at/hannibal2/skyhanni/features/misc/HideFarEntities.kt
Labels: Bug Fix - Sooner than Very Soon

#1977 Improvement: Faction Quest Widget is disabled
  src/main/java/at/hannibal2/skyhanni/config/features/crimsonisle/ReputationHelperConfig.java
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/CrimsonIsleReputationHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/QuestLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/kuudra/DailyKuudraBossHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/miniboss/DailyMiniBossHelper.kt
Labels: Soon

#1150 Backend: Widget abstractions
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
  src/main/java/at/hannibal2/skyhanni/events/WidgetUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
Labels: Soon, Backend

#1972 Improvement: import egg locations from NEU PV
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/HypixelPlayerApiJson.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/HoppityEggLocationsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocations.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsShared.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityUniqueEggLocations.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
Labels: Soon

#1979 Fix: Config resetting on wrong value
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/bazaar/HypixelBazaarFetcher.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/local/HotmTree.kt
  src/main/java/at/hannibal2/skyhanni/data/model/Graph.kt
  src/main/java/at/hannibal2/skyhanni/events/NeuRepositoryReloadEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarDataHolder.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
  src/main/java/at/hannibal2/skyhanni/test/TestExportTools.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/BaseGsonBuilder.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/FeatureTogglesByDefaultAdapter.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/ItemStackTypeAdapter.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/JsonUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/NBTTypeAdapter.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SimpleStringTypeAdapter.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkippingTypeAdapterFactory.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkyHanniTypeAdapters.kt
Labels: Bug Fix - Sooner than Very Soon

#1994 Fix: Area Walls in Nucleus
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsWalls.kt
Labels: Bug Fix - Sooner than Very Soon

#1985 Fix: Sea Creature Warning
  src/main/java/at/hannibal2/skyhanni/features/fishing/SeaCreatureFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeLimitedCache.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeLimitedSet.kt
Labels: Bug Fix - Sooner than Very Soon

#1990 Fix: Config reset on unknown enum values
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/BaseGsonBuilder.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/EnumSkippingTypeAdapterFactory.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkippingTypeAdapterFactory.kt
Labels: Bug Fix - Sooner than Very Soon

#2003 (Technical) Improvement: Add Perkapocolypse Mayor to MayorAPI
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/MayorConfig.java
  src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/Mayors.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockTime.kt
Labels: Soon

#873 Improvement: Refactor of /ff for Improved Modularity and Code Reusability
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/commands/tabcomplete/TabComplete.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/CropType.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CarrolynTable.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFGuideGUI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFInfos.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FarmingItems.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FarmingReforges.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FortuneStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FortuneUpgrade.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FortuneUpgrades.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/CropPage.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/OverviewPage.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/UpgradePage.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/guide/GuideGUI.kt
  src/main/java/at/hannibal2/skyhanni/utils/guide/GuidePage.kt
  src/main/java/at/hannibal2/skyhanni/utils/guide/GuideRenderablePage.kt
  src/main/java/at/hannibal2/skyhanni/utils/guide/GuideScrollPage.kt
  src/main/java/at/hannibal2/skyhanni/utils/guide/GuideTab.kt
  src/main/java/at/hannibal2/skyhanni/utils/guide/GuideTablePage.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
Labels: Soon

#1899 Backend: More second passed
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/data/QuiverAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/AllBurrowsList.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/easter/EasterEggWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/halloween/BasketWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/event/spook/TheGreatSpook.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/tiarelay/TiaRelayHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/HighlightMiningCommissionMobs.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MarkedPlayerManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/NonGodPotEffectDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangBlazes.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangHideParticles.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
Labels: Soon, Backend

#2002 Feature: Favorite Power Stones
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/data/MaxwellAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/FavoritePowerStone.kt
Labels: Soon

#1956 Backend: Remove deprecated function: getMultiplier
  src/main/java/at/hannibal2/skyhanni/api/CollectionAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/MinionCraftHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenCropMilestoneFix.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenCropTimeCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenCropsInCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionCollectLogic.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Soon, Backend

#1987 Backend: Remove deprecated BazaarData values
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarBestSellMethod.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarData.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarOrderHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon, Backend

#2020 Improvement: Attribute Prices in Estimated Item Value
  src/main/java/at/hannibal2/skyhanni/features/inventory/AuctionsHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedWardrobePrice.kt
Labels: Bug Fix - Sooner than Very Soon

#2018 Fix: Some stuff in garden tooltips not showing
  src/main/java/at/hannibal2/skyhanni/events/item/ItemHoverEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorListener.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinItemStack.java
Labels: Bug Fix - Sooner than Very Soon

#1999 Backend/Fix : "Removed" HypixelCommands.getFromSack
  src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonArchitectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/PabloHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
Labels: Bug Fix - Sooner than Very Soon

#2019 Fix: Non Craftable Items breaking the Visitor Shopping List
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#2008 Backend: Custom event bus
  .live-plugins/event/plugin.kts
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/api/FmlEventApi.kt
  src/main/java/at/hannibal2/skyhanni/api/event/CancellableSkyHanniEvent.kt
  src/main/java/at/hannibal2/skyhanni/api/event/EventHandler.kt
  src/main/java/at/hannibal2/skyhanni/api/event/GenericSkyHanniEvent.kt
  src/main/java/at/hannibal2/skyhanni/api/event/HandleEvent.kt
  src/main/java/at/hannibal2/skyhanni/api/event/SkyHanniEvent.kt
  src/main/java/at/hannibal2/skyhanni/api/event/SkyHanniEvents.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandType.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/DisabledEventsJson.kt
  src/main/java/at/hannibal2/skyhanni/events/entity/EntityEnterWorldEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/UniqueGiftingOpportunitiesFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingHookDisplay.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
Labels: Soon, Backend

#2023 Backend: Start using new event system
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/api/FmlEventApi.kt
  src/main/java/at/hannibal2/skyhanni/data/GuiData.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/ToolTipData.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
  src/main/java/at/hannibal2/skyhanni/events/PreInitFinishedEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/bingo/BingoCardUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/bingo/BingoGoalReachedEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/diana/InquisitorFoundEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/farming/FarmingLaneSwitchEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/fishing/TrophyFishCaughtEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/garden/farming/FarmingLaneSwitchEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/garden/pests/PestSpawnEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/garden/pests/PestUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/item/ItemHoverEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/minecraft/ClientDisconnectEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/utils/PreInitFinishedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardReader.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/HighlightInquisitors.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishMessages.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleWaypoint.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestSpawn.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestSpawnTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorListener.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordRPCManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
Labels: Backend

#2007 Fix: Account Upgrade Reminders with simultaneous profile and account upgrades
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/PlayerSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/fame/AccountUpgradeReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/UpgradeReminder.kt
Labels: Bug Fix - Sooner than Very Soon

#2024 Backend: Make build fail on wrong annotation
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProcessor.kt
Labels: Bug Fix - Sooner than Very Soon

#2025 Backend: Packet Events
  src/main/java/at/hannibal2/skyhanni/data/BlockData.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/EntityData.kt
  src/main/java/at/hannibal2/skyhanni/data/ItemClickData.kt
  src/main/java/at/hannibal2/skyhanni/data/MinecraftData.kt
  src/main/java/at/hannibal2/skyhanni/data/OtherInventoryData.kt
  src/main/java/at/hannibal2/skyhanni/data/OwnInventoryData.kt
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
  src/main/java/at/hannibal2/skyhanni/data/TitleData.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
  src/main/java/at/hannibal2/skyhanni/events/PacketEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/minecraft/packet/PacketReceivedEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/minecraft/packet/PacketSentEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/ArachneSpawnTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonShadowAssassinNotification.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowParticleFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleWaypoint.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/HighlightVisitorsOutsideOfGarden.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorListener.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/FixGhostEntities.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/NonGodPotEffectDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/TpsCounter.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/NetHandlerPlayClientHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/NetworkManagerHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinNetHandlerPlayClient.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinNetworkManager.java
  src/main/java/at/hannibal2/skyhanni/test/PacketTest.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
Labels: Soon

#2027 Backend: Typos
  .idea/dictionaries/default_user.xml
  docs/CHANGELOG.md
  docs/FEATURES.md
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
Labels: Soon, Backend

#1997 Feature: Add location rabbit requirement tracker
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocations.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
Labels: Soon

#2029 Fix: Consider Y=64 part of Magma Fields
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsWalls.kt
Labels: Bug Fix - Sooner than Very Soon

#2034 Fix: FF cake time
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/OverviewPage.kt
Labels: Bug Fix - Sooner than Very Soon

#2009 Feature: Add Reminder to open Calendar for Temp Mayor
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
Labels: Soon

#2030 Feature: Skymart Copper Price Bazaar Options
  src/main/java/at/hannibal2/skyhanni/config/features/garden/SkyMartConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/SkyMartCopperPrice.kt
Labels: Soon

#2026 Feature: Compact Chat for Garden Visitor Reward Summary
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/VisitorConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorCompactChat.kt
Labels: Soon

#2043 Fix: chum bucket cache
  src/main/java/at/hannibal2/skyhanni/utils/TimeLimitedSet.kt
Labels: Bug Fix - Sooner than Very Soon

#1996 Backend: Add automated style checking
  .editorconfig
  .github/workflows/check-style.yaml
Labels: Soon, Backend

#2011 Backend: Dev Modules
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProcessor.kt
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/SkyHanniModule.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/events/LorenzEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/MessageSendToServerEvent.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/ReflectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/system/PlatformUtils.kt
Labels: Soon, Backend

#1978 Feature: Add chocolate production time for stray rabbits
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTooltipStray.kt
Labels: Soon

#2044 Backend: Change editor config a bit
  .editorconfig
Labels: Soon, Backend

#2039 Feature: Custom Wardrobe
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/customwardrobe/ColorConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/customwardrobe/CustomWardrobeConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/customwardrobe/SpacingConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/EstimatedWardrobePrice.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/WardrobeAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/WardrobeSlot.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedWardrobePrice.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiContainerHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/AccessorGuiContainer.java
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableTooltips.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
Labels: Soon

#2045 Fix: Perkapocalypse Max Time
  src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1454 Backend: Graph Editor
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevToolConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/dev/GraphConfig.java
  src/main/java/at/hannibal2/skyhanni/data/model/Graph.kt
  src/main/java/at/hannibal2/skyhanni/data/model/TextInput.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigFeatures.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinKeyBinding.java
  src/main/java/at/hannibal2/skyhanni/test/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/test/GriffinUtils.kt
  src/main/java/at/hannibal2/skyhanni/test/ParkourWaypointSaver.kt
  src/main/java/at/hannibal2/skyhanni/utils/ConditionalUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Soon, Backend

#2051 Backend: Change editor config
  .editorconfig
Labels: Soon, Backend

#2060 Fix: Chat formatting categorising stash pickup messages as private chat
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerChatManager.kt
Labels: Bug Fix - Sooner than Very Soon

#2052 Fix: Custom Wardrobe Color
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
Labels: Bug Fix - Sooner than Very Soon

#2058 Fix: Anniversary Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvents.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1861 Fix: FF rework
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFGuideGUI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFInfos.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFTypes.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/CropPage.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/OverviewPage.kt
Labels: Bug Fix - Sooner than Very Soon

#2053 Fix: Scrollables infinitly scrolling
  src/main/java/at/hannibal2/skyhanni/utils/renderables/ScrollInput.kt
Labels: Bug Fix - Sooner than Very Soon

#2062 Backend: Fixed wardrobe not using tooltip event
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#2065 Fix: No MP Message
  src/main/java/at/hannibal2/skyhanni/data/MaxwellAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1995 Improvement: Add Carnival (Alpha) Stuff to Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvents.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Soon

#2064 Improvement: Better Hypixel detection
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
Labels: Soon

#2033 Use EnumMap and fields for config
  .gitignore
  .idea/scopes/Mixins.xml
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/core/config/Position.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinBlockFire.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntityBlaze.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntityEnderman.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntityFireball.java
Labels: Soon

#1930 Backend: No more GriffinUtils, move drawWaypointFilled to RenderUtils
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonLividFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/christmas/PresentWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/easter/EasterEggWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/halloween/BasketWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/ThunderSparksHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/OdgerWaypoint.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenStartLocation.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneCreator.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleLine.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleWaypoint.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/tiarelay/TiaRelayWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/MineshaftWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/JoinCrystalHollows.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/PatcherSendCoordinates.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangBlazingSouls.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/kuudra/DailyKuudraBossHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/miniboss/DailyMiniBossHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveDefenseBlocks.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveLivingMetalHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/stillgorechateau/RiftBloodEffigies.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/kloon/KloonHacking.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/EnigmaSoulWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/motes/RiftMotesOrb.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/enderman/EndermanSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/test/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/test/GriffinUtils.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon, Backend

#2066 Fix: isKeyHeld crash
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
Labels: Bug Fix - Sooner than Very Soon

#2070 Fix: ConcurrentModificationException in EnchantParser in CustomWardrobe
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
Labels: Bug Fix - Sooner than Very Soon

#2074 Fix: Fixed enchant parsing causing errors in custom wardrobe
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
Labels: Bug Fix - Sooner than Very Soon

#2057 Fix: Prefixes being incorrectly stripped from non-Kuudra armor items
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Bug Fix - Sooner than Very Soon

#2068 Future Fix: CustomeScoreboard UnkownLinesHandler auto adds patterns from the repo
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Bug Fix - Sooner than Very Soon

#2071 Fix: Stranded Placable NPCs
  src/main/java/at/hannibal2/skyhanni/features/stranded/HighlightPlaceableNpcs.kt
Labels: Bug Fix - Sooner than Very Soon

#2086 Fix: Magenta LIvid
  src/main/java/at/hannibal2/skyhanni/utils/LorenzColor.kt
Labels: Bug Fix - Sooner than Very Soon

#2087 Feature: Added Rabbit pet warning
  src/main/java/at/hannibal2/skyhanni/config/features/event/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/MythicRabbitPetWarning.kt
Labels: Soon

#2083 Removal: Removed mineshaft from mining event display.
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningEventConfig.java
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
Labels: Soon

#2072 Fix: Wardrobe slot color & Event priority
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/WardrobeAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1460 Feature: Total Powder Cost in Perk Lore
  src/main/java/at/hannibal2/skyhanni/config/features/mining/HotmConfig.java
  src/main/java/at/hannibal2/skyhanni/data/HotmData.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/PowderPerHotmPerk.kt
Labels: Soon

#1442 Improvement: Added Display Options to Powder in Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/api/HotmAPI.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/DisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Soon

#2079 Improvement: Wardrobe Outline Color
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
Labels: Soon

#2088 Backend: code cleanup in custom wardrobe
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
Labels: Backend

#1983 Backend: Apply annotations to everything
  .idea/dictionaries/default_user.xml
  .live-plugins/module/plugin.kts
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
  src/main/java/at/hannibal2/skyhanni/data/SkillExperience.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobData.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/Translator.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/BurrowWarpHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CollectionTracker.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
Labels: Soon, Backend

#1898 Backend: Remove deprecated time utils format
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingMilestoneCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenCropTimeCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenBestCropTime.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/KingTalismanHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangNextResetCooldown.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
Labels: Soon, Backend

#1725 Backend: for each
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/Mayors.kt
  src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDebug.kt
  src/main/java/at/hannibal2/skyhanni/events/RenderEntityOutlineEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/endernodetracker/EnderNodeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyChatCommands.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/tabcomplete/PlayerTabComplete.kt
  src/main/java/at/hannibal2/skyhanni/features/cosmetics/ArrowTrail.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/CroesusChestTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonsRaceGuide.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/MythologicalCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/EventWaypoint.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/christmas/PresentWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/SeaCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/HighlightVisitorsOutsideOfGarden.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorListener.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SkyblockGuideHighlightFeature.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilSolver.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionXp.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/limbo/LimboPlaytime.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigOptionGui.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/MatriarchHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/CrimsonIsleReputationHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/colosseum/BlobbercystsHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/CruxTalismanDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/BlazeSlayerDaggerHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/enderman/EndermanSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/summonings/SummoningMobManager.kt
  src/main/java/at/hannibal2/skyhanni/test/PacketTest.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TrackSoundsCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/ComponentMatcherUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/KSerializable.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/FeatureTogglesByDefaultAdapter.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Backend

#2089 Fix: Elapsed Time in Dungeons DiscordRPC
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#2090 Fix: Golden Strays Causing New Rabbits to Detect as Dupes
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsCompactChat.kt
Labels: Bug Fix - Sooner than Very Soon

#2094 Fix: Widget, Interest & Scrap
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
Labels: Bug Fix - Sooner than Very Soon

#2097 Fix: HotmAPI Level Saving wrong with Blue Egg
  src/main/java/at/hannibal2/skyhanni/data/HotmData.kt
Labels: Bug Fix - Sooner than Very Soon

#2078 Improvement: Custom Wardrobe Tooltip Keybind
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/customwardrobe/CustomWardrobeConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
Labels: Soon

#2102 Fix: World Boarder
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonShadowAssassinNotification.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/AccessorWorldBorderPacket.java
Labels: Bug Fix - Sooner than Very Soon

#2101 Fix: Hoppity Requirement when already found.
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
Labels: Bug Fix - Sooner than Very Soon

#2095 Improvement: Area Miniboss Mob Detection
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/AreaMiniBossFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#2103 Fix: Dynamic Text being hidden after 80 blocks
  src/main/java/at/hannibal2/skyhanni/test/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1397 Backend: Add true color support to chat formatting codes
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/ExtendedColorPatch.java
  src/main/java/at/hannibal2/skyhanni/utils/ExtendedChatColor.kt
Labels: Soon

#2105 Improvement: Add Keybinds to Custom Wardrobe
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/customwardrobe/CustomWardrobeConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/customwardrobe/KeybindConfig.java
  src/main/java/at/hannibal2/skyhanni/data/GuiData.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobeKeybinds.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/WardrobeAPI.kt
Labels: Soon

#2092 Improvement: Summoning Mob Display Mob Detection
  src/main/java/at/hannibal2/skyhanni/config/features/combat/SummoningsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/summonings/SummoningMobManager.kt
Labels: Soon

#1940 Backend: Cleanup some scoreboard event stuff
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/HotmData.kt
  src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/PurseAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
  src/main/java/at/hannibal2/skyhanni/events/RawScoreboardUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/ScoreboardChangeEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/ScoreboardRawChangeEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/ScoreboardUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/stillgorechateau/RiftBloodEffigies.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerQuestWarning.kt
Labels: Soon, Backend

#1288 Feature: Add SkyHanni User Luck to stats breakdown
  src/main/java/at/hannibal2/skyhanni/features/misc/UserLuckBreakdown.kt
Labels: Soon

#1089 Feature: Add player highlighting for the Punchcard Artifact
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/rift/PunchcardConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/rift/RiftConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/PunchcardHighlight.kt
Labels: Soon

#2093 Fix: Compact Mythic Rabbit
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
Labels: Bug Fix - Sooner than Very Soon

#2098 Fix: ConcurrentModifactionException in RepoPatternManager during Tests
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
Labels: Bug Fix - Sooner than Very Soon

#2113 Fix: Event start time being null in custom scoreboard
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvents.kt
Labels: Bug Fix - Sooner than Very Soon

#2132 Fix: Summons messages not being blocked
  src/main/java/at/hannibal2/skyhanni/features/summonings/SummoningMobManager.kt
Labels: Bug Fix - Sooner than Very Soon

#2130 Fix: Deep Sea Protectors being misdetected as Automatons
  src/main/java/at/hannibal2/skyhanni/features/mining/HighlightMiningCommissionMobs.kt
Labels: Bug Fix - Sooner than Very Soon

#2126 Fix: ChocoFactory Custom Reminder trigger on TimeTower charge use.
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryCustomReminder.kt
Labels: Bug Fix - Sooner than Very Soon

#2125 Fix: Double Hook not detected with thunder bottle filled message
  src/main/java/at/hannibal2/skyhanni/features/fishing/SeaCreatureManager.kt
Labels: Bug Fix - Sooner than Very Soon

#2119 Fix: Unknown Lines Handler
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Bug Fix - Sooner than Very Soon

#2116 Fix: Trevor Tracker without Trapper Solver feature enabled
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#2107 Debug: Added /shtestisland
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyBlockIslandTest.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon

#2059 Backend: Addition to Graph Editor
  src/main/java/at/hannibal2/skyhanni/config/features/dev/GraphConfig.java
  src/main/java/at/hannibal2/skyhanni/test/GraphEditor.kt
Labels: Soon, Backend

#1334 Feature: Craftable Item List
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/CraftableItemListConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/craft/CraftableItemList.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Soon

#2124 Feature: Block opening chocolate factory without Mythic Rabbit equipped
  src/main/java/at/hannibal2/skyhanni/config/features/event/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/MythicRabbitPetWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBlockOpen.kt
Labels: Soon

#2021 Backend: Remove deprecated function ChatUtils.error
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/events/LorenzEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostUtil.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/tiarelay/TiaRelayHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/QuickModMenuSwitch.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Soon, Backend

#2123 Fix: Custom Wardrobe Price Error
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/WardrobeAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#2135 Fix Fishing Bait Warning
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingBaitWarnings.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeLimitedCache.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeLimitedSet.kt
Labels: Bug Fix - Sooner than Very Soon

#2040 Add: Special stray rabbit screen flashing
  build.gradle.kts
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryRabbitWarningConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryScreenFlash.kt
  src/main/java/at/hannibal2/skyhanni/utils/SoundUtils.kt
Labels: Soon

#2010 Backend: Fix Illegal Mob Detection with Ridable Pets
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
Labels: Soon

#1919 Improvement: Add hover descriptions to many ClickableChat messages
  src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/ProfileStorageData.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyChatCommands.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/winter/NewYearCakeReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishManager.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenLevelDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestSpawn.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryCustomReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTimeTowerManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryUpgradeWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/tiarelay/TiaRelayHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/DeepCavernsGuide.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/JoinCrystalHollows.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/NoBitsWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordRPCManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigFeatures.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/APIUtil.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon

#1341 Feature: Added Chunked Stats to Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/ChunkedStatsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/DisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ChunkedStat.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
Labels: Soon

#2136 Fix: Typo in TabWidget
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
Labels: Bug Fix - Sooner than Very Soon

#2115 Fix: Ore Event
  src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#2138 Feature & Fix: Powder Tracker Hard Stone & Goblin Eggs
  src/main/java/at/hannibal2/skyhanni/config/features/mining/PowderTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
Labels: Bug Fix - Sooner than Very Soon

#1240 Backend: Usage of TabWidget
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/ProfileStorageData.kt
  src/main/java/at/hannibal2/skyhanni/events/WidgetUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/FerocityDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenCropMilestoneFix.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorListener.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/VolcanoExplosivityDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/QuestLoader.kt
  src/test/java/at/hannibal2/skyhanni/test/garden/VisitorListenerTest.kt
Labels: Soon, Backend

#2133 Replace: Time Tower Reminder feature
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTimeTowerManager.kt
Labels: Soon

#2129 Feature: Add option to maintain sound levels during SoundUtils usage
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/utils/SoundUtils.kt
Labels: Soon

#1437 Feature: Reforge helper
  src/main/java/at/hannibal2/skyhanni/api/ReforgeAPI.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/helper/HelperConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/helper/ReforgeHelperConfig.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/NeuReforgeJson.kt
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
  src/main/java/at/hannibal2/skyhanni/events/NeuRepositoryReloadEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ReforgeHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/NumberUtil.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkyHanniTypeAdapters.kt
Labels: Soon

#1864 Backend: Drag and Drop for Renderables
  src/main/java/at/hannibal2/skyhanni/events/GuiContainerEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiContainerHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiContainer.java
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/DragNDrop.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
Labels: Soon

#2155 Add OneConfig mods to quick mod switcher
  src/main/java/at/hannibal2/skyhanni/features/misc/QuickModMenuSwitch.kt
Labels: Soon

#2159 Improvement: rename mushroom tier
  src/main/java/at/hannibal2/skyhanni/config/features/garden/cropmilestones/MushroomPetPerkConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
Labels: Soon

#2165 Fix: Chocolate per Time Tower charge ignoring Mu Rabbit
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTooltip.kt
Labels: Bug Fix - Sooner than Very Soon

#2163 Fix: Skill Progress ETA
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
Labels: Bug Fix - Sooner than Very Soon

#2161 Fix: Overflow level up message on Milestone 46
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#2158 Fix: Farming Weight Overtake ETA
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#2154 Fix: Also block opening Chocolate Factory with /factory
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBlockOpen.kt
Labels: Bug Fix - Sooner than Very Soon

#2145 Fix: Powder cost formulas and calculations
  src/main/java/at/hannibal2/skyhanni/data/HotmData.kt
Labels: Bug Fix - Sooner than Very Soon

#1934 Improvement: Make unclaimed eggs gui clickable
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
Labels: Soon, Waiting on Hypixel

#2164 Feature: Scrolling pages
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/PageScrollingConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/PageScrolling.kt
  src/main/java/at/hannibal2/skyhanni/utils/RegexUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
Labels: Soon

#2035 Backend: Enabling Shader with Enum
  src/main/java/at/hannibal2/skyhanni/features/chroma/ChromaShaderManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/ShaderManager.kt
Labels: Soon

#2076 Feature: Block achievements message spam on Alpha
  src/main/java/at/hannibal2/skyhanni/config/features/chat/FilterTypesConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Soon

#2075 Feature: Add Recipe Link to Shopping List Craftable! text
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
Labels: Soon
