Repository hannibal002/SkyHanni, pull requests merged in 2024-08, with the labels that each got.

#2293 Fix: Allow clicking Carnival Masks in /equipment
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
Labels: Bug Fix - Sooner than Very Soon

#2295 Fix: HotmData Level Detection with Blue Egg
  src/main/java/at/hannibal2/skyhanni/data/HotmData.kt
Labels: Bug Fix - Sooner than Very Soon

#2289 Backend: /shdebugprice
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Soon

#2286 Improvement: Hide Beacon on bingo
  src/main/java/at/hannibal2/skyhanni/features/gui/BeaconPower.kt
Labels: Soon

#2284 Fix: Reputation helper keybind activating while inside GUIs.
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/CrimsonIsleReputationHelper.kt
Labels: Bug Fix - Sooner than Very Soon

#2287 Fix: /shcommands empty page
  src/main/java/at/hannibal2/skyhanni/features/commands/HelpCommand.kt
Labels: Bug Fix - Sooner than Very Soon

#2288 Fix: Pablo Helper Abiphone
  src/main/java/at/hannibal2/skyhanni/features/nether/PabloHelper.kt
Labels: Bug Fix - Sooner than Very Soon

#2291 Fix: Item Pickup Wisp
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
Labels: Bug Fix - Sooner than Very Soon

#2292 Fix: Sack Item Pickup Log delay
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
Labels: Bug Fix - Sooner than Very Soon

#2294 Fix: Composter Overlay no data
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
Labels: Bug Fix - Sooner than Very Soon

#2299 Fix: Green Zorros Thumb Cape FF lore
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#2297 Fix: Visitor Shopping List AH items
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
Labels: Bug Fix - Sooner than Very Soon

#2298 Fix: Dungeon Finder item lore wrong item
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#2319 Fix: Custom Scoreboard Medals Pattern
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#2315 Fix: Added DYE to Item Category
  src/main/java/at/hannibal2/skyhanni/utils/ItemCategory.kt
Labels: Bug Fix - Sooner than Very Soon

#2312 fix pet regex
  src/main/java/at/hannibal2/skyhanni/data/PetAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#2257 Fix: Jasper Gemstone Color
  src/main/java/at/hannibal2/skyhanni/features/mining/OreBlock.kt
Labels: Bug Fix - Sooner than Very Soon

#2314 Fix: Colored Month in Discord RPC
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
Labels: Bug Fix - Sooner than Very Soon

#2303 Fix: Clicking on weight pass chat message
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#2302 Fix: Chroma Preview text showing in white
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/FontRendererHook.kt
Labels: Bug Fix - Sooner than Very Soon

#2316 Fix: Some Dungeon Features to support changed Master Mode text changes in Artist's Adobe update
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonCleanEnd.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#2307 Fix: Ore Mined Event
  src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#2305 Fix: Shift Clicking Items Triggering Pickup Log
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
Labels: Bug Fix - Sooner than Very Soon

#2304 Fix: Incorrect "This item has no attributes" message
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#2301 Fix: Lore on books with Compressed format + Regex Fix
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
Labels: Bug Fix - Sooner than Very Soon

#2318 Feature: Splatter Hearts
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/stillgorechateau/StillgoreChateauConfig.java
  src/main/java/at/hannibal2/skyhanni/features/rift/area/stillgorechateau/SplatterHearts.kt
Labels: Soon

#2317 Improvement: Add Divan's Powder Coating to Estimated Item Value
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
Labels: Soon

#2290 Backend: ItemPriceUtils
  src/main/java/at/hannibal2/skyhanni/features/combat/endernodetracker/EnderNodeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/AnitaExtraFarmingFortune.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateShopPrice.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Soon

#2313 Backend: Add Minister to MayorAPI
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/MayorConfig.java
  src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/MayorJson.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
Labels: Soon

#2330 Fix generateRepoPatterns task
  build.gradle.kts
Labels: Bug Fix - Sooner than Very Soon

#2329 Add copper dye to block visitor rewards
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/RewardWarningConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorReward.kt
Labels: Soon

#2335 Fix code preprocessing
  src/main/java/at/hannibal2/skyhanni/config/core/config/gui/GuiPositionEditor.kt
Labels: Bug Fix - Sooner than Very Soon

#2333 Improvement: Click CF block message to open pets
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBlockOpen.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
Labels: Soon

#2334 Improvement + Fix: Custom CF Reminder
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryCustomReminder.kt
Labels: Bug Fix - Sooner than Very Soon

#2338 Improvement: Repo Errors
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/GardenComposterInventoryFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUInternalName.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Soon

#2347 Fix: Akin being "Not" again
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
Labels: Bug Fix - Sooner than Very Soon

#2343 Fix: Minister Perk
  src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/MayorJson.kt
Labels: Bug Fix - Sooner than Very Soon

#2344 Fix: Visible color codes in Discord RPC
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
Labels: Bug Fix - Sooner than Very Soon

#2346 Improvement: copper dye drop statistics
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/DropsStatisticsConfig.java
Labels: Soon

#2345 Fix: ScoreboardData and splitting
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
Labels: Bug Fix - Sooner than Very Soon

#2353 Fix: Tab List Friends
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/AdvancedPlayerList.kt
Labels: Bug Fix - Sooner than Very Soon

#2349 Fix: SplatterHearts ConcurrentModificationException
  src/main/java/at/hannibal2/skyhanni/features/rift/area/stillgorechateau/SplatterHearts.kt
Labels: Bug Fix - Sooner than Very Soon

#2350 Fix: ConcurrentModificationException in SeaCreatureManager
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingTimer.kt
Labels: Bug Fix - Sooner than Very Soon

#2351 Fix: Item Pickup Log null items
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
Labels: Bug Fix - Sooner than Very Soon

#2352 Fix: Item Trackers NPC Price
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Bug Fix - Sooner than Very Soon

#2354 Fix: Mining Crash workaround
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/BlockRendererDispatcherHook.kt
Labels: Bug Fix - Sooner than Very Soon

#2355 Fix: Garden Guesting
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
Labels: Bug Fix - Sooner than Very Soon

#2358 Fix: Pet detection
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Bug Fix - Sooner than Very Soon

#2360 Fix: Negative price for items with no NPC sell price
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#2359 Fix: Finnegan Perks
  src/main/java/at/hannibal2/skyhanni/data/Mayors.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropSpeed.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#2365 Fix: Fishing Timer
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingTimer.kt
Labels: Bug Fix - Sooner than Very Soon

#2374 Fix: Renderable links in other mods
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Bug Fix - Sooner than Very Soon

#2373 Fix: Item Pickup Log icons
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Bug Fix - Sooner than Very Soon

#2371 Fix: Fished Item name display
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/ShowFishingItemName.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
Labels: Bug Fix - Sooner than Very Soon

#2368 Fix: One hoppity page
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
Labels: Bug Fix - Sooner than Very Soon

#2367 Fix: Wrong Slayer alert Bladesoul
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerQuestWarning.kt
Labels: Bug Fix - Sooner than Very Soon

#2366 Fix: Bazaar + Item Trackers
  src/main/java/at/hannibal2/skyhanni/data/OwnInventoryData.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarCancelledBuyOrderClipboard.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarOrderHelper.kt
Labels: Bug Fix - Sooner than Very Soon

#2363 Fix: Obfuscated and Shard
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#2376 Fix typo in FarmingWeightDisplay error message
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#2370 Fix: Time Limited Cache Lock
  src/main/java/at/hannibal2/skyhanni/utils/TimeLimitedCache.kt
Labels: Bug Fix - Sooner than Very Soon

#2377 Fix: Check Dependency running on beta commit
  .github/workflows/check_dependencies.yml
Labels: Bug Fix - Sooner than Very Soon

#2378 Fix Master Mode Stack Sizes in Mort #2316
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#2379 Fix: Typos
  src/main/java/at/hannibal2/skyhanni/config/features/event/waypoints/ChristmasPresentConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/waypoints/HalloweenBasketConfig.java
Labels: Bug Fix - Sooner than Very Soon

#2384 Fix: Changelog Fix
  docs/CHANGELOG.md
  docs/FEATURES.md
Labels: Bug Fix - Sooner than Very Soon

#1837 Feature + Fix: Custom Scoreboard Souflow, Margin, and more
  src/main/java/at/hannibal2/skyhanni/config/core/config/Position.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/AlignmentConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/BackgroundConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/DisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/RenderBackground.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Bug Fix - Sooner than Very Soon

#2382 Fix: Double Color in ScoreboardData Part 2
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
Labels: Bug Fix - Sooner than Very Soon

#2386 Fix: typo in corpse detection
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseLocator.kt
Labels: Bug Fix - Sooner than Very Soon

#2387 Fix: Patcher Breaking Lines
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/PatcherFixes.kt
  src/main/java/at/hannibal2/skyhanni/utils/OtherModsSettings.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#2388 Fix: New Alpha Ores
  src/main/java/at/hannibal2/skyhanni/features/mining/OreBlock.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/OreType.kt
Labels: Bug Fix - Sooner than Very Soon

#2393 Fix: Derpy Perk Name
  src/main/java/at/hannibal2/skyhanni/data/Mayors.kt
Labels: Bug Fix - Sooner than Very Soon

#2392 Fix: ItemCategory error spam
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#2389 Fix: MayorAPI not working without Ministers
  src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/MayorJson.kt
Labels: Bug Fix - Sooner than Very Soon

#2399 Improvement: /warp stonks
  src/main/java/at/hannibal2/skyhanni/config/features/event/diana/IgnoredWarpsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/diana/BurrowWarpHelper.kt
Labels: Soon

#2400 Backend: Version to download source checker
  src/main/java/at/hannibal2/skyhanni/tweaker/DownloadSourceChecker.java
Labels: Soon

#2395 Fix: Mana Enchants in Estimated Chest Value
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Bug Fix - Sooner than Very Soon

#2396 Fix: Christmas presents
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/christmas/PresentWaypoints.kt
Labels: Bug Fix - Sooner than Very Soon

#2398 Fix: Hoppity Requirement
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
Labels: Bug Fix - Sooner than Very Soon

#2404 Fix: Rounded Shaders not working with a scale less than 1
  src/main/resources/assets/skyhanni/shaders/rounded_rect.fsh
  src/main/resources/assets/skyhanni/shaders/rounded_rect_outline.fsh
  src/main/resources/assets/skyhanni/shaders/rounded_texture.fsh
Labels: Bug Fix - Sooner than Very Soon

#2311 Feature + Fix: Hoppity Event Summarization
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/EventConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEventSummaryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/events/hoppity/RabbitFoundEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggDisplayManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityNpc.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzRarity.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockTime.kt
Labels: Waiting on Hypixel, Bug Fix - Sooner than Very Soon

#2403 Improvement: Multiple Languages
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/chat/TranslatorConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/translation/TranslatableLanguage.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/translation/Translator.kt
Labels: Soon

#2397 Improvement: Wording in config, dev options
  src/main/java/at/hannibal2/skyhanni/config/features/combat/damageindicator/DamageIndicatorConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/bingo/BingoCardConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/diana/DianaConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/TotemOfCorruptionConfig.java
Labels: Soon

#2357 Improvement: Add toggle to UserLuck Breakdown
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/UserLuckBreakdown.kt
Labels: Soon

#2402 Fix: Custom Scoreboard Issues
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/RenderBackground.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1708 Feature: Remind Command
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/RemindersConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/Storage.java
  src/main/java/at/hannibal2/skyhanni/features/misc/reminders/Reminder.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/reminders/ReminderManager.kt
Labels: Soon

#2411 Fix: Rare Scoreboard Errors
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Bug Fix - Sooner than Very Soon

#1717 Improvement: Enchant Parsing SBA Convert Roman Numerals and NEU Inventories compat
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/FormattedEnchant.kt
Labels: Soon

#1558 Feature: Starred Mob Highlight + Fels Highlight/Line
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/DungeonConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/ObjectHighlighterConfig.java
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonMobManager.kt
Labels: Soon

#1957 Feature: "Not any pests" chat filter and "No pests!" title
  src/main/java/at/hannibal2/skyhanni/config/features/chat/FilterTypesConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestFinderConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestFinder.kt
Labels: Soon

#2323 Feature: Motes in Session
  src/main/java/at/hannibal2/skyhanni/config/features/rift/RiftConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/rift/motes/MotesConfig.java
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/motes/MotesSession.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
Labels: Soon

#1988 Feature: Exp in Superpairs as Stack Size.
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
Labels: Soon

#2310 Improvement: Mineshaft Count
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/features/mining/MineshaftPityDisplay.kt
Labels: Soon

#1927 Improvement: Default amount for /gfs
  src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/GetFromSackConfig.java
Labels: Soon

#2321 Feature: Made dye hex code show actual colour
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/ColorHexInLore.kt
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemCategory.kt
Labels: Soon

#2408 Improvement: Fossil Excavator Reset Command
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorProfitTracker.kt
Labels: Soon

#2414 Docs: Add Odinclient to FAQ 12
  docs/DISCORD_FAQ.md
Labels: Soon

#2166 Improvement: Clicked blocks highlight
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/DungeonConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/HighlightClickedBlocksConfig.java
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHighlightClickedBlocks.kt
Labels: Soon

#2308 Improvement: Mineshaft Message
  src/main/java/at/hannibal2/skyhanni/features/mining/MineshaftPityDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/OreType.kt
Labels: Soon

#2106 Feature: Forge recipe Get from Sack
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
  src/main/java/at/hannibal2/skyhanni/features/mining/ForgeGfs.kt
Labels: Soon

#2409 Fix: Fossil Solver texture pack
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilSolverDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#2216 Feature: Colors and formatting helper in chat
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ColorFormattingHelper.kt
Labels: Soon

#2415 Fix: Clicked Blocks Highlight Migrator
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHighlightClickedBlocks.kt
Labels: Bug Fix - Sooner than Very Soon

#2416 Fix: Minor Typos/Formatting in Hoppity's
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
Labels: Bug Fix - Sooner than Very Soon

#2410 Fix: Patcher coordinates chat detection
  src/main/java/at/hannibal2/skyhanni/features/misc/PatcherSendCoordinates.kt
Labels: Bug Fix - Sooner than Very Soon

#2424 FIX optimal speed for cactus
  src/main/java/at/hannibal2/skyhanni/config/features/garden/optimalspeed/CustomSpeedConfig.java
Labels: Bug Fix - Sooner than Very Soon

#2429 Fix: Github Actions Artifact path
  .github/workflows/build.yml
Labels: Bug Fix - Sooner than Very Soon, Backend

#2432 Fix: Tunnel Maps commission
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
Labels: Bug Fix - Sooner than Very Soon

#2412 Backend: /shdebugscoreboard
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
Labels: Soon

#2435 Fix: /show not showing all enchants
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
Labels: Bug Fix - Sooner than Very Soon

#2420 Fix: Global Scale affecting Custom Wardrobe
  src/main/java/at/hannibal2/skyhanni/config/core/config/Position.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
Labels: Bug Fix - Sooner than Very Soon

#2422 Fix: Powder for 10 Level
  src/main/java/at/hannibal2/skyhanni/features/mining/PowderPerHotmPerk.kt
Labels: Bug Fix - Sooner than Very Soon

#2428 Improvement: Click on chat
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/composter/ComposterConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityNpc.kt
  src/main/java/at/hannibal2/skyhanni/features/event/winter/NewYearCakeReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/UpgradeReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBlockOpen.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryCustomReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTimeTowerManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryUpgradeWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experiments/GuardianReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/PatcherFixes.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
Labels: Soon

#2433 Improvement: Help finding Rift Guide
  src/main/java/at/hannibal2/skyhanni/config/features/rift/EnigmaSoulConfig.java
Labels: Soon

#2431 Backend: Stop sound errors in console
  src/main/java/at/hannibal2/skyhanni/utils/SoundUtils.kt
Labels: Soon

#2427 Fix: ! Crash
  src/main/java/at/hannibal2/skyhanni/mixins/init/SkyhanniMixinPlugin.java
Labels: Bug Fix - Sooner than Very Soon

#2413 Improvement: Warning rancher chat command
  src/main/java/at/hannibal2/skyhanni/config/features/garden/optimalspeed/OptimalSpeedConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenOptimalSpeed.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
Labels: Soon

#2430 Fix: Autopet Rule Detection
  src/main/java/at/hannibal2/skyhanni/features/inventory/experiments/GuardianReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CurrentPetDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#2046 Feature: Last server
  src/main/java/at/hannibal2/skyhanni/config/features/misc/LastServersConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/LastServers.kt
Labels: Soon

#1961 Feature: /shtps command
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/TpsCounter.kt
Labels: Soon

#2265 Feature: Bits on Cookie
  src/main/java/at/hannibal2/skyhanni/config/features/misc/BitsConfig.java
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/BitsPerCookieVisual.kt
  src/main/java/at/hannibal2/skyhanni/utils/RegexUtils.kt
Labels: Soon

#1712 Feature: Reverse Party Transfer
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/commands/CommandsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/commands/ReversePartyTransferConfig.java
  src/main/java/at/hannibal2/skyhanni/data/PartyAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyCommands.kt
Labels: Soon

#2254 Improvement: Enchant Parsing Exceptions
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/Enchant.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/FormattedEnchant.kt
Labels: Soon
