Repository hannibal002/SkyHanni, pull requests merged in 2024-03, with the labels that each got.

#1028 Internal Change: printStackTrace -> ErrorManager
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/QuestLoader.kt
  src/main/java/at/hannibal2/skyhanni/utils/APIUtil.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SoundUtils.kt
Labels: Soon

#1052 Added copy underbid keybind + config group
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/AuctionHouseConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/AuctionsHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/AuctionHouseCopyUnderbidPrice.kt
Labels: Soon

#835 Added Command /shconfig toggle
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniConfigSearchResetCommand.kt
Labels: Soon

#1065 Backend: Remove log error
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/NonGodPotEffectDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/QuickModMenuSwitch.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordRPCManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/VisualWordGui.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniConfigSearchResetCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ClipboardUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzColor.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/OSUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ParkourHelper.kt
Labels: Soon

#1078 Internal Change: String to number final changes
  src/main/java/at/hannibal2/skyhanni/utils/NumberUtil.kt
Labels: Soon

#1077 Internal Change: Code Cleanup
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/NPCVisitorFix.kt
  src/main/java/at/hannibal2/skyhanni/test/WorldEdit.kt
Labels: Soon

#1083 Fix: BingoCardTips using correct slot
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardTips.kt
Labels: Bug Fix - Sooner than Very Soon

#861 Backend: Add stacking enchants to repo
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/StackingEnchantsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordRPCManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
Labels: Soon

#1087 Fix: Skill Progress message
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1092 Fix: SkyblockGuideHighlightFeature minion/collection pattern
  src/main/java/at/hannibal2/skyhanni/features/inventory/SkyblockGuideHighlightFeature.kt
Labels: Bug Fix - Sooner than Very Soon

#1093 Backend: Remove dupe command
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
Labels: Bug Fix - Sooner than Very Soon

#1086 Docs: Using docs for markdown files
  README.md
  docs/CHANGELOG.md
  docs/DISCORD_FAQ.md
  docs/FEATURES.md
  docs/INSTALLING.md
  docs/OPEN_SOURCE_SOFTWARE.md
Labels: Soon

#1030 Feature: Add more messages to chat hider
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon

#1091 Fix: Make crafted minions a set instead of a list
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/Storage.java
  src/main/java/at/hannibal2/skyhanni/features/bingo/FirstMinionTier.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/MinionCraftHelper.kt
Labels: Bug Fix - Sooner than Very Soon

#1096 refactor melody quick restart
  src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#1098 Feature: Hide useless Booster Cookie message
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Soon

#1099 Feature: Toggle to only render Custom Text Box while in GUIs
  src/main/java/at/hannibal2/skyhanni/config/features/gui/TextBoxConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/CustomTextBox.kt
Labels: Soon

#1071 Backend: String colored
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Soon

#1100 Bugfix: SkyHanni features not working on Alpha
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
Labels: Bug Fix - Sooner than Very Soon

#603 Feature: Added option to show some features outside SB.
  src/main/java/at/hannibal2/skyhanni/config/enums/OutsideSbFeature.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/WaypointsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/EliteFarmingWeightConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/NextJacobContestConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/YawPitchDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/ModifyWordsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/data/RenderData.kt
  src/main/java/at/hannibal2/skyhanni/features/cosmetics/ArrowTrail.kt
  src/main/java/at/hannibal2/skyhanni/features/cosmetics/CosmeticFollowingLine.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenYawAndPitch.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CustomTextBox.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MarkedPlayerManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MovementSpeedDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/PartyMemberOutlines.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/QuickModMenuSwitch.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/TimeFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/TpsCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/ModifyVisualWords.kt
  src/main/java/at/hannibal2/skyhanni/test/ParkourWaypointSaver.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityOutlineRenderer.kt
Labels: Soon

#1097 [Feat] Gfs message after supercrafting
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/GetFromSackConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/SuperCraftFeatures.kt
Labels: Soon

#1102 Change: Add Goal to CollectionTracker
  src/main/java/at/hannibal2/skyhanni/features/misc/CollectionTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/NumberUtil.kt
Labels: Soon

#1106 Fix: Anita Accessory Chat Filter
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Bug Fix - Sooner than Very Soon

#1103 [Feat] block player from destroying fuel in inferno minion
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/minion/MinionsConfig.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/InfernoMinionFuelsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/InfernoMinionFeatures.kt
Labels: Soon

#1107 Backend: Use more isInIsland
  src/main/java/at/hannibal2/skyhanni/features/chat/ArachneChatMessageHider.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/JoinCrystalHollows.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/teleportpad/TeleportPadCompactName.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/teleportpad/TeleportPadInventoryNumber.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/CrimsonIsleReputationHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailykuudra/DailyKuudraBossHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/miniboss/DailyMiniBossHelper.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
Labels: Soon

#1105 Fix: Auto-Tip Chat Filter
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Bug Fix - Sooner than Very Soon

#1112 Renormalize line endings to be \n
  .gitattributes
  src/main/java/at/hannibal2/skyhanni/events/RenderEntityOutlineEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/SpawnTimers.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonTeammateOutlines.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/QuickCraftFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/PartyMemberOutlines.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/GlowingDroppedItems.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/RenderGlobalHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/RendererLivingEntityHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/CustomRenderGlobal.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinRenderGlobal.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinRendererLivingEntity.java
  src/main/java/at/hannibal2/skyhanni/utils/LorenzRarity.kt
Labels: Soon

#1109 Backend: Reformat code in all files in src directory
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/SensitivityReducerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningEventConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/skillprogress/SkillETADisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/data/ItemClickData.kt
  src/main/java/at/hannibal2/skyhanni/data/PetAPI.kt
  src/main/java/at/hannibal2/skyhanni/events/EntityClickEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/SkillOverflowLevelupEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chroma/ChromaShaderManager.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/cosmetics/CosmeticFollowingLine.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/HighlightInquisitors.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/MythologicalCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/christmas/PresentWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GeyserFishing.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenOptimalSpeed.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/MaxPurseItems.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/QuiverNotification.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/InfernoMinionFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionXp.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/BetterWikiFromMenus.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CustomTextBox.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MarkedPlayerManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/QuickModMenuSwitch.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangFreezeCooldown.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillTooltip.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillUtil.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerQuestWarning.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiContainerHook.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniConfigSearchResetCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemNameResolver.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/ShaderManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/Uniform.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
  src/main/resources/assets/skyhanni/sounds.json
  src/test/java/at/hannibal2/skyhanni/test/garden/VisitorToolTipParserTest.kt
  src/test/resources/testdata/Item/10starnecronhead.json
Labels: Soon

#1114 Backend: Use less item name
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
Labels: Soon - Backend

#1113 Interlal Change: Code cleanup
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningEventConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/diana/HighlightInquisitors.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GeyserFishing.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionXp.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CustomTextBox.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MarkedPlayerManager.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiContainerHook.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
  src/test/java/at/hannibal2/skyhanni/test/garden/VisitorToolTipParserTest.kt
Labels: Soon - Backend

#1056 Internal Change: Code cleanup in FishingAPI
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/SharkFishCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GeyserFishing.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
Labels: Soon - Backend

#1072 Fix: EntityClick cancellability
  src/main/java/at/hannibal2/skyhanni/data/ItemClickData.kt
Labels: Bug Fix - Sooner than Very Soon

#1085 Backend: Use less forge events
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/events/GuiKeyPressEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/SkyHanniRenderEntityEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/HideDamageSplash.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/AshfangMinisNametagHider.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/WikiManager.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonBossHideDamageSplash.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/TerracottaPhase.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenOptimalSpeed.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorListener.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/HideArmor.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/AuctionHouseCopyUnderbidPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/teleportpad/TeleportPadCompactName.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangBlazes.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangHideDamageIndicator.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/HideMobNames.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/summonings/SummoningMobManager.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/TestExportTools.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
Labels: Soon - Backend

#1108 Docs: Added PR template
  pull_request_template.md
Labels: Soon

#935 Add maven info
  build.gradle.kts
  jitpack.yml
Labels: Soon - Backend

#1115 Fix: Anita's Accessory Chat Filter not working with multi-word crops
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Bug Fix - Sooner than Very Soon

#1120 Fix: Profile name on alpha
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
Labels: Bug Fix - Sooner than Very Soon

#1122 Feature: Full Auto Update
  src/main/java/at/hannibal2/skyhanni/config/features/About.java
  src/main/java/at/hannibal2/skyhanni/features/misc/update/UpdateManager.kt
Labels: Soon

#1117 Feature: Hide zero bank interest message
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Soon

#1125 Fix: Visitor spam temporarily
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#848 Feature: Limbo time PB v2
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/Storage.java
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyCommands.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/LimboTimeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MiscFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/limbo/LimboPlaytime.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/limbo/LimboTimeTracker.kt
Labels: Soon

#1011 Feature: Kismet Feather Tracker
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/Storage.java
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/DungeonChestConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/DungeonConfig.java
  src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
  src/main/java/at/hannibal2/skyhanni/events/DungeonCompleteEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/InventoryFullyOpenedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/CroesusChestTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/CroesusUnopenedChestTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
Labels: Soon

#1130 Fix: minion hopper profit and /shdefaultoptions
  src/main/java/at/hannibal2/skyhanni/config/features/minion/MinionsConfig.java
Labels: Bug Fix - Sooner than Very Soon

#1133 Fixed typos
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestFinderConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestFinder.kt
Labels: Bug Fix - Sooner than Very Soon

#1040 Feature: Display current and upcoming mining events
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningEventConfig.java
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventData.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventType.kt
  src/main/java/at/hannibal2/skyhanni/utils/JsonUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon

#855 Debug Feature: Added TrackSoundsCommand
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.java
  src/main/java/at/hannibal2/skyhanni/events/PlaySoundEvent.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TrackSoundsCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/SimpleTimeMark.kt
Labels: Soon - Backend

#1075 Feature: Lane Switching Notification
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/laneswitch/LaneSwitchConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/laneswitch/LaneSwitchNotificationConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/laneswitch/LaneSwitchNotificationSettings.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/laneswitch/LaneSwitchSoundSettings.java
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenPlotAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/LaneSwitchNotification.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/LaneSwitchUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MovementSpeedDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
Labels: Soon

#1111 Feature: Show available/missing classes
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/PartyFinderConfig.java
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
Labels: Soon

#1138 Fix: Fix Lane Switch Calculation
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/LaneSwitchUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1142 Fix: Some issues in event tracker
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventType.kt
Labels: Bug Fix - Sooner than Very Soon

#1127 Backend: RenderEntityLiving performance fix
  src/main/java/at/hannibal2/skyhanni/config/features/markedplayer/MarkedPlayerConfig.java
  src/main/java/at/hannibal2/skyhanni/events/RenderMobColoredEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/ResetEntityHurtEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/AreaMiniBossFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/MobHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHideItems.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonLividFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/HighlightDungeonDeathmite.kt
  src/main/java/at/hannibal2/skyhanni/features/event/UniqueGiftingOpportunitiesFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/HighlightInquisitors.kt
  src/main/java/at/hannibal2/skyhanni/features/event/jerry/HighlightJerries.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/SeaCreatureFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/HighlightVisitorsOutsideOfGarden.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/HighlightMiningCommissionMobs.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MarkedPlayerManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangBlazes.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/colosseum/BlobbercystsHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/VoltHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveDefenseBlocks.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/RiftLarva.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/RiftOdonata.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerMiniBossFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/HellionShieldHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/enderman/EndermanSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/summonings/SummoningMobManager.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/RenderLivingEntityHelper.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinRendererLivingEntity.java
  src/main/java/at/hannibal2/skyhanni/test/WorldEdit.kt
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1137 Disable action bar hider if Skill Progress feature is disabled
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
Labels: Soon

#1144 Fix: Add Burningsoul Demon to line to miniboss
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerMiniBossFeatures.kt
Labels: Soon

#1116 improvement: Anita and SkyMart calculation breakdowns
  src/main/java/at/hannibal2/skyhanni/config/features/garden/SkyMartConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/AnitaMedalProfit.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/SkyMartCopperPrice.kt
  src/main/java/at/hannibal2/skyhanni/utils/DisplayTableEntry.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon

#1047 Internal Change: Code cleanup ContainerChest getAllItems
  src/main/java/at/hannibal2/skyhanni/features/anvil/AnvilCombineHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardTips.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/GardenComposterInventoryFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobFarmingContestsInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/AuctionsHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/QuickCraftFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarOrderHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/EnigmaSoulWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
Labels: Soon, Backend

#1143 Technical Detail: code cleanup in LaneSwitchUtils.isBoundaryPlot
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/LaneSwitchUtils.kt
Labels: Soon, Backend

#1145 Internal Change: /shtestmessage upgrade
  src/main/java/at/hannibal2/skyhanni/test/command/TestChatCommand.kt
Labels: Soon, Backend

#1147 Fix fire sale chat hider
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Bug Fix - Sooner than Very Soon

#1148 Fix: Skill progress tab pattern
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1151 fixed hypixel update: showing `new` next to garden visitors in tab list
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1153 fixed hypixel update: tab widget allow to disable profile name
  src/main/java/at/hannibal2/skyhanni/data/ProfileStorageData.kt
Labels: Bug Fix - Sooner than Very Soon

#1154 fixed hypixel update: splitting SkyMart into three categories
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/SkyMartCopperPrice.kt
Labels: Bug Fix - Sooner than Very Soon

#1121 Backend + Fix: Improve visitor getting
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorListener.kt
  src/test/java/at/hannibal2/skyhanni/test/garden/VisitorListenerTest.kt
Labels: Bug Fix - Sooner than Very Soon

#1162 Fix: DungeonFinderFeatures IndexOutOfBounds
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#1161 Fix: Compact Tab List Render Layer
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/TabListRenderer.kt
Labels: Bug Fix - Sooner than Very Soon

#1160 Fix: Skill pattern
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1157 Improvement: Show Town Board with accepted Rescue Mission quest
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
Labels: Soon

#1156 Fix: Fixed Custom Scoreboard issues and added some small things
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/DisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/InformationFilteringConfig.java
  src/main/java/at/hannibal2/skyhanni/data/MaxwellAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/RenderBackground.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvents.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#1152 Fix: Fixed some pattern in scoreboard
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ServerRestartTitle.kt
Labels: Bug Fix - Sooner than Very Soon

#1168 Removed Feature: Plot Name in Scoreboard
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiIngameHook.kt
Labels: Soon, Bug Fix - Sooner than Very Soon

#1166 Fix: advanced player list error with pet in widget and "hide spacing"
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/AdvancedPlayerList.kt
Labels: Bug Fix - Sooner than Very Soon

#339 Feature: AH estimated item value comparison
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/AuctionHousePriceComparisonConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/AuctionsHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/AuctionHousePriceComparison.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzColor.kt
Labels: Soon

#1104 Feature: Craft Materials From Bazaar
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/BazaarConfig.java
  src/main/java/at/hannibal2/skyhanni/events/InventoryFullyOpenedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/CraftMaterialsFromBazaar.kt
  src/main/java/at/hannibal2/skyhanni/utils/PrimitiveItemStack.kt
Labels: Soon

#1158 Removed Feature: Desk in sb menu
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/GardenDeskInSBMenu.kt
Labels: Soon

#1170 Fix: Fixed Hypixel Scoreboard never reappearing
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
Labels: Bug Fix - Sooner than Very Soon

#1167 Fix: crimson isle detection after tab list widget
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/CrimsonIsleReputationHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/QuestLoader.kt
Labels: Bug Fix - Sooner than Very Soon

#1174 Improvement + Fix: Custom Scoreboard Fixed and Additions Part 2
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/BackgroundConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/DisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Bug Fix - Sooner than Very Soon

#1171 Backend: Storage Config Moving
  src/main/java/at/hannibal2/skyhanni/config/Features.java
  src/main/java/at/hannibal2/skyhanni/config/Storage.java
  src/main/java/at/hannibal2/skyhanni/config/storage/PlayerSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/config/storage/Storage.java
  src/main/java/at/hannibal2/skyhanni/data/ProfileStorageData.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/BingoAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/CroesusChestTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailykuudra/DailyKuudraBossHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/QuestLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/miniboss/DailyMiniBossHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerRngMeterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniConfigSearchResetCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon, Backend

#1179 Fix: Entity Render Event
  src/main/java/at/hannibal2/skyhanni/features/summonings/SummoningMobManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1186 Fix: Trapper area waypoints not working
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrapperMobArea.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorMob.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorSolver.kt
Labels: Bug Fix - Sooner than Very Soon

#1187 Backend: Chat History Search
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
Labels: Soon, Backend

#1188 Fix: Guesting Detection
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
Labels: Bug Fix - Sooner than Very Soon

#1169 Feature: Custom fishing hook alert text
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/FishingHookDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingHookDisplay.kt
Labels: Soon

#1183 Improvement + Fix: Custom Scoreboard Part 3
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/DisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvents.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Soon, Bug Fix - Sooner than Very Soon

#1189 Fix: Fixed Bits to claim & current power
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/MaxwellAPI.kt
Labels: Bug Fix - Sooner than Very Soon, Waiting on Dependency PR

#1194 Hotfix: QuiverAPI
  src/main/java/at/hannibal2/skyhanni/data/QuiverAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1141 Improvement: Allow translate commands w/o feature on
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/Translator.kt
Labels: Soon

#1195 Fix: OpenBrowser Crash
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/OSUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1203 Fix: Party Leader detection when name ends with an S
  src/main/java/at/hannibal2/skyhanni/data/PartyAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1201 Feature: Thaumaturgy Tuning in Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/DisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/data/MaxwellAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/SprayDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/StatsTuning.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Soon

#1196 Fix: SuperBoom TNT wrong itemNameQuery
  src/main/java/at/hannibal2/skyhanni/utils/ItemNameResolver.kt
Labels: Bug Fix - Sooner than Very Soon

#1198 Fix: Remove unused config element
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
Labels: Bug Fix - Sooner than Very Soon

#1199 Fix: Fixed Custom Scoreboard Dungeon Problems
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvents.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Bug Fix - Sooner than Very Soon

#1202 Fix: Dungeon Complete Event not getting triggered on Entrance
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1205 Fix: Fixed two unknown line problems
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Bug Fix - Sooner than Very Soon

#840 Improvement: Add delay after tool swap before warning about wrong speed
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenOptimalSpeed.kt
Labels: Soon

#1164 Improvement: Garden level from Skyblock menu
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenLevelDisplay.kt
Labels: Soon

#1132 Removed Feature: Removed max pet xp tooltip
  src/main/java/at/hannibal2/skyhanni/config/features/misc/pets/PetExperienceToolTipConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/PetExpTooltip.kt
Labels: Soon

#1090 Improvement: Consistent enhanced backspace
  src/main/java/at/hannibal2/skyhanni/features/misc/BetterSignEditing.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/VisualWordGui.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
Labels: Soon

#1211 Fix: Party Finder "Mark Missing Class" highlighting too much
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#1180 Backend: Rewrote DungeonFinderFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonRankTabListColor.kt
Labels: Bug Fix - Sooner than Very Soon, Backend

#1149 Feature: Update Rancher's Boots stack size for new update
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
Labels: Soon, Bug Fix - Sooner than Very Soon

#1212 Improvement + Fix: Custom Scoreboard Fixes Part 4
  src/main/java/at/hannibal2/skyhanni/data/MaxwellAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvents.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Bug Fix - Sooner than Very Soon

#1208 Improvement: Lane Switch v2
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/laneswitch/FarmingLaneConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/laneswitch/LaneSwitchConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/laneswitch/LaneSwitchNotificationConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/laneswitch/LaneSwitchNotificationSettings.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/laneswitch/LaneSwitchSoundSettings.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/events/CropClickEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/farming/FarmingLaneSwitchEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobContestStatsSummary.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropSpeedMeter.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropSpeed.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenStartLocation.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/LaneSwitchNotification.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/LaneSwitchUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/WrongFungiCutterWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingDirection.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLane.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneCreator.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorTimer.kt
Labels: Bug Fix - Sooner than Very Soon

#1210 Backend: Add open in regex101.com intention
  .live-plugins/regexr/plugin.kts
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPattern.kt
Labels: Soon

#1193 Feature: Easter Egg Hunt Waypoints
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/waypoints/EasterEggConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/waypoints/LobbyWaypointsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/easter/EasterEgg.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/easter/EasterEggWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/easter/EggEntrances.kt
Labels: Soon

#1217 Fix: Crash in /ff
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/OverviewPage.kt
Labels: Bug Fix - Sooner than Very Soon

#1218 Fix: getting slayer spawn cost from bank
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerProfitTracker.kt
Labels: Bug Fix - Sooner than Very Soon

#1222 Typo: Fishing "Contest"
  src/main/java/at/hannibal2/skyhanni/features/fishing/SharkFishCounter.kt
Labels: Bug Fix - Sooner than Very Soon

#1220 Fix: Slayer cost from bank counting wrong
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerProfitTracker.kt
Labels: Bug Fix - Sooner than Very Soon

#1224 Fix: Visitor status not updating in some cases
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1225 Feature: Add Curse of Greed to non-God Potion effects
  src/main/java/at/hannibal2/skyhanni/features/misc/NonGodPotEffectDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#1226 Fix: NEUInternalName is null for item name 'Mushroom'
  src/main/java/at/hannibal2/skyhanni/api/CollectionAPI.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUInternalName.kt
Labels: Bug Fix - Sooner than Very Soon

#1229 Fix: Fixed two Scoreboard Patterns
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#1228 Removed Feature: Colored Visitor Name
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/VisitorConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorColorNames.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
Labels: Soon

#1230 Improvement: Added another gui for bits to claim
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
Labels: Soon

#1214 Improvement: Add event level up message to chat filter
  src/main/java/at/hannibal2/skyhanni/config/features/chat/FilterTypesConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Soon

#821 Improvement: HoverTips improvements
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzColor.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderLineTooltips.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon

#1146 Backend: Improved the data loading to use kotlin serialisation and fixed bug
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/HypixelPlayerApiJson.kt
  src/main/java/at/hannibal2/skyhanni/events/NeuProfileDataLoadedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishManager.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishMessages.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Soon, Backend

#1232 Backend: code cleanup in RenderLineTooltips
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderLineTooltips.kt
Labels: Backend

#1235 Backend: Add Mineshaft IslandType
  src/main/java/at/hannibal2/skyhanni/data/IslandType.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
Labels: Backend

#1238 Improvement: Add new Alpha Content to Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon

#1123 Improvement: Load Trophy Fishing from NEU
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/trophyfishing/TrophyFishingConfig.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/HypixelPlayerApiJson.kt
  src/main/java/at/hannibal2/skyhanni/events/NeuProfileDataLoadedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishManager.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishMessages.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Soon

#1231 Backend: Shorter inventory and sack amount
  src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/CroesusChestTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarBestSellMethod.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
Labels: Soon, Backend

#1234 Feature: Shwords saves to new file
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/Storage.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/local/VisualWordsJson.java
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/ModifyVisualWords.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/VisualWordGui.kt
Labels: Soon

#1128 Backend: ChatClickActionManager
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatClickActionManager.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishManager.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Soon, Waiting on Dependency PR, Backend

#1237 Improvement + Fix: Pests Rework
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/events/garden/pests/PestSpawnEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/garden/pests/PestUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenPlotAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestSpawn.kt
Labels: Bug Fix - Sooner than Very Soon

#1239 Fix: Lane Detection
  src/main/java/at/hannibal2/skyhanni/config/features/garden/laneswitch/LaneSwitchSoundSettings.java
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneCreator.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MovementSpeedDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1242 Fix: Typo in not clickable items
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
Labels: Bug Fix - Sooner than Very Soon

#1241 Fix: Lane Switch again
  src/main/java/at/hannibal2/skyhanni/features/misc/MovementSpeedDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#1177 Backend: Fixed usage of checkCurrentServerId()
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
Labels: Backend

#1243 Fix Crop milestones pest drops
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenCropMilestoneFix.kt
Labels: Bug Fix - Sooner than Very Soon

#1244 Fix: Fixed custom scoreboard issue with the cold line
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#1181 Feature: Plot Menu Highlighting
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/PlotIconConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/PlotMenuHighlightingConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenNextPlotPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenPlotIcon.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenPlotMenuHighlighting.kt
Labels: Soon

#1139 Feature: Totem Of Corruption Overlay & Effective Area
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/FishingConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/TotemOfCorruptionConfig.java
  src/main/java/at/hannibal2/skyhanni/features/fishing/TotemOfCorruption.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon

#1250 Fix: Event level up chat filter
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Bug Fix - Sooner than Very Soon

#1246 Fix: Duplicate chat prefix in pv loading
  src/main/java/at/hannibal2/skyhanni/data/ChatClickActionManager.kt
Labels: Bug Fix - Sooner than Very Soon

#1135 Improvement: Visitor Drops Statistics reset command
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
Labels: Soon

#1248 Improvement: Added wireframe as Totem of Corruption outline
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/TotemOfCorruptionConfig.java
  src/main/java/at/hannibal2/skyhanni/features/fishing/TotemOfCorruption.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon

#1245 Fix: Lane Switch Warning (part 5)
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MovementSpeedDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#1249 Fix: Fixed In-game Time in Scoreboard displaying 0 instead of 12
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1140 Improvement: Allow teleporting when in an infested plot
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestFinderConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestFinder.kt
Labels: Soon

#1252 Fix: Various limbo stats related fixes
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/limbo/LimboPlaytime.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/limbo/LimboTimeTracker.kt
Labels: Bug Fix - Sooner than Very Soon

#1253 Fix: Sensitivity Reducer + Mouse Lock incompatbility
  src/main/java/at/hannibal2/skyhanni/features/garden/SensitivityReducer.kt
Labels: Bug Fix - Sooner than Very Soon

#1255 Fix: Fixed Scoreboard Error in F3/M3 Boss Fight
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#1254 Improvement: Plot Menu Highlighting and isBeingPasted for Plot
  src/main/java/at/hannibal2/skyhanni/config/features/garden/PlotMenuHighlightingConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenPlotAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenPlotMenuHighlighting.kt
Labels: Soon

#1175 Feature: Added Highlighting for tab widgets.
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/TabWidgetSettings.kt
Labels: Soon

#1258 Internal Fix: RepoPattern and Tests
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
Labels: Backend

#1221 Improvement: Events Priority in Custom Scoreboard
  CONTRIBUTING.md
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/CustomScoreboardConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/DisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/EventsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvents.kt
Labels: Bug Fix - Sooner than Very Soon

#1259 Improvement: Add 4 more empty lines to custom scoreboard
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
Labels: Soon
