Repository hannibal002/SkyHanni, pull requests merged in 2024-01, with the labels that each got.

#859 Fix mushroom counter when farming sugar cane/cactus with Mooshroom Cow
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropSpeed.kt
Labels: Very Soon

#856 Remove flawless
  src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
Labels: Very Soon

#866 Update max reforge fortune for Fungi Cutter
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFStats.kt
Labels: Very Soon

#867 Fix: TiaHelper chatmessage
  src/main/java/at/hannibal2/skyhanni/features/inventory/tiarelay/Relay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/tiarelay/TiaRelayWaypoints.kt
Labels: Very Soon

#870 Don't count Bountiful as max reforge fortune on tools
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFStats.kt
Labels: Bug Fix - Sooner than Very Soon

#823 Backend: Add Dark Auction as IslandType and fix IslandType detection for dungeons
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandType.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#872 Tia Relay Helper: Suggest /togglemusic
  src/main/java/at/hannibal2/skyhanni/features/inventory/tiarelay/TiaRelayHelper.kt
Labels: Very Soon

#827 Minor fix: modify instead of block trophy fishing and sea creature messages
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/events/LorenzChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/SeaCreatureMessageShortener.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishMessages.kt
Labels: Bug Fix - Sooner than Very Soon

#833 Only show vacuum bag on your own vacuums
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#842 Added options to only show vermin tracker with vacuum on inventory an…
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/westvillage/VerminTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminTracker.kt
Labels: Bug Fix - Sooner than Very Soon

#877 Fix: Fix IslandType detection for The Rift
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
Labels: Bug Fix - Sooner than Very Soon

#878 Change: Changed description of Dungeon Filter
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.java
Labels: Very Soon

#883 Fix: Firesale Pattern update
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Bug Fix - Sooner than Very Soon

#892 Fix Poisoned Candy patterns
  src/main/java/at/hannibal2/skyhanni/features/chat/CompactSplashPotionMessage.kt
Labels: Bug Fix - Sooner than Very Soon

#894 Fix: Fixed Trophy Fish chat message Regex
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishMessages.kt
Labels: Bug Fix - Sooner than Very Soon

#897 Fix: Title rendering layering
  src/main/java/at/hannibal2/skyhanni/data/TitleManager.kt
Labels: Bug Fix - Sooner than Very Soon

#896 Fix: Item rendering layering
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Bug Fix - Sooner than Very Soon

#899 Fix: Hide gem message
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Bug Fix - Sooner than Very Soon

#900 Jacob Contest: Grammar fixes & clickable chat for /calendar
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
Labels: Bug Fix - Sooner than Very Soon

#845 Mark carrot/pumpkin fortune as completed when giving to Carrolyn after already done
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
Labels: Bug Fix - Sooner than Very Soon

#832 Add ability to get unique visitors served without Green Thumb
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
Labels: Very Soon

#865 Add fire hide tab list
  src/main/java/at/hannibal2/skyhanni/config/features/misc/compacttablist/CompactTabListConfig.java
  src/main/java/at/hannibal2/skyhanni/events/LorenzEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/SkipTabListLineEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/RenderColumn.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/TabListRenderer.kt
Labels: Very Soon

#884 Change: "Dungeon Filter" toggle changed to list
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.java
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonChatFilter.kt
Labels: Very Soon

#907 Feature: ShiftClickNPCSell
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ShiftClickNPCSell.kt
Labels: Very Soon

#918 Fix: Hatcessory detection
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
Labels: Very Soon

#924 Fix: GuiEditor Key working in NEUs PV textboxes
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#927 Fix Frozen Treasure Tracker showing incorrect Compact Procs number
  src/main/java/at/hannibal2/skyhanni/features/event/jerry/frozentreasure/FrozenTreasureTracker.kt
Labels: Bug Fix - Sooner than Very Soon

#928 Fix daily city project reminder triggering for released projects
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#689 Internal Change: Cleanup calculate()
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Very Soon

#850 Feature: Pet Item Display
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/pets/PetConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/PetItemDisplay.kt
Labels: Very Soon

#931 Fix names of Crystal Hollows mining areas
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsNamesInCore.kt
Labels: Bug Fix - Sooner than Very Soon

#898 Check if sneaking for optimal speed in garden
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenOptimalSpeed.kt
Labels: Very Soon

#910 Add hotswap agent support
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/test/hotswap/HotswapSupport.kt
  src/main/java/at/hannibal2/skyhanni/test/hotswap/HotswapSupportHandle.kt
  src/main/java/at/hannibal2/skyhanni/test/hotswap/HotswapSupportImpl.kt
  src/main/resources/hotswap-agent.properties
Labels: Very Soon

#869 add crop milestone commands
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/CropType.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingMilestoneCommand.kt
Labels: Very Soon

#919 Feature: SkyblockXPInChat
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.java
  src/main/java/at/hannibal2/skyhanni/data/ActionBarStatsData.kt
  src/main/java/at/hannibal2/skyhanni/events/ActionBarValueUpdate.kt
  src/main/java/at/hannibal2/skyhanni/events/LorenzActionBarEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/SkyblockXPInChat.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
Labels: Very Soon

#811 Backend: ItemCategory + better LorenzeRarity
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.java
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/CachedItemData.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemCategory.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzRarity.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
Labels: Very Soon

#923 Feature: Option to show visitor shopping list in Farming Islands
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/ShoppingListConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
Labels: Very Soon

#939 Change: Pet item display scale
  src/main/java/at/hannibal2/skyhanni/config/features/misc/pets/PetConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/PetItemDisplay.kt
Labels: Very Soon

#746 Backend: DelayedRun sync
  src/main/java/at/hannibal2/skyhanni/utils/DelayedRun.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Very Soon

#941 Fix: Added cooldown to Garden Warp Commands
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenWarpCommands.kt
Labels: Bug Fix - Sooner than Very Soon

#741 Feature: Extra Harp Features
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/helper/HelperConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Very Soon

#937 Feature: Volcano Explosivity Display
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/crimsonisle/CrimsonIsleConfig.java
  src/main/java/at/hannibal2/skyhanni/features/nether/VolcanoExplosivityDisplay.kt
Labels: Very Soon

#942 feature: TALBOTS_THEODOLITE support
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbility.kt
Labels: Very Soon

#926 Feature: Colored month in scoreboard
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiIngameHook.kt
Labels: Very Soon

#949 Allow putting Water Bottles into Potion Bag
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
Labels: Very Soon

#950 Replaced Npc with NPC (typos)
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/test/PriceSource.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
Labels: Very Soon, Bug Fix - Sooner than Very Soon

#959 Fix: NPE in Harp Quick Restart
  src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
Labels: Very Soon, Bug Fix - Sooner than Very Soon

#956 Feature: Disable Fishing Profit/SC Tracker in Kuudra
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/SeaCreatureTracker.kt
Labels: Very Soon

#953 Fix: Overlay Rendering Layer
  src/main/java/at/hannibal2/skyhanni/data/RenderData.kt
  src/main/java/at/hannibal2/skyhanni/data/TitleManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Very Soon, Bug Fix - Sooner than Very Soon

#952 Skip unavailable experiments for number of clicks
  src/main/java/at/hannibal2/skyhanni/features/misc/SuperpairsClicksAlert.kt
Labels: Very Soon, Bug Fix - Sooner than Very Soon
