Repository hannibal002/SkyHanni, pull requests merged in 2024-12, with the labels that each got.

#3011 Fix: Connection error messages
  src/main/java/at/hannibal2/skyhanni/data/bazaar/HypixelBazaarFetcher.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
Labels: Bug Fix

#2970 Backend: Graph Editor Directional Edge Support
  src/main/java/at/hannibal2/skyhanni/config/features/dev/GraphConfig.java
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon, Backend

#3015 Fix: Stray Timer w/Hitman Eggs
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTimer.kt
Labels: Bug Fix

#3012 Fix: Time Tower new profiles
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBlockOpen.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTimeTowerManager.kt
Labels: Bug Fix

#3007 Fix: Anita Medal Display for Visitor
  src/main/java/at/hannibal2/skyhanni/features/garden/AnitaMedalProfit.kt
Labels: Bug Fix

#3005 Fix: Supercraft Spelling
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorSupercraft.kt
Labels: Bug Fix

#3010 Fix: Hoppity Unclaimed Eggs
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
Labels: Bug Fix

#3013 Fix: Stray Hoard & Golden Click
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
Labels: Bug Fix

#3006 Fix: Custom Scoreboard in Kuudra
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
Labels: Bug Fix

#3018 Fix: Golden Fish Timer
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GoldenFishTimer.kt
Labels: Bug Fix

#3016 Fix: Crimson Isle Quest Parsing
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/CrimsonIsleReputationHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/QuestLoader.kt
Labels: Bug Fix

#3019 Fix: Defensing
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
Labels: Bug Fix

#3009 Fix + Improvement: Stash Compact
  src/main/java/at/hannibal2/skyhanni/config/features/chat/StashConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/StashCompact.kt
Labels: Bug Fix

#3021 Fix: Limbo playtime detailed sorting
  src/main/java/at/hannibal2/skyhanni/features/misc/limbo/LimboPlaytime.kt
Labels: Bug Fix

#2941 Backend: Add Minecraft Version to jar file name
  build.gradle.kts
  src/main/java/at/hannibal2/skyhanni/features/misc/update/CustomGithubReleaseUpdateSource.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/UpdateManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/system/PlatformUtils.kt
Labels: Soon, Backend

#3008 Improvement: Detect New Year Cake Baker Claims
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
Labels: Soon

#2805 Feature: Re-color TT Chocolate Gains
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
Labels: Soon

#2753 Backend: Migrate some events to be GenericSkyHanniEvent
  src/main/java/at/hannibal2/skyhanni/api/DataWatcherAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/EntityData.kt
  src/main/java/at/hannibal2/skyhanni/data/EntityMovementData.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/events/CheckRenderEntityEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/DataWatcherUpdatedEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/EntityCustomNameUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/EntityEquipmentChangeEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/EntityMoveEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/entity/EntityDisplayNameEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonCleanEnd.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonCopilot.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHideItems.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonLividFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/event/UniqueGiftingOpportunitiesFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/ChumBucketHider.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingHookDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorListener.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ContributorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ExpOrbsOnGroundHider.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/FixGhostEntities.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/HideFarEntities.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/LesserOrbHider.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pets/PetNametag.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangHider.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/VoltHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/CraftRoomHolographicMob.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/DanceRoomHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/RiftLavaMazeParkour.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/RiftUpsideDownParkour.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/TubulatorParkour.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/RiftGunthersRace.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/RiftHorsezookaHider.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/BlazeSlayerClearView.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/enderman/EndermanSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinNetHandlerPlayClient.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinRenderManager.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/UpdateDataWatcherEventPatch.java
Labels: Soon, Backend

#2939 Improvement: Cake Tracker Scrollable and AH Tips
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/CakeTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Soon

#3000 Improvement: chocolate factory wording
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTimeTowerManager.kt
Labels: Soon

#2984 Improvement: Add Pest Traps tab widget
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/TabWidgetDisplay.kt
Labels: Soon, Wrong Title/Changelog

#2807 Improvement: Option for Disabling Tracker Search
  src/main/java/at/hannibal2/skyhanni/config/features/misc/TrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon

#2907 Improvement: CF Stray Filter
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryRabbitWarningConfig.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/HoppityRabbitTexturesJson.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityTextureHandler.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryScreenFlash.kt
Labels: Soon

#3029 Backend: Detect Obsidian & Pure Gold in Mineshafts
  src/main/java/at/hannibal2/skyhanni/features/mining/OreBlock.kt
Labels: Backend

#3028 Backend: Add mid-tier Umber
  src/main/java/at/hannibal2/skyhanni/features/mining/OreBlock.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/OreType.kt
Labels: Backend

#3030 Backend: Move the location of some events to more appropriate packages
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/NEURenderEvent.kt
  src/main/java/at/hannibal2/skyhanni/data/GardenCropMilestones.kt
  src/main/java/at/hannibal2/skyhanni/data/GuiData.kt
  src/main/java/at/hannibal2/skyhanni/events/DungeonStartEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/bazaar/BazaarOpenedProductEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/diana/BurrowDetectEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/diana/BurrowDugEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/diana/BurrowGuessEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/dungeon/DungeonBlockClickEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/dungeon/DungeonBossPhaseChangeEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/dungeon/DungeonBossRoomEnterEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/dungeon/DungeonCompleteEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/dungeon/DungeonEnterEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/dungeon/DungeonStartEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/garden/farming/CropMilestoneUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/CroesusChestTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonBossAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonCopilot.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonDeathCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHighlightClickedBlocks.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonMilestonesDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonSecretChime.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/AllBurrowsList.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaFixChat.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowParticleFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinPetWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/SoopyGuessBurrow.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropSpeedMeter.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/GardenCropMilestoneInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/quiver/QuiverWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarBestSellMethod.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinNEUOverlay.java
Labels: Backend

#3033 Fix: Arguments being swapped in shtranslateadvanced
  src/main/java/at/hannibal2/skyhanni/features/chat/translation/Translator.kt
Labels: Bug Fix

#3034 Backend: Add the regex 101 link when a pattern fails
  detekt/src/main/kotlin/RepoPatternElement.kt
  detekt/src/main/kotlin/repo/RepoPatternRegexTest.kt
Labels: Backend

#3031 Fix red errors
  src/main/java/at/hannibal2/skyhanni/events/chat/TabCompletionEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyChatCommands.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/tabcomplete/TabComplete.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/tabcomplete/WarpTabComplete.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/AccessorEventBus.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/ExtendedColorPatch.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinGuiChat.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinItemStack.java
Labels: Bug Fix

#3023 Fix: sulphur skitter box visual slightly too small
  src/main/java/at/hannibal2/skyhanni/features/nether/SulphurSkitterBox.kt
Labels: Bug Fix

#3027 Fix: Decrease Next Visitor Timer on Pest Kill
  src/main/java/at/hannibal2/skyhanni/events/garden/pests/PestKillEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorTimer.kt
Labels: Bug Fix

#3036 Fix: CS Queue Line Error
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventQueue.kt
Labels: Bug Fix

#2823 Improvement + Backend: ServerTimeMark
  src/main/java/at/hannibal2/skyhanni/data/MinecraftData.kt
  src/main/java/at/hannibal2/skyhanni/events/minecraft/ServerTickEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GoldenFishTimer.kt
  src/main/java/at/hannibal2/skyhanni/utils/ServerTimeMark.kt
Labels: Soon

#2859 Improvement: Option for optimal speed warning when not wearing rancher's
  src/main/java/at/hannibal2/skyhanni/config/features/garden/optimalspeed/OptimalSpeedConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenOptimalSpeed.kt
Labels: Soon

#2962 Backend: Migrate more stuff to work on 1.12
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/NeuReforgeJson.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/events/GuiContainerEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/MinionCraftHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SnakeGame.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryKeybinds.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TestChatCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/BlockUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Backend

#3043 Backend: A few more things for making 1.12 work in skyhanni
  src/main/java/at/hannibal2/skyhanni/data/ItemClickData.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/test/PacketTest.kt
  src/main/java/at/hannibal2/skyhanni/utils/HolographicEntities.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/EntityCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/PacketCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/ItemStackTypeAdapterFactory.kt
  versions/mapping-1.12.2-1.8.9.txt
  versions/mapping-1.16.5-forge-1.12.2.txt
Labels: Backend

#3049 Fix: total collected regex
  src/main/java/at/hannibal2/skyhanni/api/CollectionAPI.kt
Labels: Bug Fix

#3053 Fix: NeuRenderEvent
  src/main/java/at/hannibal2/skyhanni/events/NEURenderEvent.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinNEUOverlay.java
Labels: Bug Fix

#3032 Improvement: Adds a chat filter to being hit by a venom shot
  src/main/java/at/hannibal2/skyhanni/features/chat/ArachneChatMessageHider.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon

#3037 Fix: Composter message spam
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
Labels: Bug Fix

#3026 Fix: Custom Scoreboard Player Count Including Offline Players
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
Labels: Bug Fix

#3050 Fix: Non Transparent Backgrounds in Notification
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/GuardianReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/UltraRareBookAlert.kt
Labels: Bug Fix

#3046 Fix: New Rift CS Lines
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventRift.kt
Labels: Bug Fix

#3055 Improvement + Backend: Mining event sending check
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningEventConfig.java
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
Labels: Soon, Backend

#3038 Backend: Sulphur Skitter performance updates
  src/main/java/at/hannibal2/skyhanni/features/nether/SulphurSkitterBox.kt
Labels: Soon, Backend

#2991 Feature: Hitman Statistics
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/hitman/HitmanAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/hitman/HitmanSlots.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockTime.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyblockSeason.kt
Labels: Soon

#2729 Backend: TimeLimitedCache
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/events/LorenzEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHighlightClickedBlocks.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/ChumBucketHider.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/HideMobNames.kt
  src/main/java/at/hannibal2/skyhanni/features/summonings/SummoningSoulsName.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeLimitedCache.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeLimitedSet.kt
Labels: Soon, Backend

#3045 Improvement: `/shtps` wording
  src/main/java/at/hannibal2/skyhanni/features/misc/TpsCounter.kt
Labels: Soon

#3057 Fix + Backend: Allow removing items with ReplaceItemEvent
  src/main/java/at/hannibal2/skyhanni/events/render/gui/ReplaceItemEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenPlotIcon.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/CarnivalShopHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/EssenceShopHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/UserLuckBreakdown.kt
Labels: Bug Fix, Backend

#3060 Backend: DiscordStatus Formatting
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
Labels: Backend

#2900 Feature: Reopen last storage command
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/commands/OpenLastStorage.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
Labels: Soon

#3066 Fix: Experiments Profit Tracker
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
Labels: Bug Fix

#3068 Fix: Skill Detection
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
Labels: Bug Fix

#3056 Backend: Compacting CFStats.updateDisplay
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
Labels: Soon, Backend

#2973 Feature: Hoppity Live Display Date/Time
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEventSummaryLiveDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
  src/main/java/at/hannibal2/skyhanni/utils/SimpleTimeMark.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyblockSeason.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
Labels: Soon

#3071 Backend: Graph Editor Description for one way edges
  src/main/java/at/hannibal2/skyhanni/config/features/dev/GraphConfig.java
Labels: Backend

#3070 Improvement: Colorfus /shcommand aliases
  src/main/java/at/hannibal2/skyhanni/features/commands/HelpCommand.kt
Labels: Soon

#3074 Fix: Cruzx Display
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/CruxTalismanDisplay.kt
Labels: Bug Fix

#3054 Fix + Feature: Chocolate Factory Party Time 🥳️‍🌈
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryCustomReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTooltipCompact.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
Labels: Bug Fix, Waiting on Dependency PR

#3076 Fix: Event Stats CF Leaderboard Edge Case
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
Labels: Bug Fix

#3073 Fix: Miniboss Amount
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
Labels: Bug Fix

#3080 Fix: SuperPairs/Experiment Tracker Edge Case
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/SuperpairDataDisplay.kt
Labels: Bug Fix

#3079 Fix: Special Rabbit Flash
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayWarning.kt
Labels: Bug Fix

#3078 Remove: Rip Out Half-Baked Hitman Replace Feature
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/hitman/HitmanSlots.kt
Labels: Soon

#3075 Fix: Hitman Full Time
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/hitman/HitmanAPI.kt
  src/main/java/at/hannibal2/skyhanni/utils/SimpleTimeMark.kt
Labels: Bug Fix

#3081 Fix: Misc Party Mode
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggDisplayManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
Labels: Bug Fix

#3003 Fix: replace roman numeral v2
  src/main/java/at/hannibal2/skyhanni/features/misc/ReplaceRomanNumerals.kt
Labels: Bug Fix

#3088 Fix: Vacuum Bag Item Stack after 1k Pests
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
Labels: Bug Fix

#3082 Fix: shtrackcollection not counting Youngite and Obsolite when tracking timite
  src/main/java/at/hannibal2/skyhanni/features/misc/CollectionTracker.kt
Labels: Bug Fix

#3086 Fix: Hoppity Call Warning on World Change
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCallWarning.kt
Labels: Bug Fix

#3083 Improvement: Graph Navigation performance boost
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
Labels: Soon

#3084 Fix: Skill overflow edge case
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
Labels: Bug Fix

#3085 Backend: Added /shtestactionbar and more debug
  src/main/java/at/hannibal2/skyhanni/data/ActionBarData.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyBlockIslandTest.kt
  src/main/java/at/hannibal2/skyhanni/test/TestBingo.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
Labels: Soon, Backend

#3040 Backend: Commands to Guide, move Party Commands
  CONTRIBUTING.md
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyCommands.kt
Labels: Backend

#3004 Backend: Move Next Jacobs Contest, Best Crop Milestone & Jyrre Timer to Renderable
  src/main/java/at/hannibal2/skyhanni/features/event/winter/JyrreTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenBestCropTime.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Backend

#3095 Improvement: CF Shop non purhcaseable
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateShopPrice.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Soon

#3096 Feature: Carrolyn
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
  src/main/java/at/hannibal2/skyhanni/events/ItemClickEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/OdgerWaypoint.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/CarrolynHelper.kt
Labels: Soon

#3093 Fix: Reforge Helper NPE
  src/main/java/at/hannibal2/skyhanni/features/inventory/ReforgeHelper.kt
Labels: Bug Fix

#3089 Improvement: Gemstone unlock material name
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Soon

#3090 Improvement: opt in persistent search
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/data/model/TextInput.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/GuiOptionEditorUpdateCheck.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphNodeEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/SearchTextInput.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Searchable.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon

#3092 Backend: Discord RCP /shdebug
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordRPCManager.kt
Labels: Soon, Backend

#3094 Improvement + Fix: Craftable Item list
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/craft/CraftableItemList.kt
Labels: Bug Fix

#3099 Fix: Special Zealot Highlight
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/MobHighlight.kt
Labels: Bug Fix

#3104 Backend: Better formatting settings
  .editorconfig
  detekt/detekt.yml
  src/main/java/at/hannibal2/skyhanni/data/BossbarData.kt
Labels: Backend

#3103 Backend: Remove Unused Config Option
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
Labels: Backend

#3114 Backend: More crop reading error data
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/FarmingContestAPI.kt
Labels: Soon, Backend

#3105 Fix: Skill progress NumberFormatException
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
Labels: Bug Fix

#3109 Backend: Contributor Rabbit Name
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionData.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/ReplaceHoppityWithContributor.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ContributorManager.kt
Labels: Soon, Backend

#3112 Backend: Added /shdebugvisualwords
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/ModifyVisualWords.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/VisualWordGui.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon, Backend

#3111 Fix up the installation guide
  docs/INSTALLING.md
Labels: Bug Fix

#3110 Fix: shwords causing blank messages in chat
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/ModifyVisualWords.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiUtilRenderComponents.java
Labels: Bug Fix

#3118 Fix: Kuudra Lines in CS
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
Labels: Bug Fix

#3108 Fix: Class Cast Error in Stray Warning
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayWarning.kt
Labels: Bug Fix

#3113 Improvement + Backend: Roman Allow List
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementSlayer.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ReplaceRomanNumerals.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerRngMeterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Soon, Backend

#3121 Fix: Farming Skill XP
  .editorconfig
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
Labels: Bug Fix

#3122 Improvement: Profit per Anita Medal
  src/main/java/at/hannibal2/skyhanni/features/garden/AnitaMedalProfit.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
Labels: Soon

#3107 Backend: Add more error logging to trevor solver
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorSolver.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Bug Fix, Backend

#3124 Fix: Force zero price for glitched Gemstone Collection item
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUInternalName.kt
Labels: Bug Fix

#3130 Backend: Bump NEU depend to 2.5.0
  build.gradle.kts
Labels: Backend

#3134 Fix: Typo in README.md
  README.md
Labels: Bug Fix

#3126 Improvement: Default Custom Scoreboard Config
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/DisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/EventsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardConfigElement.kt
Labels: Wrong Title/Changelog

#3129 Fix: Stray Timer not Rendering When not Hoppity's
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTimer.kt
Labels: Bug Fix

#3127 Fix: Moby Highlighted by Trapper Highlight
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
Labels: Bug Fix

#3128 Fix: Stray Tracker Staying in Party Mode
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
Labels: Bug Fix

#3133 Fix: SkyblockStat parse error
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
Labels: Bug Fix

#3131 Fix: Heat "null" on Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementHeat.kt
Labels: Bug Fix, Wrong Title/Changelog

#3135 Fix: page scrolling in neu storage
  src/main/java/at/hannibal2/skyhanni/features/inventory/PageScrolling.kt
Labels: Bug Fix

#3138 fix heat
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ChunkedStatsLine.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementHeat.kt
Labels: Soon, Bug Fix

#3136 Improvement: HEDGEHOG in /ff
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFInfos.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FarmingItems.kt
Labels: Soon

#3137 Improvement: load trophy fish data by talking with odger
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishManager.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishMessages.kt
Labels: Soon

#3139 Improvement: Damage Indicator forever
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.java
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/SeaCreatureFeatures.kt
Labels: Soon

#3140 Fix: End Portal Fumes
  src/main/java/at/hannibal2/skyhanni/features/misc/NonGodPotEffectDisplay.kt
Labels: Bug Fix
