Repository hannibal002/SkyHanni, pull requests merged in 2024-11, with the labels that each got.

#2863 Improvement: Add spirit sceptre message to patterns
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Soon

#2809 Backend: More preprocessor mappings
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
  versions/mapping-1.12.2-1.8.9.txt
  versions/mapping-1.16.5-1.16.5-forge.txt
  versions/mapping-1.16.5-forge-1.12.2.txt
  versions/mapping-1.21-1.16.5.txt
Labels: Backend

#2872 Backend: Add compat files for preprocessing
  CONTRIBUTING.md
  src/main/java/at/hannibal2/skyhanni/features/misc/HideArmor.kt
  src/main/java/at/hannibal2/skyhanni/utils/DelayedRun.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/EffectsCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/EnchantmentsCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/EntityCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/ItemCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/PacketCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/World.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/WorldCompat.kt
Labels: Soon, Backend

#2870 Backend: Fix NeuInternalName.equals
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/SprayFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/GuiOptionEditorUpdateCheck.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/kloon/KloonHacking.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/RiftLarva.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/RiftHorsezookaHider.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyBlockIslandTest.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Soon, Backend

#2874 Fix: Bingo found by
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/BingoJson.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardTips.kt
Labels: Soon, Bug Fix

#2856 Backend: `messageHistory` Length Config Option
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.java
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
Labels: Soon, Backend

#2774 Backend: Remove Hard-Coded Skull Textures
  detekt/detekt.yml
  detekt/src/main/kotlin/userepo/SkullTexturesUseRepo.kt
  detekt/src/main/kotlin/userepo/UseRepoRuleSetProvider.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/IslandExceptions.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/FlareDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHideItems.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/ShowFishingItemName.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/ThunderSparksHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GoldenFishTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/StereoHarmonyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryShortcut.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationTableAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventType.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/LesserOrbHider.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/VisualWordGui.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangHighlights.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/VoltHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/RiftLarva.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/RiftOdonata.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/enderman/EndermanSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/summonings/SummoningSoulsName.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkullTextureHolder.kt
Labels: Soon, Backend

#2845 Improvement: Focus Mode hide menu
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/FocusModeConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/FocusMode.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
Labels: Soon

#2827 Fix: Ore Event Pure Ores
  src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/MiningCommissionsBlocksColor.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/OreBlock.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/OreType.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
Labels: Bug Fix

#2108 Improvement + Backend: Dungeon Features Cleanup
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/MobFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHighlightClickedBlocks.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonLividFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonSecretChime.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/HighlightDungeonDeathmite.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/TerracottaPhase.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementLobbyCode.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
  src/main/java/at/hannibal2/skyhanni/utils/BlockUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/MobUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon, Backend

#2738 Backend: Remove more neu dependent code !!!
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProcessor.kt
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/SkyHanniModule.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/GuiData.kt
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/events/NeuEventWrappers.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/FixNEUHeavyPearls.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pets/PetExpTooltip.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiContainerHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntityHorse.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinNEUOverlay.java
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUCalculator.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUVersionCheck.kt
  src/main/java/at/hannibal2/skyhanni/utils/system/PlatformUtils.kt
Labels: Soon, Backend

#2877 Improvement: SBO inquis support
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
Labels: Soon

#2866 Fix: Pest Count
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
Labels: Bug Fix

#2868 Fix: Text Deleting on Mac
  src/main/java/at/hannibal2/skyhanni/data/model/TextInput.kt
Labels: Bug Fix

#2871 Fix: White player names and too liberal all chat replacement.
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerNameFormatter.kt
Labels: Soon, Bug Fix

#2865 Backend: Alter regex to account for Champion XP number
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
Labels: Soon, Backend

#2588 Feature: Option to ignore Spaceman in visitor shopping list
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/ShoppingListConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
Labels: Soon

#2808 Fix: Skill Overflow
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/NeuSkillLevelJson.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillTooltip.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillUtil.kt
Labels: Bug Fix

#2660 Improvement: Add pathfinding to Halloween baskets 2024
  src/main/java/at/hannibal2/skyhanni/config/features/event/waypoints/HalloweenBasketConfig.java
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/model/GraphNodeTag.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/EventWaypoint.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/halloween/Basket.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/halloween/BasketEntrance.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/halloween/BasketWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphNodeEditor.kt
Labels: Soon

#2878 Fix + Backend: No more random chat + CircularList
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/event/spook/TheGreatSpook.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/CircularList.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Soon, Bug Fix, Backend

#2881 Backend: Allow building without detekt
  .github/workflows/build.yml
  build.gradle.kts
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
Labels: Soon, Backend

#2879 Backend: Detekt Label
  .github/workflows/detekt.yml
Labels: Backend

#2882 Backend: Use some preprocessed compat methods
  .github/workflows/detekt.yml
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHideItems.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonLividFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalZombieShootout.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/ChumBucketHider.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/FixGhostEntities.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangHider.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/VoltHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/test/command/CopyNearbyEntitiesCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityOutlineRenderer.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/EntityCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/Pattern.java
  src/main/java/at/hannibal2/skyhanni/utils/compat/Pattterns.java
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Soon, Backend

#2883 Backend: More mapping and make compat files mostly work for 1.16
  .github/workflows/detekt.yml
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/EntityCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/GuiScreenUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/ItemCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/PacketCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  versions/mapping-1.16.5-forge-1.12.2.txt
Labels: Soon, Backend

#2884 Backend: Changes SBO to Volc in Inquis Detection for Clarity
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
Labels: Backend

#2889 Backend: Make unusable enchants be valid by the enchant parser
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
Labels: Backend

#2888 Fix: Personal Compactor Hypixel Id
  src/main/java/at/hannibal2/skyhanni/features/inventory/PersonalCompactorOverlay.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Soon, Bug Fix

#2901 Fix: Dojo in Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventDojo.kt
Labels: Bug Fix

#2896 Fix: Rabbit the Fish detection in middle slot
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityRabbitTheFishChecker.kt
Labels: Bug Fix

#2903 Fix: items not loading properly in skyhanni
  src/main/java/at/hannibal2/skyhanni/events/NeuEventWrappers.kt
Labels: Bug Fix

#2892 Fix: Scoreboard Hiding
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiIngame.java
Labels: Bug Fix

#2904 Fix: Island Area
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
Labels: Bug Fix

#2887 Fix: Deep Caverns Guide
  src/main/java/at/hannibal2/skyhanni/features/mining/DeepCavernsGuide.kt
Labels: Bug Fix

#2894 Fix: Goblin Mining Event Render Issue
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventType.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Bug Fix

#2890 Improvement: More DateFormatter in Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/DisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/data/DateFormat.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementLobbyCode.kt
Labels: Soon

#2794 Improvement: Lava Replacement Dungeons/Kuudra only addition
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/LavaReplacementConfig.java
  src/main/java/at/hannibal2/skyhanni/features/fishing/LavaReplacement.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinBlockLiquid.java
Labels: Soon

#2906 Fix: double sending locraw
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
Labels: Bug Fix

#2908 Fix: Stray Rabbit Requirement Pattern
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
Labels: Bug Fix

#2910 Fix: Hoppity Softlock Round 2
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityRabbitTheFishChecker.kt
Labels: Bug Fix

#2749 Feature + Improvement: Hoppity Event Card Live Display
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEventSummaryCFReminderConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEventSummaryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEventSummaryLiveDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
  src/main/java/at/hannibal2/skyhanni/utils/GenericWrapper.kt
  src/main/java/at/hannibal2/skyhanni/utils/SimpleTimeMark.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockTime.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/BaseGsonBuilder.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkyHanniTypeAdapters.kt
Labels: Soon, Waiting on Hypixel

#2899 Backend: HoppityAPI Improvements
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsShared.kt
Labels: Soon, Backend

#2829 Improvement: Carry Tracker Remove
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CarryTracker.kt
Labels: Soon

#2912 Backend: Cleanup Detekt and add CustomAnnotationSpacing
  build.gradle.kts
  detekt/baseline.xml
  detekt/detekt.yml
  detekt/src/main/kotlin/formatting/CustomAnnotationSpacing.kt
  detekt/src/main/kotlin/formatting/CustomCommentSpacing.kt
  detekt/src/main/kotlin/formatting/FormattingRuleSetProvider.kt
  detekt/src/main/kotlin/grammar/AvoidBritishSpelling.kt
  detekt/src/main/kotlin/imports/CustomImportOrdering.kt
  detekt/src/main/kotlin/userepo/SkullTexturesUseRepo.kt
  src/main/java/at/hannibal2/skyhanni/data/BossbarData.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Backend

#2913 colon, print, skull texture
  src/main/java/at/hannibal2/skyhanni/data/ProfileStorageData.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/test/command/CopyNearbyEntitiesCommand.kt
Labels: Soon

#2847 Backend: Respect minecraft nullability in more places
  src/main/java/at/hannibal2/skyhanni/events/ChatHoverEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/PrecisionMiningHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/QuickModMenuSwitch.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ReplaceRomanNumerals.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/TabLine.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/RenderGlobalHook.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  versions/1.8.9/detekt/baseline.xml
  versions/1.8.9/shots.txt
Labels: Soon, Backend

#2916 Backend: Remove Deprecated Color.withAlpha
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/MobHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHideItems.kt
  src/main/java/at/hannibal2/skyhanni/features/event/UniqueGiftingOpportunitiesFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/event/jerry/HighlightJerries.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GoldenFishTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/HighlightVisitorsOutsideOfGarden.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/GuardianReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/UltraRareBookAlert.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/HighlightMiningCommissionMobs.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MarkedPlayerManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/colosseum/BlobbercystsHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveDefenseBlocks.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/RiftLarva.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/RiftOdonata.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/PunchcardHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/HellionShieldHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/enderman/EndermanSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/RenderLivingEntityHelper.kt
  src/main/java/at/hannibal2/skyhanni/test/WorldEdit.kt
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Backend

#2917 Backend: Add Conditions to Detekt Label Adding/Removing
  .github/workflows/detekt.yml
Labels: Backend

#2918 Backend: Detekt Concurrency
  .github/workflows/detekt.yml
  .github/workflows/pr-check.yml
Labels: Backend

#2928 Fix: Two Broken Regex(-Tests)
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pets/PetNametag.kt
Labels: Bug Fix

#2930 Backend: Add REGEX-FAIL and fix some regex and tests
  .live-plugins/regexr/plugin.kts
  CONTRIBUTING.md
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerChatManager.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/PowderMiningChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/StashCompact.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonBossAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonCleanEnd.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/CarnivalShopHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/FossilExcavatorAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/RiftGunthersRace.kt
Labels: Soon, Backend

#2929 Backend: Remove deprecated Regex Methods
  src/main/java/at/hannibal2/skyhanni/api/CollectionAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/GardenCropMilestones.kt
  src/main/java/at/hannibal2/skyhanni/data/GardenCropUpgrades.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/MaxwellAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/winter/UniqueGiftCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/UpgradeReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenCropMilestoneFix.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterInventoryNumbers.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/FarmingContestAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/GardenInventoryNumbers.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/LogBookStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/AuctionsHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/DojoRankDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/MaxPurseItems.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/StatsTuning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/auctionhouse/AuctionHouseCopyUnderbidPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarCancelledBuyOrderClipboard.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTooltipStray.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateShopPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ServerRestartTitle.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pets/CurrentPetDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/FirePillarDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/RegexUtils.kt
Labels: Backend

#2932 Fix: Maxwell & BitsAPI saving alpha stuff
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/MaxwellAPI.kt
Labels: Bug Fix

#2933 msg to detekt
  buildSrc/src/main/kotlin/skyhannibuildsystem/ChangelogVerification.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/LogBookStats.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/FirePillarDisplay.kt
Labels: Soon, Wrong Title/Changelog

#2924 Fix: Acaricus Cap Timer
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/RiftAgaricusCap.kt
Labels: Soon, Bug Fix

#2926 Fix: BitsAPI
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
Labels: Bug Fix

#2921 Fix: SkillAPI
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
Labels: Bug Fix

#2923 Fix: Widget Update
  src/main/java/at/hannibal2/skyhanni/data/ProfileStorageData.kt
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
Labels: Bug Fix, Detekt

#2922 Fix: Barn Fishing Timer
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingTimer.kt
Labels: Bug Fix

#2915 Improvement: Better Custom Scoreboard Debug
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
Labels: Soon

#2237 Feature: New Year Cake Tracker
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/CakeTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon

#2936 Fix: Rift mobs can't be corrupted or runic
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
Labels: Bug Fix

#2931 Backend: Add regex test detekt rule
  detekt/detekt.yml
  detekt/src/main/kotlin/repo/RepoPatternRegexTest.kt
  detekt/src/main/kotlin/repo/RepoRuleSetProvider.kt
  detekt/src/main/kotlin/repo/SkullTexturesUseRepo.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#2935 Backend: Add ScoreboardPattern Regex Tests
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Backend

#2938 Fix: Pre-Fix Hoppity/CF
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityRabbitTheFishChecker.kt
Labels: Bug Fix

#2942 Backend: Even more ScoreboardPattern regexes
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Backend

#2944 Backend: Remove NEUItems.getPrice()
  src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/SlayerAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/endernodetracker/EnderNodeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishFillet.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/AnitaMedalProfit.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/GardenComposterInventoryFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FortuneUpgrades.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/SkyMartCopperPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenNextPlotPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/PowerStoneGuideFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/auctionhouse/AuctionHouseCopyUnderbidPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/CraftMaterialsFromBazaar.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateShopPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/craft/CraftableItemList.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ProfitPerExcavation.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/ProfitPerMineshaftCorpse.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Backend

#2943 Backend: Remove unused and minimal used Deprecated Methods
  src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/ActionBarData.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/SlayerAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/translation/Translator.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/tabcomplete/GetFromSacksTabComplete.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/SoopyGuessBurrow.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/NumberUtil.kt
  src/main/java/at/hannibal2/skyhanni/utils/RegexUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Backend

#2950 Fix: Fisherman Attribute
  src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/AttributeAPI.kt
Labels: Bug Fix

#2949 Backend: Detekt VarCouldBeVal
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/CompactBestiaryChatMessage.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/FlareDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/MobFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostData.kt
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalZombieShootout.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/SoopyGuessBurrow.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityNpc.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/SeaCreatureFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/ShowFishingItemName.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenPlotIcon.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenPlotMenuHighlighting.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorColorNames.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/quiver/QuiverWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/PowerStoneGuideFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ReforgeHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SkyblockGuideHighlightFeature.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/tiarelay/TiaRelayHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/UserLuckBreakdown.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/AdvancedPlayerList.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/Enchant.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/reminders/ReminderManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/CraftRoomHolographicMob.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/PunchcardHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerItemsOnGround.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/FontRendererHook.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzLogger.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/BucketedItemTrackerData.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Backend

#2953 Fix: Pest Death Pattern
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
Labels: Bug Fix

#2955 Fix: Vacuum Bag Pattern
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
Labels: Bug Fix

#2954 Fix: Pest Spawn Patterns
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestSpawn.kt
Labels: Bug Fix

#2958 Backend: Disallow unnamed capture groups
  detekt/detekt.yml
  detekt/src/main/kotlin/RepoPatternElement.kt
  detekt/src/main/kotlin/SkyHanniRule.kt
  detekt/src/main/kotlin/formatting/CustomAnnotationSpacing.kt
  detekt/src/main/kotlin/formatting/CustomCommentSpacing.kt
  detekt/src/main/kotlin/grammar/AvoidBritishSpelling.kt
  detekt/src/main/kotlin/imports/CustomImportOrdering.kt
  detekt/src/main/kotlin/repo/RepoPatternRegexTest.kt
  detekt/src/main/kotlin/repo/RepoPatternUnnamedGroup.kt
  detekt/src/main/kotlin/repo/RepoRuleSetProvider.kt
  detekt/src/main/kotlin/repo/SkullTexturesUseRepo.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#2961 Fix: UnnamedGroups Rule and Instances
  detekt/src/main/kotlin/repo/RepoPatternUnnamedGroup.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonCleanEnd.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonCopilot.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/event/UniqueGiftingOpportunitiesFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/halloween/BasketWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/DicerRngDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/InGameDateDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MagicalPowerDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/TabListReader.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/limbo/LimboPlaytime.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/stillgorechateau/RiftBloodEffigies.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/BlazeSlayerDaggerHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/summonings/SummoningMobManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Bug Fix

#2920 Backend: Use more specific methods for checking skull textures
  src/main/java/at/hannibal2/skyhanni/data/mob/IslandExceptions.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/endernodetracker/EnderNodeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHideItems.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GoldenFishTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationTableAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangHighlights.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/RiftLarva.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/RiftOdonata.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/BlazeSlayerDaggerHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/enderman/EndermanSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
Labels: Backend

#2947 Improvement: Add Mining Event Display to Outside Skyblock Features
  src/main/java/at/hannibal2/skyhanni/config/enums/OutsideSbFeature.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventDisplay.kt
Labels: Soon

#2946 Fix: Mineshaft roomId in Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementLobbyCode.kt
Labels: Bug Fix

#2925 Fix: Hoppity/Choc Factory Updates
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/HoppityEggLocationsJson.kt
  src/main/java/at/hannibal2/skyhanni/events/hoppity/EggFoundEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/hoppity/RabbitFoundEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggDisplayManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityRabbitTheFishChecker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/WarpMenuUniques.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockTime.kt
Labels: Bug Fix

#2948 Fix: Custom Garden Keybinds
  src/main/java/at/hannibal2/skyhanni/config/features/garden/KeyBindConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCustomKeybinds.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/AccessorKeyBinding.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinKeyBinding.java
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
Labels: Bug Fix

#2959 Fix: Cactus/Sugar Cane Money Per Hour
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
Labels: Bug Fix

#2964 Fix: Pest FF Reduction
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
Labels: Bug Fix

#2965 Improvement: Added Hot Chocolate Mixin in Non God Pot effect display
  src/main/java/at/hannibal2/skyhanni/features/misc/NonGodPotEffectDisplay.kt
Labels: Soon

#2968 Backend: No unknown lines after changes are declared
  buildSrc/build.gradle.kts
Labels: Backend

#2854 Backend: SpecialColor translation
  src/main/java/at/hannibal2/skyhanni/features/fishing/ThunderSparksHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GeyserFishing.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/PartyMemberOutlines.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/SulphurSkitterBox.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/VoltHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SpecialColor.java
  src/main/java/at/hannibal2/skyhanni/utils/SpecialColor.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Backend

#2972 Backend: Remove usages of deprecated color functions
  src/main/java/at/hannibal2/skyhanni/features/combat/FlareDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/cosmetics/ArrowTrail.kt
  src/main/java/at/hannibal2/skyhanni/features/cosmetics/CosmeticFollowingLine.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHighlightClickedBlocks.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonMobManager.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonsRaceGuide.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/HighlightInquisitors.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCallWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/TotemOfCorruption.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/RenderBackground.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryScreenFlash.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/FireVeilWandParticles.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/DeepCavernsGuide.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/AuctionHousePriceComparison.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/PatcherSendCoordinates.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/MatriarchHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangHighlights.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/WoodenButtonsHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveDefenseBlocks.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveLivingMetalHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/RiftLavaMazeParkour.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/RiftUpsideDownParkour.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/TubulatorParkour.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/RiftGunthersRace.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/RiftLarva.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/RiftOdonata.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/EnigmaSoulWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/PunchcardHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/enderman/EndermanSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/SpecialColor.kt
Labels: Soon, Backend

#2969 Fix: Garden Keybinds Crash
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCustomKeybinds.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/AccessorKeyBinding.java
Labels: Bug Fix

#2974 Improvement: Turn on Private Island Ability Block & Terminal Waypoints by default
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/DungeonConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
Labels: Soon

#2976 Backend: ChatUtils.consoleError()
  src/main/java/at/hannibal2/skyhanni/tweaker/DownloadSourceChecker.java
  src/main/java/at/hannibal2/skyhanni/tweaker/ModLoadingTweaker.java
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUVersionCheck.kt
Labels: Soon, Backend

#2967 Fix: Error parsing mouse pest from Elite API
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/EliteBotJson.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
Labels: Bug Fix

#2975 Fix: Garden BPS Underestimation Bug
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropSpeed.kt
Labels: Bug Fix

#2978 Fix: Pesterminator & Bestiary Fortune
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFInfos.kt
Labels: Bug Fix

#1753 Feature: Ghost Profit Tracker
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/combat/CombatConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/combat/ghostcounter/GhostCounterConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/combat/ghostcounter/GhostProfitTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/combat/ghostcounter/textformatting/BestiaryFormattingConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/combat/ghostcounter/textformatting/ETAFormattingConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/combat/ghostcounter/textformatting/KillHourFormattingConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/combat/ghostcounter/textformatting/TextFormattingConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/combat/ghostcounter/textformatting/XPHourFormattingConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/GhostDropsJson.kt
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostData.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostFormatting.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostUtil.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghosttracker/GhostTracker.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinXPInformation.java
  src/main/java/at/hannibal2/skyhanni/utils/CombatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon

#2983 Fix: Field Mouse Name & Crop Type
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/BossType.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestType.kt
Labels: Bug Fix

#2911 Backend: carry tracker cleanup
  src/main/java/at/hannibal2/skyhanni/features/misc/CarryTracker.kt
Labels: Soon, Backend

#2993 Improvement + Fix: HelpCommand
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/HelpCommand.kt
Labels: Bug Fix

#2982 Fix: Various bugs in /shtestmessage
  src/main/java/at/hannibal2/skyhanni/test/command/TestChatCommand.kt
Labels: Bug Fix

#2986 Fix + Improvement: Don't Show Last-Spawned Hoppity Eggs
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggDisplayManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
Labels: Bug Fix

#2998 Fix: ComputerTimeOffset Error
  build.gradle.kts
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.java
  src/main/java/at/hannibal2/skyhanni/utils/ComputerTimeOffset.kt
Labels: Bug Fix

#2994 Fix: Strays & Stray Timer
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
Labels: Bug Fix

#3002 Fix: Include Maeve as one of the exceptions in the visitor hide chat config description
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/VisitorConfig.java
Labels: Bug Fix

#2996 Improvement + Fix: Personal Bests Gain
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/PersonalBestsConfig.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/GardenJson.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/FarmingPersonalBestGain.kt
Labels: Bug Fix
