Repository hannibal002/SkyHanni, pull requests merged in 2024-07, with the labels that each got.

#2173 Fix: Gillsplash in Estimated Item Value
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/craft/CraftableItemList.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Bug Fix - Sooner than Very Soon

#2174 Backend: Readme Update
  README.md
Labels: Soon

#2180 Improvement: Estimated Item Value
  src/main/java/at/hannibal2/skyhanni/config/features/misc/EstimatedItemValueConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Soon

#2194 Improvement + Fix: FF exporting
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CarrolynTable.kt
Labels: Bug Fix - Sooner than Very Soon

#2193 Fix: HypixelData Npe
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
Labels: Bug Fix - Sooner than Very Soon

#2192 Fix: Custom Scoreboard Winter Patterns
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#2191 Fix: Guild Rank Chat Formatting
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerChatManager.kt
Labels: Bug Fix - Sooner than Very Soon

#2190 Backend: Dragon Widget
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
Labels: Bug Fix - Sooner than Very Soon

#2189 Backend: ItemCategory Carnival Mask
  src/main/java/at/hannibal2/skyhanni/utils/ItemCategory.kt
Labels: Bug Fix - Sooner than Very Soon

#2188 Fix: Pet Pattern
  src/main/java/at/hannibal2/skyhanni/data/PetAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#2186 Fix: Powder Percentage CW Conflict
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/data/HotmData.kt
Labels: Bug Fix - Sooner than Very Soon

#2184 Fix: Scoreboard Votes Pattern
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#2183 Fix: Craftable! Text and Internal Names
  src/main/java/at/hannibal2/skyhanni/features/inventory/craft/CraftableItemList.kt
Labels: Bug Fix - Sooner than Very Soon

#2182 Fix: Double-Bit in Reforge Helper
  src/main/java/at/hannibal2/skyhanni/api/ReforgeAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#2179 Fix: Worldedit command
  src/main/java/at/hannibal2/skyhanni/test/WorldEdit.kt
Labels: Bug Fix - Sooner than Very Soon

#2091 Improvement + Fix: Unclaimed Eggs feature while busy
  src/main/java/at/hannibal2/skyhanni/config/features/event/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
Labels: Bug Fix - Sooner than Very Soon

#2148 Feature: Line to Nukekebi Skull
  src/main/java/at/hannibal2/skyhanni/config/features/slayer/SlayerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/slayer/endermen/EndermanConfig.java
  src/main/java/at/hannibal2/skyhanni/features/slayer/enderman/EndermanSlayerFeatures.kt
Labels: Soon

#1811 Feature: Armor Stack Display
  src/main/java/at/hannibal2/skyhanni/config/features/combat/CombatConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/combat/StackDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/features/combat/ArmorStackDisplay.kt
Labels: Soon

#2080 Improvement: Estimated Item Value support in Custom Wardrobe
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
Labels: Soon

#2199 Fix: Stackoverflow for getPrice
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Bug Fix - Sooner than Very Soon

#2198 Fix: Wardrobe Keybinds
  src/main/java/at/hannibal2/skyhanni/data/GuiData.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobeKeybinds.kt
Labels: Bug Fix - Sooner than Very Soon

#2187 Fix: Adds new mayor perks to scoreboard
  src/main/java/at/hannibal2/skyhanni/data/Mayors.kt
Labels: Bug Fix - Sooner than Very Soon

#2142 Improvement: Add Config option for Time Tower in "Best Upgrade"
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateUpgradeWarningsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
Labels: Soon

#2144 Backend: Move hoppity rabbit chat patterns to eggs manager
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
Labels: Soon

#2069 Backend: Fix RepoPattern localeLoading
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
Labels: Soon

#2096 Backend: Mobdetection First Seen Event
  src/main/java/at/hannibal2/skyhanni/data/mob/MobData.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
  src/main/java/at/hannibal2/skyhanni/events/MobEvent.kt
Labels: Soon

#2196 Hoppity and Chocolate being less annoying
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityNpc.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
Labels: Soon

#2223 Fix: Typo in shcommands
  src/main/java/at/hannibal2/skyhanni/features/commands/HelpCommand.kt
Labels: Bug Fix - Sooner than Very Soon

#2202 Fix: Pet Pattern for ItemCategory
  src/main/java/at/hannibal2/skyhanni/data/PetAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#2201 Fix: Buying items may incorrectly trigger compact hoppity messages
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
Labels: Bug Fix - Sooner than Very Soon

#2221 Fix: price source inconsistencies (bz sell/buy and npc price)
  src/main/java/at/hannibal2/skyhanni/config/features/garden/SkyMartConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/composter/ComposterConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/SackDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/EstimatedItemValueConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/TrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/TrackerManager.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/SkyMartCopperPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/test/PriceSource.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceSource.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Bug Fix - Sooner than Very Soon

#2219 Fix: Craftable! text (again)
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/craft/CraftableItemList.kt
Labels: Bug Fix - Sooner than Very Soon

#2215 Fix: Fine Flour exportation pattern
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CarrolynTable.kt
Labels: Bug Fix - Sooner than Very Soon

#2214 Fix: Hot Potato Book in Community Project
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#2212 Fix: Fragged Daedalus Axe not getting detected as farming tool
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#2208 Fix: Page Scrolling missing museum pattern
  src/main/java/at/hannibal2/skyhanni/features/inventory/PageScrolling.kt
Labels: Bug Fix - Sooner than Very Soon

#2207 Fix: Powder Tracker Pattern.
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderChestReward.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
Labels: Bug Fix - Sooner than Very Soon

#2205 Fix: Kuudra Key Value
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Bug Fix - Sooner than Very Soon

#2218 Improvement: own inventory support for estimate chest value
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/ChestValueConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
Labels: Soon

#2220 Backend: Cleaner visitor rarity handling
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/GardenJson.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorColorNames.kt
Labels: Soon

#2224 Fix: Powder Tracker NPE on older versions
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderChestReward.kt
Labels: Bug Fix - Sooner than Very Soon

#2151 Backend: RecalculatingValue as a ReadOnlyProperty
  src/main/java/at/hannibal2/skyhanni/data/SlayerAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/AtmosphericFilterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/TimeFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/GlowingDroppedItems.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerQuestWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerRngMeterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/RecalculatingValue.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyblockSeason.kt
Labels: Soon

#2217 Fix: Farming ETA Duration "NaN"
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#2137 Improvement: Compact Rancher Speed GUI
  src/main/java/at/hannibal2/skyhanni/config/features/garden/optimalspeed/OptimalSpeedConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenOptimalSpeed.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Soon

#2128 Backend: Remove redundant property from HotmAPI.Powder
  src/main/java/at/hannibal2/skyhanni/api/HotmAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/HotmData.kt
Labels: Soon

#2141 Improvement: Add Reset Buttons to Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/CustomScoreboardConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/EventsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
Labels: Soon

#2120 Feature: Reset Custom Wardrobe Settings
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/customwardrobe/ColorConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/customwardrobe/SpacingConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobeReset.kt
Labels: Soon

#2225 Fix: Fish The Rabbit Production Time in Lore
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTooltipStray.kt
Labels: Bug Fix - Sooner than Very Soon

#2230 Fix: Farming ETA Approaches 0
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#2229 Feature: Crown of Avarice Counter
  src/main/java/at/hannibal2/skyhanni/config/features/itemability/CrownOfAvariceConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/itemability/ItemAbilityConfig.java
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/CrownOfAvariceCounter.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Soon

#2240 Fix: PowderTracker Pattern
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderChestReward.kt
Labels: Bug Fix - Sooner than Very Soon

#2244 Fix: Reforge Helper Carnival Mask
  src/main/java/at/hannibal2/skyhanni/api/ReforgeAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#2236 Fix: Kuudra Errors
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Bug Fix - Sooner than Very Soon

#2235 Fix: Ignore Jasper/Ruby Crystal price
  src/main/java/at/hannibal2/skyhanni/utils/NEUInternalName.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Bug Fix - Sooner than Very Soon

#2232 Fix: Slayer detection
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerQuestWarning.kt
Labels: Bug Fix - Sooner than Very Soon

#2238 Feature: Crash Game On Death
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/CrashOnDeath.kt
Labels: Soon

#2181 Improvement: Royal Pigeon Left Click
  src/main/java/at/hannibal2/skyhanni/config/features/mining/TunnelMapsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
Labels: Soon

#2233 Improvement: Short Bazaar Price Source Name
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceSource.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
Labels: Soon

#2160 Backend: RegexUtils deprecation and new functions
  src/main/java/at/hannibal2/skyhanni/data/HotmData.kt
  src/main/java/at/hannibal2/skyhanni/utils/RegexUtils.kt
Labels: Soon

#2172 Improvement: Added SkyBlock Level to Item Number
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
Labels: Soon

#2245 Fix: Custom Scoreboard Carnival Error
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#2246 Fix: Disabled style checking throwing an error
  .github/workflows/check-style.yaml
  .github/workflows/check-style.yaml.disabled
Labels: Bug Fix - Sooner than Very Soon

#1945 Feature: Bestiary Level as Stack Size
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
Labels: Soon

#2211 Improvement: Add Toggle for Unclaimed Egg Warp
  src/main/java/at/hannibal2/skyhanni/config/features/event/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggDisplayManager.kt
Labels: Soon

#2247 Fix: Carnival Mask Fix
  src/main/java/at/hannibal2/skyhanni/api/ReforgeAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#2157 Fix: Double Powder Detection
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
Labels: Soon, Bug Fix - Sooner than Very Soon

#2239 Fix: Stray Rabbit Production Time Tooltip
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTooltipStray.kt
Labels: Bug Fix - Sooner than Very Soon

#2260 Fix: renderStringsAndItems y issue
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#2252 Fix: Custom Scoreboard Reset Issue
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/CustomScoreboardConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/EventsConfig.java
Labels: Bug Fix - Sooner than Very Soon

#2251 Fix: Fine Flour in Sprayonator
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/SprayFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/SprayType.kt
Labels: Bug Fix - Sooner than Very Soon

#2250 Fix: Hoppity Abiphone Call Compact
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
Labels: Bug Fix - Sooner than Very Soon

#1960 Improvement + Fix: Barn Fishing Timer
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/BarnTimerConfig.java
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingTimer.kt
Labels: Bug Fix - Sooner than Very Soon

#2259 Improvement: Made Hoppity Egg Waypoint Color customizable
  src/main/java/at/hannibal2/skyhanni/config/features/event/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
Labels: Soon

#1937 Feature: Item Pickup Log
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/ItemPickupLogConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Soon

#2258 Backend: Change colour (UK) to color (US)
  CONTRIBUTING.md
  docs/CHANGELOG.md
  docs/FEATURES.md
  src/main/java/at/hannibal2/skyhanni/config/features/crimsonisle/MatriarchHelperConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/TextBoxConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/AuctionHousePriceComparisonConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/TunnelMapsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/dreadfarm/VoltCruxConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/westvillage/KloonHackingConfig.java
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonDeathCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonMilestonesDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/ThunderSparksHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GeyserFishing.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CarrolynTable.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorColorNames.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ReforgeHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventType.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MarkedPlayerManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/PartyMemberOutlines.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/Enchant.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/VisualWordGui.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/SulphurSkitterBox.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangGravityOrbs.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/VoltHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/kloon/KloonHacking.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzColor.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SpecialColor.java
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Soon

#2264 Fix: Double Color in ScoreboardData
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
  src/main/java/at/hannibal2/skyhanni/utils/RegexUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#2248 Fix: Dicer Tracker Reset Button
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/DicerRngDropTracker.kt
Labels: Bug Fix - Sooner than Very Soon

#2263 Fix: HotM total powder being reset
  src/main/java/at/hannibal2/skyhanni/data/HotmData.kt
Labels: Bug Fix - Sooner than Very Soon

#2262 Fix: Jacob Contest FF Needed Display not showing
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobContestFFNeededDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#2261 Fix: Duration below 1s
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#2249 Improvement: Add Slug pet to FF Guide
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFInfos.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFTypes.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FarmingItems.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/OverviewPage.kt
Labels: Soon

#2226 Chocolate Factory Milestones instead of maxed prestige not showing
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/HoppityEggLocationsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
Labels: Soon

#2234 Feature: Thunder Bottle Charged Notification
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/ThunderBottleNotification.kt
Labels: Soon

#2228 Improvement: Apply border radius to scoreboard texture
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/RenderBackground.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/RoundedShader.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/ShaderManager.kt
  src/main/resources/assets/skyhanni/shaders/rounded_texture.fsh
  src/main/resources/assets/skyhanni/shaders/rounded_texture.vsh
Labels: Soon

#2267 Fix: Hypixel error negative magma cubes
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#2271 Fix: Config Typo
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/ItemPickupLogConfig.java
Labels: Bug Fix - Sooner than Very Soon

#2273 Fix: Fixed small typos in FF guide.
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/OverviewPage.kt
Labels: Bug Fix - Sooner than Very Soon

#2266 Improvement: Fewer Tab list chat errors
  src/main/java/at/hannibal2/skyhanni/config/storage/PlayerSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/ProfileStorageData.kt
Labels: Soon

#2269 Fix: Hotm wrong max Powder if disabled
  src/main/java/at/hannibal2/skyhanni/data/HotmData.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/PowderPerHotmPerk.kt
Labels: Bug Fix - Sooner than Very Soon

#2268 Fix: NPE in CorpseLocator
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseLocator.kt
Labels: Bug Fix - Sooner than Very Soon

#2210 Feature: Stray Rabbit Tracker
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
Labels: Soon

#2227 Backend: Updated getting active Mayor from API
  src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/Mayors.kt
Labels: Soon

#2152 Improvement: Powder Mining Chat Filter V2
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/FilterTypesConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/chat/PowderMiningFilterConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/chat/PowderMiningGemstoneFilterConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/PowderMiningChatFilter.kt
Labels: Soon

#2275 Fix: TunnelMaps values not clearing on lobby swap
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
Labels: Bug Fix - Sooner than Very Soon

#2195 Feature: Price per Stock of Stonks
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/StockOfStonkFeature.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
Labels: Soon

#2276 Backend: Add cache powder chat filter
  src/main/java/at/hannibal2/skyhanni/features/chat/PowderMiningChatFilter.kt
Labels: Soon

#2278 Feature: Tactical Insertion Ability Cooldown
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbility.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbilityCooldown.kt
Labels: Soon

#2277 Fix: TunnelMaps Deadlock
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
Labels: Bug Fix - Sooner than Very Soon

#2282 Fix: Potm always disabled
  src/main/java/at/hannibal2/skyhanni/data/HotmData.kt
Labels: Bug Fix - Sooner than Very Soon

#2281 Fix: Flawless Gemstones in Powder Filter
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/PowderMiningGemstoneFilterConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/PowderMiningChatFilter.kt
Labels: Bug Fix - Sooner than Very Soon

#2280 Fix: Hoppity Goal Levels Off-by-One
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryCustomReminder.kt
Labels: Bug Fix - Sooner than Very Soon

#2279 Fix: Discord RPC dynamic off-by-one
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
Labels: Bug Fix - Sooner than Very Soon
