Repository hannibal002/SkyHanni, pull requests merged in 2024-09, with the labels that each got.

#2440 Fix: Last Server Slider
  src/main/java/at/hannibal2/skyhanni/config/features/misc/LastServersConfig.java
Labels: Bug Fix - Sooner than Very Soon

#2436 Fix: Pity Counter
  src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#2451 Backend: Graph Node Editor improvements
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenYawAndPitch.kt
  src/main/java/at/hannibal2/skyhanni/test/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
Labels: Soon

#2450 Fix: El Dorado and Stray Rabbit Horde patterns
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
Labels: Bug Fix - Sooner than Very Soon

#2449 Fix: Armor Hider in Custom Wardrobe
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/HideArmor.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinContributorRendererEntityLiving.java
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/FakePlayer.kt
Labels: Bug Fix - Sooner than Very Soon

#2445 Fix: showBingoRankNumber option not working
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/AdvancedPlayerList.kt
Labels: Bug Fix - Sooner than Very Soon

#2441 Fix: Custom Scoreboard Error in Dungeon Queue
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Bug Fix - Sooner than Very Soon

#2444 Fix: Profit Tracker coin formatting
  src/main/java/at/hannibal2/skyhanni/data/SlayerAPI.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
Labels: Soon, Bug Fix - Sooner than Very Soon

#2442 Add IntelliJ setup documentation
  CONTRIBUTING.md
  docs/gradle-settings.png
  docs/gradle-tab.jpg
  docs/minecraft-client.webp
  docs/run-configuration-settings.avif
Labels: Soon

#2439 Fix: Reputation helper sack update
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/CrimsonIsleReputationHelper.kt
Labels: Bug Fix - Sooner than Very Soon

#2456 Fix: Dungeon Complete Event
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#2455 Fix: Carnival Scoreboard Patterns
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#2464 Backend: Added Tags to Graph Editor
  src/main/java/at/hannibal2/skyhanni/data/model/Graph.kt
  src/main/java/at/hannibal2/skyhanni/data/model/GraphNodeTag.kt
  src/main/java/at/hannibal2/skyhanni/data/model/TextInput.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
  src/main/java/at/hannibal2/skyhanni/test/GraphEditor.kt
Labels: Soon

#2461 Backend: Ghost Mode Graph Editor
  src/main/java/at/hannibal2/skyhanni/config/features/dev/GraphConfig.java
  src/main/java/at/hannibal2/skyhanni/test/GraphEditor.kt
Labels: Soon

#2467 Fix: Minister not resetting
  src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#2465 Fix: Ultimate enchants not showing in /show
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
Labels: Bug Fix - Sooner than Very Soon

#2458 Docs: Readme updates
  README.md
Labels: Soon

#2459 Improvement: Guardian Pet Experimentation Table
  src/main/java/at/hannibal2/skyhanni/features/inventory/experiments/GuardianReminder.kt
Labels: Soon

#2446 Fix: shtps command printing nothing
  src/main/java/at/hannibal2/skyhanni/features/misc/TpsCounter.kt
Labels: Bug Fix - Sooner than Very Soon

#2448 Feature: /shedittracker
  src/main/java/at/hannibal2/skyhanni/api/CollectionAPI.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/ItemAddManager.kt
  src/main/java/at/hannibal2/skyhanni/data/TrackerManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUInternalName.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/ItemTrackerData.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
Labels: Soon

#2470 Fix: Mod Compatilibty issues in Party Finder
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#2472 Fix: Typo in mob detection config
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugMobConfig.java
Labels: Bug Fix - Sooner than Very Soon

#2476 Fix: Stuck in text box forever
  src/main/java/at/hannibal2/skyhanni/data/model/TextInput.kt
Labels: Bug Fix - Sooner than Very Soon

#2471 Fix: grab item name none
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#2454 Fix: Merged enchant books tooltip being overwritten (+ backend)
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/Enchant.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
Labels: Bug Fix - Sooner than Very Soon

#2243 Feature: Accessory MP as stack size
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/MagicalPowerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/misc/MagicalPowerDisplay.kt
Labels: Soon

#1276 Feature: Display Tab Widgets
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/core/config/Position.java
  src/main/java/at/hannibal2/skyhanni/config/core/config/PositionList.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/GUIConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/TabWidgetConfig.java
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/TabWidgetDisplay.kt
  src/test/java/at/hannibal2/skyhanni/test/RepoPatternTest.kt
Labels: Soon

#1869 Feature: Personal Compactor Overlay
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/PersonalCompactorConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/PersonalCompactorOverlay.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableInventory.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableTooltips.kt
  src/main/resources/assets/skyhanni/gui/slot.png
Labels: Soon

#2478 Feature: Dungeon Secret Chime
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/DungeonConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/SecretChimeConfig.java
  src/main/java/at/hannibal2/skyhanni/data/ClickedBlockType.kt
  src/main/java/at/hannibal2/skyhanni/events/DungeonClickedBlockEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHighlightClickedBlocks.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonSecretChime.kt
Labels: Soon

#2209 Feature: Experiment Rewards compacting
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/CompactExperimentRewards.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SuperpairsClicksAlert.kt
Labels: Soon

#2434 Backend: Cleanup Forge Gfs
  src/main/java/at/hannibal2/skyhanni/features/mining/ForgeGfs.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/PrimitiveItemStack.kt
Labels: Soon

#2469 Improvement: Make pest middle waypoint optional
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestWaypointConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleLine.kt
Labels: Soon

#1993 Feature: Arachne kill timer
  src/main/java/at/hannibal2/skyhanni/config/features/combat/MobsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/ArachneChatMessageHider.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/ArachneKillTimer.kt
Labels: Soon

#2473 Docs: diana burrow logic in discord FAQ
  docs/DISCORD_FAQ.md
Labels: Soon

#2015 Feature: Rift time Nametag Format
  src/main/java/at/hannibal2/skyhanni/config/features/rift/RiftTimerConfig.java
  src/main/java/at/hannibal2/skyhanni/data/EntityData.kt
  src/main/java/at/hannibal2/skyhanni/events/entity/EntityHealthDisplayEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/RiftTimer.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinRenderPlayer.java
Labels: Soon

#2462 Backend: Use on DelayedRun to add scheduled tasks
  src/main/java/at/hannibal2/skyhanni/data/FixedRateTimerManager.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/UpdateManager.kt
  src/main/java/at/hannibal2/skyhanni/test/hotswap/HotswapSupportImpl.kt
  src/main/java/at/hannibal2/skyhanni/utils/DelayedRun.kt
  src/main/java/at/hannibal2/skyhanni/utils/SoundUtils.kt
Labels: Soon

#2348 Improvement: Added parkour and teleport messages to blockable messages
  src/main/java/at/hannibal2/skyhanni/config/features/chat/FilterTypesConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Soon

#2479 Fix: Heavy Pearls sometimes not detected
  src/main/java/at/hannibal2/skyhanni/data/mob/IslandExceptions.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
Labels: Bug Fix - Sooner than Very Soon

#2394 Improvement: Powder Tracker revamped
  src/main/java/at/hannibal2/skyhanni/api/HotmAPI.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/data/HotmData.kt
  src/main/java/at/hannibal2/skyhanni/events/mining/PowderGainEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
Labels: Soon

#2272 Feature: Hoppity Call Warning
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityCallWarningConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCallWarning.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Soon

#2178 Feature: Mirrorverse Crafting Room Helper
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/mirrorverse/CraftingRoomConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/mirrorverse/MirrorVerseConfig.java
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/CraftRoomHolographicMob.kt
Labels: Soon

#2474 Backend: No List<Any> in Trackers
  src/main/java/at/hannibal2/skyhanni/features/combat/endernodetracker/EnderNodeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/MythologicalCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/jerry/frozentreasure/FrozenTreasureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/SeaCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/ArmorDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/DicerRngDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/test/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon

#2480 Fix: Scoreboard Error with Barry Protestors
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Bug Fix - Sooner than Very Soon

#2482 Fix: Sound Utils Over-correction
  src/main/java/at/hannibal2/skyhanni/utils/SoundUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#2042 Feature: Miniboss timer
  src/main/java/at/hannibal2/skyhanni/config/features/crimsonisle/CrimsonIsleConfig.java
  src/main/java/at/hannibal2/skyhanni/features/nether/CrimsonMinibossRespawnTimer.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
Labels: Soon

#1881 Feature: Show Custom Scoreboard outside SkyBlock
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/enums/OutsideSbFeature.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/DisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/TitleAndFooterConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Soon

#2477 Improvement: SH Tracker Search
  src/main/java/at/hannibal2/skyhanni/features/combat/endernodetracker/EnderNodeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/MythologicalCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/jerry/frozentreasure/FrozenTreasureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/SeaCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/ArmorDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/DicerRngDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/test/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Searchable.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon

#2489 Fix: Hoppity Event Stats Resetting
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
Labels: Bug Fix - Sooner than Very Soon

#2493 fix red
  build.gradle.kts
Labels: Bug Fix - Sooner than Very Soon

#2485 Fix : Glacite Commissions tunnel map
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
Labels: Bug Fix - Sooner than Very Soon

#2483 Fix: AH Price Comparison
  src/main/java/at/hannibal2/skyhanni/features/misc/AuctionHousePriceComparison.kt
Labels: Bug Fix - Sooner than Very Soon

#2490 Fix: Fix some regex tests from old pr
  src/main/java/at/hannibal2/skyhanni/config/features/chat/FilterTypesConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Bug Fix - Sooner than Very Soon

#2486 Fix: Personal Compactor Skull Sizes
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableInventory.kt
Labels: Bug Fix - Sooner than Very Soon

#2487 Improvement: Add per election year diana trackers
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/MythologicalCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon

#2306 Feature: Corpse Tracker
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/CorpseTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/GlaciteMineshaftConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/events/mining/CorpseLootedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseType.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/MineshaftCorpseProfitPer.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/BucketedItemTrackerData.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/ItemTrackerData.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniBucketedItemTracker.kt
Labels: Soon

#1941 Feature: Golden Fish Timer
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/trophyfishing/GoldenFishTimerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/trophyfishing/TrophyFishingConfig.java
  src/main/java/at/hannibal2/skyhanni/events/FishingBobberInLiquidEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/FishingBobberInWaterEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingBaitWarnings.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/IsFishingDetection.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GoldenFishTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishMessages.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
Labels: Soon

#2495 Fix: Last Server Chat Spam
  src/main/java/at/hannibal2/skyhanni/config/features/misc/LastServersConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/LastServers.kt
Labels: Bug Fix - Sooner than Very Soon

#2500 Fix: Build actions failing
  build.gradle.kts
  settings.gradle.kts
Labels: Bug Fix - Sooner than Very Soon

#1751 Feature: Transfer Cooldown Prevention
  src/main/java/at/hannibal2/skyhanni/config/features/commands/CommandsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/commands/TransferCooldown.kt
Labels: Soon

#1880 Feature: Pet Nametag
  src/main/java/at/hannibal2/skyhanni/config/features/misc/pets/PetConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/pets/PetNametagConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/pets/CurrentPetDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pets/PetCandyUsedDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pets/PetExpTooltip.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pets/PetItemDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pets/PetNametag.kt
Labels: Soon

#2503 Improvement: Chocolate Factory time to next instead of max milestone
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/HoppityEggLocationsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
Labels: Soon

#2497 Feature: Zombie Shootout QOL
  src/main/java/at/hannibal2/skyhanni/config/features/event/EventConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/carnival/CarnivalConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/carnival/ZombieShootoutConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalZombieShootout.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon

#2492 Improvement: Stars in Estimated Item Value
  src/main/java/at/hannibal2/skyhanni/config/features/misc/EstimatedItemValueConfig.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/NeuEssenceCostJson.kt
  src/main/java/at/hannibal2/skyhanni/events/NeuRepositoryReloadEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/utils/EssenceItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
Labels: Soon

#2501 Fix: Duplex
  src/main/java/at/hannibal2/skyhanni/utils/ItemNameResolver.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
Labels: Bug Fix - Sooner than Very Soon

#2325 Feature: Broodmother alerts/messages and damage indicator support
  src/main/java/at/hannibal2/skyhanni/config/features/combat/CombatConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/combat/broodmother/BroodmotherConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/combat/broodmother/BroodmotherSpawnAlertConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/combat/damageindicator/DamageIndicatorConfig.java
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/BroodmotherFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/SpidersDenAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/BossType.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/MobFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvent.kt
Labels: Soon

#2150 Feature: GetFromSack Piggy Bank
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/GFSPiggyBank.kt
Labels: Soon

#2504 Fix: MobDetection Memory Collection
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
Labels: Bug Fix - Sooner than Very Soon

#2498 Feature: Carnival QoL
  src/main/java/at/hannibal2/skyhanni/config/features/event/EventConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/carnival/CarnivalConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalGoal.kt
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalQuickStart.kt
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalReminder.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/BaseGsonBuilder.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkyHanniTypeAdapters.kt
Labels: Soon

#2468 Feature: Graphs Pathfinding
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/GraphConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/AreaNavigationConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/AreaPathfinderConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/PurseAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/model/Graph.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocations.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
  src/main/java/at/hannibal2/skyhanni/test/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Searchable.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon

#2507 Fix: Zombie Shootout QOL
  src/main/java/at/hannibal2/skyhanni/config/features/event/carnival/ZombieShootoutConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalZombieShootout.kt
Labels: Bug Fix - Sooner than Very Soon

#2496 Improvement: Spade tracker visibility
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/MythologicalCreatureTracker.kt
Labels: Soon

#2510 Fix: Scoreboard Error during M7 Dragons
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
Labels: Bug Fix - Sooner than Very Soon

#2513 Fix: Broodmother countdown wrong in singular case
  src/main/java/at/hannibal2/skyhanni/features/combat/BroodmotherFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#2512 Fix: Zombie Shootout Baby Zombie Bounding Box
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalZombieShootout.kt
Labels: Bug Fix - Sooner than Very Soon

#2517 Fix: Catch a Fish Goals
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalGoal.kt
Labels: Bug Fix - Sooner than Very Soon

#2438 Feature: Highlight More Hoppity's Collection Rabbits
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
Labels: Soon

#2524 Fix: Old mayor perks not being marked as inactive
  src/main/java/at/hannibal2/skyhanni/data/Mayors.kt
Labels: Bug Fix - Sooner than Very Soon

#2525 Fix: Lag spikes in pathfinder
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
Labels: Soon, Bug Fix - Sooner than Very Soon

#2516 Fix: Corpse Tracker visiblility
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseTracker.kt
Labels: Bug Fix - Sooner than Very Soon

#2528 Fix: BucketedItemTrackerData Not Exposed
  src/main/java/at/hannibal2/skyhanni/utils/tracker/BucketedItemTrackerData.kt
Labels: Bug Fix - Sooner than Very Soon

#2526 Fix: Efficient Miner on Ore Mined Event
  src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
  src/main/java/at/hannibal2/skyhanni/events/ServerBlockChangeEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/OreBlock.kt
Labels: Bug Fix - Sooner than Very Soon

#2519 Fix: Dojo Pattern
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#2518 Fix: Baby Zombie Carnival Size
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalZombieShootout.kt
Labels: Bug Fix - Sooner than Very Soon

#2520 Removed Feature: Wild Strawberry Dye notification
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/WildStrawberryDyeNotification.kt
Labels: Soon

#2511 Improvement: Updated Carnival Diamond Zombie Color
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalZombieShootout.kt
Labels: Soon

#2515 Improvement: More Graph Things
  src/main/java/at/hannibal2/skyhanni/config/features/dev/GraphConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/rift/EnigmaSoulConfig.java
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/model/GraphNodeTag.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/EnigmaSoulWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/test/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/test/GraphNodeEditor.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
Labels: Soon

#2529 Fix: Mining Update ItemCategory
  src/main/java/at/hannibal2/skyhanni/api/ReforgeAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/PrivateIslandNoPickaxeAbility.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemCategory.kt
Labels: Bug Fix - Sooner than Very Soon

#2530 Fix: TunnelMaps area and missing stats for reforge helper
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
Labels: Bug Fix - Sooner than Very Soon

#2532 Fix: Garden Color in Messages
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenPlotAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#2531 Fix: Custom Scoreboard Errors
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#2437 Fix: Tungsten Detection on Alpha
  src/main/java/at/hannibal2/skyhanni/features/mining/OreBlock.kt
Labels: Waiting on Hypixel, Bug Fix - Sooner than Very Soon

#2534 Fix: Revert Gauntlet item category change
  src/main/java/at/hannibal2/skyhanni/api/ReforgeAPI.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemCategory.kt
Labels: Bug Fix - Sooner than Very Soon

#2545 Fix: Custom Scoreboard Raffle Patterns
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#2549 Fix: Corpse Tracker not being modifed by /shdefaultoptions
  src/main/java/at/hannibal2/skyhanni/config/features/mining/CorpseTrackerConfig.java
Labels: Bug Fix - Sooner than Very Soon

#2505 Improvment: Click on Garden Shopping List now uses /viewrecipe instead of /recipe
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorSupercraft.kt
Labels: Soon

#2552 Fix: Visitor Supercraft use internal name
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorSupercraft.kt
Labels: Bug Fix - Sooner than Very Soon

#2548 Fix: github source checking
  src/main/java/at/hannibal2/skyhanni/tweaker/DownloadSourceChecker.java
Labels: Bug Fix - Sooner than Very Soon

#2488 Fixes & Improvements: Hoppity Rework
  src/main/java/at/hannibal2/skyhanni/events/hoppity/EggFoundEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
Labels: Soon, Bug Fix - Sooner than Very Soon

#2553 Fix: Mining Commission Blocks Color and Connected Textures
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinOptifineConfig.java
Labels: Bug Fix - Sooner than Very Soon

#2551 Fix: Update Sky Mall patterns
  src/main/java/at/hannibal2/skyhanni/api/HotmAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#2550 Fix: Kuudra armor always showing as starred
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Bug Fix - Sooner than Very Soon

#2543 Fix: HotmData perk rework
  src/main/java/at/hannibal2/skyhanni/data/HotmData.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/MineshaftPityDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#2537 Improvement: Area Navigation updates
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/GraphConfig.java
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/model/Graph.kt
  src/main/java/at/hannibal2/skyhanni/data/model/GraphNodeTag.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinKeyBinding.java
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditorBugFinder.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphNodeEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/GraphUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
  src/main/java/at/hannibal2/skyhanni/utils/RaycastUtils.kt
Labels: Soon

#2536 Fix: Hardstone and Tungsten detection in Mineshafts
  src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/MineshaftPityDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/MiningCommissionsBlocksColor.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/OreBlock.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/OreType.kt
Labels: Bug Fix - Sooner than Very Soon

#2522 Feature: Hoppity Collection Dye Recolor
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
Labels: Soon

#2523 Improvement (?): Descriptive Milestones in Hoppity Collection
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/HoppityEggLocationsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
Labels: Soon

#2171 Feature: Inventory - Experiments rework
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/experimentationtable/ExperimentationTableConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/experimentationtable/ExperimentsDryStreakConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/experimentationtable/ExperimentsProfitTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/helper/HelperConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationTableAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationTableEnums.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsDryStreakDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/GuardianReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/SuperpairExperimentInformationDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/SuperpairsClicksAlert.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/UltraRareBookAlert.kt
Labels: Soon

#2555 Fix: Mining Stats Reforge
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
Labels: Bug Fix - Sooner than Very Soon

#2557 Fix: Glacite Powder being counted as an item in CorpseTracker
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/ProfitPerMineshaftCorpse.kt
Labels: Bug Fix - Sooner than Very Soon

#2535 Backend: AreaChangeEvent and Islands in HandleEvent
  src/main/java/at/hannibal2/skyhanni/api/event/EventHandler.kt
  src/main/java/at/hannibal2/skyhanni/api/event/HandleEvent.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/LocationFixData.kt
  src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
  src/main/java/at/hannibal2/skyhanni/events/skyblock/AreaChangeEvents.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/ArachneSpawnTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonShadowAssassinNotification.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowParticleFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleWaypoint.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorListener.kt
Labels: Soon

#2556 Feature: Hoppity Duplicate Count
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
Labels: Soon

#2185 Feature: Carry Tracker
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/data/OtherPlayersSlayerAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/CarryTrackerJson.kt
  src/main/java/at/hannibal2/skyhanni/events/entity/slayer/SlayerDeathEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CarryTracker.kt
Labels: Soon

#2546 Feature: Highlight Active Beacon Effect
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/ActiveBeaconEffect.kt
Labels: Soon

#2539 Feature: Excavator Tooltip Hider
  src/main/java/at/hannibal2/skyhanni/config/features/mining/FossilExcavatorConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorTooltipHider.kt
Labels: Soon

#2562 Fix: ReforgeAPI fix hard crash for unkown stat
  src/main/java/at/hannibal2/skyhanni/api/ReforgeAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkyHanniTypeAdapters.kt
Labels: Bug Fix - Sooner than Very Soon

#2560 Fix: Experiments Profit Tracker & Superpairs Data
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/SuperpairExperimentInformationDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#2372 Backend: Renderable Wrapped String Internal Alignement
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
Labels: Soon

#2572 Fix: Stonks of stonks auction on auction
  src/main/java/at/hannibal2/skyhanni/features/inventory/StockOfStonkFeature.kt
Labels: Bug Fix - Sooner than Very Soon

#2565 Fix: Great Glacite Lake detection
  src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordLocationKey.kt
Labels: Bug Fix - Sooner than Very Soon

#2558 Backend: Add blossom and make source checker show version again
  build.gradle.kts
  root.gradle.kts
  settings.gradle.kts
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/tweaker/DownloadSourceChecker.java
Labels: Soon

#2460 Backend: Create and use primitive recipe and ingredient
  src/main/java/at/hannibal2/skyhanni/features/bingo/FirstMinionTier.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/MinionCraftHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorSupercraft.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/craft/CraftableItemList.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/PrimitiveIngredient.kt
  src/main/java/at/hannibal2/skyhanni/utils/PrimitiveRecipe.kt
Labels: Soon

#2463 Internal: Shared Live Templates for common structures
  .gitignore
  .idea/liveTemplates/SkyHanni.xml
Labels: Soon

#2544 Improvement: Glacite Tunnels Area Navigation
  src/main/java/at/hannibal2/skyhanni/api/event/SkyHanniEvent.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/events/LorenzEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
Labels: Soon, Waiting on Dependency PR

#2577 Fix: Mining Commissions Blocks Color connected textures v2
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinOptifineConnectedTextures.java
Labels: Soon, Bug Fix - Sooner than Very Soon

#2540 Improvement: Add Pickobulus support to OreMineEvent
  src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
  src/main/java/at/hannibal2/skyhanni/events/mining/OreMinedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/MineshaftPityDisplay.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
Labels: Soon

#2571 Backend: Carry Tracker Number format depending on Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/features/misc/CarryTracker.kt
Labels: Soon

#2419 Backend: Remove more neu code from SkyHanni
  .github/workflows/illegal-imports.txt
  .idea/dictionaries/default_user.xml
  build.gradle.kts
  src/main/java/at/hannibal2/skyhanni/events/NeuRepositoryReloadEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilterGui.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostUtil.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenPlotIcon.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorSupercraft.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/HighlightVisitorsOutsideOfGarden.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/auctionhouse/AuctionHouseOpenPriceWebsite.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarOpenPriceWebsite.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/ColdOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/DeepCavernsGuide.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/UserLuckBreakdown.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/limbo/LimboPlaytime.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigOptionGui.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/EnigmaSoulWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillType.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniConfigSearchResetCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/JsonUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/Shimmy.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableTooltips.kt
Labels: Soon

#2578 Backend: Add Http Request Patching
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/bazaar/HypixelBazaarFetcher.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/translation/Translator.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarDataHolder.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/UpdateManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/APIUtils.kt
  src/main/resources/mykeystore.jks
Labels: Soon

#2569 Feature: Reindrake Warp Helper
  src/main/java/at/hannibal2/skyhanni/config/features/event/winter/WinterConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/winter/ReindrakeWarpHelper.kt
Labels: Soon

#1931 Backend: Replace round and roundToPrecision with roundTo
  src/main/java/at/hannibal2/skyhanni/config/core/config/gui/GuiPositionEditor.kt
  src/main/java/at/hannibal2/skyhanni/data/QuiverAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/model/Graph.kt
  src/main/java/at/hannibal2/skyhanni/events/PlaySoundEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/ReceiveParticleEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostUtil.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/BurrowWarpHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenYawAndPitch.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/FarmingPersonalBestGain.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobContestFFNeededDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobContestStatsSummary.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobContestTimeNeeded.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropSpeedMeter.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/GardenCropMilestoneInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/SkyMartCopperPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTooltip.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbility.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbilityCooldown.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/MineshaftPityDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/PowderPerHotmPerk.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilSolverDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MovementSpeedDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/TpsCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/UserLuckBreakdown.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/limbo/LimboPlaytime.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/limbo/LimboTimeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pets/PetExpTooltip.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingMetalSuitProgress.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/CruxTalismanDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/motes/RiftMotesOrb.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillTooltip.kt
  src/main/java/at/hannibal2/skyhanni/test/PacketTest.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TrackParticlesCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TrackSoundsCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
  src/main/java/at/hannibal2/skyhanni/utils/NumberUtil.kt
Labels: Soon, Backend

#2580 Fix: Hard Stone in Crystal Hollows misdetected as Mithril
  src/main/java/at/hannibal2/skyhanni/features/mining/OreBlock.kt
Labels: Bug Fix - Sooner than Very Soon

#2576 Backend: PrimitiveIngredient changes and code cleanup
  src/main/java/at/hannibal2/skyhanni/features/bingo/MinionCraftHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorSupercraft.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/PrimitiveIngredient.kt
  src/main/java/at/hannibal2/skyhanni/utils/PrimitiveItemStack.kt
Labels: Soon

#2575 Feature: /shnavigate
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/model/GraphNodeTag.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/HelpCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pathfind/NavigationHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/reminders/ReminderManager.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditorBugFinder.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphNodeEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/chat/Text.kt
Labels: Soon

#2583 Backend: Add pages to /shnavigate
  src/main/java/at/hannibal2/skyhanni/features/commands/HelpCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pathfind/NavigationHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/reminders/ReminderManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/chat/Text.kt
Labels: Soon, Backend

#2587 Fix: NoSuchElementException in ChumBucketHider
  src/main/java/at/hannibal2/skyhanni/features/fishing/ChumBucketHider.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeLimitedCache.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeLimitedSet.kt
Labels: Bug Fix - Sooner than Very Soon

#2590 Fix: Update radius for Sulphur Skitter to 4 blocks
  src/main/java/at/hannibal2/skyhanni/features/nether/SulphurSkitterBox.kt
Labels: Bug Fix - Sooner than Very Soon

#2603 Backend: Detekt Fixes Part 1
  src/main/java/at/hannibal2/skyhanni/config/ConfigGuiForgeInterop.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/core/config/gui/GuiPositionEditor.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/PowderMiningChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/tabcomplete/GetFromSacksTabComplete.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonRankTabListColor.kt
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalZombieShootout.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/OverviewPage.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ReforgeHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryCustomReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/MineshaftPityDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/OreBlock.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/Enchant.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/FeatureToggleProcessor.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/RiftTimer.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzLogger.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUVersionCheck.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/GuiScreenUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/SkyhanniBaseScreen.kt
Labels: Soon

#2609 Backend: Explain double baseline.xml file
  CONTRIBUTING.md
Labels: Soon, Backend

#2608 Fix: Item category detection
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
Labels: Bug Fix - Sooner than Very Soon

#2611 Fix: Diamond/Golden heads + Master Skulls using Name not ID causing an incompatibility with NEURenamed items
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#2606 Backend: Detekt Fixes Part 3
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
  src/main/java/at/hannibal2/skyhanni/events/DungeonBlockClickEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/PowderMiningChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/MobFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonCleanEnd.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/easter/EasterEggWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishMessages.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/OverviewPage.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/HighlightVisitorsOutsideOfGarden.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/MovableHotBar.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/SuperpairExperimentInformationDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/SuperpairsClicksAlert.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbilityCooldown.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/KingTalismanHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MarkedPlayerManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigOptionGui.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/ModifyVisualWords.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/VoltHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniConfigSearchResetCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemNameResolver.kt
  src/main/java/at/hannibal2/skyhanni/utils/MinecraftConsoleFilter.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/ItemStackTypeAdapterFactory.kt
Labels: Soon, Backend

#2601 Improvement: Blaze Slayer Flares cooldown
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbility.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbilityCooldown.kt
Labels: Soon

#2597 abstracted navigation rerouting
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/model/Graph.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityNpc.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pathfind/NavigationHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/EnigmaSoulWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditorBugFinder.kt
  src/main/java/at/hannibal2/skyhanni/utils/GraphUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon

#2602 Fix: Broodmother countdown when imminent
  src/main/java/at/hannibal2/skyhanni/features/combat/BroodmotherFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#2599 Fix: add Kuudra + Dungeon items that replace the SB Menu to banned items
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
Labels: Bug Fix - Sooner than Very Soon

#2595 Fix: Race Condition in Hoppity Duplicate Number & Stray no-fire
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
Labels: Bug Fix - Sooner than Very Soon

#2592 Fix: Custom Scoreboard Active Tablist Event
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvent.kt
Labels: Bug Fix - Sooner than Very Soon

#2591 Fix: Powder Tracker
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
Labels: Bug Fix - Sooner than Very Soon

#2600 Backend: Change the detekt rule to be more generalised
  detekt/detekt.yml
  detekt/src/main/kotlin/grammar/AvoidBritishSpelling.kt
  detekt/src/main/kotlin/grammar/AvoidColour.kt
  detekt/src/main/kotlin/grammar/GrammarRuleSetProvider.kt
Labels: Soon

#2594 Fix: Experiments Profit Tracker bottle counting + edit tracker
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationTableAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
Labels: Bug Fix - Sooner than Very Soon
