Repository hannibal002/SkyHanni, pull requests merged in 2024-02, with the labels that each got.

#970 Bug Fix: Fix pets menu detection for /ff
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
Labels: Bug Fix - Sooner than Very Soon

#979 Fix: Powder mining pattern
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
Labels: Bug Fix - Sooner than Very Soon

#972 Fix: Check for in garden
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/NPCVisitorFix.kt
Labels: Bug Fix - Sooner than Very Soon

#971 Fix: Click Keybinds (Minion Feature)
  src/main/java/at/hannibal2/skyhanni/data/ItemClickData.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#976 Fix: shupdaterepo
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
Labels: Bug Fix - Sooner than Very Soon

#885 Backend: Renderable added Alignment
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#846 Backend: Render Rendables rework
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#969 Send Mining Island Events
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningEventConfig.java
  src/main/java/at/hannibal2/skyhanni/data/BossbarData.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/events/BossbarUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventData.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
  src/main/java/at/hannibal2/skyhanni/test/command/CopyBossbarCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/APIUtil.kt
  src/main/java/at/hannibal2/skyhanni/utils/JsonUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/MinecraftConsoleFilter.kt
Labels: Very Soon

#716 Feature: Add mouse sensitivity reduction
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/Storage.java
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/SensitivityReducerConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/SensitivityReducer.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/LockMouseLook.kt
Labels: Very Soon

#831 Better /wiki - Fixed bugs + added official wiki support
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/commands/BetterWikiCommandConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/commands/CommandsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/commands/FandomWikiCommandConfig.java
  src/main/java/at/hannibal2/skyhanni/features/commands/WikiManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/BetterWikiFromMenus.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/FandomWikiFromMenus.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#988 Fix: Add support for Roman Numerals to unique visitors grabber
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#989 Feature: Add hiding completed Reputation Helper tasks
  src/main/java/at/hannibal2/skyhanni/config/features/crimsonisle/ReputationHelperConfig.java
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/CrimsonIsleReputationHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailykuudra/DailyKuudraBossHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/miniboss/DailyMiniBossHelper.kt
Labels: Very Soon

#858 Adds a toggle for the Skyblock Area debug
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.java
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
Labels: Very Soon

#993 Added hoverable for hidden cheap items in ItemTracker
  src/main/java/at/hannibal2/skyhanni/utils/tracker/ItemTrackerData.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
Labels: Very Soon

#992 Fix: Sensitivity Reducer
  src/main/java/at/hannibal2/skyhanni/features/garden/SensitivityReducer.kt
Labels: Bug Fix - Sooner than Very Soon

#990 Fix: ShiftClickNPCSell
  src/main/java/at/hannibal2/skyhanni/features/inventory/ShiftClickNPCSell.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1000 Feature: Add Soul of the Alpha to area minibosses
  src/main/java/at/hannibal2/skyhanni/config/features/combat/MobsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/AreaMiniBossFeatures.kt
Labels: Very Soon

#996 Fix: ShiftClickNPCSell empty invenotry
  src/main/java/at/hannibal2/skyhanni/features/inventory/ShiftClickNPCSell.kt
Labels: Bug Fix - Sooner than Very Soon

#1005 Change: Ignore Shift Click NPC Sell when right-clicking a sack
  src/main/java/at/hannibal2/skyhanni/utils/ItemCategory.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
Labels: Bug Fix - Sooner than Very Soon

#991 Feature: Add auto mouse unlocking on plot teleport
  src/main/java/at/hannibal2/skyhanni/features/misc/LockMouseLook.kt
Labels: Very Soon

#1001 Improve visitor items in sack display
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
Labels: Very Soon

#987 Add mod identification for outgoing mod calls
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/events/PacketEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilterGui.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/EntityPlayerSPHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntityPlayerSP.java
  src/main/java/at/hannibal2/skyhanni/test/CommandsSendToServerLogger.kt
  src/main/java/at/hannibal2/skyhanni/utils/ReflectionUtils.kt
Labels: Very Soon

#1014 Fix: api errors when response was empty
  src/main/java/at/hannibal2/skyhanni/utils/APIUtil.kt
Labels: Bug Fix - Sooner than Very Soon

#1007 Fix: Sensitivity Reducer (again)
  src/main/java/at/hannibal2/skyhanni/features/garden/SensitivityReducer.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/LockMouseLook.kt
Labels: Bug Fix - Sooner than Very Soon

#975 Refactor: Clean up pluralization methods
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestSpawn.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Very Soon

#980 Feature: Draw Geyser Box & Hide Geyser Particles
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/trophyfishing/GeyserFishingConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/trophyfishing/TrophyFishingConfig.java
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GeyserFishing.kt
Labels: Very Soon

#1017 Fixed Purse Pattern
  src/main/java/at/hannibal2/skyhanni/data/PurseAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1020 Fix: tablist footer being uncoloured
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/TabListReader.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1016 Item Name Rewrite and Cache
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.java
  src/main/java/at/hannibal2/skyhanni/data/OwnInventoryData.kt
  src/main/java/at/hannibal2/skyhanni/data/PetAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/SlayerAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/bazaar/BazaarBestSellMethod.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/MinionCraftHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenCropTimeCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenCropsInCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FortuneUpgrades.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/PowerStoneGuideFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/CachedItemData.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUInternalName.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
Labels: Bug Fix - Sooner than Very Soon

#1002 Fix wording of composter fuel warning
  src/main/java/at/hannibal2/skyhanni/config/features/garden/composter/NotifyLowConfig.java
Labels: Bug Fix - Sooner than Very Soon

#977 Backend: Create ActionBarUpdateEvent and use it
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/ActionBarData.kt
  src/main/java/at/hannibal2/skyhanni/data/ActionBarStatsData.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/SkillExperience.kt
  src/main/java/at/hannibal2/skyhanni/events/ActionBarUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/ActionBarValueUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/LorenzActionBarEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/SkyblockXPInChat.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbilityCooldown.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/RiftTimer.kt
  src/main/java/at/hannibal2/skyhanni/test/command/CopyActionBarCommand.kt
Labels: Very Soon

#1021 Improve Exportable Carrots/Expired Pumpkin tooltip in /ff
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FortuneStats.kt
Labels: Very Soon

#880 Feature: Low Quiver Notification
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/QuiverNotification.kt
  src/main/java/at/hannibal2/skyhanni/utils/SoundUtils.kt
Labels: Very Soon

#851 Backend: Add Rounded Rectangles
  src/main/java/at/hannibal2/skyhanni/features/misc/RoundedRectangleShader.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/Shader.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/ShaderHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/ShaderManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/Uniform.kt
  src/main/resources/assets/skyhanni/shaders/rounded_rect.fsh
  src/main/resources/assets/skyhanni/shaders/rounded_rect.vsh
Labels: Very Soon

#986 Backend: Horizontal Container Renderable
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Very Soon

#1022 Fix Sheep pet triggering geyser box and fixed particles being permane…
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GeyserFishing.kt
Labels: Bug Fix - Sooner than Very Soon

#1004 Debug Change: Improved Packet Test
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/test/PacketTest.kt
Labels: Very Soon

#958 Add shader reload capabilities
  src/main/java/at/hannibal2/skyhanni/utils/shader/Shader.kt
Labels: Very Soon

#1031 Fix: Queued Gfs Description
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/GetFromSackConfig.java
Labels: Bug Fix - Sooner than Very Soon

#1032 Fix: Gfs Bazaar using itemName instead of InternalName
  src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionXp.kt
  src/main/java/at/hannibal2/skyhanni/utils/PrimitiveItemStack.kt
Labels: Bug Fix - Sooner than Very Soon

#1026 Fishing Tracker using SH Repo over NEU recipes.
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/events/LorenzEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingTrackerCategoryManager.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
Labels: Very Soon

#1025 Backend: Deprecate LorenzUtils.sendCommandToServer
  src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/PlotIconConfig.java
  src/main/java/at/hannibal2/skyhanni/features/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyCommands.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/SendCoordinatedCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/ViewRecipeCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/BurrowWarpHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenPlotAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenWarpCommands.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/GardenDeskInSBMenu.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Very Soon

#1034 Fixed flawed ruby pattern
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderChestReward.kt
Labels: Bug Fix - Sooner than Very Soon

#960 Backend: Non Textured Chroma Shader
  src/main/java/at/hannibal2/skyhanni/features/chroma/ChromaFontRenderer.kt
  src/main/java/at/hannibal2/skyhanni/features/chroma/ChromaShader.kt
  src/main/java/at/hannibal2/skyhanni/features/chroma/ChromaShaderManager.kt
  src/main/java/at/hannibal2/skyhanni/features/chroma/StandardChromaShader.kt
  src/main/java/at/hannibal2/skyhanni/features/chroma/TexturedChromaShader.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/Shader.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/ShaderManager.kt
  src/main/resources/assets/skyhanni/shaders/standard_chroma.fsh
  src/main/resources/assets/skyhanni/shaders/standard_chroma.vsh
  src/main/resources/assets/skyhanni/shaders/textured_chroma.fsh
  src/main/resources/assets/skyhanni/shaders/textured_chroma.vsh
Labels: Very Soon

#974 Feature: Skyblock Guide Highlights
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/SkyblockGuideConfig.java
  src/main/java/at/hannibal2/skyhanni/events/GuiContainerEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SkyBlockLevelGuideHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SkyblockGuideHighlightFeature.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiContainerHook.kt
Labels: Very Soon

#1036 Fix: Some npc price stuff
  src/main/java/at/hannibal2/skyhanni/features/bazaar/BazaarDataHolder.kt
  src/main/java/at/hannibal2/skyhanni/utils/JsonUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1037 Fix: Send coords being command instead of a message
  src/main/java/at/hannibal2/skyhanni/features/commands/SendCoordinatedCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/ViewRecipeCommand.kt
Labels: Bug Fix - Sooner than Very Soon

#1027 Code Cleanup: Removed Pet Repo Duplications
  src/main/java/at/hannibal2/skyhanni/data/PetAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
Labels: Very Soon

#938 shcopyfoundburrowlocations
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/Storage.java
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/diana/AllBurrowsListConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/diana/DianaConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/diana/AllBurrowsList.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
Labels: Very Soon

#1039 Backend: Make hypixel items api response a proper json object
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/SkyblockItemsDataJson.kt
  src/main/java/at/hannibal2/skyhanni/features/bazaar/BazaarDataHolder.kt
  src/main/java/at/hannibal2/skyhanni/utils/JsonUtils.kt
Labels: Very Soon

#1041 Hide main lobby pet consumables messages
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Very Soon

#1043 Fix: Book bundle showing wrong amount of books
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/ItemsJson.java
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Bug Fix - Sooner than Very Soon

#957 Feature: Skill progress display
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
  src/main/java/at/hannibal2/skyhanni/config/Features.java
  src/main/java/at/hannibal2/skyhanni/config/Storage.java
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/skillprogress/AllSkillDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/skillprogress/CustomGoalConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/skillprogress/SkillETADisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/skillprogress/SkillOverflowConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/skillprogress/SkillProgressBarConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/skillprogress/SkillProgressConfig.java
  src/main/java/at/hannibal2/skyhanni/data/ActionBarData.kt
  src/main/java/at/hannibal2/skyhanni/events/ActionBarUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/SkillOverflowLevelupEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chroma/ChromaShaderManager.kt
  src/main/java/at/hannibal2/skyhanni/features/chroma/StandardChromaShader.kt
  src/main/java/at/hannibal2/skyhanni/features/chroma/TexturedChromaShader.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionXp.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/RoundedRectangleShader.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillTooltip.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillType.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillUtil.kt
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NumberUtil.kt
  src/main/java/at/hannibal2/skyhanni/utils/Quad.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/Shader.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/ShaderHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/ShaderManager.kt
  src/main/resources/assets/skyhanni/bars/1.png
  src/main/resources/assets/skyhanni/bars/2.png
  src/main/resources/assets/skyhanni/bars/3.png
  src/main/resources/assets/skyhanni/bars/4.png
  src/main/resources/assets/skyhanni/bars/5.png
  src/main/resources/assets/skyhanni/shaders/textured_chroma.vsh
  src/main/resources/mixins.skyhanni.json
Labels: Very Soon

#1046 Fixed internal name resolving
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/MinionCraftHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CollectionTracker.kt
  src/main/java/at/hannibal2/skyhanni/test/HighlightMissingRepoItems.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemNameResolver.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUInternalName.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Very Soon, Bug Fix - Sooner than Very Soon

#1045 Fix: GFS mess
  src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/SacksJson.java
  src/main/java/at/hannibal2/skyhanni/features/commands/tabcomplete/GetFromSacksTabComplete.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
Labels: Very Soon, Bug Fix - Sooner than Very Soon, Waiting on Dependency PR

#1048 Fix: SkillProgess display size without bar
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
Labels: Bug Fix - Sooner than Very Soon

#1049 Fixed wrong entry in changelog
  CHANGELOG.md
Labels: Bug Fix - Sooner than Very Soon

#1053 Use neu repo instead of skyhanni repo
  src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/NeuSacksJson.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/SacksJson.java
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/events/NeuRepositoryReloadEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/test/HighlightMissingRepoItems.kt
Labels: Bug Fix - Sooner than Very Soon

#1055 Fixed multiple edge cases with /gfs.
  src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/tabcomplete/GetFromSacksTabComplete.kt
Labels: Bug Fix - Sooner than Very Soon

#1060 fix: Missing colour code in deletion message
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
Labels: Bug Fix - Sooner than Very Soon

#1057 Fixed creating too many timers
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillType.kt
Labels: Bug Fix - Sooner than Very Soon

#1058 Fix: Skill Display
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Bug Fix - Sooner than Very Soon

#1054 Geyser fixes
  src/main/java/at/hannibal2/skyhanni/config/features/crimsonisle/SulphurSkitterBoxConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/trophyfishing/GeyserFishingConfig.java
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GeyserFishing.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/SulphurSkitterBox.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1062 Fix: bring back NEUItems.allInternalNames
  src/main/java/at/hannibal2/skyhanni/test/HighlightMissingRepoItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemNameResolver.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Bug Fix - Sooner than Very Soon

#1061 Fix: Current mayor taking 20 minutes to get loaded
  src/main/java/at/hannibal2/skyhanni/data/MayorElection.kt
Labels: Bug Fix - Sooner than Very Soon

#1068 Talbot's Theodolite: Support exact height message
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#1063 Fix: Box of Seeds not working with /shcroptime
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#1069 Fix: More Skill Progress Bugs
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillTooltip.kt
Labels: Bug Fix - Sooner than Very Soon

#1073 Fix: Weight display
  src/main/java/at/hannibal2/skyhanni/data/ProfileStorageData.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/EliteBotJson.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#787 Auto enable+configure devauth
  .devauth/config.toml
  .gitignore
  build.gradle.kts
Labels: Very Soon

#1079 Improve performance of removeColor.
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/test/java/at/hannibal2/skyhanni/test/RemoveColorTest.kt
Labels: Very Soon

#1067 Backend: Remove wildcard import
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/VisualWordGui.kt
Labels: Very Soon

#876 Feature: Max Items with current Purse
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/data/PurseAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/MaxPurseItems.kt
Labels: Very Soon
