Repository hannibal002/SkyHanni, pull requests merged in 2024-05, with the labels that each got.

#1599 Improvement: Move Cookies and rabbits
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/EventConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsShared.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityNpc.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateAmount.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryShortcut.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTimeTowerManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTooltip.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTooltipCompact.kt
Labels: Soon, Backend

#1600 Improvements: Better descriptions
  src/main/java/at/hannibal2/skyhanni/config/features/event/EventConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
Labels: Soon, Waiting on Dependency PR

#1601 Feature: Chocolate Shop Price
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateShopPriceConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/SkyMartCopperPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTooltip.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateShopPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordRPCManager.kt
Labels: Soon, Waiting on Dependency PR

#1604 Fix: flicker in tooltip move
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTooltipCompact.kt
Labels: Bug Fix - Sooner than Very Soon

#1608 Fix: not sharing location when barn full
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
Labels: Bug Fix - Sooner than Very Soon

#1602 Feature: Chocolate change leaderboard
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolatePositionChange.kt
Labels: Soon, Waiting on Dependency PR

#1612 fix calculation
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTooltip.kt
Labels: Bug Fix - Sooner than Very Soon

#1398 Fix: Composter GfS Messages
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
Labels: Bug Fix - Sooner than Very Soon

#1613 Fix: Shortened some rpc stuff
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordRPCManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
Labels: Bug Fix - Sooner than Very Soon

#1471 Feature: add guide to dungeon hub races
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/DungeonConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/DungeonsRaceGuideConfig.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/DungeonHubRacesJson.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonsRaceGuide.kt
Labels: Soon

#1632 Fix: Magical Power not setting to 0 when the Line doesn't exist
  src/main/java/at/hannibal2/skyhanni/data/MaxwellAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1469 Feature: Add Ignored users for Party Commands
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/PartyCommandsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/Storage.java
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyChatCommands.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
Labels: Soon

#1622 added inventory background to gui editor
  src/main/java/at/hannibal2/skyhanni/config/core/config/gui/GuiPositionEditor.kt
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/AccessorGuiContainer.java
Labels: Soon

#1562 Backend: Cleanup HoppityCollectionStats to improve readability
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
Labels: Soon, Backend

#1637 fixed a few bugs
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateShopPrice.kt
Labels: Bug Fix - Sooner than Very Soon

#1618 Fix: Pest render priority
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleLine.kt
Labels: Bug Fix - Sooner than Very Soon

#1623 Backend: Pet rarity support
  src/main/java/at/hannibal2/skyhanni/utils/ItemNameResolver.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Soon, Backend

#1627 Fix: Slayer warning rift
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerQuestWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerType.kt
Labels: Bug Fix - Sooner than Very Soon

#1628 Fix: Excavator Profile Tracker
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/FossilExcavatorAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ProfitPerExcavation.kt
Labels: Bug Fix - Sooner than Very Soon

#1626 disable mark low levels
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
Labels: Soon

#1639 Fix: ClickType IDs and Visitor Reward Warning
  src/main/java/at/hannibal2/skyhanni/events/GuiContainerEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorListener.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorRewardWarning.kt
Labels: Bug Fix - Sooner than Very Soon

#1648 Improvement: Hide garden guis in cf
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
Labels: Soon

#1606 Fix: Bazaar buy order error when nothing to cancel
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarCancelledBuyOrderClipboard.kt
Labels: Bug Fix - Sooner than Very Soon

#1645 Fix: Farming lane detection
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1638 added choc until next prestige
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
Labels: Soon

#1641 Improvement: Show stars on time tower and coach jackrabbit
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorRewardWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/QuickCraftFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateAmount.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTooltip.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryUpgrade.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon

#1652 Improvement: Updating Chocolate Shop
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateAmount.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateShopPrice.kt
Labels: Soon

#1642 warning when upgrade avaliavble
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateUpgradeWarningsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTooltip.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryUpgradeWarning.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
Labels: Soon

#1631 Fix: sendcoords too long description
  src/main/java/at/hannibal2/skyhanni/features/misc/PatcherSendCoordinates.kt
Labels: Bug Fix - Sooner than Very Soon

#1619 Fix: mining islands slayer
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
Labels: Bug Fix - Sooner than Very Soon

#1607 Fix: Nicked vampire slayer
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#1597 Backend: Bazaar Fetcher
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.java
  src/main/java/at/hannibal2/skyhanni/data/bazaar/BazaarJson.kt
  src/main/java/at/hannibal2/skyhanni/data/bazaar/HypixelBazaarFetcher.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarData.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarDataHolder.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/APIUtil.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Soon, Backend

#1650 Improvement: Armor Drop Tracker
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/ArmorDropTracker.kt
Labels: Soon

#1654 Improvement: Show time until upgrade
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
Labels: Soon

#1625 added timer to hoppity egg gui and chat messages
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
Labels: Soon

#1659 Fix: A few chocolate factory issues
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateAmount.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTooltip.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryUpgrade.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryUpgradeWarning.kt
Labels: Bug Fix - Sooner than Very Soon

#1658 Fix upside down mixin and split up spinny from upside down
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/ContributorsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ContributorManager.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/RendererLivingEntityHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinRendererLivingEntity.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinContributorRendererEntityLiving.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinRendererLivingEntityHookSBA.java
Labels: Soon

#1662 Fix: Egglocator occasionally breaking
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
Labels: Bug Fix - Sooner than Very Soon

#997 Feature: Add overflow crop milestones
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/cropmilestones/CropMilestonesConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/cropmilestones/CropMilestonesOverflowConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/data/GardenCropMilestones.kt
  src/main/java/at/hannibal2/skyhanni/data/GardenCropMilestonesCommunityFix.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/CropType.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingMilestoneCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenLevelDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenBestCropTime.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/GardenCropMilestoneInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/GardenInventoryNumbers.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/GardenInventoryTooltipOverflow.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillTooltip.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon

#1665 Improvement: Update saved chocolate when getting a duplicate rabbit
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateAmount.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
Labels: Soon

#1663 Add shtestmessage for complex messages
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TestChatCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
Labels: Backend

#1534 Backend: Renderable in GardenCropMilestoneDisplay
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon, Backend

#1680 Fix: chat click and hover
  src/main/java/at/hannibal2/skyhanni/features/chat/playerchat/PlayerChatModifier.kt
Labels: Bug Fix - Sooner than Very Soon

#1629 Fix: Quiver Warning
  src/main/java/at/hannibal2/skyhanni/data/QuiverAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/quiver/QuiverWarning.kt
Labels: Bug Fix - Sooner than Very Soon

#1666 Improvement: Add Incoming Tablist Event to Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvents.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Soon

#1671 Improvement: Duplicate Rabbit Time
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateAmount.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
Labels: Backend

#1670 Improvement: Show during contest
  src/main/java/at/hannibal2/skyhanni/config/features/event/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/ReminderUtils.kt
Labels: Soon

#1675 Improvement: egg hunt include note
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsShared.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
Labels: Soon

#1669 Improvement: line to hoppity guess
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
Labels: Soon

#1682 Improvement: Use raw craft cost
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Soon

#1690 Fix: inventory hotkeys hotbar item move behaviour
  src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryKeybinds.kt
Labels: Bug Fix - Sooner than Very Soon

#1633 Fix: Reputation Helper wrong miniboss amount
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/QuestLoader.kt
Labels: Bug Fix - Sooner than Very Soon

#1683 Fix: Raw per second being wrong sometimes
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
Labels: Bug Fix - Sooner than Very Soon

#1685 Fix: Filter out colour codes correctly
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsShared.kt
Labels: Bug Fix - Sooner than Very Soon

#1686 Fix: Pluralize negative changes
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolatePositionChange.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1693 Fix: Crop Milestone Tab List
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenCropMilestoneFix.kt
Labels: Bug Fix - Sooner than Very Soon

#1697 Fix: Another Instance of double Objectives
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#1710 Backend: Migrate and Simplify SkyBlockTime.kt from NEU -> SkyHanni
  src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/anniversary/Year300RaffleEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/winter/NewYearCakeReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/FarmingContestAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobFarmingContestsInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/KingTalismanHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/InGameDateDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/TimeFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SimpleTimeMark.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockTime.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyblockSeason.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
Labels: Soon

#1699 Fixed highlights in inventory staying when exiting via NEU recipes
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/data/ScreenData.kt
Labels: Bug Fix - Sooner than Very Soon

#1535 Backend: Enum in GardenCropMilestoneDisplay
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
Labels: Soon, Backend

#1634 Backend: better error detection in enchant parser
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
Labels: Soon, Backend

#1694 Improvement: Open rng inv via the Display
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerRngMeterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerType.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
Labels: Soon

#1726 Fix: Time to prestige being wrong the second after using time tower
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
Labels: Bug Fix - Sooner than Very Soon

#1721 Fix: Rift Hay Eaten Scoreboard Line
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvents.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Bug Fix - Sooner than Very Soon

#1727 Fix: showing time to upgrade when maxed
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
Labels: Bug Fix - Sooner than Very Soon

#1716 Fix: Stash chat
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerChatManager.kt
Labels: Bug Fix - Sooner than Very Soon

#1701 Feature: Mining Commissions Blocks Color
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/CommissionsBlocksColorConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
  src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowParticleFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/HighlightMiningCommissionMobs.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/MiningCommissionsBlocksColor.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/BlockRendererDispatcherHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinBlockRendererDispatcher.java
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzColor.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeLimitedSet.kt
Labels: Soon

#1728 Fix: npe in inventory utils
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1692 Fix: Farming tool detection
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1723 Improvement: made the garden chat message clickable
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterDisplay.kt
Labels: Soon

#1707 Fix rare chat crash
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/event/PlayerAllChatEvent.kt
Labels: Bug Fix - Sooner than Very Soon

#1730 Hotfix: Custom Scoreboard Issue with transparency or smth
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/RenderBackground.kt
Labels: Bug Fix - Sooner than Very Soon

#1736 description update
  src/main/java/at/hannibal2/skyhanni/config/features/chat/FilterTypesConfig.java
Labels: Soon

#1732 Improvement: Compatibility with Architect Draft and copy & paste from chat.
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonArchitectFeatures.kt
Labels: Soon

#1718 Backend: Text API
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatClickActionManager.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerNameFormatter.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyChatCommands.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonArchitectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/AccountUpgradeReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishManager.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TestChatCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatComponentUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/chat/ChatClickActionManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/chat/Text.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Bug Fix - Sooner than Very Soon, Backend

#1739 Improvement + Fix: More Hoppity Waypoint options
  src/main/java/at/hannibal2/skyhanni/config/features/event/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
Labels: Soon, Bug Fix - Sooner than Very Soon

#1704 Fix: Spaces in chat formatting
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerNameFormatter.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/AdvancedPlayerList.kt
Labels: Bug Fix - Sooner than Very Soon

#1722 Feature: Replace Roman Numerals with Arabic Numerals
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/playerchat/PlayerChatModifier.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ReplaceRomanNumerals.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Soon

#1740 Improvement: Custom Reminder
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryCustomReminderConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/fame/ReminderUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryCustomReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryUpgradeWarning.kt
Labels: Soon

#1696 Improvement: Cleanup HoppityEggPlayerOpacityChanger
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/events/render/EntityRenderLayersEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggDisplayManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggPlayerOpacityChanger.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinRendererLivingEntity.java
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon

#1737 Fix: Visitor timer flickering while farming
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorTimer.kt
Labels: Bug Fix - Sooner than Very Soon

#1746 Fix: Mining Event Error Spam
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/APIUtil.kt
Labels: Bug Fix - Sooner than Very Soon

#1756 Backend: code duplication in AxisAlignedBB.getCorners
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsWalls.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Backend

#1630 Fix: oldest bug in skyhanni
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#1749 Improvement: Disable colored blocks in the mineshaft
  src/main/java/at/hannibal2/skyhanni/features/mining/MiningCommissionsBlocksColor.kt
Labels: Soon

#1757 Fix: Double Spooky Festival Time in Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvents.kt
Labels: Bug Fix - Sooner than Very Soon

#1758 Fix: Chocolate factory upgrade warning breaking
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryCustomReminder.kt
Labels: Bug Fix - Sooner than Very Soon

#1752 Improvement: Quiver Design Change
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
Labels: Soon

#1647 Improvement: Pest line middle of plot
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleLine.kt
Labels: Soon

#1766 Feature: Blaze Slayer Fire Pillar Display
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/slayer/SlayerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/slayer/blaze/BlazeConfig.java
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/FirePillarDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Soon

#1770 Fix: Faction Chat
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerNameFormatter.kt
Labels: Bug Fix - Sooner than Very Soon

#1768 Improvement: sh gui 20s
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeLimitedCache.kt
Labels: Soon

#1767 Improvement: Changed some default settings and positions
  src/main/java/at/hannibal2/skyhanni/config/features/chat/FilterTypesConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/combat/QuiverDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/crimsonisle/ReputationHelperConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/DropsStatisticsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/TimerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/ParticleHiderConfig.java
Labels: Soon

#1762 Improvement: Rabbit crush warning only during Hoppity
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
Labels: Soon

#1774 Fix: Chocolate Factory Time Tower math
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1780 Improvement: better performance by reducing line of sight check for minion display
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
Labels: Soon

#1536 Improvement: Crops per second/per hour
  src/main/java/at/hannibal2/skyhanni/config/features/garden/cropmilestones/CropMilestonesConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
Labels: Soon

#1765 Feature: simple ferocity display
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/combat/CombatConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/combat/FerocityDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/features/combat/FerocityDisplay.kt
Labels: Soon

#1760 Improvement: Time until Full Tower Charges
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTimeTowerManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/SimpleTimeMark.kt
Labels: Soon

#1779 Improvement: updating scoreboard and tab list less often
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
Labels: Soon

#1782 Improvement: performance in various ways
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/ChumBucketHiderConfig.java
  src/main/java/at/hannibal2/skyhanni/data/EventCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/ChumBucketHider.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyblockSeason.kt
Labels: Soon

#1786 Fix: some REFINED_BOTTLE_OF_JYRRE errors
  src/main/java/at/hannibal2/skyhanni/features/event/winter/JyrreTimer.kt
Labels: Bug Fix - Sooner than Very Soon

#1783 use some more gl constants
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/data/TitleManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon, Backend

#1785 Fix: Removed excess space in chat formatting
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerChatManager.kt
Labels: Bug Fix - Sooner than Very Soon

#1764 Improvement: Fixpests delay
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
Labels: Soon

#1747 Improvement: 3 egg warn
  src/main/java/at/hannibal2/skyhanni/config/features/event/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
Labels: Soon

#1789 Fix: Winter Event, Total Damage Pattern
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix - Sooner than Very Soon

#1771 Backend: performance improvement trevor trapper
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorTracker.kt
Labels: Soon, Backend

#1791 Fix: remove bugged minions
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#1792 Fix: A few small bugs
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/EntityMovementData.kt
  src/main/java/at/hannibal2/skyhanni/data/GardenCropUpgrades.kt
  src/main/java/at/hannibal2/skyhanni/events/CropUpgradeUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFStats.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MiscFeatures.kt
Labels: Bug Fix - Sooner than Very Soon

#1775 Fix: Profit Tracker Enchanted Book
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
Labels: Bug Fix - Sooner than Very Soon

#1797 Fix: Griffin Spots
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowHelper.kt
Labels: Bug Fix - Sooner than Very Soon

#1805 Fixed choc shop profit calculations
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/SkyMartCopperPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateShopPrice.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1796 Fix: Hoppity Egg warnings
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryCustomReminder.kt
Labels: Bug Fix - Sooner than Very Soon

#1801 Fix: Yog Slayer commissions highlighting Bal
  src/main/java/at/hannibal2/skyhanni/features/mining/HighlightMiningCommissionMobs.kt
Labels: Bug Fix - Sooner than Very Soon

#1795 Improvement: Arrow count in Custom Scoreboard when wearing Skeleton Masters Chestplate
  src/main/java/at/hannibal2/skyhanni/data/QuiverAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
Labels: Soon

#1798 Fix white enchantments
  src/main/java/at/hannibal2/skyhanni/config/features/chroma/ChromaConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/EnchantParsingConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/Enchant.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/FontRendererHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/MixinPatcherFontRendererHookHook.kt
Labels: Bug Fix - Sooner than Very Soon

#1743 Feature: cofl ah search item
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/AuctionHouseConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/auctionhouse/AuctionHouseCopyUnderbidPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/auctionhouse/AuctionHouseOpenPriceWebsite.kt
Labels: Soon

#1810 Fix: Outside SkyBlock
  src/main/java/at/hannibal2/skyhanni/config/enums/OutsideSbFeature.kt
Labels: Bug Fix - Sooner than Very Soon

#1809 Fix: Error in AllBurrowsList
  src/main/java/at/hannibal2/skyhanni/features/event/diana/AllBurrowsList.kt
Labels: Bug Fix - Sooner than Very Soon

#1808 Improvement: Fix Diana chat help
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaFixChat.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
Labels: Soon

#1813 Fix: Armor Hider
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1806 Fixed time until next charge being wrong
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
Labels: Bug Fix - Sooner than Very Soon

#1819 Fix plot border rendering
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenPlotAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1820 Few bug fixes
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/christmas/PresentWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
Labels: Bug Fix - Sooner than Very Soon

#1822 Fix: Max Island Size with Crimson + Catacombs
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
Labels: Bug Fix - Sooner than Very Soon

#1825 Fix: Co-op capitalization in PlayerNameFormatter
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerNameFormatter.kt
Labels: Bug Fix - Sooner than Very Soon

#1821 Fix: Volcano Explosivity Display
  src/main/java/at/hannibal2/skyhanni/features/nether/VolcanoExplosivityDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#1827 choc factory stats show prestige level
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
Labels: Soon

#1828 Fix: Bestiary Display when in search results
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
Labels: Bug Fix - Sooner than Very Soon

#1755 Fixed ReplaceRomanNumerals replacing the word "I" in dialogue
  src/main/java/at/hannibal2/skyhanni/features/misc/ReplaceRomanNumerals.kt
Labels: Bug Fix - Sooner than Very Soon

#1823 Fix: FF ioobe
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#1831 Fix: Wrong Visitor Time
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorTimer.kt
Labels: Bug Fix - Sooner than Very Soon

#1832 Fix: Quiver Warning
  src/main/java/at/hannibal2/skyhanni/data/QuiverAPI.kt
  src/main/java/at/hannibal2/skyhanni/events/QuiverUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/quiver/QuiverDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/quiver/QuiverWarning.kt
Labels: Bug Fix - Sooner than Very Soon

#1814 Fix: Reworked slayer warning
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
  src/main/java/at/hannibal2/skyhanni/data/SlayerAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerQuestWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerType.kt
Labels: Bug Fix - Sooner than Very Soon

#1829 Fix: Farming Contest bugs
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/FarmingContestAPI.kt
Labels: Bug Fix - Sooner than Very Soon

#1833 Fix: Storage Value Bz
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
Labels: Bug Fix - Sooner than Very Soon

#1834 Fix: Chest value in Minion
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
Labels: Bug Fix - Sooner than Very Soon

#1842 Fix: Ultimate Jerry
  src/main/java/at/hannibal2/skyhanni/utils/ItemNameResolver.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#1841 Fix: bazaar empty data
  src/main/java/at/hannibal2/skyhanni/data/bazaar/HypixelBazaarFetcher.kt
Labels: Bug Fix - Sooner than Very Soon

#1840 Fix: Craft Materials
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/CraftMaterialsFromBazaar.kt
Labels: Bug Fix - Sooner than Very Soon

#1839 Fix: Memory leaks
  src/main/java/at/hannibal2/skyhanni/features/slayer/HideMobNames.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/HellionShieldHelper.kt
Labels: Bug Fix - Sooner than Very Soon

#1844 Fix: MobDetection Memory Leak
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
Labels: Bug Fix - Sooner than Very Soon

#1848 Fix: small memory leak
  src/main/java/at/hannibal2/skyhanni/data/EntityData.kt
Labels: Bug Fix - Sooner than Very Soon

#1846 Fix: Hover and clicks in guis
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableTooltips.kt
Labels: Bug Fix - Sooner than Very Soon

#1773 Backend: rewrote getclipboard logic
  src/main/java/at/hannibal2/skyhanni/utils/ClipboardUtils.kt
Labels: Soon, Backend

#1873 Remove unneeded code
  src/main/java/at/hannibal2/skyhanni/features/garden/ToolTooltipTweaks.kt
Labels: Soon

#1835 Add: Ability to switch repo branch
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/dev/RepositoryConfig.java
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoUtils.kt
  src/main/java/at/hannibal2/skyhanni/events/RepositoryReloadEvent.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
Labels: Soon, Backend

#1748 Improvement: Compact Hoppity Chat
  src/main/java/at/hannibal2/skyhanni/config/features/event/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TestChatCommand.kt
Labels: Soon

#1849 Fix: Incorrect crop type for rat.
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestType.kt
Labels: Bug Fix - Sooner than Very Soon
