Repository hannibal002/SkyHanni, pull requests merged in 2024-10, with the labels that each got.

#2629 Fix: Typos in readme
  README.md
Labels: Soon

#2631 Fix: Custom Scoreboard Carnival
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvent.kt
Labels: Bug Fix - Sooner than Very Soon

#2636 Fix: Add more Pablo patterns
  src/main/java/at/hannibal2/skyhanni/features/nether/PabloHelper.kt
Labels: Bug Fix - Sooner than Very Soon

#2632 Fix: Minister in Calendar Color Reset
  src/main/java/at/hannibal2/skyhanni/features/inventory/MinisterInCalendar.kt
Labels: Bug Fix - Sooner than Very Soon

#2627 Fix: Strays Wrongly Counting as Unique
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
Labels: Soon, Bug Fix - Sooner than Very Soon

#2620 Fix: Item trackers saying removed item name from item name
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
Labels: Soon, Bug Fix - Sooner than Very Soon

#2622 Improvement: Add ignored crops for lane features
  src/main/java/at/hannibal2/skyhanni/config/features/garden/laneswitch/FarmingLaneConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneAPI.kt
Labels: Soon

#2633 Improvement: Change "efficient miner" to "spread" in mineshaft pity breakdown
  src/main/java/at/hannibal2/skyhanni/features/mining/MineshaftPityDisplay.kt
Labels: Soon

#2619 Backend: Rename keystore file to specify it is for skyhanni
  src/main/java/at/hannibal2/skyhanni/utils/APIUtils.kt
  src/main/resources/skyhanni-keystore.jks
Labels: Soon

#2566 Fix: Superpair Data
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationTableAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/SuperpairDataDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/SuperpairExperimentInformationDisplay.kt
Labels: Soon, Bug Fix - Sooner than Very Soon

#2628 Improvement: Added cooldown to Carnival NPC click
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalQuickStart.kt
Labels: Soon

#2635 Automatically stating pathfind after clicking the hypixel reminder ch…
  src/main/java/at/hannibal2/skyhanni/data/EntityMovementData.kt
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityNpc.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/UpgradeReminder.kt
Labels: Soon

#2634 Improvement: Pathfind Rendering
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/IslandExceptions.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/PowderMiningChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pathfind/NavigationHelper.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/MobUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon

#2623 Backend: Alert Clock Offsets
  build.gradle.kts
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/utils/ComputerTimeOffset.kt
  src/main/java/at/hannibal2/skyhanni/utils/OSUtils.kt
Labels: Soon

#2638 Improvement: Slight Touch up for Hoppity Event Summary
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
Labels: Soon

#2643 Fix: Flare expire warning
  src/main/java/at/hannibal2/skyhanni/features/combat/FlareDisplay.kt
Labels: Bug Fix - Sooner than Very Soon

#2644 Fix: Ender node tracker
  src/main/java/at/hannibal2/skyhanni/features/combat/endernodetracker/EnderNodeTracker.kt
Labels: Bug Fix - Sooner than Very Soon

#2645 Fix: Powder Tracker not tracking items
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
Labels: Soon, Bug Fix - Sooner than Very Soon

#2641 Fix: Preconditions to debug commands
  src/main/java/at/hannibal2/skyhanni/test/command/TrackParticlesCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TrackSoundsCommand.kt
Labels: Soon, Bug Fix - Sooner than Very Soon

#2646 Fix: Dummies and Damage Indicator
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/MobFinder.kt
Labels: Bug Fix - Sooner than Very Soon

#2647 Improvement: Superpair Experimentation data always visible
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/experimentationtable/ExperimentationTableConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/SuperpairDataDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilSolverDisplay.kt
Labels: Soon

#2617 Backend: Detekt Fixes Part 5
  build.gradle.kts
  src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/HotmData.kt
  src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/goals/GoalType.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ColorFormattingHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/PowderMiningChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/BossType.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/MobHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHideItems.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/HighlightDungeonDeathmite.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/jerry/frozentreasure/FrozenTreasureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/easter/EasterEggWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/SeaCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/AnitaMedalProfit.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/ArmorDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/DicerRngDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingDirection.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/QuickCraftFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/CrownOfAvariceCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/HighlightMiningCommissionMobs.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/NonGodPotEffectDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/VoltHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/RiftUpsideDownParkour.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerMiniBossFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerType.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/HellionShield.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/PrimitiveRecipe.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkyHanniTypeAdapters.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon

#2652 change neu to 2.4
  build.gradle.kts
Labels: Soon

#2661 Fix: Template
  pull_request_template.md
Labels: Soon, Bug Fix - Sooner than Very Soon

#2649 Backend: Removed Password in Download Source Check
  src/main/java/at/hannibal2/skyhanni/tweaker/DownloadSourceChecker.java
Labels: Soon

#2662 Fix: Add delay to Pablo GfS message
  src/main/java/at/hannibal2/skyhanni/features/nether/PabloHelper.kt
Labels: Bug Fix - Sooner than Very Soon

#2669 Fix: repo getting redownloaded on the same commit
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
Labels: Bug Fix - Sooner than Very Soon

#2651 Fix: error punctuation
  src/main/java/at/hannibal2/skyhanni/api/event/EventHandler.kt
  src/main/java/at/hannibal2/skyhanni/events/LorenzEvent.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Bug Fix - Sooner than Very Soon

#2663 Fix: Stop king talisman tracker on finish
  src/main/java/at/hannibal2/skyhanni/features/mining/KingTalismanHelper.kt
Labels: Soon, Bug Fix

#2650 Fix: Made it so you can shift click to disable features like it says
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiScreen.java
Labels: Soon, Bug Fix

#2666 Fix: chroma disabling patchers font renderer for no reason
  src/main/java/at/hannibal2/skyhanni/config/features/chroma/ChromaConfig.java
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/FontRendererHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/MixinPatcherFontRendererHookHook.kt
Labels: Soon, Bug Fix

#2655 Improvement: Option to hide other players while in Gunther's Race
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/westvillage/GunthersRaceConfig.java
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/RiftGunthersRace.kt
Labels: Soon

#2656 Remove: Mithril Powder from Powder Tracker
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/PowderTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderChestReward.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
Labels: Soon

#2658 Improvement: Make visitor GUI clickable to tp to barn
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/TimerConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorTimer.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon

#2670 Fixed trophy fish title
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishMessages.kt
Labels: Bug Fix

#2671 Improvement: Mining Event Error Format
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
Labels: Soon

#2676 Improvement: Add Search Tag to the Account Upgrade Reminder
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
Labels: Soon

#2672 Improvement: Working on scoreboard errors again
  src/main/java/at/hannibal2/skyhanni/features/combat/SpidersDenAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Soon

#2678 Fix: Powder Tracker IndexOutOfBoundsException
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderChestReward.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
Labels: Soon, Bug Fix

#2674 Fix: Account upgrade warning
  src/main/java/at/hannibal2/skyhanni/features/fame/UpgradeReminder.kt
Labels: Bug Fix

#2677 Improvement: Add Mining Effects to Non God Pot Effect Display
  src/main/java/at/hannibal2/skyhanni/features/misc/NonGodPotEffectDisplay.kt
Labels: Soon

#2681 Improvement: Better bz errors
  src/main/java/at/hannibal2/skyhanni/data/bazaar/HypixelBazaarFetcher.kt
Labels: Soon

#2680 Improvement: Fewer Server id errors
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
Labels: Soon

#2682 Fix: Wiki keybind searching for <null>
  src/main/java/at/hannibal2/skyhanni/config/features/commands/BetterWikiCommandConfig.java
  src/main/java/at/hannibal2/skyhanni/features/commands/WikiManager.kt
Labels: Soon, Bug Fix

#2683 Fix: Unknown Perkpocalypse Mayor Chat Spam
  src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
Labels: Soon, Bug Fix

#2679 Fixed /viewrecipe replace breaking pages
  src/main/java/at/hannibal2/skyhanni/features/commands/ViewRecipeCommand.kt
Labels: Soon, Bug Fix

#2684 Backend: Migrate Plhlegblast
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/SeaCreatureTracker.kt
Labels: Soon

#2685 Fix: Custom Scoreboard Update time
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
Labels: Bug Fix

#2686 Fix: Hoppity wrong amount
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
Labels: Bug Fix

#2687 Backend: Update pr template
  pull_request_template.md
Labels: Soon

#2688 Fix: Hoppity > max
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateAmount.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
Labels: Soon, Bug Fix

#2690 Backend: Assign relevant labels
  .github/workflows/assign-relevant-labels.yml
  .github/workflows/label-bug-fix.yml
Labels: Soon, Backend

#2699 Fix: Experimentation Table Pet Rule
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/GuardianReminder.kt
Labels: Soon, Bug Fix

#2698 Improvement: Pocket Sack-in-a-Sack in Estimated Item Value
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Soon

#2696 Fix: Ghost Counter area detection
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
Labels: Soon, Bug Fix

#2625 Feature: Show unique hoppity eggs in the warp menu
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/WarpMenuUniques.kt
Labels: Soon

#2702 Fix: empty list in compact experiment rewards
  src/main/java/at/hannibal2/skyhanni/features/chat/CompactExperimentRewards.kt
Labels: Bug Fix

#2694 Feature: Inventory Focus Mode
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/FocusModeConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/FocusMode.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
Labels: Soon

#2253 Backend: Stats API
  src/main/java/at/hannibal2/skyhanni/config/features/combat/FerocityDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/FerocityDisplay.kt
Labels: Soon

#2708 Fix: Soopy Spam
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Bug Fix

#1885 Feature: Change lava color
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/FishingConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/LavaReplacementConfig.java
  src/main/java/at/hannibal2/skyhanni/features/fishing/LavaReplacement.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinBlockLiquid.java
Labels: Soon

#2709 Fix: Custom Scoreboard Second Objective
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Soon, Bug Fix

#2710 Fix: MP Reset in Dungeons
  src/main/java/at/hannibal2/skyhanni/data/MaxwellAPI.kt
Labels: Soon, Bug Fix

#2711 Fix: Remove color codes from hoppity eggs share message
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
Labels: Soon, Bug Fix

#2704 Improvement: Add Distance to Patcher Send Coords Waypoints
  src/main/java/at/hannibal2/skyhanni/features/misc/PatcherSendCoordinates.kt
Labels: Soon

#2703 Fix: buy from bazaar supercraft on overflowed inventory names
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/CraftMaterialsFromBazaar.kt
Labels: Soon, Bug Fix

#2056 Backend: LorenzVec up/down and drawLineToEye
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDebug.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/MobHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/cosmetics/CosmeticFollowingLine.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHighlightClickedBlocks.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonLividFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocations.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/ShowFishingItemName.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/ThunderSparksHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/TotemOfCorruption.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenStartLocation.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleWaypoint.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/MineshaftWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/PatcherSendCoordinates.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/MatriarchHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangBlazingSouls.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangGravityOrbs.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/RiftAgaricusCap.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/RiftWiltedBerberisHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/VoltHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveDefenseBlocks.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/RiftUpsideDownParkour.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/EnigmaSoulWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/motes/RiftMotesOrb.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerItemsOnGround.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerMiniBossFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/enderman/EndermanSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/summonings/SummoningSoulsName.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TrackParticlesCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TrackSoundsCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
  src/main/java/at/hannibal2/skyhanni/utils/ParkourHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon, Backend

#2614 Feature: Precision Mining Hightlighter
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
  src/main/java/at/hannibal2/skyhanni/features/mining/PrecisionMiningHighlight.kt
Labels: Soon

#2598 Feature: Highlight Crystal Nucleus Crystals
  src/main/java/at/hannibal2/skyhanni/config/features/mining/CrystalHighlighterConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/NucleusBarriersBox.kt
Labels: Soon

#2706 Improvement: Added Item Cooldown to Totem of Corruption and Enrager
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbility.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbilityCooldown.kt
Labels: Soon

#2693 Fix/Improvement: Translator feature
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/TranslatorConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/translation/TranslatableLanguage.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/translation/Translator.kt
Labels: Soon, Bug Fix

#2715 Fix: Make adding stars debug only
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Soon, Bug Fix

#2701 Backend: Update upload artifact action version
  .github/workflows/build.yml
  .github/workflows/generate-constants.yaml
Labels: Soon, Backend

#2692 Backend: Add Changelog Verification
  .github/workflows/pr-check.yml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/skyhannibuildsystem/ChangelogVerification.kt
Labels: Soon, Backend

#1865 Backend: Add dungeon phases
  src/main/java/at/hannibal2/skyhanni/events/DungeonBossPhaseChangeEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonBossAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/TerracottaPhase.kt
Labels: Soon

#2718 Fix: Guardian warn text
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationTableAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/GuardianReminder.kt
Labels: Soon, Bug Fix

#2112 Improvement + Fix: Ashfang Features with Mob Detection
  src/main/java/at/hannibal2/skyhanni/data/EntityData.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobData.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
  src/main/java/at/hannibal2/skyhanni/events/MobEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/entity/EntityLeaveWorldEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangBlazes.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangBlazingSouls.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangFreezeCooldown.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangGravityOrbs.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangHideDamageIndicator.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangHideParticles.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangHider.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangHighlights.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangManager.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangNextResetCooldown.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinWorld.java
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ExtendedChatColor.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon, Bug Fix

#2719 Feature: Terminal Waypoints
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/DungeonConfig.java
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonBossAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/floor7/TerminalInfo.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/floor7/TerminalWaypoints.kt
Labels: Soon

#2731 Fix: Farming Weight Overlay
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
Labels: Soon, Bug Fix

#2642 Backend: Command Register Event
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigGuiManager.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/CommandBuilder.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/CommandCategory.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/RegisterCommandsEvent.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/SimpleCommand.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/FarmingFortuneConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/ModifyWordsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/commands/HelpCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/CroesusChestTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFGuideGUI.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/UpdateManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/VisualWordGui.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/PunchcardHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
Labels: Soon, Backend

#2720 Improvement: More Inquis messages
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
Labels: Soon

#2717 Improvement: Line to goblin
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
  src/main/java/at/hannibal2/skyhanni/data/mob/LineToMobHandler.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/GoldenGoblinHighlight.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon

#2713 Feature: Chocolate Factory Booster Cookie Blocker
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBlockOpen.kt
Labels: Soon

#2639 Feature: Stash Warning Compact
  src/main/java/at/hannibal2/skyhanni/config/features/chat/FilterTypesConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/chat/StashConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/StashCompact.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
Labels: Soon

#2732 Fix: Enchant Parsing not displaying locked enchants
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
Labels: Soon, Bug Fix

#2561 Feature: Flowstate helper
  src/main/java/at/hannibal2/skyhanni/config/features/mining/FlowstateHelperConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
  src/main/java/at/hannibal2/skyhanni/features/mining/FlowstateHelper.kt
Labels: Soon

#2727 Fix: Lava replacement not working with optifine installed
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinBlockLiquid.java
Labels: Soon, Bug Fix

#2722 Fix: Griffin Pet warning Autopet
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinPetWarning.kt
Labels: Soon, Bug Fix

#2743 Fix: Hypixel Carpentry Chests with Weird names
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
Labels: Bug Fix

#2664 Feature: Hoppity Purse Blocker
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityCallWarningConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCallWarning.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
Labels: Soon

#2740 Fix: Crash with FlowstateHelperConfig
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/config/features/mining/FlowstateHelperConfig.java
Labels: Soon, Bug Fix

#2742 Fix: El Dorado HoppityAPI
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
Labels: Soon, Bug Fix

#2707 Fix: Millennia-Aged Blaze not getting highlighted by the Area Boss Highlight feature
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/AreaMiniBossFeatures.kt
Labels: Soon, Bug Fix

#2735 Improvement: Added option to show the barn fishing timer anywhere.
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/BarnTimerConfig.java
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingTimer.kt
Labels: Soon

#2736 Fix: Stop SkyHanni messages from being sent twice by accident
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
Labels: Soon, Bug Fix

#2730 Improvement: Stop Time Tower Usage Warning spam
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTimeTowerManager.kt
Labels: Soon

#2725 Backend: No longer use neu gui elements in config
  src/main/java/at/hannibal2/skyhanni/config/core/elements/GuiElement.kt
  src/main/java/at/hannibal2/skyhanni/config/core/elements/GuiElementButton.kt
  src/main/java/at/hannibal2/skyhanni/config/core/elements/GuiElementText.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/GuiOptionEditorUpdateCheck.kt
Labels: Soon, Backend

#2630 Backend: Add skyhanni notifications
  src/main/java/at/hannibal2/skyhanni/data/NotificationManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Soon, Backend

#2741 Fix: Compact Item Stars
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemStars.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/kuudra/KuudraAPI.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Soon, Bug Fix

#2712 Feature: Rabbit the Fish GUI Close Blocker
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEggsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityWarpMenuConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityRabbitTheFishChecker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/WarpMenuUniques.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiContainer.java
Labels: Soon

#2673 Backend: Add backup repo
  build.gradle.kts
  buildSrc/src/main/kotlin/skyhannibuildsystem/DownloadBackupRepo.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
Labels: Soon, Backend

#2748 Fix: Typo
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
Labels: Bug Fix

#2747 Backend: More precise repo debug
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
Labels: Soon, Backend

#2754 Backend: GraphAreaChangeEvent
  src/main/java/at/hannibal2/skyhanni/events/skyblock/AreaChangeEvents.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghostcounter/GhostCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/NucleusBarriersBox.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
Labels: Soon, Backend

#2760 Fix: Draft PRs having PR checks run on them
  .github/workflows/pr-check.yml
Labels: Bug Fix

#2759 Backend: Carnival graph area
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalGoal.kt
Labels: Soon, Backend

#2746 Fix: Fel Highlight in Edge Case
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonMobManager.kt
  src/main/java/at/hannibal2/skyhanni/test/command/CopyNearbyEntitiesCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
Labels: Soon, Bug Fix

#2751 Fix: Time Tower usage warnings sending excessively
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryTimeTowerManager.kt
Labels: Soon, Bug Fix

#2762 Backend Fix: Detekt Annotations
  .github/scripts/process_detekt_sarif.sh
Labels: Bug Fix, Backend

#2767 Fix: New Visitor Ping sent too late while farming
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorTimer.kt
Labels: Soon, Bug Fix

#2726 Fix: Duration Format
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
Labels: Soon, Bug Fix

#2761 Fix: Brave Downloads Cutting `host`
  src/main/java/at/hannibal2/skyhanni/tweaker/DownloadSourceChecker.java
Labels: Soon, Bug Fix

#2766 Fix: Fear stat display
  src/main/java/at/hannibal2/skyhanni/config/features/event/GreatSpookConfig.java
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
  src/main/java/at/hannibal2/skyhanni/features/event/spook/TheGreatSpook.kt
Labels: Soon, Bug Fix

#2764 Backend: Update build gradle to allow launching 1.21
  .github/workflows/build.yml
  build.gradle.kts
  root.gradle.kts
Labels: Soon, Backend

#2772 Fix: Carnival in Garden
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
Labels: Soon, Bug Fix

#2775 Backend: Add custom import ordering detekt rule
  detekt/baseline.xml
  detekt/detekt.yml
  detekt/src/main/kotlin/PreprocessingPatterns.kt
  detekt/src/main/kotlin/formatting/CustomCommentSpacing.kt
  detekt/src/main/kotlin/imports/CustomImportOrdering.kt
  detekt/src/main/kotlin/imports/ImportRuleSetProvider.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonLividFinder.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#2705 Improvement: Added Flare Expire Sound and Flash Warning
  src/main/java/at/hannibal2/skyhanni/config/features/combat/FlareConfig.java
  src/main/java/at/hannibal2/skyhanni/features/combat/FlareDisplay.kt
Labels: Soon

#2773 Fix: MIrrorverse Detection
  src/main/java/at/hannibal2/skyhanni/features/rift/RiftAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/RiftLavaMazeParkour.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/RiftUpsideDownParkour.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/TubulatorParkour.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/RiftTimer.kt
Labels: Soon, Bug Fix

#2777 Backend: Mixin Plugin Packages
  src/main/java/at/hannibal2/skyhanni/mixins/init/SkyhanniMixinPlugin.java
Labels: Backend

#2077 Feature: Draconic Sacrifice Tracker
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/combat/CombatConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/combat/end/EndIslandConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/DraconicSacrificeTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/features/misc/DraconicSacrificeTracker.kt
Labels: Soon

#1968 Feature: Snake Game Keybinds
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/SnakeGame.kt
Labels: Soon

#2758 Fix: item stars + Estimated Item Value issues
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemStars.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Bug Fix

#2769 Fix: tab completions for /p [ign] shorthand
  src/main/java/at/hannibal2/skyhanni/features/commands/tabcomplete/PlayerTabComplete.kt
Labels: Bug Fix

#2780 Fix: Custom Scoreboard Party Leader
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementParty.kt
Labels: Bug Fix

#2779 Fix: Scoreboard Patterns
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix

#2781 Fix: Compact Stash - Item Stash & Empty Line
  src/main/java/at/hannibal2/skyhanni/config/features/chat/StashConfig.java
  src/main/java/at/hannibal2/skyhanni/features/chat/StashCompact.kt
Labels: Bug Fix

#2783 Fix: Custom Scoreboard Printing Class Name
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementParty.kt
Labels: Bug Fix

#2787 Fix: Estimated Item Value OpenGL Error & Data Dump NBT
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/test/command/CopyItemCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Bug Fix

#2784 Backend: Add MultiMC to known launchers
  src/main/java/at/hannibal2/skyhanni/utils/ComputerEnvDebug.kt
Labels: Soon, Backend

#2786 Fix: El Dorado Dupe (Again)
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
Labels: Soon, Bug Fix

#2788 Fix: Slayer Mini Boss Walls
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerMiniBossFeatures.kt
Labels: Bug Fix

#2785 Fix: Rabbit the Fish Indexing Error
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityRabbitTheFishChecker.kt
Labels: Soon, Bug Fix

#2789 Fix: Detekt Tag Compound FB
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Bug Fix

#2782 Fix: Stop CF Screen Flash on Stray Found
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryScreenFlash.kt
Labels: Soon, Bug Fix

#2790 Backend: Detekt Comments
  .github/scripts/process_detekt_sarif.sh
  .github/workflows/build.yml
  .github/workflows/detekt.yml
  .github/workflows/detekt_beta.yml
Labels: Backend

#2776 Backend: Start preprocessing mappings
  .idea/dictionaries/default_user.xml
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProcessor.kt
  build.gradle.kts
  shots.txt
  src/main/java/at/hannibal2/skyhanni/data/ActionBarData.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/FriendAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonLividFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
  src/main/java/at/hannibal2/skyhanni/utils/DelayedRun.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/SkyhanniBaseScreen.kt
  versions/mapping-1.12.2-1.8.9.txt
  versions/mapping-1.16.5-1.16.5-forge.txt
  versions/mapping-1.16.5-forge-1.12.2.txt
Labels: Backend

#2793 Fix: Debug Messages not triggering
  src/main/java/at/hannibal2/skyhanni/api/HotmAPI.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon, Bug Fix

#2792 Backend Fix: Detekt Comment Processor Todos
  .github/scripts/process_detekt_output.js
  .github/workflows/detekt.yml
Labels: Bug Fix, Backend

#2771 Feature: Added Primal Fear solvers
  src/main/java/at/hannibal2/skyhanni/config/features/dev/RepositoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/GreatSpookConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/PrimalFearSolverConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/spook/TheGreatSpook.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Soon

#2001 Feature: Attribute Overlay
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/AttributeOverlayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/AttributeGoodRollsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/AttributeAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/AttributeOverlay.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
Labels: Soon

#2423 Feature: Essence Shop & Carnival Shop Helper
  src/main/java/at/hannibal2/skyhanni/config/features/event/carnival/CarnivalConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/NeuCarnivalShops.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/NeuEssenceShopJson.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/CarnivalShopHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/EssenceShopHelper.kt
Labels: Soon

#2791 Fix: Tps Display
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/TpsCounter.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon, Bug Fix

#2795 Fix: Inconsistency in items created by SkyHanni
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorSupercraft.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/auctionhouse/AuctionHouseOpenPriceWebsite.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarOpenPriceWebsite.kt
Labels: Bug Fix

#2796 Fix: Rev Viscera Multi-Drop Pattern
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Bug Fix

#2798 Fix: change spook solver color
  src/main/java/at/hannibal2/skyhanni/features/event/spook/TheGreatSpook.kt
Labels: Bug Fix

#2799 Fix: Unlock mouse on barn tp
  src/main/java/at/hannibal2/skyhanni/features/misc/LockMouseLook.kt
Labels: Bug Fix

#2803 Fix: Dyes being modified when "Re-Color Missing Rabbit Dyes" is off
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
Labels: Bug Fix

#2801 Backend Fix: Detekt on Build Failure
  .github/workflows/detekt.yml
  .github/workflows/detekt_beta.yml
  .github/workflows/pr-check.yml
Labels: Bug Fix, Backend

#2800 Backend: Add shot support for multi version builds
  build.gradle.kts
  shots.txt
  versions/1.8.9/shots.txt
Labels: Backend

#2812 Backend Fix: Detekt Runner
  .github/workflows/detekt.yml
Labels: Bug Fix, Backend
