Repository hannibal002/SkyHanni, pull requests merged in 2025-03, with the labels that each got.

#3517 Fix: Attribute combo being incorrectly greyed out
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Bug Fix

#3516 Fix: GuildAPI reading from /g online
  src/main/java/at/hannibal2/skyhanni/data/GuildApi.kt
Labels: Bug Fix

#3537 Backend: rename 1.16.5 -> 1.16.5-fabric
  CONTRIBUTING.md
  build.gradle.kts
  sharedVariables/src/ProjectTarget.kt
  versions/mapping-1.16.5-fabric-1.16.5-forge.txt
  versions/mapping-1.21.4-1.16.5-fabric.txt
Labels: Soon, Backend

#2830 Improvement: Color, Prefix, Number Customization in Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/DisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardConfigFix.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementBank.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementBits.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementCold.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementCopper.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementGems.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementHeat.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementMotes.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementNorthStars.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementPlayerAmount.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementPowder.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementPower.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementPurse.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementQuiver.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementSkyBlockXP.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementSoulflow.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementTuning.kt
Labels: Soon

#3532 Backend: Mutliversion action + mouse preprocessing
  .github/workflows/build.yml
  src/main/java/at/hannibal2/skyhanni/config/core/config/gui/GuiPositionEditor.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilterGui.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/PageScrolling.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigOptionGui.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/GuiOptionEditorUpdateCheck.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/VisualWordGui.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/GuiScreenUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/MouseCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/ScrollInput.kt
  versions/1.21.4/buildpaths.txt
  versions/mapping-1.16.5-fabric-1.16.5-forge.txt
Labels: Backend

#3543 Backend: Code for 1.21
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/ChumBucketHider.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/FixGhostEntities.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/RoundedShader.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangHider.kt
  src/main/java/at/hannibal2/skyhanni/utils/BlockUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/FakePlayer.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/EffectsCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/EnchantmentsCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/EntityCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/ItemCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/PacketCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/SkyhanniBaseScreen.kt
  versions/1.21.4/buildpaths.txt
  versions/mapping-1.16.5-fabric-1.16.5-forge.txt
  versions/mapping-1.16.5-forge-1.12.2.txt
  versions/mapping-1.21.4-1.16.5-fabric.txt
Labels: Soon, Backend

#3544 Fix: add missing rod part category
  src/main/java/at/hannibal2/skyhanni/utils/ItemCategory.kt
Labels: Bug Fix

#3546 Backend: Kotlin Patterns but scuffed
  CONTRIBUTING.md
  build.gradle.kts
  gradle.properties
  root.gradle.kts
  settings.gradle.kts
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  versions/mapping-1.16.5-forge-1.12.2.txt
  versions/mapping-1.21.4-1.16.5-fabric.txt
  versions/pattern-mappings-1.16.5-forge-1.12.2.txt
Labels: Soon, Backend

#3549 Backend: Make class names a bit more specific
  src/main/java/at/hannibal2/skyhanni/api/event/EventHandler.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerNameFormatter.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/HelpCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/MineshaftPityDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pathfind/NavigationHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pets/PetNametag.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/reminders/ReminderManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/chat/TextHelper.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#3553 Fix: Foraging Fortune
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
Labels: Bug Fix

#3540 Backend: Fix some 1.21 errors
  src/main/java/at/hannibal2/skyhanni/events/RenderEntityOutlineEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/cosmetics/CosmeticFollowingLine.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
  versions/mapping-1.12.2-1.8.9.txt
  versions/mapping-1.16.5-fabric-1.16.5-forge.txt
  versions/mapping-1.16.5-forge-1.12.2.txt
  versions/pattern-mappings-1.16.5-forge-1.12.2.txt
Labels: Soon, Backend

#3556 Backend: Launching 1.21
  CONTRIBUTING.md
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProcessor.kt
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProvider.kt
  build.gradle.kts
  gradle/libs.versions.toml
  root.gradle.kts
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/SkyHanniModLoader.kt
  versions/1.16.5-fabric/src/main/java/at/hannibal2/skyhanni/SkyHanniModLoader.kt
  versions/1.21.4/buildpaths.txt
  versions/1.21.4/src/main/resources/fabric.mod.json
Labels: Soon, Backend

#3558 Backend: more 1.21 errors
  src/main/java/at/hannibal2/skyhanni/api/ItemBuyApi.kt
  src/main/java/at/hannibal2/skyhanni/data/OwnInventoryData.kt
  src/main/java/at/hannibal2/skyhanni/data/SlayerApi.kt
  src/main/java/at/hannibal2/skyhanni/data/bazaar/HypixelBazaarFetcher.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/MinionCraftHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
  src/main/java/at/hannibal2/skyhanni/features/event/yearoftheseal/FishyTreatProfit.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/AnitaMedalProfit.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenCropTimeCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenCropsInCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FortuneUpgrades.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/UpgradePage.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/SkyMartCopperPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/UltimateEnchantStar.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarBestSellMethod.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarCancelledBuyOrderClipboard.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/CraftMaterialCollector.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateShopPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/craft/CraftableItemList.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/FlowstateHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalNucleusApi.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalNucleusProfitPer.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ProfitPerExcavation.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/ProfitPerMineshaftCorpse.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionUpgradeHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/Enchant.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerRngMeterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/PrimitiveItemStack.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniBucketedItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
  src/test/java/at/hannibal2/skyhanni/test/ItemModifierTest.kt
  versions/mapping-1.16.5-fabric-1.16.5-forge.txt
  versions/mapping-1.16.5-forge-1.12.2.txt
  versions/mapping-1.21.4-1.16.5-fabric.txt
Labels: Backend

#3559 Backend: Rename compat methods so they cause less issues
  root.gradle.kts
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/ItemCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  versions/1.21.4/src/test/kotlin/TestLegacyColorFormat.kt
  versions/mapping-1.21.4-1.16.5-fabric.txt
  versions/pattern-mappings-1.16.5-forge-1.12.2.txt
Labels: Soon

#3561 Backend: 2 Compat methods
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/NeuReforgeJson.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/ItemCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/MouseCompat.kt
  versions/mapping-1.16.5-forge-1.12.2.txt
Labels: Soon, Backend

#3368 Backend: Create SignUtils
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenOptimalSpeed.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/BetterSignEditing.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SignUtils.kt
Labels: Soon, Backend

#3563 Backend: Get some chat stuff working
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerNameFormatter.kt
  src/main/java/at/hannibal2/skyhanni/events/ActionBarUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/ChatHoverEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ColorFormattingHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/CompactBestiaryChatMessage.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ShortenCoins.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/StashCompact.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/WatchdogHider.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/translation/Translator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/MythologicalCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/SeaCreatureMessageShortener.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishManager.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishMessages.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ContributorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ReplaceRomanNumerals.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiChatHook.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TestChatCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ComponentMatcherUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SignUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
  src/main/java/at/hannibal2/skyhanni/utils/chat/TextHelper.kt
  versions/mapping-1.16.5-fabric-1.16.5-forge.txt
  versions/mapping-1.16.5-forge-1.12.2.txt
  versions/mapping-1.21.4-1.16.5-fabric.txt
Labels: Soon, Backend

#3564 Backend: Create Enum Utils and Modern Command Registration
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/api/ReforgeApi.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/CommandRegistrationEvent.kt
  src/main/java/at/hannibal2/skyhanni/data/GardenCropMilestonesCommunityFix.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFactories.kt
  src/main/java/at/hannibal2/skyhanni/events/WidgetUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/FarmingContestApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobFarmingContestsInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleLine.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/SuperpairDataDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/GlowingDroppedItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/EnumUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPattern.kt
  src/main/java/at/hannibal2/skyhanni/utils/system/PlatformUtils.kt
  versions/1.21.4/buildpaths.txt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/SkyHanniModLoader.kt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/config/commands/SimpleCommand.kt
  versions/mapping-1.16.5-fabric-1.16.5-forge.txt
  versions/mapping-1.16.5-forge-1.12.2.txt
Labels: Soon, Backend

#3566 Backend: Centralise receiving of forge events
  src/main/java/at/hannibal2/skyhanni/api/FmlEventApi.kt
  src/main/java/at/hannibal2/skyhanni/api/event/EventListeners.kt
  src/main/java/at/hannibal2/skyhanni/api/event/SkyHanniEvents.kt
  src/main/java/at/hannibal2/skyhanni/api/minecraftevents/ClientEvents.kt
  src/main/java/at/hannibal2/skyhanni/api/minecraftevents/EntityEvents.kt
  src/main/java/at/hannibal2/skyhanni/api/minecraftevents/RenderEvents.kt
  src/main/java/at/hannibal2/skyhanni/data/ActionBarData.kt
  src/main/java/at/hannibal2/skyhanni/data/BossbarData.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/GuiData.kt
  src/main/java/at/hannibal2/skyhanni/data/ItemClickData.kt
  src/main/java/at/hannibal2/skyhanni/data/MinecraftData.kt
  src/main/java/at/hannibal2/skyhanni/data/RenderData.kt
  src/main/java/at/hannibal2/skyhanni/events/entity/EndermanTeleportEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/entity/EntityDeathEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/player/PlayerInteractionEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/render/BlockOverlayRenderEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/render/gui/DrawBackgroundEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/render/gui/GameOverlayRenderPostEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/render/gui/GameOverlayRenderPreEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/render/gui/GuiActionPerformedEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/render/gui/GuiMouseInputEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/render/gui/GuiScreenOpenEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/render/gui/InitializeGuiEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/render/gui/RenderingTickEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/render/gui/ScreenDrawnEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chroma/ChromaShader.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenOptimalSpeed.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/MovableHotBar.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/MovableXPBar.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SkyBlockXPBar.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobeKeybinds.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ButtonOnPause.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MiscFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/QuickModMenuSwitch.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/TabListRenderer.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/colosseum/BlobbercystsHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableTooltips.kt
Labels: Soon, Backend

#3565 Backend: new compat method !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCallWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenLevelDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FarmingItems.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/GardenInventoryTooltipOverflow.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/MinisterInCalendar.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/NucleusBarriersBox.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionUpgradeHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillTooltip.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/ItemCompat.kt
Labels: Backend

#3568 Backend: More mappings for modern
  gradle/libs.versions.toml
  root.gradle.kts
  src/main/java/at/hannibal2/skyhanni/config/core/config/Position.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/EntityCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/api/minecraftevents/ClientEvents.kt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/api/minecraftevents/EntityEvents.kt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/api/minecraftevents/RenderEvents.kt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/test/hotswap/HotswapSupport.kt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/test/hotswap/HotswapSupportImpl.kt
  versions/mapping-1.16.5-forge-1.12.2.txt
  versions/pattern-mappings-1.16.5-forge-1.12.2.txt
  versions/pattern-mappings-1.21.4-1.16.5-fabric.txt
Labels: Soon, Backend

#3569 Backend: preprocessed ResourceLocations
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/RenderBackground.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/ColdOverlay.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableInventory.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/ShaderManager.kt
  versions/mapping-1.16.5-forge-1.12.2.txt
Labels: Backend

#3575 Backend + Fix: Inventories Compat + HighlightMissingRepoItems
  src/main/java/at/hannibal2/skyhanni/data/OwnInventoryData.kt
  src/main/java/at/hannibal2/skyhanni/events/GuiContainerEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardTips.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/WikiManager.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/GardenComposterInventoryFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobFarmingContestsInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorRewardWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ActiveBeaconEffect.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/AuctionsHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/FavoritePowerStone.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HighlightBonzoMasks.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/PageScrolling.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/PowerStoneGuideFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/QuickCraftFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SkyblockGuideHighlightFeature.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SnakeGame.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/auctionhouse/AuctionHouseCopyUnderbidPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarOrderHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryKeybinds.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/TabWidgetSettings.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/EnigmaSoulWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiContainerHook.kt
  src/main/java/at/hannibal2/skyhanni/test/HighlightMissingRepoItems.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemNameResolver.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NeuItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/InventoryCompat.kt
  versions/1.16.5-forge/src/main/java/at/hannibal2/skyhanni/utils/compat/ScreenAlias.kt
  versions/1.21.4/buildpaths.txt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/SkyHanniModLoader.kt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/TestingModFeatures.kt
  versions/mapping-1.16.5-forge-1.12.2.txt
Labels: Soon, Bug Fix, Backend

#3576 Fix: Wrong fallback texture + ban realms
  .github/workflows/illegal-imports.txt
  src/main/java/at/hannibal2/skyhanni/test/command/TrackSoundsCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkullTextureHolder.kt
Labels: Soon, Bug Fix

#3579 Backend: Particles for modern
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowParticleFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleLine.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/PrecisionMiningHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MiscFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/stillgorechateau/SplatterHearts.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/enderman/EndermanSlayerHideParticles.kt
  versions/mapping-1.16.5-forge-1.12.2.txt
Labels: Soon, Backend

#3577 Backend: some preprocessing to item utils
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Backend

#3581 Backend: Scoreboard compat
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/ScoreboardCompat.kt
  versions/1.21.4/buildpaths.txt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/api/minecraftevents/ClientEvents.kt
Labels: Backend

#3573 Fix: Hitman Calculation
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/hitman/HitmanApi.kt
Labels: Bug Fix

#3550 Backend: pr changelog guildelines
  CONTRIBUTING.md
Labels: Soon, Backend

#3534 Fix: CustomScoreboard ChunkedStats Motes wrong color
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ChunkedStatsLine.kt
Labels: Bug Fix

#3529 Fix: Garden Sethome Key Preventing Warp
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenWarpCommands.kt
Labels: Bug Fix

#3519 Fix: Skyblock level not displaying in show messages when custom chat formatting is enabled
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerNameFormatter.kt
Labels: Bug Fix

#3583 Backend: Remove Quad
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillLevel.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillUtil.kt
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/Quad.kt
Labels: Soon, Backend

#3551 Feature: Hotspot guessing logic
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/FishingConfig.java
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingHotspotRadar.kt
Labels: Soon

#3523 Fix: Show Sulphur Skitter Box without lava
  src/main/java/at/hannibal2/skyhanni/features/nether/SulphurSkitterBox.kt
Labels: Bug Fix

#3530 Improvement + Backend: Outline option for Highlight Nucleus Barriers
  src/main/java/at/hannibal2/skyhanni/config/features/mining/nucleus/CrystalHighlighterConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/nucleus/CrystalHighlighterConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/NucleusBarriersBox.kt
Labels: Soon, Backend

#3584 Backend: More modern mappings and fixes
  build.gradle.kts
  src/main/java/at/hannibal2/skyhanni/data/FriendApi.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/SackApi.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerNameFormatter.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ColorFormattingHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/HelpCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishMessages.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/MineshaftPityDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pathfind/NavigationHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/reminders/ReminderManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ComponentMatcherUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzColor.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/chat/TextHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  versions/mapping-1.16.5-fabric-1.16.5-forge.txt
  versions/mapping-1.16.5-forge-1.12.2.txt
Labels: Soon, Backend

#3545 Backend: StatsApi Treasure Chance
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
Labels: Soon, Backend

#3585 Fix: Renderable hoverable
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
Labels: Soon, Bug Fix

#3346 Backend: Auto Config Bump
  .github/workflows/bump_config.yml
  CONTRIBUTING.md
  Config_Version
  build.gradle.kts
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
Labels: Soon, Backend

#3594 config change v2
  src/main/java/at/hannibal2/skyhanni/config/features/combat/CombatConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ArmorStackDisplay.kt
Labels: Soon

#3591 Fix: Superpairs XP overlay
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationXPOverlay.kt
Labels: Soon, Bug Fix

#3588 Backend: Get item resolution query working 1.21
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/ItemResolutionQuery.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NeuItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/InventoryCompat.kt
  versions/mapping-1.16.5-forge-1.12.2.txt
  versions/mapping-1.21.4-1.16.5-fabric.txt
  versions/pattern-mappings-1.16.5-forge-1.12.2.txt
Labels: Soon, Backend

#844 Feature: Dragon Weight + Protector Weight + Superior Notifier
  src/main/java/at/hannibal2/skyhanni/config/features/combat/CombatConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/combat/DragonConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/DragonFeatures.kt
Labels: Soon

#3102 Feature: Add Timite tracker and helpers
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/mountaintop/MountaintopConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/mountaintop/TimiteConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/RiftApi.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mountaintop/TimiteHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mountaintop/TimiteTracker.kt
Labels: Soon

#3596 Backend: nearbyBlocks
  src/main/java/at/hannibal2/skyhanni/features/nether/SulphurSkitterBox.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mountaintop/TimiteHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/BlockUtils.kt
Labels: Soon, Backend

#3605 Backend: Add gradle wrapper verification
  .github/workflows/validate-gradle-wrapper.yml
Labels: Soon, Backend

#3604 Backend: Update Loom to 1.9 and Gradle to 8.13
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  root.gradle.kts
  settings.gradle.kts
Labels: Backend

#1928 Feature: Crimson Isle Rescue Mission Waypoints
  src/main/java/at/hannibal2/skyhanni/config/features/crimsonisle/ReputationHelperConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/crimsonisle/RescueMissionConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/RescueParkourJson.kt
  src/main/java/at/hannibal2/skyhanni/data/model/Graph.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/RescueMissionWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/test/ParkourWaypointSaver.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/GraphUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ParkourHelper.kt
Labels: Soon

#3541 Improvement: Temporal Pillar Dodge
  src/main/java/at/hannibal2/skyhanni/config/features/rift/RiftConfig.java
  src/main/java/at/hannibal2/skyhanni/features/rift/RiftApi.kt
Labels: Soon, Waiting on Dependency PR

#3599 Improvement: Fishing Hotspot pathfind
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/FishingConfig.java
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/ItemClickData.kt
  src/main/java/at/hannibal2/skyhanni/data/model/Graph.kt
  src/main/java/at/hannibal2/skyhanni/data/model/GraphNodeTag.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/halloween/BasketWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingHotspotRadar.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/WoodenButtonsHelper.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphNodeEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/RaycastUtils.kt
Labels: Soon

#3611 Maybe fix wrapper failing
  .github/workflows/validate-gradle-wrapper.yml
Labels: Soon, Bug Fix

#3610 fix stack overflow
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
Labels: Bug Fix

#3069 Backend: Migrate some methods from renderStringsAndItems
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Soon, Backend

#3527 Backend: BitsApi debug data
  src/main/java/at/hannibal2/skyhanni/data/BitsApi.kt
Labels: Soon, Backend

#3451 Fix + Backend: Fixes Corpse profit tracker not diplaying profit Titles
  src/main/java/at/hannibal2/skyhanni/data/TitleManager.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniBucketedItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Bug Fix, Backend

#3601 Fix: CustomScoreboard formatDisplay Tuning
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementTuning.kt
Labels: Bug Fix

#3615 Backend: Edit parkours via graph editor
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphParkour.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#3620 Fix: Trophy Fish Features
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishMessages.kt
Labels: Bug Fix

#3621 Fix: Gemstone Slot Error
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Bug Fix

#3625 Backend: Weird enum island thing
  src/main/java/at/hannibal2/skyhanni/utils/json/SimpleStringTypeAdapter.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkyHanniTypeAdapters.kt
Labels: Soon, Backend

#3623 Fix: Prevent the egglocator from wildly guessing when a fishing bobber is in a hotspot
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
Labels: Bug Fix

#3613 Fix: /shupdate not letting you update to beta from a full release
  src/main/java/at/hannibal2/skyhanni/features/misc/update/UpdateManager.kt
Labels: Soon, Bug Fix

#3612 Backend + Fix: More mappings and modern fixes
  src/main/java/at/hannibal2/skyhanni/api/minecraftevents/RenderEvents.kt
  src/main/java/at/hannibal2/skyhanni/events/render/gui/GameOverlayRenderPreEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishFillet.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenApi.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/MovableHotBar.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/MovableXPBar.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/AccessorGuiEditSign.java
  src/main/java/at/hannibal2/skyhanni/utils/ApiUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/MinecraftDispatcher.kt
  src/main/java/at/hannibal2/skyhanni/utils/MobUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NeuItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SignUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SoundUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/MinecraftCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/utils/NeuCalculator.kt
  versions/mapping-1.16.5-forge-1.12.2.txt
  versions/mapping-1.21.4-1.16.5-fabric.txt
Labels: Soon, Bug Fix, Backend

#3592 Backend: Keyboard helper mostly working 1.21
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/TestingModFeatures.kt
  versions/mapping-1.16.5-forge-1.12.2.txt
Labels: Soon, Backend

#3608 Backend: Block Utils, Lorenz Utils, Silly Number, Player Utils
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/cosmetics/CosmeticFollowingLine.kt
  src/main/java/at/hannibal2/skyhanni/utils/BlockUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityOutlineRenderer.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NeuItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/PlayerUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
  versions/mapping-1.16.5-fabric-1.16.5-forge.txt
  versions/mapping-1.16.5-forge-1.12.2.txt
Labels: Soon, Backend

#3628 Fix: bitsapi randomly increasing sometimes
  src/main/java/at/hannibal2/skyhanni/data/BitsApi.kt
Labels: Bug Fix

#3562 Fix: Visitor Shopping List disappearing while supercrafting
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/SignUtils.kt
Labels: Bug Fix

#3424 Backend: Add ping and tps to shdebug
  src/main/java/at/hannibal2/skyhanni/api/hypixelapi/HypixelEventApi.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CurrentPing.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/TpsCounter.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
Labels: Soon, Backend

#3640 Fix: Disocrd
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Bug Fix

#3567 Improvement: Improve full thunder in a bottle notification
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/ChargeBottleNotification.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ThunderBottleNotification.kt
Labels: Soon

#3632 Fix: cs double slash thing
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementPlayerAmount.kt
Labels: Soon, Bug Fix

#3426 Backend: `NonStorageDoesntNeedExpose`
  detekt/detekt.yml
  detekt/src/main/kotlin/potentialbugs/NonStorageDoesntNeedExpose.kt
  detekt/src/main/kotlin/potentialbugs/PotentialBugsProvider.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chroma/ChromaConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEventSummaryCFReminderConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEventSummaryLiveDisplayConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/CakeTrackerConfig.kt
Labels: Soon, Backend

#3617 Improvement: Added Ragnarok to Damage Indicator
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/BossType.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/MobFinder.kt
Labels: Soon

#3634 Fix: Sea Creature Features through walls
  src/main/java/at/hannibal2/skyhanni/features/fishing/SeaCreatureFeatures.kt
Labels: Bug Fix

#3642 Fix: Fix fishing coin catches not counting in the profit tracker
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingProfitTracker.kt
Labels: Bug Fix

#3347 Improvement: Alternative Boosted Crop Highlight
  src/main/java/at/hannibal2/skyhanni/config/features/garden/NextJacobContestConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Soon

#3638 Fix + Feature: Add a line to the detected fishing hotspot
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/FishingConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingHotspotRadar.kt
Labels: Bug Fix

#3307 Backend: Translate lot of displays to Renderable
  src/main/java/at/hannibal2/skyhanni/config/features/rift/motes/RiftInventoryValueConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobContestFFNeededDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobContestTimeNeeded.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CollectionTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/QuickModMenuSwitch.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingMetalSuitProgress.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/CruxTalismanDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/motes/ShowMotesNpcSellPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#3643 Improvement: Auto disable fishing pathfind
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingHotspotRadar.kt
Labels: Soon

#3645 Improvement: Update faq to address "new" plans for multiversion support
  docs/DISCORD_FAQ.md
Labels: Soon

#3650 Fix: Crop Icon Lag
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenApi.kt
Labels: Bug Fix

#3652 Fix: Allow hoppity guesses to guess when close to the egg
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
Labels: Bug Fix

#3644 Fix: Stored Compost Not Displaying
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterDisplay.kt
Labels: Soon, Bug Fix

#3648 Fix: XP display missing in renew experiments menu
  src/main/java/at/hannibal2/skyhanni/features/misc/XPInInventories.kt
Labels: Bug Fix

#3649 Improvement + Fix: Update Repo and report locations
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingHotspotRadar.kt
Labels: Soon, Bug Fix, Detekt

#3653 Fix: Sea Creature Warning
  src/main/java/at/hannibal2/skyhanni/features/fishing/SeaCreatureFeatures.kt
Labels: Bug Fix

#3654 Backend: Make mixins work on modern versions
  build.gradle.kts
  src/main/java/at/hannibal2/skyhanni/mixins/init/SkyhanniMixinPlugin.java
  versions/1.21.4/buildpaths.txt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/mixins/init/BeforeForLoopInjectionPoint.java
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinClientConnection.java
  versions/1.21.4/src/main/resources/fabric.mod.json
  versions/1.21.4/src/main/resources/mixins.skyhanni.json
Labels: Soon, Backend

#3655 fix detekt
  versions/1.8.9/detekt/baseline.xml
Labels: Bug Fix

#3627 Backend: More preprocessing for modern
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/HolographicEntities.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
  src/main/java/at/hannibal2/skyhanni/utils/NeuItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SoundUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/system/PlatformUtils.kt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/utils/FakePlayer.kt
Labels: Soon, Backend

#3641 Backend: Remove infix functions in RenderUtils
  src/main/java/at/hannibal2/skyhanni/data/HighlightOnHoverSlot.kt
  src/main/java/at/hannibal2/skyhanni/features/anvil/AnvilCombineHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardTips.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/CroesusChestTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityNpc.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/GardenComposterInventoryFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobFarmingContestsInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenPlotMenuHighlighting.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorRewardWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ActiveBeaconEffect.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/AuctionsHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/FavoritePowerStone.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/PowerStoneGuideFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/QuickCraftFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ReforgeHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/RngMeterInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SkyblockGuideHighlightFeature.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/StatsTuning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarOrderHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbilityCooldown.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilSolverDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/AuctionHousePriceComparison.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/kloon/KloonHacking.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/EnigmaSoulWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/HighlightRiftGuide.kt
  src/main/java/at/hannibal2/skyhanni/features/stranded/HighlightPlaceableNpcs.kt
  src/main/java/at/hannibal2/skyhanni/test/HighlightMissingRepoItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon, Backend

#3635 Backend: Fixed Event Listener Commands
  src/main/java/at/hannibal2/skyhanni/api/event/EventListeners.kt
  src/main/java/at/hannibal2/skyhanni/api/event/SkyHanniEvents.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
Labels: Backend, Wrong Title/Changelog

#3666 Backend + Fix: Create KeyDownEvent
  src/main/java/at/hannibal2/skyhanni/events/minecraft/KeyDownEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/minecraft/KeyPressEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenWarpCommands.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/FocusMode.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
Labels: Bug Fix, Backend

#3631 Feature: Add Estimated Item Value in Tooltip
  src/main/java/at/hannibal2/skyhanni/config/features/misc/EstimatedItemValueConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/AuctionsHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/WardrobeApi.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/AuctionHousePriceComparison.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueTooltip.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon

#3668 Backend: keyboard manager again
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
Labels: Backend

#3661 Fix: Cs redstone error when visiting
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventRedstone.kt
Labels: Bug Fix

#3660 Fix: Chat Spam in Fairy Souls Guide
  src/main/java/at/hannibal2/skyhanni/features/misc/FastFairySoulsPathfinder.kt
Labels: Bug Fix

#3662 Fix: Unclickable Shortened Coin Amounts
  src/main/java/at/hannibal2/skyhanni/features/chat/ShortenCoins.kt
Labels: Bug Fix

#3633 Fix: visitor shopping list in sign
  src/main/java/at/hannibal2/skyhanni/events/GuiRenderEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
Labels: Bug Fix

#3671 Backend: Disable Ping packet
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CurrentPing.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
Labels: Soon, Backend

#3542 Improvement: Estimated Item Value Prestige Cost
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/ItemsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/kuudra/KuudraApi.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CollectionUtils.kt
Labels: Soon

#3651 Backend: Cleanup RenderUtils
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDebug.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonLividFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GeyserFishing.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleLine.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/PrecisionMiningHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/NucleusBarriersBox.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/MatriarchHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/SulphurSkitterBox.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/RiftWiltedBerberisHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/VoltHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/stillgorechateau/SplatterHearts.kt
  src/main/java/at/hannibal2/skyhanni/test/ParkourWaypointSaver.kt
  src/main/java/at/hannibal2/skyhanni/test/WorldEdit.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/ParkourHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon, Backend

#3526 Feature + Fix + Backend: Total Trophy Fish Caught
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/trophyfishing/TrophyFishingConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GoldenFishTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/OdgerTotalCaught.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishApi.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishManager.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishMessages.kt
Labels: Soon, Bug Fix, Backend

#3507 Feature: Add Dragon Profit Tracker
  src/main/java/at/hannibal2/skyhanni/config/features/combat/CombatConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/combat/end/DragonConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/combat/end/DragonProfitTrackerConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/combat/end/EndIslandConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/DragonProfitTrackerItemsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/DragonFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/DragonFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/DragonFightAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/DragonProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/DragonType.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/ProfitPerDragon.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/endernodetracker/EnderNode.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/endernodetracker/EnderNodeTracker.kt
Labels: Soon

#3682 Backend: Config Fix for DragonFeatures
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/DragonFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/DragonProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/ProfitPerDragon.kt
Labels: Soon, Backend

#3676 Fix: `KeyDownEvent` Breaking Garden Warp Keys
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
Labels: Bug Fix

#3686 Fix: TitleManagerV2
  src/main/java/at/hannibal2/skyhanni/data/TitleManager.kt
Labels: Bug Fix

#3672 Improvement: Rare Sea Creature Party Announcer
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/RareCatchesConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/PartyApi.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/SeaCreatureFeatures.kt
Labels: Soon

#3674 Backend: DVD Logo Renderable
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.kt
  src/main/java/at/hannibal2/skyhanni/test/DVDTest.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/DVDLogoRenderable.kt
Labels: Soon, Backend

#3688 Fix: Cs Lines with NONE Island
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
Labels: Bug Fix

#3371 Improvement: better Totem of Corruption expiry sound
  src/main/java/at/hannibal2/skyhanni/features/fishing/TotemOfCorruption.kt
  src/main/java/at/hannibal2/skyhanni/utils/SoundUtils.kt
Labels: Soon

#2426 Improvement: Show Stacking Enchant Progress
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/EnchantParsingConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/Enchant.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Soon

#2914 Improvement: Attribute Overlay Options
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/AttributeOverlayConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/AttributeApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/AttributeOverlay.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CollectionUtils.kt
Labels: Soon

#3673 Fix: Shorten coin working on gold full stops
  src/main/java/at/hannibal2/skyhanni/features/chat/ShortenCoins.kt
Labels: Soon, Bug Fix

#3695 Fix: jyrre timer pattern
  src/main/java/at/hannibal2/skyhanni/features/event/winter/JyrreTimer.kt
Labels: Bug Fix
