Repository hannibal002/SkyHanni, pull requests merged in 2025-02, with the labels that each got.

#3352 Fix: Custom Scoreboard Century Raffle
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix

#3349 Feature + Fix: GUI Button Scroll + Null Fix
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/ScrollInput.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Bug Fix

#2654 Improvement: Added Coins Per Hour and Time until Max to Avarice Counter
  src/main/java/at/hannibal2/skyhanni/config/features/itemability/CrownOfAvariceConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/CrownOfAvariceCounter.kt
  src/main/java/at/hannibal2/skyhanni/utils/NumberUtil.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
Labels: Soon

#3351 Fix: Experimentation Tracker Issues
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationTableApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsDryStreakDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/SuperpairDataDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/UltraRareBookAlert.kt
Labels: Bug Fix

#3355 Feature: Highlight Century Daily Tasks
  src/main/java/at/hannibal2/skyhanni/config/features/event/AnniversaryCelebration400Config.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/EventConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/SkyblockGuideHighlightFeature.kt
Labels: Soon

#3345 Improvement: Gui Button hover
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/SackDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/SeaCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/DragNDrop.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/ScrollInput.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/BucketedItemTrackerData.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniBucketedItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon

#3354 Feature: Slice of Cake team finder.
  src/main/java/at/hannibal2/skyhanni/config/features/event/AnniversaryCelebration400Config.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/AnniversaryTeamFinderColorConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/event/SystemMessageEvent.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/features/event/anniversary/Year400Features.kt
Labels: Soon

#2005 Feature: Bingo Boop Party Invite
  src/main/java/at/hannibal2/skyhanni/config/features/event/bingo/BingoConfig.java
  src/main/java/at/hannibal2/skyhanni/features/bingo/BingoBoopParty.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
Labels: Soon

#3098 Backend: TickEvent repeatSeconds Deprecation
  src/main/java/at/hannibal2/skyhanni/events/minecraft/SkyHanniTickEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/nextstephelper/BingoNextStepHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/SulphurSkitterBox.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/RiftLarva.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/RiftOdonata.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
Labels: Soon, Backend

#3279 Feature: Pesthunter Shop Profit Display
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PesthunterShopConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PesthunterProfit.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
Labels: Soon

#3357 Fix: we do not want to talk about it
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/CrownOfAvariceCounter.kt
Labels: Bug Fix

#3365 Backend: Disable Detekt Comments on Draft PRs
  .github/workflows/detekt.yml
Labels: Backend

#3321 Backend: Addition to snake highlighter
  src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
Labels: Soon, Backend, Detekt

#3364 Fix: Crouching or sleeping sometimes made lines render strangely.
  src/main/java/at/hannibal2/skyhanni/data/mob/LineToMobHandler.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Bug Fix

#3372 Fix: typos in InventoryFullyOpenedEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/InventoryFullyOpenedEvent.kt
Labels: Bug Fix

#3367 Fix: slice finder baker
  src/main/java/at/hannibal2/skyhanni/features/event/anniversary/Year400Features.kt
Labels: Bug Fix

#3361 Fix: Neu PV not loading
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/NeuEventWrappers.kt
Labels: Bug Fix

#2839 Backend: Hotm Powder
  src/main/java/at/hannibal2/skyhanni/api/HotmApi.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.java
  src/main/java/at/hannibal2/skyhanni/data/HotmData.kt
  src/main/java/at/hannibal2/skyhanni/events/mining/PowderEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/mining/PowderGainEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementPowder.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
Labels: Soon, Backend

#3035 Backend: Use Repo for IslandType Data
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandType.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/IslandTypeJson.kt
Labels: Soon, Backend

#3206 Fix: faulty page scrolling invert logic
  src/main/java/at/hannibal2/skyhanni/features/inventory/PageScrolling.kt
Labels: Bug Fix

#3381 Fix: Gemstones in ModifierUtils
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
Labels: Bug Fix

#3374 Fix: Motes per Session when leaving Hypixel
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/events/hypixel/HypixelLeaveEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/skyblock/SkyBlockLeaveEvent.kt
  src/main/java/at/hannibal2/skyhanni/utils/DelayedRun.kt
Labels: Bug Fix

#3385 Fix: BZ Instant Buy item trackers
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Bug Fix

#3386 Improvement: craft materials from ah
  src/main/java/at/hannibal2/skyhanni/api/ItemBuyApi.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/BazaarConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/CraftMaterialCollector.kt
Labels: Soon

#3388 Fix + Feature: Modernized Jerry Feature
  src/main/java/at/hannibal2/skyhanni/config/features/event/MayorJerryConfig.java
  src/main/java/at/hannibal2/skyhanni/data/mob/LineToMobHandler.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/features/event/jerry/HighlightJerries.kt
  src/main/java/at/hannibal2/skyhanni/features/summonings/SummoningMobManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ConditionalUtils.kt
Labels: Bug Fix

#3097 Feature: Add Sun Gecko Helper
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/RiftAreasConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/mountaintop/MountaintopConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/mountaintop/SunGeckoConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/BossType.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/MobFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/RiftApi.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mountaintop/SunGeckoHelper.kt
Labels: Soon

#3390 Fix: Experementation table fixes
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationTableApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/SuperpairsClicksAlert.kt
Labels: Bug Fix

#3376 Fix: Damage Indicator Ender Dragon
  src/main/java/at/hannibal2/skyhanni/features/combat/DragonFightAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/BossType.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
Labels: Bug Fix

#3382 Fix: chest value display buttons scroll infinite
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
Labels: Bug Fix

#3378 Fix: TPS calculation error
  src/main/java/at/hannibal2/skyhanni/features/misc/TpsCounter.kt
Labels: Bug Fix

#3383 Fix: Harp GUI Scale Limbo
  src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
Labels: Bug Fix

#3384 Fix: minion upgrade helper workaround
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionUpgradeHelper.kt
Labels: Bug Fix

#3356 Fix: Damage Indicator times in F6/M6
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/MobFinder.kt
Labels: Bug Fix

#3391 Improvement: Disabled "Block Refusing New Visitors" on Bingo
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/RewardWarningConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorApi.kt
Labels: Soon

#3389 Backend: Improved /shtestitem
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/HelpCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pathfind/NavigationHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/reminders/ReminderManager.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemNameResolver.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NeuItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/chat/Text.kt
Labels: Soon, Backend

#3392 Fix: Bingo Minion Craft Helper not working
  src/main/java/at/hannibal2/skyhanni/features/bingo/MinionCraftHelper.kt
Labels: Bug Fix

#3393 Fix: golden jerry detection
  src/main/java/at/hannibal2/skyhanni/features/event/jerry/HighlightJerries.kt
Labels: Bug Fix

#3396 Fix: MobDetection Runic Jerry
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
Labels: Bug Fix

#3395 Backend: Remove wrong spelling of "caducous" from dictionairy
  .idea/dictionaries/default_user.xml
Labels: Backend

#3399 Fix: Jerry statspocalypse not correctly effecting the Skyhanni User Luck stat
  src/main/java/at/hannibal2/skyhanni/features/misc/UserLuckBreakdown.kt
Labels: Soon, Bug Fix

#3397 Fix: LineToMob ignoring condition
  src/main/java/at/hannibal2/skyhanni/data/mob/LineToMobHandler.kt
Labels: Bug Fix

#3401 Fix: TPS rounding
  src/main/java/at/hannibal2/skyhanni/features/misc/TpsCounter.kt
Labels: Bug Fix

#3406 Improvement: re-add coins to cancelled buy order text
  src/main/java/at/hannibal2/skyhanni/features/chat/ShortenCoins.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarCancelledBuyOrderClipboard.kt
Labels: Soon

#3375 Fix: Scrolling List
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Bug Fix

#3404 Improvement: Readded Hide outside Inventory tracker
  src/main/java/at/hannibal2/skyhanni/config/features/misc/TrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon

#3408 Fix: Waypoints behind blocks
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Bug Fix

#3416 Backend: reorder storage
  src/main/java/at/hannibal2/skyhanni/config/storage/PlayerSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
Labels: Backend

#3420 Backend: cleanup in InventoryUtils
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
Labels: Soon, Backend

#3413 Fix: Hide Other Players in Dance Room Helper not updating if disabled
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/DanceRoomHelper.kt
Labels: Bug Fix

#3421 Fix: Opening Hotm Updating Powder Tracker
  src/main/java/at/hannibal2/skyhanni/api/HotmApi.kt
  src/main/java/at/hannibal2/skyhanni/data/HotmData.kt
Labels: Bug Fix

#3410 Fix: Copy Rng Meter Debug Feature
  src/main/java/at/hannibal2/skyhanni/test/TestCopyRngMeterValues.kt
Labels: Soon

#3402 Backend: revert gson bump
  build.gradle.kts
  gradle/libs.versions.toml
  sharedVariables/build.gradle.kts
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/NeuEventWrappers.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkippingTypeAdapterFactory.kt
Labels: Soon, Backend

#3379 Backend: Fix IDE error in newer IntelliJ versions
  build.gradle.kts
Labels: Backend

#3414 Backend: Cache CheckRenderEntityEvent
  src/main/java/at/hannibal2/skyhanni/data/EntityData.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinRenderManager.java
Labels: Soon, Backend

#3407 Backend: add button with boolean
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/CakeTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
Labels: Soon, Backend

#3350 Feature: NEU Soul Path Find
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/FairySoulPathFind.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/neu/MixinFairySouls.java
Labels: Soon

#3387 throw error if someone does something silly to an internal name
  src/main/java/at/hannibal2/skyhanni/utils/NeuInternalName.kt
Labels: Soon

#3417 Backend: Event Predicates
  src/main/java/at/hannibal2/skyhanni/api/event/EventHandler.kt
  src/main/java/at/hannibal2/skyhanni/api/event/EventListeners.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ConfigUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
Labels: Soon, Backend

#3436 Fix: Visitor Supercraft incorrectly showing/not showing
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorSupercraft.kt
Labels: Bug Fix

#3438 Improvement: Item Tracker Text Order
  src/main/java/at/hannibal2/skyhanni/config/features/misc/TrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/data/TrackerManager.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NeuItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/ScrollInput.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Searchable.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/ItemTrackerData.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon

#3443 Backend: Amount of detekt failures
  .github/scripts/process_detekt_output.js
Labels: Backend

#3400 Fix: config load/save with StringFileHandler
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringFileHandler.kt
Labels: Bug Fix

#3435 Fix: Neu Souls Dwarven Mines/Glacite Tunnels
  src/main/java/at/hannibal2/skyhanni/features/misc/FairySoulPathFind.kt
Labels: Bug Fix

#3444 Fix: Stash empty lines
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/StashCompact.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
Labels: Bug Fix

#3072 Feature: Gift Profit Tracker
  src/main/java/at/hannibal2/skyhanni/config/features/event/EventConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/gifting/GiftTrackerConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/gifting/GiftingConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/winter/WinterConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/gifting/GiftApi.kt
  src/main/java/at/hannibal2/skyhanni/features/gifting/GiftProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/gifting/IsGiftingDetection.kt
  src/main/java/at/hannibal2/skyhanni/features/gifting/UniqueGiftCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/gifting/UniqueGiftingOpportunitiesFeatures.kt
Labels: Soon

#3429 Backend: cachedExtraData
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
Labels: Soon, Backend

#3440 Fix: Wrong skill level being displayed in some places and some instances of it freezing
  src/main/java/at/hannibal2/skyhanni/api/SkillApi.kt
Labels: Bug Fix, Detekt

#3442 Fix: Douce Pluie de Stinky Cheese in Non God Pot display
  src/main/java/at/hannibal2/skyhanni/features/misc/NonGodPotEffectDisplay.kt
Labels: Bug Fix

#3430 Backend: Added the ability to disable api requests via repo
  src/main/java/at/hannibal2/skyhanni/data/bazaar/HypixelBazaarFetcher.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/DisabledApiJson.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/utils/ApiUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
Labels: Soon, Backend

#3342 Feature: Superpair Exp Overlay
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/experimentationtable/ExperimentationTableConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationXPOverlay.kt
Labels: Soon

#3445 Backend: Added update java tutorial
  docs/update_java.md
  src/main/java/at/hannibal2/skyhanni/utils/ComputerEnvDebug.kt
Labels: Soon, Backend

#3448 Fix: Reset sprays used when resetting Pest Profit Tracker
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
Labels: Bug Fix

#3453 Backend: Detekt Output -1
  .github/scripts/process_detekt_output.js
Labels: Soon, Backend

#3455 Fix: ElectionAPI not checking every minute if no mayor is known
  src/main/java/at/hannibal2/skyhanni/data/ElectionApi.kt
Labels: Bug Fix

#3452 Fix: Bucket Trackers and Scroll Tables
  src/main/java/at/hannibal2/skyhanni/utils/tracker/BucketedItemTrackerData.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniBucketedItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
Labels: Bug Fix

#3450 Fix: Shit Code in Hoppity
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggDisplayManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
Labels: Bug Fix

#3458 Fix: Precise griffin burrow detection with pet out
  src/main/java/at/hannibal2/skyhanni/features/event/diana/PreciseGuessBurrow.kt
Labels: Bug Fix

#3459 Fix: Remove bugs in burrow guessing logic
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/PreciseGuessBurrow.kt
Labels: Bug Fix

#3457 Fix: Enchanted Book Name
  src/main/java/at/hannibal2/skyhanni/data/OwnInventoryData.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
Labels: Bug Fix

#3463 Fix: Decouple Pest Tracker and Message Fixing
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
Labels: Bug Fix

#3447 Backend: API and Errors
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/BitsApi.kt
  src/main/java/at/hannibal2/skyhanni/data/ElectionApi.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/MaxwellApi.kt
  src/main/java/at/hannibal2/skyhanni/data/QuiverApi.kt
  src/main/java/at/hannibal2/skyhanni/data/bazaar/HypixelBazaarFetcher.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/HypixelItemApi.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ApiUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ClipboardUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/OSUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderDisplayHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/SoundUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/guide/GuideGUI.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#3464 Backend: `NEW TEXT` in `/shchathistory`
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilterGui.kt
Labels: Backend

#3465 Fix: HypixelData Comparison
  src/main/java/at/hannibal2/skyhanni/api/hypixelapi/HypixelLocationApi.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
Labels: Bug Fix

#3469 Fix: Burrow location wildly inaccurate under specific circumstances
  src/main/java/at/hannibal2/skyhanni/features/event/diana/PreciseGuessBurrow.kt
Labels: Bug Fix

#3476 Fix: `inChocolateFactory` Check for Hoppity Collection
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
Labels: Bug Fix

#3471 Fix: Pet tooltip out of bounds
  src/main/java/at/hannibal2/skyhanni/features/misc/pets/PetExpTooltip.kt
Labels: Bug Fix

#3472 Fix: Dungeon block texture reading
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Bug Fix

#3481 Fix: tab list widget event
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
Labels: Bug Fix

#3479 Improvement: Change hoppity guess logic to be the same as the Diana burrow guess
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/PreciseGuessBurrow.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/PolynomialFitter.kt
Labels: Soon

#3480 Fix: Prevent burrows from existing after they have been dug
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowParticleFinder.kt
Labels: Bug Fix

#3487 Fix: User Luck in rare drop messages when disabled
  src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
Labels: Bug Fix

#3490 Improvement: Enchanted Book Message
  src/main/java/at/hannibal2/skyhanni/config/features/chat/RareDropMessagesConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
Labels: Soon

#3489 Improvement: /shnavigate coordinates
  src/main/java/at/hannibal2/skyhanni/features/misc/pathfind/NavigationHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
Labels: Soon

#3488 Improvement: /shedittracker ghost tracker
  src/main/java/at/hannibal2/skyhanni/features/combat/ghosttracker/GhostTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniBucketedItemTracker.kt
Labels: Soon

#3484 Improvement: Reduce warp keybind reaction time
  src/main/java/at/hannibal2/skyhanni/features/event/diana/BurrowWarpHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
Labels: Soon

#3486 Improvement: Better guess name for hoppity
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
Labels: Soon

#3485 Backend: Config backend format change
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
Labels: Soon, Backend

#3483 Backend: Post messages
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/ApiUtils.kt
Labels: Soon, Backend

#3482 Remove: duplicate superpair xp feature
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
Labels: Soon

#3466 Backend: `HoppityDataSet` + `ResettableStorageSet`
  src/main/java/at/hannibal2/skyhanni/config/storage/ResettableStorageSet.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityApi.kt
Labels: Soon, Backend

#3423 Improvement + Backend: Cake Tracker Renderable Buttons
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/CakeTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/CakeTrackerConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggDisplayManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenOptimalSpeed.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FarmingItems.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ReforgeHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/CraftMaterialCollector.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryCustomReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/craft/CraftableItemList.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CarryTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/QuickModMenuSwitch.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerRngMeterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphNodeEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/guide/GuideTab.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/DragNDrop.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/ScrollInput.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon, Backend

#3493 Fix: No active patterns when no island known
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
Labels: Bug Fix

#3496 Fix: Attribute Shard Check in ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Bug Fix

#3492 Fix: NPE in chat line
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
Labels: Bug Fix

#3494 Fix: Experiment Dry-Streak not Incrementing
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsDryStreakDisplay.kt
Labels: Bug Fix

#3370 Backend: `StorageNeedsExpose` Improvements
  detekt/src/main/kotlin/potentialbugs/ImmutableTypesWithExpectedInteriorMutabilityInConfig.kt
  detekt/src/main/kotlin/potentialbugs/StorageNeedsExpose.kt
Labels: Backend

#3497 Fix: Bazaar cancel detection
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarCancelledBuyOrderClipboard.kt
Labels: Bug Fix

#3514 Fix: Ghost Tracker Kill Combo not saving for combos over 1,000 kills
  src/main/java/at/hannibal2/skyhanni/features/combat/ghosttracker/GhostTracker.kt
Labels: Bug Fix

#3508 Fix: (CustomScoreboard) unknown lines warning on laggy server
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Bug Fix

#3506 Fix: Experiment Tracker Incrementing
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
Labels: Bug Fix

#3501 Fix: Scroll Table Rendering Last Element outside
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Bug Fix

#3505 Fix: Wardrobe Keys Empty Slots option
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobeKeybinds.kt
Labels: Bug Fix

#3500 Improvement: Added Jungle Key to list of tracked garden visitor rewards
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorReward.kt
Labels: Soon

#3513 Improvement + Fix: City Project feature
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon, Bug Fix

#3515 Fix: Skill ETA resest
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
Labels: Soon, Bug Fix, Wrong Title/Changelog
