Repository hannibal002/SkyHanni, pull requests merged in 2025-07, with the labels that each got.

#4236 Fix: Tree progress display showing on other islands
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/foraging/TreeProgressDisplay.kt
Labels: Bug Fix

#4210 Improvement: Rewrite the visual words system to use component replacing rather than string replacing
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/local/VisualWordsJson.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/local/VisualWordsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/CopyChat.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/ModifyVisualWords.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/VisualWordGui.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/chroma/ChromaFontManager.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/ModifyVisualWords.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinChatHud.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinTextColor.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinTextHandler.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinTextRenderer.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/compat/OrderedTextUtils.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/compat/OrdereredTextUtils.kt
  versions/1.21.5/src/main/resources/skyhanni.accesswidener
Labels: Soon

#4255 Fix: Custom Scoreboard Error on 1.8 Garden
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix

#4235 Fix: Movable xp bar not moving the experience number
  src/main/java/at/hannibal2/skyhanni/api/minecraftevents/RenderEvents.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/MovableXPBar.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SkyBlockXPBar.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/api/minecraftevents/RenderEvents.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiIngame.java
Labels: Soon, Bug Fix

#4256 Fix: Chat message hiders
  src/main/java/at/hannibal2/skyhanni/api/pet/PetStorageApi.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Bug Fix

#4260 fix: crash
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/compat/ReiCompat.kt
Labels: Bug Fix

#4245 Fix: Hotx
  src/main/java/at/hannibal2/skyhanni/api/HotfApi.kt
  src/main/java/at/hannibal2/skyhanni/api/HotmApi.kt
  src/main/java/at/hannibal2/skyhanni/data/hotx/HotfData.kt
  src/main/java/at/hannibal2/skyhanni/data/hotx/HotmData.kt
  src/main/java/at/hannibal2/skyhanni/data/hotx/HotxHandler.kt
  src/main/java/at/hannibal2/skyhanni/data/hotx/RepoPatternEnum.kt
Labels: Bug Fix

#4240 Fix: Text input still being active after inventory closed
  src/main/java/at/hannibal2/skyhanni/data/model/TextInput.kt
Labels: Soon, Bug Fix

#4269 Fix: Hide "Config Button" option on 1.21
  src/main/java/at/hannibal2/skyhanni/config/features/gui/GuiConfig.kt
Labels: Bug Fix

#4268 fix: foraging pattern
  src/main/java/at/hannibal2/skyhanni/api/HotfApi.kt
Labels: Bug Fix

#4077 Backend + Improvement: Experimentation Table Api Rework
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/experimentationtable/ExperimentsProfitTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ResettableStorageSet.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/ExperimentsJson.kt
  src/main/java/at/hannibal2/skyhanni/events/experiments/TableRareUncoverEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/experiments/TableTaskCompletedEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/experiments/TableTaskStartedEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/experiments/TableXPBottleUsedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationTableApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationTableEnums.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationXPOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsDryStreakDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/SuperpairDataDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/UltraRareBookAlert.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon, Backend

#4267 Fix: Wrongly named option in AttributeShardOverlay
  src/main/java/at/hannibal2/skyhanni/data/bazaar/HypixelBazaarFetcher.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/AttributeShardOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarBestSellMethod.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarData.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarOrderHelper.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
Labels: Soon, Bug Fix

#4238 Fix: Offset invisibug highlighter
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/foraging/InvisibugHighlighter.kt
Labels: Soon, Bug Fix

#4276 Fix: Color Preview in the config editor
  gradle/libs.versions.toml
  src/main/java/at/hannibal2/skyhanni/config/GuiOptionEditorBlocked.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/GuiOptionEditorUpdateCheck.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/DrawContext.kt
Labels: Soon, Bug Fix

#4279 Fix: Some stuff in custom wardrobe
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinHandledScreen.java
Labels: Soon, Bug Fix

#4229 Backend: Buildscript changes to more easily support additional modern versions
  build.gradle.kts
  gradle/libs.versions.toml
  sharedVariables/src/MultiVersionStage.kt
  sharedVariables/src/ProjectTarget.kt
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatHistoryGui.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiContainerHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinGuiIngame.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiIngame.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiNewChat.java
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/system/PlatformUtils.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/api/minecraftevents/RenderEvents.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinTextRenderLayerSet.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiIngame.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiNewChat.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/SkyHanniRenderLayers.kt
  versions/1.21.5/src/main/resources/skyhanni.accesswidener
Labels: Backend

#4286 Fix: Unneeded memory use when a OrderedText object was kept in use
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/ModifyVisualWords.kt
Labels: Bug Fix

#4278 Fix: Blaze Daggers display on 1.21
  src/main/java/at/hannibal2/skyhanni/data/TitleData.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/BlazeSlayerDaggerHelper.kt
Labels: Soon, Bug Fix

#4280 Fix: Sounds Loud on 1.21
  src/main/java/at/hannibal2/skyhanni/utils/SoundUtils.kt
Labels: Soon, Bug Fix

#4221 Backend: Pretty + Non-Duped Detekt Comments
  .github/scripts/processDetektOutput.kts
  .github/scripts/process_detekt_output.js
  .github/workflows/detekt.yml
Labels: Soon, Backend

#4294 Fix: BZ best sell method
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/BazaarConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarBestSellMethod.kt
Labels: Bug Fix

#4300 Backend: Detekt File Hash
  .github/scripts/process-detekt-output.kts
Labels: Backend

#4266 Backend: Automatically publish releases to Modrinth
  .github/workflows/post-release.yml
  CONTRIBUTING.md
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/skyhannibuildsystem/DownloadBackupRepo.kt
  buildSrc/src/main/kotlin/skyhannibuildsystem/PublishToModrinth.kt
  buildSrc/src/main/kotlin/skyhannibuildsystem/utils/ModVersion.kt
  docs/default-project-structure.png
  docs/gradle-reload-button.png
  docs/target-project-structure.png
  sharedVariables/src/ModrinthInfo.kt
  sharedVariables/src/ProjectTarget.kt
Labels: Soon, Backend

#4292 Backend: Retry Gradle Resolution Failure
  .github/actions/gradle-retry/action.yml
  .github/scripts/gradlew-retry.kts
  .github/workflows/build.yml
  .github/workflows/detekt.yml
  .github/workflows/detekt_beta.yml
  .github/workflows/generate-constants.yaml
  .github/workflows/pr-check.yml
Labels: Soon, Backend

#4293 Backend: Check Dependencies Improvement(s)
  .github/scripts/check-dependencies.js
  .github/scripts/checkDependencies.mjs
  .github/workflows/check_dependencies.yml
Labels: Soon, Backend

#4305 Fix: Script Dir
  .github/actions/gradle-retry/action.yml
Labels: Bug Fix

#4243 Feature: Coral Fish Helper
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/utils/ModernPatterns.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/misc/CoralFIshHelper.kt
Labels: Soon

#4237 Backend: No longer use z translations in ChatHistoryGui
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatHistoryGui.kt
Labels: Soon, Backend

#4295 Fix: Jacob farming contest inventory
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/FarmingContestApi.kt
Labels: Soon, Bug Fix

#4301 Fix: Most tooltip features on 1.21
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/OdgerTotalCaught.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenLevelDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/ToolTooltipTweaks.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/AnitaExtraFarmingFortune.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/GardenCropMilestoneInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/BitsPerCookieVisual.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/StockOfStonkFeature.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Bug Fix

#4244 Backend: Better ResettableStorageSet
  src/main/java/at/hannibal2/skyhanni/config/storage/ResettableStorageSet.kt
  src/test/java/at/hannibal2/skyhanni/test/ResettableStorageSetTest.kt
  versions/1.21.5/buildpaths-excluded.txt
Labels: Soon, Backend

#4302 Backend: Fix intellij warnings
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProcessor.kt
  src/main/java/at/hannibal2/skyhanni/utils/system/PlatformUtils.kt
Labels: Backend

#4310 Fix: Modrinth action breaking intellij
  .github/workflows/post-release.yml
  build.gradle.kts
  buildSrc/src/main/kotlin/skyhannibuildsystem/PublishToModrinth.kt
Labels: Soon, Bug Fix

#4081 Feature: Experiment Addons + Superpairs Helpers
  src/main/java/at/hannibal2/skyhanni/api/ExperimentationTableApi.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/experimentationtable/ExperimentationTableConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/experimentationtable/ExperimentationTableConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/experimentationtable/ExperimentsAddonsConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/experimentationtable/ExperimentsProfitTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/experimentationtable/ExperimentsSuperpairsConfig.kt
  src/main/java/at/hannibal2/skyhanni/events/experiments/TableTaskCompletedEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/experiments/TableTaskStartedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationXPOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsAddonsHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsDryStreakDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/GuardianReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/superpairs/SuperPairsItemVisibility.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/superpairs/SuperpairDataDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/superpairs/SuperpairsClicksAlert.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/superpairs/UltraRareBookAlert.kt
Labels: Soon

#4311 Improvement + Fix: Add config option for self-trigger party commands and fix self-trigger interaction with trust level
  src/main/java/at/hannibal2/skyhanni/config/features/misc/PartyCommandsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyChatCommands.kt
Labels: Bug Fix

#4312 Fix: Changelog Viewer wrong format for last entry
  src/main/java/at/hannibal2/skyhanni/features/misc/update/ChangelogViewer.kt
Labels: Bug Fix

#4315 Fix: Fix Ghost Entities behaving incorrectly
  src/main/java/at/hannibal2/skyhanni/features/misc/FixGhostEntities.kt
Labels: Soon, Bug Fix

#4319 Backend: Detekt WF Fix
  .github/workflows/detekt.yml
Labels: Backend

#3525 Feature + Backend: Sirih Helper
  src/main/java/at/hannibal2/skyhanni/config/features/crimsonisle/CrimsonIsleConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/PabloHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/SirihHelper.kt
Labels: Soon, Backend

#4257 Feature: SkyBlock Profile Viewer and NeuProfileDataLoadedEvent
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityWaypointsConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/trophyfishing/TrophyFishingConfig.kt
  src/main/java/at/hannibal2/skyhanni/events/NeuProfileDataLoadedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocations.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishManager.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/api/SkyBlockAPIEventWrappers.kt
  versions/1.21.5/src/main/resources/fabric.mod.json
Labels: Soon

#4262 Backend: Remove `Renderable.itemStack`
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonSpiritLeapOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/event/anniversary/Year300RaffleEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalGoal.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GoldenFishTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenOptimalSpeed.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/DicerRngDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/stereo/StereoHarmonyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/quiver/QuiverDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/BlockStrengthGuide.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/MineshaftPityDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventType.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/FrogMaskFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/PunchcardHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/RenderableCollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/guide/GuideTab.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/DragNDrop.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableInventory.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
Labels: Soon, Backend

#2999 Feature: Optimal Angles Overlay for Squeaky Mousemat
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/optimalAngles/CustomAnglesConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/optimalAngles/OptimalAnglesConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenOptimalAngles.kt
Labels: Soon

#3377 Feature + Backend: Prevent command early execution
  src/main/java/at/hannibal2/skyhanni/config/features/commands/CommandsConfig.kt
  src/main/java/at/hannibal2/skyhanni/events/MessageSendToServerEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/PreventEarlyCommands.kt
Labels: Soon, Backend

#3467 Feature + Backend: Runic mob highlight
  src/main/java/at/hannibal2/skyhanni/config/features/combat/MobsConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/MobHighlight.kt
Labels: Backend

#3875 Feature: Superprotectron Highlight
  src/main/java/at/hannibal2/skyhanni/config/features/mining/GoblinRaidConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningEventConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/GoblinRaidFeatures.kt
Labels: Soon

#3899 Improvement: Added Coin Support to Trade Value
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/TradeValue.kt
Labels: Soon

#4306 Backend: NoConfigLink Annotation
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/NoConfigLink.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/GuiConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
Labels: Soon, Backend

#4063 Feature: Trinity Helper
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/DungeonConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/TrinityConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonTrinityHelper.kt
Labels: Soon

#4233 Backend: `onAnyToggled`
  src/main/java/at/hannibal2/skyhanni/utils/ConditionalUtils.kt
Labels: Soon, Backend

#4074 Backend: Component Replace Reason
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/event/SystemMessageEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/chat/SkyHanniChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatHistoryGui.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/playerchat/PlayerChatModifier.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Soon, Backend

#4323 Backend: Fixes
  .github/scripts/check-dependencies.js
  .github/scripts/gradlew-retry.kts
Labels: Backend

#4259 Feature: Compact Sweep Details
  src/main/java/at/hannibal2/skyhanni/config/features/foraging/TreesConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandTypeTag.kt
  src/main/java/at/hannibal2/skyhanni/features/foraging/CompactSweepDetails.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
Labels: Soon

#2653 Feature: Notify when a player join/leave your lobby
  src/main/java/at/hannibal2/skyhanni/config/features/markedplayer/JoinLeaveMessageConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/markedplayer/MarkedPlayerConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MarkedPlayerManager.kt
Labels: Soon

#4318 Improvement: Made stack under cursor also pull items from rei
  src/main/java/at/hannibal2/skyhanni/features/commands/WikiManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/auctionhouse/AuctionHouseCopyUnderbidPrice.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/TestExportTools.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/InventoryCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/system/PlatformUtils.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/compat/ReiCompat.kt
Labels: Soon

#4331 Backend: Fix Comment WF
  .github/workflows/detekt.yml
Labels: Soon, Backend

#4333 only legacy, remove useless description
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/compacttablist/CompactTabListConfig.kt
Labels: Soon

#4281 Feature: Mute Hoppity Egg "Rolling" Sounds
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEggsConfig.kt
  src/main/java/at/hannibal2/skyhanni/events/PlaySoundEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityMuteEggSounds.kt
Labels: Soon

#4335 Backend: Remove old weird config migrations
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/Storage.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/limbo/LimboTimeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/ModifyVisualWords.kt
Labels: Soon, Backend

#4328 Backend: KuudraTier Enum Class
  src/main/java/at/hannibal2/skyhanni/features/nether/kuudra/KuudraTier.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/quest/KuudraQuest.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/kuudra/DailyKuudraBossHelper.kt
Labels: Soon, Backend

#3504 Fix + Backend: Renderable Test Suite
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/Storage.kt
  src/main/java/at/hannibal2/skyhanni/data/RenderData.kt
  src/main/java/at/hannibal2/skyhanni/events/GuiRenderEvent.kt
  src/main/java/at/hannibal2/skyhanni/test/DVDTest.kt
  src/main/java/at/hannibal2/skyhanni/test/ItemRenderableTest.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphNodeEditor.kt
  src/main/java/at/hannibal2/skyhanni/test/renderable/RenderableTestSuite.kt
  src/main/java/at/hannibal2/skyhanni/test/renderable/TestDVD.kt
  src/main/java/at/hannibal2/skyhanni/test/renderable/TestDragNDrop.kt
  src/main/java/at/hannibal2/skyhanni/test/renderable/TestOrbital.kt
  src/main/java/at/hannibal2/skyhanni/test/renderable/TestRenderItems.kt
  src/main/java/at/hannibal2/skyhanni/test/renderable/TestScrollable.kt
  src/main/java/at/hannibal2/skyhanni/test/renderable/TestWrappedString.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/BlockCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/DragNDrop.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/StringRenderable.kt
Labels: Soon, Backend

#4271 Feature: Old SB Menu
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/OldSkyblockMenu.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Soon

#4336 Fix: Make metal detector credits visible to the user
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/nucleus/MetalDetectorConfig.kt
Labels: Soon, Bug Fix

#4067 Feature: Prevent Closing CF While [...]
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEggsConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityStrayTimerConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/CFStrayRabbitWarningConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/HoppityEggLocationsJson.kt
  src/main/java/at/hannibal2/skyhanni/events/inventory/AttemptedInventoryCloseEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityRabbitTheFishChecker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/data/CFDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/stray/CFStrayTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/stray/CFStrayTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/stray/CFStrayWarning.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiContainer.java
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinHandledScreen.java
Labels: Soon

#3586 Feature: Gemstone money per hour display
  src/main/java/at/hannibal2/skyhanni/config/features/mining/GemstoneMoneyPerHourConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/GemstoneMoneyPerHour.kt
Labels: Soon

#3363 Improvement: Better onomatopoeia recognition and new sounds for Sound Responses
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatSoundResponse.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/SoundCompat.kt
Labels: Soon

#4265 Backend + Fix: Make ApiUtils use IO Couroutine
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/ElectionApi.kt
  src/main/java/at/hannibal2/skyhanni/data/bazaar/HypixelBazaarFetcher.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/translation/Translator.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/EliteDevApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/HypixelItemApi.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/ChangelogViewer.kt
  src/main/java/at/hannibal2/skyhanni/utils/ApiUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ComputerTimeOffset.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
Labels: Soon, Backend

#4340 Improvement: Add command to reset skyhanni keybinds
  src/main/java/at/hannibal2/skyhanni/config/UpdateKeybinds.kt
Labels: Soon

#4342 version 4.2.0
  docs/CHANGELOG.md
  docs/FEATURES.md
  root.gradle.kts
Labels: Soon

#4346 Fix + Improvement: Old SB Menu
  src/main/java/at/hannibal2/skyhanni/features/inventory/OldSkyblockMenu.kt
Labels: Soon, Bug Fix

#4350 Backend: Add `synchronize` to Dep Workflow
  .github/workflows/check_dependencies.yml
Labels: Backend

#4352 Fix: Profile component being invalid
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/NeuNbtInfoJson.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Soon, Bug Fix

#4351 Backend: Added TextRenderable
  src/main/java/at/hannibal2/skyhanni/features/mining/FlowstateHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ColorHexInLore.kt
  src/main/java/at/hannibal2/skyhanni/test/renderable/TestText.kt
  src/main/java/at/hannibal2/skyhanni/utils/ExtendedChatColor.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/chat/TextHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/Text.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/TextRenderable.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/compat/Text.kt
  versions/mapping-1.16.5-fabric-1.16.5-forge.txt
Labels: Soon, Backend

#4349 Feature + Backend: 1.21.7 shaders
  sharedVariables/src/ModrinthInfo.kt
  sharedVariables/src/ProjectTarget.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/DrawContextUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/render/ShaderRenderUtils.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiIngame.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/RenderPipelineDrawer.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/RoundedShapeDrawer.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/SkyHanniRenderLayers.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/SkyHanniRenderPipeline.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/layers/ChromaRenderLayer.kt
  versions/1.21.7/src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiRendererHook.kt
  versions/1.21.7/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinGuiRenderer.java
  versions/1.21.7/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinRenderSystem.java
  versions/1.21.7/src/main/java/at/hannibal2/skyhanni/utils/render/uniforms/SkyHanniChromaUniform.kt
  versions/1.21.7/src/main/java/at/hannibal2/skyhanni/utils/render/uniforms/SkyHanniCircleUniform.kt
  versions/1.21.7/src/main/java/at/hannibal2/skyhanni/utils/render/uniforms/SkyHanniRoundedOutlineUniform.kt
  versions/1.21.7/src/main/java/at/hannibal2/skyhanni/utils/render/uniforms/SkyHanniRoundedUniform.kt
  versions/1.21.7/src/main/resources/assets/skyhanni/shaders/circle.fsh
  versions/1.21.7/src/main/resources/assets/skyhanni/shaders/circle.vsh
  versions/1.21.7/src/main/resources/assets/skyhanni/shaders/rounded_rect.fsh
  versions/1.21.7/src/main/resources/assets/skyhanni/shaders/rounded_rect.vsh
  versions/1.21.7/src/main/resources/assets/skyhanni/shaders/rounded_rect_outline.fsh
  versions/1.21.7/src/main/resources/assets/skyhanni/shaders/rounded_rect_outline.vsh
  versions/1.21.7/src/main/resources/assets/skyhanni/shaders/rounded_texture.fsh
  versions/1.21.7/src/main/resources/assets/skyhanni/shaders/rounded_texture.vsh
  versions/1.21.7/src/main/resources/assets/skyhanni/shaders/standard_chroma.fsh
  versions/1.21.7/src/main/resources/assets/skyhanni/shaders/standard_chroma.vsh
  versions/1.21.7/src/main/resources/assets/skyhanni/shaders/textured_chroma.fsh
  versions/1.21.7/src/main/resources/assets/skyhanni/shaders/textured_chroma.vsh
  versions/1.21.7/src/main/resources/fabric.mod.json
  versions/1.21.7/src/main/resources/skyhanni.accesswidener
Labels: Soon, Backend

#4071 Backend: Remove HasLegacyId
  src/main/java/at/hannibal2/skyhanni/config/HasLegacyId.java
  src/main/java/at/hannibal2/skyhanni/config/features/chroma/ChromaConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/combat/BestiaryConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/combat/damageindicator/DamageIndicatorConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/combat/end/EnderNodeConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/crimsonisle/ReputationHelperConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/winter/FrozenTreasureConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/trophyfishing/ChatMessagesConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/MoneyPerHourConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/NextJacobContestConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/PlotMenuHighlightingConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/TooltipTweaksConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/composter/ComposterConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/cropmilestones/CropMilestonesConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/cropmilestones/MushroomPetPerkConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/cropmilestones/NextConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestSpawnConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/DropsStatisticsConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/VisitorConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/ChestValueConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/SackDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/itemability/FireVeilWandConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/nucleus/PowderTrackerConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/DiscordRPCConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/HideArmorConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/TrevorTheTrapperConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/compacttablist/AdvancedPlayerListConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/rift/motes/RiftInventoryValueConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/slayer/blaze/BlazeHellionConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/chroma/ChromaManager.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/endernodetracker/EnderNodeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/jerry/frozentreasure/FrozenTreasureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishMessages.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/ToolTooltipTweaks.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenBestCropTime.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestSpawn.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorReward.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/FireVeilWandParticles.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/HideArmor.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/AdvancedPlayerList.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordRPCManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/CrimsonIsleReputationHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/motes/ShowMotesNpcSellPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/BlazeSlayerDaggerHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/ConfigUtils.kt
Labels: Soon, Backend

#4076 Improvement + Backend: Hide 0-Crop Contest Stats
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/contest/ContestSummaryConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/contest/ContestTimesConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/contest/JacobContestConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/FarmingPersonalBestGain.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobContestFFNeededDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobContestStatsSummary.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobContestTimeNeeded.kt
Labels: Soon, Backend

#4358 Backend: checkPrDescription null check
  build.gradle.kts
Labels: Backend

#4357 Fix: ConcurrentModificationException
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/RenderLivingEntityHelper.kt
Labels: Soon, Bug Fix

#4356 Fix: Minion features and maybe some other stuff as well
  src/main/java/at/hannibal2/skyhanni/data/ItemClickData.kt
Labels: Soon, Bug Fix

#4355 Feature: Shiny Orb Tracker
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/EventConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/yearofthepig/ShinyOrbTrackerConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/yearofthepig/YearOfThePigConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
  src/main/java/at/hannibal2/skyhanni/events/yearofthepig/ShinyOrbChargedEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/yearofthepig/ShinyOrbLootedEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/yearofthepig/ShinyOrbUsedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/yearofthepig/PigFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/event/yearofthepig/PigFeaturesApi.kt
  src/main/java/at/hannibal2/skyhanni/features/event/yearofthepig/ShinyOrbTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/gifting/GiftProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/TrackerUtils.kt
Labels: Soon

#4360 Fix: Keybinds getting converted twice
  src/main/java/at/hannibal2/skyhanni/config/UpdateKeybinds.kt
Labels: Soon, Bug Fix

#4361 Fix: Pet experience tooltip on Jade Dragons
  src/main/java/at/hannibal2/skyhanni/config/features/pets/PetExperienceToolTipConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/pets/PetExpTooltip.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Soon, Bug Fix

#4314 Fix + Backend: Abstract Repo Handler(s)
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/api/ReforgeApi.kt
  src/main/java/at/hannibal2/skyhanni/api/SkillApi.kt
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesRepo.kt
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesRepoManager.kt
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/ItemResolutionQuery.kt
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/NeuEventWrappers.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/NeuRepositoryConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/RepositoryConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/NotificationManager.kt
  src/main/java/at/hannibal2/skyhanni/data/SackApi.kt
  src/main/java/at/hannibal2/skyhanni/data/bazaar/HypixelBazaarFetcher.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/AbstractRepoConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/AbstractRepoLocationConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/AbstractRepoManager.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/AbstractRepoReloadEvent.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoCommitStorage.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoComparison.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoFileSystem.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoLogger.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoUtils.kt
  src/main/java/at/hannibal2/skyhanni/events/NeuRepositoryReloadEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/RepositoryReloadEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/anniversary/Year300RaffleEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionData.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/EliteDevApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/quiver/QuiverDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/CarnivalShopHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/EssenceShopHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerRngMeterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/renderable/TestRenderItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/ApiUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/GitHubUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NeuItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/JsonUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/item/AnimatedItemStackRenderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/item/ItemStackRenderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/item/NeuItemStackProvider.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/system/LazyVar.kt
Labels: Soon, Bug Fix, Backend

#4363 version 4.3.0
  docs/CHANGELOG.md
  docs/FEATURES.md
  root.gradle.kts
Labels: Soon

#4365 Fix: comma
  src/main/java/at/hannibal2/skyhanni/features/misc/ColorfulItemStats.kt
Labels: Soon, Bug Fix

#4367 Fix: Gfs not working on some items
  src/main/java/at/hannibal2/skyhanni/data/SackApi.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemNameResolver.kt
  src/main/java/at/hannibal2/skyhanni/utils/NeuItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
Labels: Soon, Bug Fix

#4261 Backend: Load in Pet Skins
  src/main/java/at/hannibal2/skyhanni/api/pet/PetStorageApi.kt
  src/main/java/at/hannibal2/skyhanni/data/PetData.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/PetsJson.kt
  src/main/java/at/hannibal2/skyhanni/utils/NeuInternalName.kt
  src/main/java/at/hannibal2/skyhanni/utils/PetUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
Labels: Soon, Backend

#4369 Fix: TextCompat Hover NPE
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
Labels: Soon, Bug Fix

#4270 Feature: Neu Improved SB Menus
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/ImprovedSBMenusConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/LegacyBetterContainers.kt
  src/main/java/at/hannibal2/skyhanni/utils/CTMUtils.kt
  src/main/resources/assets/skyhanni/dynamic_54/style1/dynamic_54.png
  src/main/resources/assets/skyhanni/dynamic_54/style1/dynamic_54_button_ctm.png
  src/main/resources/assets/skyhanni/dynamic_54/style1/dynamic_54_slot_ctm.png
  src/main/resources/assets/skyhanni/dynamic_54/style1/dynamic_config.json
  src/main/resources/assets/skyhanni/dynamic_54/style2/dynamic_54.png
  src/main/resources/assets/skyhanni/dynamic_54/style2/dynamic_54_button_ctm.png
  src/main/resources/assets/skyhanni/dynamic_54/style2/dynamic_54_slot_ctm.png
  src/main/resources/assets/skyhanni/dynamic_54/style2/dynamic_config.json
  src/main/resources/assets/skyhanni/dynamic_54/style3/dynamic_54.png
  src/main/resources/assets/skyhanni/dynamic_54/style3/dynamic_54_button_ctm.png
  src/main/resources/assets/skyhanni/dynamic_54/style3/dynamic_54_slot_ctm.png
  src/main/resources/assets/skyhanni/dynamic_54/style3/dynamic_config.json
  src/main/resources/assets/skyhanni/dynamic_54/style4/dynamic_54.png
  src/main/resources/assets/skyhanni/dynamic_54/style4/dynamic_54_button_ctm.png
  src/main/resources/assets/skyhanni/dynamic_54/style4/dynamic_54_slot_ctm.png
  src/main/resources/assets/skyhanni/dynamic_54/style5/dynamic_54.png
  src/main/resources/assets/skyhanni/dynamic_54/style5/dynamic_54_button_ctm.png
  src/main/resources/assets/skyhanni/dynamic_54/style5/dynamic_54_slot_ctm.png
  src/main/resources/assets/skyhanni/dynamic_54/style6/dynamic_54.png
  src/main/resources/assets/skyhanni/dynamic_54/style6/dynamic_54_button_ctm.png
  src/main/resources/assets/skyhanni/dynamic_54/style6/dynamic_54_slot_ctm.png
  src/main/resources/assets/skyhanni/dynamic_54/style7/dynamic_54.png
  src/main/resources/assets/skyhanni/dynamic_54/style7/dynamic_54_button_ctm.png
  src/main/resources/assets/skyhanni/dynamic_54/style7/dynamic_54_slot_ctm.png
  src/main/resources/assets/skyhanni/dynamic_54/toggle_off.png
  src/main/resources/assets/skyhanni/dynamic_54/toggle_on.png
  src/test/java/at/hannibal2/skyhanni/test/CTMTest.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/inventory/BetterContainers.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/hooks/GenericContainerScreenHook.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinHandledScreen.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGenericContainerScreen.java
Labels: Soon

#4374 Fix: Add Unpack Check to Repos
  src/main/java/at/hannibal2/skyhanni/data/repo/AbstractRepoManager.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoFileSystem.kt
Labels: Bug Fix

#4373 Fix: Berberis Highlight on 1.21
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/RiftWiltedBerberisHelper.kt
Labels: Soon, Bug Fix

#4371 Fix: Vermin Tracker on 1.21
  .live-plugins/regexr/plugin.kts
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminTracker.kt
Labels: Bug Fix

#4307 Backend: Split Tracking Commands
  .live-plugins/event/plugin.kts
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/TrackCommandConfig.kt
  src/main/java/at/hannibal2/skyhanni/events/CancellableWorldEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/PlaySoundEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/ReceiveParticleEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowParticleFinder.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TrackParticlesCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TrackSoundsCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/command/track/TrackCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/command/track/TrackParticlesCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/command/track/TrackSoundsCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/ParticleUtils.kt
Labels: Soon, Backend

#3696 Improvement: Compact mode for golden fish timer
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/trophyfishing/GoldenFishTimerConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GoldenFishTimer.kt
Labels: Soon

#4379 Improvement: bait detection accuracy
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingBaitWarnings.kt
Labels: Soon

#4383 Fix: Jacob Contest saying it took 55 years
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobContestStatsSummary.kt
Labels: Soon, Bug Fix

#4386 Fix: Pet Tab Pattern
  src/main/java/at/hannibal2/skyhanni/api/pet/PetStorageApi.kt
Labels: Bug Fix

#4388 Improvement: Filter Swoop's Message
  src/main/java/at/hannibal2/skyhanni/config/features/chat/HuntingFilterConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Soon

#4384 Fix + Backend: Agaricus Timer on 1.21 etc.
  src/main/java/at/hannibal2/skyhanni/api/ExperimentationTableApi.kt
  src/main/java/at/hannibal2/skyhanni/data/MiningApi.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowParticleFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/PreciseGuessBurrow.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenStartLocation.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/PrecisionMiningHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/MetalDetectorSolver.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/MineshaftWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/RiftAgaricusCap.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/RiftWiltedBerberisHelper.kt
  src/main/java/at/hannibal2/skyhanni/test/ParkourWaypointSaver.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/BlockUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
Labels: Soon, Bug Fix, Backend

#4390 reword option
  src/main/java/at/hannibal2/skyhanni/config/features/mining/glacite/MineshaftDetectionConfig.kt
Labels: Soon

#4389 Improvement + Backend: Shards stuff
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/AttributeShardsConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/ItemPickupLogConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/data/ItemAddManager.kt
  src/main/java/at/hannibal2/skyhanni/events/item/ShardGainEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/DragonProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/AttributeShardOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/AttributeShardsData.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/HuntingBoxValue.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
Labels: Soon, Backend

#4392 Feature: Glowing Mushroom Highlighter
  src/main/java/at/hannibal2/skyhanni/config/features/misc/GlowingMushroomHighlighterConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/GlowingMushroomHighlighter.kt
Labels: Soon

#4395 version 4.5.0
  docs/CHANGELOG.md
  docs/FEATURES.md
  root.gradle.kts
Labels: Soon

#4401 Fix: Replacing Potions
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/inventory/BetterContainers.kt
Labels: Soon, Bug Fix

#4398 Backend + Fix: ApiUtils
  src/main/java/at/hannibal2/skyhanni/data/ElectionApi.kt
  src/main/java/at/hannibal2/skyhanni/data/bazaar/HypixelBazaarFetcher.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/translation/Translator.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/EliteDevApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/HypixelItemApi.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/ChangelogViewer.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/UpdateManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ApiUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/GitHubUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/api/ApiIntentionContext.kt
  src/main/java/at/hannibal2/skyhanni/utils/api/ApiInternalUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/api/ApiResponse.kt
  src/main/java/at/hannibal2/skyhanni/utils/api/ApiStaticPath.kt
  src/main/java/at/hannibal2/skyhanni/utils/api/ApiUtils.kt
Labels: Bug Fix, Backend

#4404 Fix: Errors in hunting box
  src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/AttributeShardOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/AttributeShardsData.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/HuntingBoxValue.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
Labels: Soon, Bug Fix

#4406 Fix: Skill Overflow For Hunting And Foraging
  src/main/java/at/hannibal2/skyhanni/api/SkillApi.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillUtil.kt
Labels: Soon, Bug Fix

#4407 Fix: Experience Artifact in Estimated Item Value
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Soon, Bug Fix

#4408 Improvement: Copy chat on 1.21
  src/main/java/at/hannibal2/skyhanni/features/chat/CopyChat.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinGuiChat.java
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  versions/1.21.5/buildpaths-excluded.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinGuiChat.java
  versions/1.21.5/src/main/resources/skyhanni.accesswidener
  versions/1.21.7/buildpaths-excluded.txt
  versions/1.21.7/src/main/resources/skyhanni.accesswidener
Labels: Soon

#4413 Fix: CustomWardrobe wrong vertical
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
Labels: Soon, Bug Fix

#4410 Backend: Fix NoSuchFieldException in PacketTest
  src/main/java/at/hannibal2/skyhanni/test/PacketTest.kt
Labels: Soon, Backend

#4416 Fix: typo
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
Labels: Soon, Bug Fix

#4417 Fix: Shorten Coin Amount on < 1 values
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ShortenCoins.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarCancelledBuyOrderClipboard.kt
  src/main/java/at/hannibal2/skyhanni/utils/NumberUtil.kt
Labels: Soon, Bug Fix

#4119 Backend: Radial Gradient Circular Renderable
  src/main/java/at/hannibal2/skyhanni/config/ConfigGuiManager.kt
  src/main/java/at/hannibal2/skyhanni/shader/RoundedShader.kt
  src/main/java/at/hannibal2/skyhanni/test/renderable/TestCircular.kt
  src/main/java/at/hannibal2/skyhanni/test/renderable/TestRadialGradient.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/DrawContextUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/render/ShaderRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/animated/RadialGradientCircularRenderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/ShaderHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/ShaderManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/Uniform.kt
  src/main/resources/assets/skyhanni/shaders/radial_gradient_circle.fsh
  src/main/resources/assets/skyhanni/shaders/radial_gradient_circle.vsh
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/RoundedShapeDrawer.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/SkyHanniRenderPipeline.kt
  versions/1.21.5/src/main/resources/assets/skyhanni/shaders/radial_gradient_circle.fsh
  versions/1.21.5/src/main/resources/assets/skyhanni/shaders/radial_gradient_circle.vsh
  versions/1.21.7/src/main/java/at/hannibal2/skyhanni/utils/render/uniforms/SkyHanniRadialGradientCircleUniform.kt
  versions/1.21.7/src/main/resources/assets/skyhanni/shaders/radial_gradient_circle.fsh
  versions/1.21.7/src/main/resources/assets/skyhanni/shaders/radial_gradient_circle.vsh
Labels: Soon, Backend

#4419 Fix: ColorfulItemStats
  src/main/java/at/hannibal2/skyhanni/config/features/misc/ColorfulItemTooltips.kt
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ColorfulItemStats.kt
Labels: Soon, Bug Fix

#4420 Fix: converting config from 1.21
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
Labels: Soon, Bug Fix

#4422 version 4.7.0
  docs/CHANGELOG.md
  docs/FEATURES.md
  root.gradle.kts
Labels: Soon

#4433 Backend: formatting
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/api/ExperimentationTableApi.kt
  src/main/java/at/hannibal2/skyhanni/api/HotfApi.kt
  src/main/java/at/hannibal2/skyhanni/api/HotmApi.kt
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/ItemResolutionQuery.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/FilterTypesConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chroma/ChromaConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/combat/InstanceChestProfitConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/combat/damageindicator/DamageIndicatorConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/crimsonisle/CrimsonIsleConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillUtil.kt
  versions/1.21.7/src/main/java/at/hannibal2/skyhanni/utils/render/uniforms/SkyHanniChromaUniform.kt
  versions/1.21.7/src/main/java/at/hannibal2/skyhanni/utils/render/uniforms/SkyHanniCircleUniform.kt
  versions/1.21.7/src/main/java/at/hannibal2/skyhanni/utils/render/uniforms/SkyHanniRadialGradientCircleUniform.kt
  versions/1.21.7/src/main/java/at/hannibal2/skyhanni/utils/render/uniforms/SkyHanniRoundedOutlineUniform.kt
  versions/1.21.7/src/main/java/at/hannibal2/skyhanni/utils/render/uniforms/SkyHanniRoundedUniform.kt
Labels: Soon, Backend

#4436 Improvement: Effigy Search Tags
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/stillgorechateau/EffigiesConfig.kt
Labels: Soon

#4435 Fix: Small chat formatting fixes
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ColorFormattingHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/WikiManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ComputerTimeOffset.kt
Labels: Soon, Bug Fix

#4308 Feature: Bazaar Daily Limit Tracker
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/BazaarConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/PlayerSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/BazaarJson.kt
  src/main/java/at/hannibal2/skyhanni/events/bazaar/BazaarTransactionEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarLimitTracker.kt
Labels: Soon

#4442 Backend: Click on `fun` Name to Jump
  .live-plugins/deffunjumpr/plugin.kts
Labels: Backend

#4428 Backend: Resettable
  src/main/java/at/hannibal2/skyhanni/api/ExperimentationTableApi.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/customwardrobe/ColorConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/customwardrobe/SpacingConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/NoReset.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/Resettable.kt
  src/main/java/at/hannibal2/skyhanni/events/garden/contests/rewards/ContestRewardsClaimedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityApi.kt
  src/main/java/at/hannibal2/skyhanni/features/foraging/CompactSweepDetails.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/FannCost.kt
  src/test/java/at/hannibal2/skyhanni/test/ResettableTest.kt
  versions/1.21.5/buildpaths-excluded.txt
  versions/1.21.7/buildpaths-excluded.txt
Labels: Soon, Backend

#4432 Improvement: Make Beacon Solver work with Signal Enhancer
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/foraging/MoongladeBeaconConfig.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/primitives/TextRenderable.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/foraging/MoongladeBeacon.kt
Labels: Soon

#4399 Improvement: Gui Navigation Feedback
  src/main/java/at/hannibal2/skyhanni/config/features/misc/PathfindConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/FastFairySoulsPathfinder.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pathfind/NavigationFeedback.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pathfind/NavigationHelper.kt
Labels: Soon

#4431 Fix: Incorrect Sun Gecko Highlight
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mountaintop/SunGeckoHelper.kt
Labels: Bug Fix

#4444 Backend: Improve some repo stuff
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/AbstractRepoManager.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/AbstractRepoReloadEvent.kt
Labels: Soon, Backend

#4445 very small performance improvement
  src/main/java/at/hannibal2/skyhanni/features/event/yearoftheseal/BeachBallCatchHelper.kt
Labels: Soon

#4446 version 4.8.0
  docs/CHANGELOG.md
  docs/FEATURES.md
  root.gradle.kts
Labels: Soon

#4425 Backend: Jump to Config (from ConfigFix)
  .live-plugins/jump-to-definition/plugin.kts
Labels: Soon, Backend

#4448 Backend: Convert ConfigOption to Property Plugin
  .live-plugins/convert-config-to-property/plugin.kts
Labels: Backend

#4449 Fix: Repo Early Exceptions
  src/main/java/at/hannibal2/skyhanni/data/repo/AbstractRepoManager.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoFileSystem.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoLogger.kt
Labels: Bug Fix

#4447 Fix: 1.21 NPE in entity utils
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
Labels: Bug Fix

#4382 Backend: Added support for spaces in enum argument type
  src/main/java/at/hannibal2/skyhanni/config/commands/brigadier/arguments/EnumArgumentType.kt
Labels: Soon, Backend

#4452 Fix: Some of Custom Wardrobe on 1.21.7
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGenericContainerScreen.java
Labels: Soon, Bug Fix

#3622 Feature: Add ordered waypoints
  build.gradle.kts
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/brigadier/BrigadierUtils.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/orderedwaypoints/OrderedWaypointsConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/OrderedWaypointsRoutes.kt
  src/main/java/at/hannibal2/skyhanni/data/ProfileStorageData.kt
  src/main/java/at/hannibal2/skyhanni/data/model/waypoints/ColeweightWaypointFormat.kt
  src/main/java/at/hannibal2/skyhanni/data/model/waypoints/SkyhanniWaypoint.kt
  src/main/java/at/hannibal2/skyhanni/data/model/waypoints/WaypointFormat.kt
  src/main/java/at/hannibal2/skyhanni/data/model/waypoints/Waypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/OrderedWaypoints.kt
Labels: Soon

#4453 Fix: Tab complete on some commands not working on 1.21
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingMilestoneCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigFeatures.kt
  src/main/java/at/hannibal2/skyhanni/test/WorldEdit.kt
Labels: Soon, Bug Fix

#4403 Improvement: Full Reset on Repo Manger Update Command
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesRepoManager.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/RepositoryConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/AbstractRepoManager.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/SkyHanniRepoManager.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/DeepCavernsGuide.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
Labels: Soon

#4008 Backend: Save Private Island Chest inside StorageAPI
  src/main/java/at/hannibal2/skyhanni/api/StorageApi.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/model/SkyHanniInventoryContainer.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
Labels: Backend

#4258 Feature: Compact Starlyn Sisters Contest Messages
  src/main/java/at/hannibal2/skyhanni/config/features/foraging/ForagingConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/foraging/StarlynContestsConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/foraging/CompactStarlynSisters.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
Labels: Soon

#2581 Feature: Floor 7 Spring Boots Helper
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/DungeonConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/SpringBootsHelper.kt
Labels: Soon

#3125 Feature: ubiks cube reminder
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/mountaintop/MountaintopConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/UbikReminder.kt
Labels: Soon

#4465 Improvement: Make SkyHanni tab completion work on 1.21
  src/main/java/at/hannibal2/skyhanni/events/chat/TabCompletionEvent.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinCommandDispatcher.java
Labels: Soon

#4470 Backend: Add opacity stuff to 1.21
  src/main/java/at/hannibal2/skyhanni/data/entity/EntityOpacityManager.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/hooks/EntityRenderDispatcherHook.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntityRenderDispatcher.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntityRenderer.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinCapeFeatureRenderer.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinEquipmentRenderer.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinModel.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinRendererLivingEntity.java
Labels: Soon, Backend, Detekt

#4474 Backend: Remove unnecessary `.intern()` in ItemResolutionQuery
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/ItemResolutionQuery.kt
Labels: Backend, Detekt

#4475 fix detekt
  src/main/java/at/hannibal2/skyhanni/features/slayer/HideIrrelevantMobsInSlayer.kt
Labels: Soon, Bug Fix

#4479 Improvement: Give opacity to held items and block helmets
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinItemRenderer.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinRendererLivingEntity.java
Labels: Soon

#4480 Fix: Added missing carolyn items
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CarrolynTable.kt
Labels: Soon, Bug Fix

#4463 Backend: cw waypoint cleanup
  src/main/java/at/hannibal2/skyhanni/data/model/waypoints/ColeweightWaypointFormat.kt
  src/main/java/at/hannibal2/skyhanni/data/model/waypoints/Waypoints.kt
Labels: Soon, Backend

#4478 Feature: Add ping command
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyChatCommands.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CurrentPing.kt
Labels: Soon

#4488 Backend: Use native ping on 1.21
  src/main/java/at/hannibal2/skyhanni/api/hypixelapi/HypixelEventApi.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyChatCommands.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CurrentPing.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinDebugHud.java
Labels: Soon, Backend
