Repository hannibal002/SkyHanni, pull requests merged in 2025-05, with the labels that each got.

#3900 Backend: Ignore some types in /shtrackparticles
  src/main/java/at/hannibal2/skyhanni/test/command/TrackParticlesCommand.kt
Labels: Soon, Backend

#3920 Fix: Time Chamber Detection
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mountaintop/SunGeckoHelper.kt
Labels: Bug Fix

#3921 Fix: Custom Scoreboard Broken Line
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix

#3910 Fix: Disallowing negative scales for the config values
  src/main/java/at/hannibal2/skyhanni/config/core/config/Position.kt
Labels: Bug Fix

#3917 Fix: Item Profit Tracker price source
  src/main/java/at/hannibal2/skyhanni/features/combat/end/DragonProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/endernodetracker/EnderNodeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/yearoftheseal/FishyTreatProfit.kt
  src/main/java/at/hannibal2/skyhanni/features/gifting/GiftProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalNucleusApi.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalNucleusProfitPer.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalNucleusTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseTracker.kt
Labels: Bug Fix

#3922 Fix: Area locations broken
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
Labels: Bug Fix

#3886 Feature + Fix: Farming Weight Monthly LB and Fix Upcoming Players
  src/main/java/at/hannibal2/skyhanni/config/features/garden/EliteFarmingWeightConfig.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/EliteBotJson.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
Labels: Bug Fix

#3923 Improvement: CH names in core
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsNamesInCore.kt
Labels: Soon

#3924 Fix: Pest Particle Waypoints
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestsConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleLine.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleWaypoint.kt
Labels: Bug Fix

#3916 Backend: Fixed graph node edtior searcahble
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphNodeEditor.kt
Labels: Soon, Backend

#3839 Backend: Value compat method + misc 1.21 changes
  build.gradle.kts
  src/main/java/at/hannibal2/skyhanni/config/ConfigGuiManager.kt
  src/main/java/at/hannibal2/skyhanni/config/core/config/Position.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/playerchat/PlayerChatModifier.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/translation/Translator.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonTeammateOutlines.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityRabbitTheFishChecker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenOptimalSpeed.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenPlotBorders.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/stereo/StereoHarmonyDiscReplacer.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/AbiphoneFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ButtonOnPause.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/FrogMaskFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ReplaceRomanNumerals.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/GuiOptionEditorUpdateCheck.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillType.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerItemsOnGround.kt
  src/main/java/at/hannibal2/skyhanni/test/TestExportTools.kt
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/MobUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/PlayerUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/RenderableCollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/BlockCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/EnchantmentsCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/GuiScreenUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/InventoryCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/WorldCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableTooltips.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
  versions/1.21.5/buildpaths.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/hooks/MessageHandlerHook.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/EntityOutlineRenderer.kt
  versions/1.21.5/src/main/resources/skyhanni.accesswidener
  versions/1.8.9/detekt/baseline.xml
  versions/mapping-1.12.2-1.8.9.txt
  versions/mapping-1.16.5-fabric-1.16.5-forge.txt
  versions/mapping-1.16.5-forge-1.12.2.txt
  versions/mapping-1.21.5-1.16.5-fabric.txt
Labels: Soon, Backend

#3928 Backend: Collection Utils Cleanup
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/ItemResolutionQuery.kt
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/OverviewPage.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/CFTooltipCompact.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CollectionUtils.kt
Labels: Backend

#3836 Improvement: Stash on World Change
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/StashConfig.kt
  src/main/java/at/hannibal2/skyhanni/events/ProfileJoinEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/StashCompact.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/DragonFeatures.kt
Labels: Soon

#3929 Backend: Floats cleanup
  src/main/java/at/hannibal2/skyhanni/config/core/config/Position.kt
  src/main/java/at/hannibal2/skyhanni/config/features/combat/broodmother/BroodmotherSpawnAlertConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/LowHealthAlertSoundConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/SecretChimeConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/diana/InquisitorSoundConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/SensitivityReducerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/laneswitch/LaneSwitchSoundSettings.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/BackgroundOutlineConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/glacite/TunnelMapsConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/ArachneSpawnTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonSecretChime.kt
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalZombieShootout.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowParticleFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggDisplayManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingHotspotRadar.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/TotemOfCorruption.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleWaypoint.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbilityCooldown.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/UserLuckBreakdown.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/TabListRenderer.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/limbo/LimboTimeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/MatriarchHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/DanceRoomHelper.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/RendererLivingEntityHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/ExtendedColorPatch.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntity.java
  src/main/java/at/hannibal2/skyhanni/utils/EntityOutlineRenderer.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/HolographicEntities.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SoundUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/StringRenderable.kt
Labels: Soon, Backend

#3687 Backend: Further GuiRenderUtils modifications
  src/main/java/at/hannibal2/skyhanni/data/NotificationManager.kt
  src/main/java/at/hannibal2/skyhanni/data/RenderData.kt
  src/main/java/at/hannibal2/skyhanni/data/ToolTipData.kt
  src/main/java/at/hannibal2/skyhanni/events/RenderItemTooltipEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/item/ItemHoverEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatHistoryGui.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FarmingItemType.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestSpawnTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/SuperpairDataDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/ColdOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventType.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigOptionGui.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiScreenHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinItemStack.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiScreen.java
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/DrawContext.kt
  src/main/java/at/hannibal2/skyhanni/utils/guide/GuideTab.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/DragNDrop.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
Labels: Soon, Backend

#3913 Fix: Burrows being really, really wrong + ConcurrentModificationException
  src/main/java/at/hannibal2/skyhanni/data/IslandType.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/IslandTypeJson.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowParticleFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/PreciseGuessBurrow.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingHotspotRadar.kt
  src/main/java/at/hannibal2/skyhanni/utils/PolynomialFitter.kt
Labels: Waiting on Hypixel, Bug Fix

#3941 Wasnt a RenderingSkyHanniEvent
  src/main/java/at/hannibal2/skyhanni/events/GuiRenderItemEvent.kt
Labels: Soon

#3942 Backend: Better bounding box
  src/main/java/at/hannibal2/skyhanni/data/IslandType.kt
Labels: Backend

#3933 Backend: Convert The Update Checker "Option" to use moulconfig rendering
  src/main/java/at/hannibal2/skyhanni/config/core/elements/GuiElement.kt
  src/main/java/at/hannibal2/skyhanni/config/core/elements/GuiElementButton.kt
  src/main/java/at/hannibal2/skyhanni/config/core/elements/GuiElementText.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/GuiOptionEditorUpdateCheck.kt
Labels: Soon, Bug Fix, Backend

#3555 Fix + Backend: trevor mobname i18n
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorMob.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorSolver.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
Labels: Bug Fix, Backend

#3938 Improvement + Fix: Missing items in the organic matter overlay
  src/main/java/at/hannibal2/skyhanni/config/features/garden/composter/ComposterConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
Labels: Bug Fix

#3945 Backend: Fix Mouse Compat
  src/main/java/at/hannibal2/skyhanni/utils/compat/MouseCompat.kt
  versions/1.21.5/buildpaths.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinMouse.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/compat/MouseCompat.kt
Labels: Backend

#3943 Improvement: Composter Overlay Visuals
  src/main/java/at/hannibal2/skyhanni/api/ItemBuyApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/RenderableCollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
Labels: Soon

#3934 Fix: Fixed block strengh guide not loading
  src/main/java/at/hannibal2/skyhanni/features/mining/BlockStrengthGuide.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Bug Fix

#3944 fix crash in neu overlays
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/neu/MixinStorageOverlay.java
Labels: Bug Fix

#3946 Backend: Deprecate LorenzUtils, Adding SkyBlockUtils
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandType.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/kuudra/KuudraApi.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/PlayerUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
Labels: Soon, Backend

#3947 Improvement: Trevor The Trapper
  src/main/java/at/hannibal2/skyhanni/config/features/misc/TrevorTheTrapperConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
Labels: Soon

#3949 Fix: Occasional crash while rendering
  src/main/java/at/hannibal2/skyhanni/utils/compat/DrawContextUtils.kt
Labels: Soon, Bug Fix

#3948 Fix: Custom Scoreboard Error in Garden Guesting
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventGarden.kt
Labels: Bug Fix

#2104 Backend: Mobdetection Shiny Pig
  src/main/java/at/hannibal2/skyhanni/data/mob/IslandExceptions.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/MobUtils.kt
Labels: Soon, Waiting on Hypixel, Backend

#3950 Backend: Extract LineDrawer and QuadDrawer from RenderUtils
  src/main/java/at/hannibal2/skyhanni/data/mob/LineToMobHandler.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsWalls.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/snake/LivingCaveSnake.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/render/LineDrawer.kt
  src/main/java/at/hannibal2/skyhanni/utils/render/QuadDrawer.kt
Labels: Soon, Backend

#3973 Backend: Ignore File Annotations in Detekt
  detekt/src/main/kotlin/formatting/CustomAnnotationSpacing.kt
Labels: Backend

#3976 Fix: Rift Slayer Ichor
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
Labels: Bug Fix

#3968 Fix: Rare Error While Loading Items From The NEU Repo
  src/main/java/at/hannibal2/skyhanni/utils/NeuItems.kt
Labels: Bug Fix

#3935 Backend: Fix Ide no longer dies in K2 mode with live plugin
  .live-plugins/event/plugin.kts
  .live-plugins/module/plugin.kts
Labels: Soon, Backend

#3964 Fix: issues with other mods setting middle click
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiContainer.java
Labels: Bug Fix, Wrong Title/Changelog

#3982 Fix: Async chat access
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
Labels: Bug Fix

#3978 Improvement: Hide Far Entities ignore useful mobs
  src/main/java/at/hannibal2/skyhanni/config/features/misc/HideFarEntitiesConfig.java
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/AreaMiniBossFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonMobManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/HideFarEntities.kt
Labels: Soon

#3979 Fix: Pickobulus in Non-cold islands
  src/main/java/at/hannibal2/skyhanni/data/MiningApi.kt
Labels: Bug Fix

#3963 Fix: Discord Rich Presence crashing on startup
  build.gradle.kts
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordRPCManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
Labels: Bug Fix

#3980 Fix: Fishing Tracker's Times Fished
  src/main/java/at/hannibal2/skyhanni/events/fishing/FishingCatchEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingApi.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingProfitTracker.kt
Labels: Bug Fix

#3987 Fix: Wrong scissor stack
  .github/workflows/illegal-imports.txt
  src/main/java/at/hannibal2/skyhanni/utils/compat/DrawContext.kt
Labels: Soon, Bug Fix

#3902 Backend: No Private Event Handlers
  .live-plugins/event/plugin.kts
  src/main/java/at/hannibal2/skyhanni/api/event/EventListeners.kt
Labels: Soon, Backend

#3878 Improvement: Pet w/Rarity Item Resolution
  src/main/java/at/hannibal2/skyhanni/utils/ItemNameResolver.kt
Labels: Soon

#3908 Backend: Fix config set on Properties
  src/main/java/at/hannibal2/skyhanni/utils/json/Shimmy.kt
Labels: Soon, Backend

#3683 Feature + Backend: Disable Profile Viewer in Kuudra
  src/main/java/at/hannibal2/skyhanni/config/features/crimsonisle/CrimsonIsleConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/ItemClickData.kt
  src/main/java/at/hannibal2/skyhanni/events/entity/EntityClickEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/HighlightVisitorsOutsideOfGarden.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/kuudra/KuudraProfileViewerBlocker.kt
Labels: Soon, Backend

#3998 Improvement: Cleanup and more compact the hoppity reward summary
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
Labels: Soon

#4002 Fix: Zombie Shootout name detection
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalZombieShootout.kt
Labels: Bug Fix

#4013 Backend: Remove 1.12 preprocessing step
  CONTRIBUTING.md
  build.gradle.kts
  sharedVariables/src/MinecraftVersion.kt
  sharedVariables/src/ProjectTarget.kt
  src/main/java/at/hannibal2/skyhanni/api/DataWatcherApi.kt
  src/main/java/at/hannibal2/skyhanni/events/DataWatcherUpdatedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinDataWatcher.java
  src/main/java/at/hannibal2/skyhanni/utils/NeuItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
  src/main/java/at/hannibal2/skyhanni/utils/chat/TextHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/EffectsCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/EnchantmentsCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/EntityCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/ItemCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/PacketCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/SkyhanniBaseScreen.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/ItemStackTypeAdapterFactory.kt
  versions/1.12.2/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinDataWatcher.java
  versions/mapping-1.12.2-1.8.9.txt
  versions/mapping-1.16.5-fabric-1.16.5-forge.txt
  versions/mapping-1.16.5-forge-1.12.2.txt
  versions/mapping-1.16.5-forge-1.8.9.txt
  versions/mapping-1.21.5-1.16.5-fabric.txt
  versions/pattern-mappings-1.16.5-forge-1.8.9.txt
Labels: Soon, Backend
