Repository hannibal002/SkyHanni, pull requests merged in 2025-01, with the labels that each got.

#3143 Backend: Less Lazy
  src/main/java/at/hannibal2/skyhanni/data/NotificationManager.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/event/AbstractChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/event/PartyChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/event/PlayerAllChatEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/InventoryFullyOpenedEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/LorenzEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/ServerBlockChangeEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/entity/EntityMoveEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilterGui.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/SeaCreature.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/SprayFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorSupercraft.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorReward.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/RenderBackground.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/CarnivalShopHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/EssenceShopHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HeldTimeInLore.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarOpenPriceWebsite.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/FireVeilWandParticles.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/ColdOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/DeepCavernsGuide.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseType.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/MineshaftWaypointType.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/RestorePieceOfWizardPortalLore.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/RiftAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/kloon/KloonHacking.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/RiftLarva.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/RiftOdonata.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/PunchcardHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/RiftHorsezookaHider.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzRarity.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableInventory.kt
Labels: Soon, Backend

#3148 Fix: Deep Caverns Guide Small Chat Fixes
  src/main/java/at/hannibal2/skyhanni/features/mining/DeepCavernsGuide.kt
Labels: Bug Fix

#3144 Fix: Rift Transfer Logic
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/RiftAPI.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
Labels: Bug Fix

#3156 Backend: ModVersion changes
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/api/event/EventHandler.kt
  src/main/java/at/hannibal2/skyhanni/config/Features.java
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/events/LorenzEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/GuiOptionEditorUpdateCheck.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/UpdateManager.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniConfigSearchResetCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/APIUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkyHanniTypeAdapters.kt
  src/main/java/at/hannibal2/skyhanni/utils/system/ModVersion.kt
Labels: Soon, Backend

#3153 Fix: Carnival Tokens Owned
  src/main/java/at/hannibal2/skyhanni/features/inventory/CarnivalShopHelper.kt
Labels: Bug Fix

#3150 Fix: ConcurrentModificationException in ChestValue
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
Labels: Bug Fix

#3106 Backend: Storage Classes to Kotlin
  gradle/libs.versions.toml
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/Features.java
  src/main/java/at/hannibal2/skyhanni/config/Features.kt
  src/main/java/at/hannibal2/skyhanni/config/SackData.java
  src/main/java/at/hannibal2/skyhanni/config/SackData.kt
  src/main/java/at/hannibal2/skyhanni/config/core/config/Position.java
  src/main/java/at/hannibal2/skyhanni/config/storage/PlayerSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/config/storage/PlayerSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/Storage.java
  src/main/java/at/hannibal2/skyhanni/config/storage/Storage.kt
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/PetAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/QuiverAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/CroesusChestTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/AllBurrowsList.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/MythologicalCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/FarmingPersonalBestGain.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/FeatureToggleProcessor.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/GuiOptionEditorUpdateCheck.kt
  src/main/java/at/hannibal2/skyhanni/utils/ConfigUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/EnumSkippingTypeAdapterFactory.kt
Labels: Soon, Waiting on Dependency PR, Backend

#3157 Fix: Custom Scoreboard not showing Kuudra Lines - Part 3
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventKuudra.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/kuudra/KuudraAPI.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Bug Fix

#3152 Improvement: Widget Display, Hypixel Profile
  src/main/java/at/hannibal2/skyhanni/features/gui/TabWidgetDisplay.kt
Labels: Soon

#3158 Backend: More Regex Tests
  src/main/java/at/hannibal2/skyhanni/data/QuiverAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/BingoAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardTips.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/nextstephelper/BingoNextStepHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenLevelDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/AuctionOutbidWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/auctionhouse/AuctionHouseCopyUnderbidPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/AdvancedPlayerList.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/pets/CurrentPetDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/teleportpad/TeleportPadCompactName.kt
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#3146 Fix: skill overflow event not posted
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
Labels: Bug Fix

#2589 Feature: Minion Upgrade Helper
  src/main/java/at/hannibal2/skyhanni/config/features/minion/MinionsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionUpgradeHelper.kt
Labels: Soon

#3101 Improvement: Discrite Held Time
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/HeldTimeInLore.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemDisplayOverlayFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
Labels: Soon

#2876 Backend: Preprocess Data Watcher
  src/main/java/at/hannibal2/skyhanni/api/DataWatcherAPI.kt
  src/main/java/at/hannibal2/skyhanni/data/EntityData.kt
  src/main/java/at/hannibal2/skyhanni/events/DataWatcherUpdatedEvent.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinDataWatcher.java
  versions/1.12.2/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinDataWatcher.java
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#3062 Improvement: Nucleus Highlight Colors
  src/main/java/at/hannibal2/skyhanni/config/features/mining/CrystalHighlighterColorConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/CrystalHighlighterConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/NucleusBarriersBox.kt
Labels: Soon

#3159 Fix: Moby Highlight (again)
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
Labels: Bug Fix

#3117 Improvement: Mining Event Display Sorting
  src/main/java/at/hannibal2/skyhanni/features/mining/eventtracker/MiningEventDisplay.kt
Labels: Soon

#3165 Fix: auction price comparison inventory close
  src/main/java/at/hannibal2/skyhanni/features/misc/AuctionHousePriceComparison.kt
Labels: Bug Fix

#3164 Fix: CF Party Mode Chroma Check
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
Labels: Bug Fix

#3151 Backend: GardenAPI - replace LorenzWorldChangeEvent with IslandChangeEvent
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
Labels: Backend

#3154 Backend: InventoryDetector and RenderDisplayHelper
  src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
  src/main/java/at/hannibal2/skyhanni/events/GuiRenderEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/MineshaftPityDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryDetector.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderDisplayHelper.kt
Labels: Backend

#3175 Added workaround to fix minion upgrade feature showing outside minion menus
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
Labels: Bug Fix, Wrong Title/Changelog

#3168 Backend: Removing more Deprecated methods
  src/main/java/at/hannibal2/skyhanni/config/storage/Storage.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardTips.kt
  src/main/java/at/hannibal2/skyhanni/features/event/anniversary/Year300RaffleEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/RngMeterInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbilityCooldown.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUInternalName.kt
  src/main/java/at/hannibal2/skyhanni/utils/RecalculatingValue.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#3169 Improvement: Add EliteBot profile link to rich presence
  src/main/java/at/hannibal2/skyhanni/config/features/misc/DiscordRPCConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordRPCManager.kt
Labels: Soon

#2909 Feature: Remove NEU as a dependency for SkyHanni
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesRepo.kt
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/ItemResolutionQuery.kt
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/NeuEventWrappers.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/NeuPetsJson.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/events/NeuRepositoryReloadEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/FirstMinionTier.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/MinionCraftHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/APIUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemNameResolver.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/NEUVersionCheck.kt
  src/main/java/at/hannibal2/skyhanni/utils/PrimitiveIngredient.kt
  src/main/java/at/hannibal2/skyhanni/utils/PrimitiveRecipe.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/system/PlatformUtils.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon

#3176 Backend: Refactor `/config/features/mining`
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/caverns/DeepCavernsGuideConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/dwarves/KingTalismanConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/glacite/ColdOverlayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/glacite/CorpseLocatorConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/glacite/CorpseTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/glacite/ExcavatorProfitTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/glacite/ExcavatorTooltipHiderConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/glacite/FossilExcavatorConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/glacite/FossilExcavatorSolverConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/glacite/GlaciteMineshaftConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/glacite/MineshaftConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/glacite/MineshaftPityDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/glacite/MineshaftWaypointsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/glacite/TunnelMapsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/nucleus/AreaWallsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/nucleus/CrystalHighlighterColorConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/nucleus/CrystalHighlighterConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/nucleus/PowderTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
Labels: Soon, Backend

#3180 Fix: missing icons in /sh
  src/main/java/at/hannibal2/skyhanni/config/Features.kt
  src/main/resources/assets/skyhanni/social/discord.png
  src/main/resources/assets/skyhanni/social/github.png
  src/main/resources/assets/skyhanni/social/patreon.png
Labels: Bug Fix

#3100 Backend: /shgraphfindall
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/GraphUtils.kt
Labels: Soon, Backend

#3181 Remove: "Not Accepted" Crimson Isle quest state
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/QuestLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/quest/QuestState.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/quest/UnknownQuest.kt
Labels: Soon

#3142 Fix: HitmanAPI Calculations
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/hitman/HitmanAPI.kt
Labels: Bug Fix

#2768 Backend: Hypixel Mod API
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/java/at/hannibal2/skyhanni/api/hypixelapi/HypixelEventAPI.kt
  src/main/java/at/hannibal2/skyhanni/api/hypixelapi/HypixelLocationAPI.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.java
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandType.kt
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
  src/main/java/at/hannibal2/skyhanni/events/HypixelJoinEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/hypixel/modapi/HypixelAPIJoinEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/hypixel/modapi/HypixelAPIServerChangeEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/minecraft/ScoreboardTitleUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/tweaker/SkyHanniTweaker.java
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
Labels: Soon, Backend

#3177 Fix: Overflow levelups no longer hardcoded
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillType.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillUtil.kt
Labels: Bug Fix

#3119 Improvement: Compact Farming Fortune Display
  src/main/java/at/hannibal2/skyhanni/config/features/garden/FarmingFortuneConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
Labels: Soon

#3179 Fix: Rift Blood Effigies (Take 2)
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/stillgorechateau/RiftBloodEffigies.kt
Labels: Bug Fix

#3051 Feature: Enchanted Clock Reminders
  src/main/java/at/hannibal2/skyhanni/config/features/misc/EnchantedClockConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/EnchantedClockJson.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBlockOpen.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStats.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/hitman/HitmanAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/EnchantedClockHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/SimpleTimeMark.kt
Labels: Soon

#3178 Backend + Fix: Use correct type for item attributes
  src/main/java/at/hannibal2/skyhanni/utils/NumberUtil.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
Labels: Bug Fix, Backend

#3185 Backend: Suppress LargeClass in LoadedModules
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProcessor.kt
Labels: Backend

#3115 Backend: Repo pattern dashes and fixes
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/SpidersDenAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/TerracottaPhase.kt
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalQuickStart.kt
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/CarnivalShopHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/EssenceShopHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemStars.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/PageScrolling.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ReforgeHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SkyblockGuideHighlightFeature.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/StockOfStonkFeature.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/WardrobeAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/RiftTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/motes/MotesSession.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#3186 Fix: GardenKeybinds not working with Inventory/Chat Keybind
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCustomKeybinds.kt
Labels: Bug Fix

#3198 Backend: graph editor fix, title logic change
  src/main/java/at/hannibal2/skyhanni/data/TitleManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/BurrowWarpHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GoldenFishTimer.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon, Backend

#3184 Fix: Garden Tooltip Tweaks + Gemstones
  src/main/java/at/hannibal2/skyhanni/features/garden/ToolTooltipTweaks.kt
Labels: Bug Fix

#3155 Backend: bestiary code cleanup
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
Labels: Backend

#3194 Backend: Make getcounter() nullable
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
Labels: Soon, Backend

#3196 Fix: FF Bugs
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFGuideGUI.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFInfos.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/CropPage.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/OverviewPage.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockTime.kt
Labels: Bug Fix

#3193 Fix: Playtime Copy not working without Limbo Playtime
  src/main/java/at/hannibal2/skyhanni/features/misc/CopyPlaytime.kt
Labels: Bug Fix

#3191 Fix: Item data sometimes not loading
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
Labels: Bug Fix

#3192 Fix: Custom Scoreboard Broken Lines
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
Labels: Bug Fix

#3171 Fix: Define backports for autoupdater
  src/main/java/at/hannibal2/skyhanni/features/misc/update/CustomGithubReleaseUpdateSource.kt
  src/main/java/at/hannibal2/skyhanni/utils/system/ModVersion.kt
  src/test/java/at/hannibal2/skyhanni/test/UpdateVersionTest.kt
Labels: Soon, Bug Fix

#3197 Backend: Base Stats
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/SkyblockItemsDataJson.kt
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/HypixelItemAPI.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Soon, Backend

#2222 Feature: Sound Responses (Meow)
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatSoundResponseConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatSoundResponse.kt
  src/main/java/at/hannibal2/skyhanni/utils/SoundUtils.kt
Labels: Soon

#3205 Fix: GardenKeybinds not working with Inventory/Chat Keybind 2
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCustomKeybinds.kt
Labels: Bug Fix

#3215 Improvement: Replace old hoppity ready reminder messages
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
Labels: Soon

#3212 Backend: Delay HypixelData check
  src/main/java/at/hannibal2/skyhanni/api/hypixelapi/HypixelLocationAPI.kt
Labels: Backend

#3214 Backend: LorenzVec generated methods
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkyHanniTypeAdapters.kt
Labels: Soon, Backend

#3219 Fix: Missing Label on DungeonFinder Item Stack
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
Labels: Bug Fix

#3220 Backend: Split up RegexTestMissing and failed
  detekt/detekt.yml
  detekt/src/main/kotlin/repo/RepoPatternRegexTestFailed.kt
  detekt/src/main/kotlin/repo/RepoPatternRegexTestMissing.kt
  detekt/src/main/kotlin/repo/RepoRuleSetProvider.kt
  src/main/java/at/hannibal2/skyhanni/data/QuiverAPI.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Backend

#3160 Feature: Custom user sounds for Inquisitor waypoint sharing
  src/main/java/at/hannibal2/skyhanni/config/features/event/diana/InquisitorSharingConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/event/diana/InquisitorSoundConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
Labels: Soon

#3207 Backend: ReputationHelper "Rewrite"
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
  src/main/java/at/hannibal2/skyhanni/events/GuiContainerEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorRewardWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryKeybinds.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/CrimsonIsleReputationHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/FactionType.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/kuudra/DailyKuudraBossHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/miniboss/DailyMiniBossHelper.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiContainerHook.kt
Labels: Soon, Backend

#3223 Fix: Minion upgrade helper showing always
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
Labels: Bug Fix

#3222 Fix: Visitor shopping list AH
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
Labels: Bug Fix

#3221 Fix: /shcarry duplicate customer
  src/main/java/at/hannibal2/skyhanni/features/misc/CarryTracker.kt
Labels: Bug Fix

#3224 Fix: Crimson Miniboss 1/2 Quest
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/QuestLoader.kt
Labels: Bug Fix

#3210 Fix: Hitman
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/hitman/HitmanAPI.kt
Labels: Bug Fix

#2927 Backend: Active Custom Scoreboard Patterns
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardConfigElement.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardConfigEventElement.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElement.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementBits.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementCold.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementCopper.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementDate.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementEvents.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementFooter.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementHeat.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementLobbyCode.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementLocation.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementMotes.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementNorthStars.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementObjective.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementProfile.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementPurse.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementSlayer.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementTime.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementVisiting.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventActiveTablist.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventAnniversary.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventBroodmother.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventCarnival.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventDamage.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventDarkAuction.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventDojo.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventDungeons.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventEssence.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventFlightDuration.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventGarden.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventJacobMedals.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventKuudra.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventMagmaBoss.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventMining.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventNewYear.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventQueue.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventRedstone.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventRift.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventServerClose.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventSpooky.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventTrapper.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventVoting.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventWinter.kt
Labels: Soon, Backend

#2542 Feature: Frog Mask Display
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryCustomReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/FrogMaskDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/RegexUtils.kt
Labels: Soon

#3211 Feature: Block Clicking Not Spawnable Slayer
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/config/features/slayer/SlayerConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/BlockNotSpawnable.kt
Labels: Soon

#3208 Backend: Detekt Max Line Length
  detekt/detekt.yml
  src/main/java/at/hannibal2/skyhanni/features/bingo/MinionCraftHelper.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#3241 Backend: Disable hoppity call warning by default
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityCallWarningConfig.java
Labels: Backend

#3244 Fix: Dance room helper hide players
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/DanceRoomHelper.kt
Labels: Bug Fix

#3233 Fix: Show Town Board for accepted Fetch quest
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
Labels: Bug Fix

#3237 Improvement: Improve text for when fewer than 10 levels remain on HOTM perk when holding shift
  src/main/java/at/hannibal2/skyhanni/features/mining/PowderPerHotmPerk.kt
Labels: Soon

#3246 Backend: removing the download source checker
  src/main/java/SkyHanniInstallerFrame.java
  src/main/java/at/hannibal2/skyhanni/tweaker/DownloadSourceChecker.java
  src/main/java/at/hannibal2/skyhanni/tweaker/SkyHanniTweaker.java
Labels: Soon, Backend

#3232 Fix: FAQ formatting
  docs/DISCORD_FAQ.md
Labels: Bug Fix

#3226 Fix: GUI Editor + GUI Search
  src/main/java/at/hannibal2/skyhanni/data/model/TextInput.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
Labels: Bug Fix

#3209 Backend: /shdebug + ram + uptime
  src/main/java/at/hannibal2/skyhanni/utils/ComputerEnvDebug.kt
Labels: Soon, Backend

#3218 Improvement: Better GUI rendering
  src/main/java/at/hannibal2/skyhanni/config/features/misc/AreaPathfinderConfig.java
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/data/RenderData.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggDisplayManager.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerRngMeterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderDisplayHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Soon

#3239 Fix: Experimentation Table (2x)
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationTableAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
Labels: Bug Fix

#2886 Feature: SkyblockXP Bar
  src/main/java/at/hannibal2/skyhanni/api/SkyBlockXPAPI.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SkyBlockXPBar.kt
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
Labels: Soon

#3229 Fix: crash with repo textures if repo missing
  src/main/java/at/hannibal2/skyhanni/utils/SkullTextureHolder.kt
Labels: Bug Fix

#3228 Improvement: Remove indent for totals on Mythological Creature Tracker
  src/main/java/at/hannibal2/skyhanni/features/event/diana/MythologicalCreatureTracker.kt
Labels: Soon

#3247 Fix: Game rarely crashing during launch
  src/main/java/at/hannibal2/skyhanni/utils/system/PlatformUtils.kt
Labels: Bug Fix

#3227 Fix: Ultimate Wither Scroll
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
Labels: Bug Fix

#3248 Backend: NBTTagCompound list utils
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/BlockUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
Labels: Soon, Backend

#3230 Fix: Custom Scoreboard Missing Patterns
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/nextstephelper/BingoNextStepHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementLocation.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementObjective.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventGarden.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventJacobMedals.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventMining.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventRift.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Bug Fix

#3243 Fix: The todo shouldve been todone
  src/main/java/at/hannibal2/skyhanni/utils/NEUItems.kt
Labels: Bug Fix

#3238 Fix: Ironman and non-ranked's /show messages not being detected
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerChatManager.kt
Labels: Bug Fix

#2895 Feature: SkyBlock Level in Custom Scoreboard
  src/main/java/at/hannibal2/skyhanni/api/SkyBlockXPAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardConfigElement.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementSkyBlockXp.kt
Labels: Soon

#3225 Backend: Renderable.line
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/event/winter/JyrreTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenBestCropTime.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/kuudra/DailyKuudraBossHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/miniboss/DailyMiniBossHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
Labels: Soon, Backend

#3063 Backend: De-Duplication
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/ItemsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/CarnivalShopHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/EssenceShopHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/utils/EssenceUtils.kt
Labels: Soon, Backend

#3250 Backend: onlyTierOnePrices and onlyTierFivePrices
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/utils/NumberUtil.kt
Labels: Soon, Backend

#3252 Fix: Skyblock XP Bar in Catacombs & Rift
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/SkyBlockXPBar.kt
Labels: Bug Fix

#3254 Fix: Custom Scoreboard MineshaftId not showing
  src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
Labels: Bug Fix

#3200 Backend: EnumMap and Storage Cleanup
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/SackData.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/PlayerSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/Storage.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionXp.kt
  src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/GenericWrapper.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
Labels: Soon, Backend

#3240 Backend: Resolve some Baseline LongMethod
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/TabListRenderer.kt
  src/main/java/at/hannibal2/skyhanni/test/command/CopyNearbyEntitiesCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/MinecraftConsoleFilter.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableTooltips.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#3251 Improvement: Neu overlays EIV support
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/neu/MixinEquipmentOverlay.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/neu/MixinStorageOverlay.java
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
Labels: Soon

#3255 Backend: EstimatedItemValueCalculator cleanup
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Soon, Backend

#3258 Fix: Anvil Combine Helper bug
  src/main/java/at/hannibal2/skyhanni/features/anvil/AnvilCombineHelper.kt
Labels: Bug Fix

#3256 Fix: Enchanted Clock Warnings
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/EnchantedClockJson.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/EnchantedClockHelper.kt
Labels: Bug Fix

#3263 Backend: Item resolution query works in experimentation table RNG meter
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/ItemResolutionQuery.kt
Labels: Backend

#3264 Fix: `/shskills` printing help when resetting goal
  src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
Labels: Bug Fix

#3267 Fix: Enchanted Clock Helper
  src/main/java/at/hannibal2/skyhanni/features/misc/EnchantedClockHelper.kt
Labels: Bug Fix

#3266 Fix: Cs Error in Guest Garden
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementCopper.kt
Labels: Bug Fix

#3268 Improvement: Add Search Tag to Private Island Ability Block Option
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
Labels: Soon

#3269 Fix: BZ insant buy detection v2
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
Labels: Bug Fix

#2897 Fix + Backend: Livid Detection
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/LividFinderConfig.java
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonLividFinder.kt
Labels: Soon, Backend

#3274 Backend: IsInIslandCheck #DeathToEarlyReturns
  detekt/detekt.yml
  detekt/src/main/kotlin/style/IsInIslandEarlyReturn.kt
  detekt/src/main/kotlin/style/SkyHanniStyleProvider.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GeyserFishing.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/FossilExcavatorAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/JoinCrystalHollows.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/teleportpad/TeleportPadCompactName.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/teleportpad/TeleportPadInventoryNumber.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangManager.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/CrimsonIsleReputationHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/kuudra/DailyKuudraBossHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/PunchcardHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/enderman/EndermanSlayerFeatures.kt
Labels: Backend

#3275 Backend: Event (Singular)
  src/main/java/at/hannibal2/skyhanni/data/MinecraftData.kt
  src/main/java/at/hannibal2/skyhanni/events/ReceiveParticleEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/SkyHanniRenderEntityEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/render/EntityRenderLayersEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/FlareDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonCleanEnd.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHideItems.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/TerracottaPhase.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/SoopyGuessBurrow.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/TotemOfCorruption.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GeyserFishing.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleLine.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleWaypoint.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/FireVeilWandParticles.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/PrecisionMiningHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/LesserOrbHider.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MiscFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ParticleHider.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangHider.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/RiftWiltedBerberisHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveDefenseBlocks.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveLivingMetalHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/stillgorechateau/SplatterHearts.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/motes/RiftMotesOrb.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/BlazeSlayerClearView.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/enderman/EndermanSlayerHideParticles.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TrackParticlesCommand.kt
Labels: Backend

#3280 Fix: Composter Overlay not Rendering
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterDisplay.kt
Labels: Bug Fix

#3278 Fix: "No Infected Plots"
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestAPI.kt
Labels: Bug Fix

#3277 Fix: Visitor Reward Highlight/Chat Warning
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorAPI.kt
Labels: Bug Fix

#3257 Backend + Fix: Bestiary Tab Widget
  src/main/java/at/hannibal2/skyhanni/features/gui/TabWidgetDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
Labels: Bug Fix, Backend

#3182 Improvement: Open Last Storage now saves across instances
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/LastStorageConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/OpenLastStorage.kt
Labels: Soon

#2745 Feature: Auto join Skyblock
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/AutoJoinSkyblock.kt
Labels: Soon

#3291 Backend: Dont ignore annotated Long- & ComplexMethods
  detekt/detekt.yml
  versions/1.8.9/detekt/baseline.xml
Labels: Backend

#3253 Feature + Fix: Xp In Inventory
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/SkyBlockXPBar.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/XpInInventories.kt
Labels: Soon, Bug Fix

#2322 Feature: Bacte Tentacle Waypoints & Phase Display
  src/main/java/at/hannibal2/skyhanni/api/FmlEventApi.kt
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/colosseum/ColosseumConfig.java
  src/main/java/at/hannibal2/skyhanni/data/mob/IslandExceptions.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
  src/main/java/at/hannibal2/skyhanni/events/MobEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/entity/EntityHurtEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/RiftAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/colosseum/BactePhase.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/colosseum/TentacleWaypoint.kt
Labels: Soon

#3287 Fix + Backend: Profit Tracker rendering
  src/main/java/at/hannibal2/skyhanni/config/features/garden/ArmorDropTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/features/combat/endernodetracker/EnderNodeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghosttracker/GhostTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/MythologicalCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/jerry/frozentreasure/FrozenTreasureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/SeaCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/ArmorDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/DicerRngDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/DraconicSacrificeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Bug Fix, Backend

#3294 Fix: Gemstones in sack display
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryCustomReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/FrogMaskDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/RegexUtils.kt
Labels: Bug Fix

#3201 Backend: Remove MutableList<List<Any>>.addButton()
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
Labels: Soon, Backend

#2285 Feature: Crystal Nucleus Tracker, Profit-Per, and Filter
  src/main/java/at/hannibal2/skyhanni/config/features/chat/CrystalNucleusConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/FilterTypesConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/PowderMiningConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/PowderMiningGemstoneConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/mining/nucleus/CrystalNucleusTrackerConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/events/mining/CrystalNucleusLootEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/CrystalNucleusChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/PowderMiningChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalNucleusApi.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalNucleusProfitPer.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalNucleusTracker.kt
Labels: Soon

#3289 Fix: ATTRIBUTE_SHARD not found chat message
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingProfitTracker.kt
Labels: Bug Fix

#3286 Improvement: Item Tracker Buttons
  src/main/java/at/hannibal2/skyhanni/config/features/misc/TrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon

#3297 Fix: NEU Field Not Existing
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
Labels: Bug Fix

#3298 Fix: King's Scent not detected
  src/main/java/at/hannibal2/skyhanni/features/misc/NonGodPotEffectDisplay.kt
Labels: Bug Fix

#3302 Fix: freeze with duplicate json entries
  src/main/java/at/hannibal2/skyhanni/utils/json/SkippingTypeAdapterFactory.kt
Labels: Bug Fix

#3301 Fix: custom value in estimated trade
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
Labels: Bug Fix

#3283 Backend: fixed /shchathistory
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilterGui.kt
Labels: Soon, Backend

#3282 Backend: Fixed /shconfig reset
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniConfigSearchResetCommand.kt
Labels: Soon, Backend

#3304 Backend: NPC -> Npc
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugMobConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/data/mob/IslandExceptions.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobData.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDebug.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFactories.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
  src/main/java/at/hannibal2/skyhanni/events/MobEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/CrystalNucleusChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/event/UniqueGiftingOpportunitiesFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/NpcVisitorFix.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ShiftClickNpcSell.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/HideArmor.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/RiftGunthersRace.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/PunchcardHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/test/command/CopyNearbyEntitiesCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#3300 Fix: A few fps improvements
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/MinecraftData.kt
  src/main/java/at/hannibal2/skyhanni/data/ProfileStorageData.kt
  src/main/java/at/hannibal2/skyhanni/events/minecraft/WorldChangeEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/BroodmotherFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/HideDamageSplash.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/ArachneMinisNametagHider.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonBossHideDamageSplash.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/TerracottaPhase.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggDisplayManager.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenCropMilestoneFix.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorListener.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/HideArmor.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/teleportpad/TeleportPadCompactName.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/VolcanoExplosivityDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/HideMobNames.kt
  src/test/java/at/hannibal2/skyhanni/test/garden/VisitorListenerTest.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Bug Fix

#3284 Backend: added /shgraphloadthisisland
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditor.kt
Labels: Soon, Backend

#3162 Backend: Kotlin Language Adapter
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/core/config/Position.java
  src/main/java/at/hannibal2/skyhanni/features/chat/translation/Translator.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilSolverDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordRPCManager.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/system/KotlinLanguageAdapter.kt
Labels: Soon, Backend

#3306 Backend: Fixed /shdebug time offset
  src/main/java/at/hannibal2/skyhanni/utils/ComputerTimeOffset.kt
Labels: Soon, Backend

#2858 Feature: Add option to only hide sack changes while in the garden
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/SackApi.kt
Labels: Soon

#3309 Backend: Move some commands to their own classes
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/GardenCropMilestonesCommunityFix.kt
  src/main/java/at/hannibal2/skyhanni/data/PartyApi.kt
  src/main/java/at/hannibal2/skyhanni/data/TitleManager.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/translation/Translator.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/endernodetracker/EnderNodeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/AllBurrowsList.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/MythologicalCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocations.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/jerry/frozentreasure/FrozenTreasureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/SeaCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/ArmorDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/DicerRngDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenStartLocation.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CollectionTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MarkedPlayerManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordRPCManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/reminders/ReminderManager.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/test/PacketTest.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyBlockIslandTest.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TrackParticlesCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/command/TrackSoundsCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Backend

#3310 Backend: Update preprocessing to 1.21.4
  build.gradle.kts
  sharedVariables/src/MinecraftVersion.kt
  sharedVariables/src/MultiVersionStage.kt
  sharedVariables/src/ProjectTarget.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  versions/1.21.4/buildpaths-test.txt
  versions/1.21.4/buildpaths.txt
  versions/1.21.4/src/test/kotlin/TestLegacyColorFormat.kt
  versions/1.21.4/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
  versions/mapping-1.21.4-1.16.5.txt
Labels: Backend

#3285 Backend + Fix: Warn for immutable types in the config
  detekt/build.gradle.kts
  detekt/detekt.yml
  detekt/src/main/kotlin/potentialbugs/ImmutableTypesWithExpectedInteriorMutabilityInConfig.kt
  detekt/src/main/kotlin/potentialbugs/PotentialBugsProvider.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/CrystalNucleusConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/PlayerMessagesConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/PowderMiningConfig.kt
Labels: Bug Fix, Backend

#3318 Allow maven local for plugins
  settings.gradle.kts
Labels: Soon

#3319 Fix: Tracker Config Positions Resetting.
  src/main/java/at/hannibal2/skyhanni/features/combat/endernodetracker/EnderNodeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghosttracker/GhostTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/jerry/frozentreasure/FrozenTreasureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/SeaCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/ArmorDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/DicerRngDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/DraconicSacrificeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Bug Fix

#3324 Backend: Exposed Runnable
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/BackgroundConfig.java
Labels: Backend

#3325 Fix: CF shortcut vs century raffle
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/HoppityEggLocationsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryShortcut.kt
Labels: Bug Fix

#3320 Fix: Fake Objective Objectives in CS
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix

#3327 Fix: stray rabbit tracker being gray
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryStrayTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryDetector.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderDisplayHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Bug Fix, Wrong Title/Changelog

#3293 Backend: bacte phase damage indicator
  src/main/java/at/hannibal2/skyhanni/config/features/combat/damageindicator/DamageIndicatorConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/colosseum/ColosseumConfig.java
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/colosseum/BacteApi.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/colosseum/TentacleWaypoint.kt
Labels: Soon, Backend

#3329 Fix: Experimentation Table profit tracker gray
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentationTableApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryDetector.kt
Labels: Bug Fix

#3288 Fix: Museum Milestone not affecting bitsPerCookie()
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/data/BitsApi.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Bug Fix

#2855 Backend: Kotlin Position
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/core/config/Position.java
  src/main/java/at/hannibal2/skyhanni/config/core/config/Position.kt
  src/main/java/at/hannibal2/skyhanni/config/core/config/PositionList.kt
  src/main/java/at/hannibal2/skyhanni/config/core/config/gui/GuiPositionEditor.kt
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingHookDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/TabWidgetDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryCustomReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/BlazeSlayerDaggerHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon, Backend

#2521 Feature: Secret chime
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/DungeonConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/SecretChimeConfig.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/ItemsJson.kt
  src/main/java/at/hannibal2/skyhanni/events/entity/EntityRemovedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonSecretChime.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinWorld.java
Labels: Soon

#3317 Backend: Cleanup Command Registration
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/CommandCategory.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/CommandRegistrationEvent.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/CommandsRegistry.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/HelpCommand.kt
Labels: Soon, Backend

#3305 Backend: More Early Return Nuking 🥳
  .idea/dictionaries/default_user.xml
  detekt/detekt.yml
  detekt/src/main/kotlin/style/IsInIslandEarlyReturn.kt
  detekt/src/main/kotlin/style/OnlyOnIslandSpecificity.kt
  detekt/src/main/kotlin/style/SkyHanniStyleProvider.kt
  src/main/java/at/hannibal2/skyhanni/data/GardenComposterUpgradesData.kt
  src/main/java/at/hannibal2/skyhanni/data/GardenCropUpgrades.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonBossHideDamageSplash.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonBossMessages.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHideItems.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/HighlightDungeonDeathmite.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingBaitWarnings.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/AtmosphericFilterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenLevelDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenOptimalSpeed.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenPlotApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenWarpCommands.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterInventoryNumbers.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/GardenComposterInventoryFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/FarmingContestApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/ArmorDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/DicerRngDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenBurrowingSporesNotifier.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/GardenInventoryNumbers.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenNextPlotPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestSpawn.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/SprayDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/SprayFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/StereoHarmonyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/NpcVisitorFix.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorListener.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalNucleusApi.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/ashfang/AshfangHighlights.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/RiftAgaricusCap.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/VoltHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/VerminTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/kloon/KloonHacking.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/wyldwoods/ShyCruxWarnings.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/PunchcardHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/RiftTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/motes/ShowMotesNpcSellPrice.kt
Labels: Soon, Backend
