Repository hannibal002/SkyHanni, pull requests merged in 2025-09, with the labels that each got.

#4628 Fix: Some config stuff that June found
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/CFInventory.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
Labels: Soon, Bug Fix

#4637 Fix: #4628
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.kt
Labels: Bug Fix

#4639 Fix: Melon
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/CropType.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/DicerRngDropTracker.kt
Labels: Bug Fix

#4602 Backend: Stop Including Kotlin on Modern
  build.gradle.kts
Labels: Soon, Backend

#4605 Feature: Tab-complete /show
  src/main/java/at/hannibal2/skyhanni/config/features/commands/TabCompleteConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/tabcomplete/ShowItemTabComplete.kt
Labels: Soon

#4643 Fix: Exception in estimate item value
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/ItemsJson.kt
Labels: Soon, Bug Fix

#4644 Fix: RenderInventoryItemTipEvent taking in air on modern
  src/main/java/at/hannibal2/skyhanni/data/ItemTipHelper.kt
Labels: Soon, Bug Fix

#4642 Improvement: Add wet book count to estimated item value
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
Labels: Soon

#4645 Fix: Allow prices over int limit in hunting box value
  src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/HuntingBoxValue.kt
Labels: Bug Fix

#4649 Fix: Issue in pest waypoint
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleWaypoint.kt
Labels: Bug Fix

#4653 Fix: Sven Slayer not being detected for Damage Indicator
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/MobFinder.kt
Labels: Bug Fix

#4662 Fix: Pet names being wrong in trackers and such
  src/main/java/at/hannibal2/skyhanni/utils/PetUtils.kt
Labels: Bug Fix

#4598 Backend: Enable Incremental Preprocessor
  gradle.properties
Labels: Soon, Backend

#4593 Improvement: Fewer Coroutine Errors
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
Labels: Soon

#4578 Backend: Re-Ramp NTP Check when Stable
  src/main/java/at/hannibal2/skyhanni/utils/ComputerTimeOffset.kt
  src/main/java/at/hannibal2/skyhanni/utils/EnumUtils.kt
Labels: Soon, Backend

#4626 Backend: Stopwatch Util
  src/main/java/at/hannibal2/skyhanni/utils/Stopwatch.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/BaseGsonBuilder.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkyHanniTypeAdapters.kt
Labels: Backend

#4617 Fix: Reliable Time-Based Dwarven King Prediction
  src/main/java/at/hannibal2/skyhanni/features/mining/KingTalismanHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockTime.kt
Labels: Bug Fix, Detekt

#4654 Fix: Some tab completion not having a skyblock check
  src/main/java/at/hannibal2/skyhanni/features/commands/ViewRecipeCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/tabcomplete/WarpTabComplete.kt
Labels: Soon, Bug Fix

#4669 Fix: Pest timer custom sounds
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestSpawnTimer.kt
Labels: Bug Fix

#4603 Improvement: Additions to Crown of Avarice Tracker
  src/main/java/at/hannibal2/skyhanni/config/features/itemability/CrownOfAvariceConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/CrownOfAvariceCounter.kt
  src/main/java/at/hannibal2/skyhanni/utils/Stopwatch.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkyHanniTypeAdapters.kt
Labels: Soon

#4599 Backend: cleanup graph editor and small perf changes
  src/main/java/at/hannibal2/skyhanni/config/features/dev/GraphConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/model/Graph.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/WoodenButtonsHelper.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditorBugFinder.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphNodeEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/GraphUtils.kt
Labels: Soon, Backend

#4660 Improvement: Add Bal Shard to Crystal Nucleus Profit Tracker
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalNucleusApi.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalNucleusTracker.kt
Labels: Soon

#4672 Fix: Skyhanni user luck in sb menu
  src/main/java/at/hannibal2/skyhanni/events/render/gui/ReplaceItemEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/stereo/StereoHarmonyDiscReplacer.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/OldSkyblockMenu.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsAddonsHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/superpairs/SuperPairsItemVisibility.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/UserLuckBreakdown.kt
Labels: Bug Fix

#4683 Fix: SkyHanni Visual Words not working with coloured text
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/ModifyVisualWords.kt
Labels: Bug Fix

#4675 Feature: Pest Trap Release Keybind
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestTrapConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestTrapApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestTrapFeatures.kt
Labels: Soon

#4687 Fix: Mob type detection matching parts of mob names
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
Labels: Bug Fix

#4686 Backend: Update for regex101 delimiter change
  .live-plugins/regexr/plugin.kts
  detekt/src/main/kotlin/RepoPatternElement.kt
Labels: Backend

#4531 Backend: Attribute Levels API
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/AttributeShardsData.kt
Labels: Soon, Backend

#4717 Backend: Disable Pest Waypoint by default
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestWaypointConfig.kt
Labels: Backend

#4718 Fix: Skill Patterns
  src/main/java/at/hannibal2/skyhanni/api/SkillApi.kt
Labels: Bug Fix

#4720 Fix: mute errors
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesRepoManager.kt
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/NeuEventWrappers.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/RepositoryConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/ElectionApi.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/bazaar/HypixelBazaarFetcher.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/IslandGraphSettingsJson.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/AbstractRepoManager.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/ChatProgressUpdates.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoFileSystem.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/HypixelItemApi.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/DeepCavernsGuide.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/AutoJoinSkyblock.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordRPCManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/ChangelogViewer.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mirrorverse/DanceRoomHelper.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/ComputerTimeOffset.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/hunting/HideonleafFinder.kt
Labels: Bug Fix
