Repository hannibal002/SkyHanni, pull requests merged in 2025-06, with the labels that each got.

#4035 Backend: Fix Spongepowered Repo
  root.gradle.kts
Labels: Backend

#4032 Backend: Galatea Island
  src/main/java/at/hannibal2/skyhanni/data/IslandType.kt
Labels: Backend

#3954 Backend: Modern version build action & label
  .github/workflows/build.yml
Labels: Soon, Backend

#4022 Fix: chat display with disabled guild chat
  src/main/java/at/hannibal2/skyhanni/features/chat/CurrentChatDisplay.kt
Labels: Bug Fix

#4034 Fix: Negative Attr Combo Prices
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Bug Fix

#3986 Improvement: Read Non-God Pot Effects from Widget
  src/main/java/at/hannibal2/skyhanni/data/effect/EffectApi.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/effects/NonGodPotEffectDisplay.kt
Labels: Soon

#3996 Fix: Explosions Hider hiding Chicken Race rings
  src/main/java/at/hannibal2/skyhanni/features/misc/MiscFeatures.kt
Labels: Bug Fix

#3999 Fix: Next Egg Time When No Spawns Left
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
Labels: Bug Fix

#3952 Backend: "Datas", SkyblockUtils, Repo working on 1.21
  build.gradle.kts
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/api/event/EventListeners.kt
  src/main/java/at/hannibal2/skyhanni/api/hypixelapi/HypixelLocationApi.kt
  src/main/java/at/hannibal2/skyhanni/config/features/About.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DevConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/RepositoryConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/cropmilestones/CropMilestonesConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/ActionBarData.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandType.kt
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoUtils.kt
  src/main/java/at/hannibal2/skyhanni/events/RepositoryReloadEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/minecraft/packet/PacketSentEvent.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiIngameHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/AccessorGuiPlayerTabOverlay.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinNetHandlerPlayClient.java
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzLogger.kt
  src/main/java/at/hannibal2/skyhanni/utils/SimpleTimeMark.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/BaseGsonBuilder.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkyHanniTypeAdapters.kt
  src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
  versions/1.21.5/buildpaths.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/hooks/MessageHandlerHook.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinClientConnection.java
  versions/1.21.5/src/main/resources/fabric.mod.json
  versions/1.8.9/detekt/baseline.xml
  versions/mapping-1.16.5-fabric-1.16.5-forge.txt
Labels: Soon, Backend

#4024 Improvement: Dwarven -> Metal
  src/main/java/at/hannibal2/skyhanni/features/mining/BlockStrengthGuide.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/kuudra/KuudraApi.kt
Labels: Soon

#4041 Backend: Make modern labels actually work
  .github/workflows/build.yml
Labels: Backend

#4043 Fix: Hotm Flickering on Stacksize
  src/main/java/at/hannibal2/skyhanni/features/mining/HotmFeatures.kt
Labels: Bug Fix

#4044 Fix: Fast Fairy Souls Pathfinder ignoring if all souls are found
  src/main/java/at/hannibal2/skyhanni/features/misc/FastFairySoulsPathfinder.kt
Labels: Bug Fix, Fails Multi-Version

#3903 Backend: Config Disabling via repo
  gradle/libs.versions.toml
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/EnforcedConfigValues.kt
  src/main/java/at/hannibal2/skyhanni/config/GuiOptionEditorBlocked.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/DisabledFeaturesJson.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/EnforcedConfigValuesJson.kt
  src/main/resources/assets/skyhanni/config_blocked.png
Labels: Soon, Backend

#4042 Improvement: Pest Guess Visuals
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestWaypointConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestsConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenPlotApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleLine.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleWaypoint.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzVec.kt
Labels: Soon

#4033 Backend + Feature: Widen Config
  gradle/libs.versions.toml
  src/main/java/at/hannibal2/skyhanni/config/ConfigGuiManager.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/GuiConfig.kt
Labels: Soon, Backend

#4023 Backend: Remove `String.toChromaColor()` + Fix alpha
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/CakeTrackerConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/nucleus/PowderChestTimerConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderChestTimer.kt
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzColor.kt
Labels: Soon, Backend

#3971 Improvement: Track Gemstones in Ghost Tracker
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/GhostDropsJson.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghosttracker/GhostTracker.kt
Labels: Soon

#4047 Fix: Vars in Cake Tracker
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/CakeTrackerConfig.kt
Labels: Bug Fix

#3992 Backend: Cache Cleanup
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/CFBarnManager.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/effects/NonGodPotEffectDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/SizeLimitedCache.kt
  src/main/java/at/hannibal2/skyhanni/utils/SizeLimitedSet.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeLimitedCache.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeLimitedSet.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CacheMap.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CacheSet.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/SizeLimitedCache.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/SizeLimitedSet.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/TimeLimitedCache.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/TimeLimitedSet.kt
  versions/1.21.5/buildpaths.txt
Labels: Soon, Backend, Fails Multi-Version

#3931 Backend: Added the ability to disable config options from showing per version
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/GuiOptionEditorHidden.kt
  src/main/java/at/hannibal2/skyhanni/config/OnlyLegacy.kt
  src/main/java/at/hannibal2/skyhanni/config/OnlyModern.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/DungeonConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/GlowingDroppedItemsConfig.java
  src/main/java/at/hannibal2/skyhanni/utils/system/PlatformUtils.kt
  versions/1.21.5/buildpaths.txt
Labels: Soon, Backend

#4050 Cleanup after cache cleanup
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/CFBarnManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CacheMap.kt
Labels: Soon

#3966 Backend: OtherInventoryData and other misc stuff for 1.21
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/data/FriendApi.kt
  src/main/java/at/hannibal2/skyhanni/data/OtherInventoryData.kt
  src/main/java/at/hannibal2/skyhanni/data/OwnInventoryData.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyBlockIslandTest.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ClipboardUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NeuItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/DrawContextUtils.kt
  versions/1.21.5/buildpaths.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/TestingModFeatures.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/ComponentUtils.kt
Labels: Soon, Backend

#4088 Backend: Bump Gradle
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: Soon, Backend

#4072 Backend: Tracker Optimizations and Synchronization
  src/main/java/at/hannibal2/skyhanni/features/combat/end/DragonProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/BucketedItemTrackerData.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/ItemTrackerData.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniBucketedItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
Labels: Soon, Backend

#4058 Fix: Custom Scoreboard Party Display not disappearing when a party of 2 players is disbanded due to the leader disconnecting for 5 mins.
  src/main/java/at/hannibal2/skyhanni/data/PartyApi.kt
Labels: Bug Fix

#4089 Backend: Bump NEU to 2.6.0
  build.gradle.kts
Labels: Backend, Wrong Title/Changelog

#3970 Backend: Extract 3d rendering from RenderUtils
  src/main/java/at/hannibal2/skyhanni/features/combat/FlareDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/FireVeilWandParticles.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/render/LineDrawer.kt
  src/main/java/at/hannibal2/skyhanni/utils/render/QuadDrawer.kt
  src/main/java/at/hannibal2/skyhanni/utils/render/WorldRenderUtils.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/WorldRenderUtils.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#4054 Backend: Remove unused library
  root.gradle.kts
Labels: Soon, Backend

#4091 Fix: rift feature toggle
  src/main/java/at/hannibal2/skyhanni/config/features/rift/area/mountaintop/MountaintopConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mountaintop/EnigmaRoseFlowerpot.kt
Labels: Bug Fix

#3995 Backend: More Rendering Stuff for 1.21
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigGuiManager.kt
  src/main/java/at/hannibal2/skyhanni/config/core/config/gui/GuiPositionEditor.kt
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatSoundResponseConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dev/DebugConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/GuiConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/TabWidgetConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/ActionBarData.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/data/ElectionApi.kt
  src/main/java/at/hannibal2/skyhanni/data/FixedRateTimerManager.kt
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/MinecraftData.kt
  src/main/java/at/hannibal2/skyhanni/data/RenderData.kt
  src/main/java/at/hannibal2/skyhanni/data/WinterApi.kt
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
  src/main/java/at/hannibal2/skyhanni/events/ReceiveParticleEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatHistoryGui.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatSoundResponse.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/FerocityDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/HelpCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonApi.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/ReminderUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/TabWidgetDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/FixIronman.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/TimeFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/TpsCounter.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/BlockUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ConfigUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LorenzLogger.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkullTextureHolder.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/SkyhanniBaseScreen.kt
  versions/1.21.5/buildpaths.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/api/minecraftevents/RenderEvents.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinKeyboard.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/AccessorHandledScreen.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/compat/MouseCompat.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/WorldRenderUtils.kt
  versions/mapping-1.21.5-1.16.5-fabric.txt
Labels: Soon, Backend

#4009 Backend: Makes renderables and trackers work 1.21
  src/main/java/at/hannibal2/skyhanni/config/Features.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/ItemPickupLogConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/TrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/PlayerSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/data/ItemAddManager.kt
  src/main/java/at/hannibal2/skyhanni/data/ProfileStorageData.kt
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
  src/main/java/at/hannibal2/skyhanni/data/SlayerApi.kt
  src/main/java/at/hannibal2/skyhanni/data/model/TextInput.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/OpenLastStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/gifting/GiftApi.kt
  src/main/java/at/hannibal2/skyhanni/features/gifting/GiftProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SuperCraftFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/DraconicSacrificeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mountaintop/TimiteTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerType.kt
  src/main/java/at/hannibal2/skyhanni/test/command/CopyActionBarCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/command/CopyBossbarCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/command/CopyScoreboardCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphEditor.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderDisplayHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/RenderableCollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/InventoryCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/ScoreboardCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableTooltips.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/SearchTextInput.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/StringRenderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniTracker.kt
  versions/1.21.5/buildpaths.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/api/minecraftevents/RenderEvents.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinHandledScreen.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinMouse.java
  versions/1.21.5/src/test/kotlin/TestLegacyColorFormat.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#4012 Backend: SackApi, GardenApi, PestApi, FishingApi, some other misc features 1.21
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/api/GetFromSackApi.kt
  src/main/java/at/hannibal2/skyhanni/api/hypixelapi/HypixelLocationApi.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigManager.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/NextJacobContestConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/RewardWarningConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/SackDisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/data/PetApi.kt
  src/main/java/at/hannibal2/skyhanni/data/ProfileStorageData.kt
  src/main/java/at/hannibal2/skyhanni/data/SackApi.kt
  src/main/java/at/hannibal2/skyhanni/data/TitleManager.kt
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
  src/main/java/at/hannibal2/skyhanni/data/model/TextInput.kt
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/events/NeuProfileDataLoadedEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/minecraft/CharEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/tabcomplete/GetFromSacksTabComplete.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingApi.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/SeaCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishManager.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenPlotApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFGuideGui.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/EssenceShopHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/RenderableCollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/BaseGsonBuilder.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkyHanniTypeAdapters.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
  versions/1.21.5/buildpaths.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/TestingModFeatures.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinHandledScreen.java
  versions/1.21.5/src/test/kotlin/TestLegacyColorFormat.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#4016 Backend: Inventory Events + Graphs Working 1.21
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/data/EntityMovementData.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/OtherInventoryData.kt
  src/main/java/at/hannibal2/skyhanni/data/ScoreboardData.kt
  src/main/java/at/hannibal2/skyhanni/data/SlayerApi.kt
  src/main/java/at/hannibal2/skyhanni/data/TrackerManager.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/IslandExceptions.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/LineToMobHandler.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/ReminderUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobFarmingContestsInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/HypixelItemApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/IslandAreas.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/PatcherFixes.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/limbo/LimboTimeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/RiftApi.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mountaintop/TimiteTracker.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
  src/main/java/at/hannibal2/skyhanni/test/TestExportTools.kt
  src/main/java/at/hannibal2/skyhanni/test/command/CopyItemCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/EntityUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  versions/1.21.5/buildpaths.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinHandledScreen.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/WorldRenderUtils.kt
  versions/1.21.5/src/test/kotlin/TestLegacyColorFormat.kt
  versions/mapping-1.16.5-forge-1.8.9.txt
Labels: Soon, Backend

#4097 Backend: reverted changes
  src/main/java/at/hannibal2/skyhanni/features/misc/discordrpc/DiscordStatus.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/RiftApi.kt
  src/main/java/at/hannibal2/skyhanni/test/command/CopyItemCommand.kt
Labels: Soon, Backend

#4098 Backend: copy item format change
  src/main/java/at/hannibal2/skyhanni/test/command/CopyItemCommand.kt
Labels: Soon, Backend

#4037 Backend: CustomScoreboard and Galatea
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardConfigFix.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardConfigEventElement.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/UnknownLinesHandler.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventGalatea.kt
Labels: Soon, Backend

#4100 Improvement: Matriarch Helper v2
  src/main/java/at/hannibal2/skyhanni/config/features/crimsonisle/MatriarchHelperConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/model/Graph.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/MatriarchHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/navigation/NavigationUtils.kt
Labels: Soon

#1636 Feature: Changelog viewer
  src/main/java/at/hannibal2/skyhanni/config/commands/ComplexCommand.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/ChangelogJson.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/ChangeLogViewerScreen.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/ChangelogViewer.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/GuiOptionEditorUpdateCheck.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/UpdateManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/SkyhanniBaseScreen.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/StringRenderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/system/ModVersion.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon

#4006 Backend: cleanup /gfs logic
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
Labels: Soon, Backend

#4104 Fix: hypixel lobby pet consuambles chat
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Bug Fix

#4020 Backend: More files working, less lorenz utils existing 1.21
  src/main/java/at/hannibal2/skyhanni/data/BitsApi.kt
  src/main/java/at/hannibal2/skyhanni/data/EventCounter.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/features/FruitBowlFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardTips.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ArachneChatMessageHider.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/CompactExperimentRewards.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/CompactSplashPotionMessage.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/CrystalNucleusChatFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/PlayerDeathMessages.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/StashCompact.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/WatchdogHider.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ArmorStackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/SpidersDenApi.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/DragonFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/ArachneKillTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/mobs/ArachneSpawnTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/ShortenWarpCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/TransferCooldown.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/tabcomplete/WarpTabComplete.kt
  src/main/java/at/hannibal2/skyhanni/features/cosmetics/ArrowTrail.kt
  src/main/java/at/hannibal2/skyhanni/features/cosmetics/CosmeticFollowingLine.kt
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalQuickStart.kt
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalReminder.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCallWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityNpc.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/ReplaceHoppityWithContributor.kt
  src/main/java/at/hannibal2/skyhanni/features/event/winter/ReindrakeWarpHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingHookDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/SeaCreatureFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/ThunderSparksHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/TotemOfCorruption.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MarkedPlayerManager.kt
  versions/1.21.5/buildpaths.txt
Labels: Soon, Backend

#4106 Fix: TimiteHelper always showing soon
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonLividFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mountaintop/TimiteHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/ColoredBlockCompat.kt
  versions/mapping-1.16.5-forge-1.8.9.txt
Labels: Soon, Bug Fix

#4105 Fix: cleanup PowderChestTimer
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderChestTimer.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiIngameHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinGuiIngame.java
Labels: Bug Fix

#4109 Improvement: Next Egg Messages Stacking
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
Labels: Soon

#4028 Backend: Got more stuff working (im running out of pr names at this stage) 1.21
  src/main/java/at/hannibal2/skyhanni/config/UpdateKeybinds.kt
  src/main/java/at/hannibal2/skyhanni/config/features/combat/broodmother/BroodmotherConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/MayorOverlayConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/FlowstateHelperConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatHistoryGui.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/BroodmotherFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonCopilot.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/OdgerWaypoint.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishFillet.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/AtmosphericFilterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenYawAndPitch.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobContestFFNeededDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobContestTimeNeeded.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/CarrolynHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/GardenInventoryTooltipOverflow.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/LogBookStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/SprayFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/HighlightVisitorsOutsideOfGarden.kt
  src/main/java/at/hannibal2/skyhanni/features/gifting/UniqueGiftCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/gifting/UniqueGiftingOpportunitiesFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/BeaconPower.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/MayorOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ActiveBeaconEffect.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/BitsPerCookieVisual.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/CarnivalShopHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/DojoRankDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/FavoritePowerStone.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/FocusMode.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/SuperpairDataDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/EstimatedWardrobePrice.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/ChickenHeadTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/BlockStrengthGuide.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/KingTalismanHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigOptionGui.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/FirePillarDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/HellionShieldHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/enderman/EndermanSlayerHideParticles.kt
  src/main/java/at/hannibal2/skyhanni/features/stranded/HighlightPlaceableNpcs.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/MouseSensitivityHook.kt
  src/main/java/at/hannibal2/skyhanni/utils/ComputerTimeOffset.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/BlockCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/ItemCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/SkyhanniBaseScreen.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/ScrollInput.kt
  versions/1.21.5/buildpaths.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/TestingModFeatures.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinMouse.java
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#3842 Backend: EquipmentApi
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/EquipmentApi.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemCategory.kt
Labels: Soon, Backend

#4029 Backend: Custom Scoreboard + Render Entity Event 1.21
  src/main/java/at/hannibal2/skyhanni/api/minecraftevents/ClientEvents.kt
  src/main/java/at/hannibal2/skyhanni/api/minecraftevents/EntityEvents.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/LividFinderConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/ChunkedStatsConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/CustomScoreboardConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/DisplayConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/EventsConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/RenderData.kt
  src/main/java/at/hannibal2/skyhanni/events/SkyHanniRenderEntityEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/player/PlayerInteractionEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/MobFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggDisplayManager.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementBits.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementGems.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementIsland.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementParty.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementTitle.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventBroodmother.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventCarnival.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventDamage.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventDarkAuction.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventDojo.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventKuudra.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventMagmaBoss.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventTrapper.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventVoting.kt
  src/main/java/at/hannibal2/skyhanni/features/minion/MinionFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/HideArmor.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/summonings/SummoningMobManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/OSUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableTooltips.kt
  versions/1.21.5/buildpaths.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/hooks/EntityRenderDispatcherHook.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntityRenderDispatcher.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntityRenderer.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinGameRenderer.java
  versions/1.8.9/detekt/baseline.xml
  versions/pattern-mappings-1.16.5-forge-1.8.9.txt
Labels: Soon, Backend

#4111 Fix: Hitman Issues
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/data/CFDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/hitman/HitmanApi.kt
Labels: Bug Fix

#4113 Backend: The rendering part of 1.21.5
  src/main/java/at/hannibal2/skyhanni/data/mob/LineToMobHandler.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/FlareDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/event/yearoftheseal/BeachBallCatchHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/FireVeilWandParticles.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsWalls.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/NucleusBarriersBox.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/MatriarchHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/SulphurSkitterBox.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/snake/LivingCaveSnake.kt
  src/main/java/at/hannibal2/skyhanni/shader/RoundedShader.kt
  src/main/java/at/hannibal2/skyhanni/test/WorldEdit.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/render/LineDrawer.kt
  src/main/java/at/hannibal2/skyhanni/utils/render/QuadDrawer.kt
  src/main/java/at/hannibal2/skyhanni/utils/render/WorldRenderUtils.kt
  versions/1.21.5/buildpaths.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/api/minecraftevents/RenderEvents.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/events/minecraft/SkyHanniRenderWorldEvent.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/DeferredDrawer.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/LineDrawer.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/QuadDrawer.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/RenderPipelineDrawer.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/RoundedShapeDrawer.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/SkyHanniRenderLayers.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/SkyHanniRenderPipeline.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/WorldRenderUtils.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/layers/ChromaRenderLayer.kt
Labels: Soon, Backend

#4108 Backend: Cleanup in hoppity classes
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/summary/HoppityEventSummaryConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/summary/HoppityLiveDisplayConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/summary/HoppityEventSummary.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/summary/HoppityLiveDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/CFStats.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/stray/CFStrayTracker.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CollectionUtils.kt
Labels: Soon, Backend

#4123 Backend: random stuff
  src/main/java/at/hannibal2/skyhanni/events/render/BlockOverlayRenderEvent.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiIngameHook.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/ComponentUtils.kt
Labels: Soon, Backend

#4122 Improvement: Dont queued gfs on alpha
  src/main/java/at/hannibal2/skyhanni/api/GetFromSackApi.kt
Labels: Soon

#4118 Fix: ParticleHider Error
  src/main/java/at/hannibal2/skyhanni/features/misc/ParticleHider.kt
Labels: Bug Fix

#4114 Backend: Add Debug for PetStorageApi
  src/main/java/at/hannibal2/skyhanni/api/pet/PetStorageApi.kt
  src/main/java/at/hannibal2/skyhanni/data/PetData.kt
Labels: Soon, Backend

#4126 Fix: NoSuchElementException in PowderChestTimer
  src/main/java/at/hannibal2/skyhanni/features/mining/powdertracker/PowderChestTimer.kt
Labels: Bug Fix

#4128 Fix: Another Concurrency Check
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
Labels: Soon, Bug Fix

#4129 Fix: Custom Scoreboard Custom Image
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/RoundedShapeDrawer.kt
Labels: Soon, Bug Fix

#4132 Fix: Crash in Changelog Viewer and all other gui screens
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/SkyhanniBaseScreen.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Bug Fix

#4134 Fix: Item Renderable Scale
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
Labels: Soon, Bug Fix

#4136 Fix: Two custom wardrobe issues on modern
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinHandledScreen.java
Labels: Soon, Bug Fix

#4135 Feature: Moonglade beacon features
  src/main/java/at/hannibal2/skyhanni/config/features/foraging/ForagingConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/foraging/MoongladeBeaconConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/TabWidgetDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillType.kt
  src/main/java/at/hannibal2/skyhanni/utils/ModernPatterns.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/foraging/MoongladeBeacon.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/foraging/MoongladeBeaconWarning.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon

#3851 Backend: pickup log 9th slot
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
Labels: Soon, Backend

#4144 Fix: Various modern version fixes
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/data/OtherInventoryData.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/NeuNbtInfoJson.kt
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/BetterSignEditing.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/AccessorGuiEditSign.java
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SignUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/SkyhanniBaseScreen.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  versions/1.21.5/buildpaths-excluded.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinGameRenderer.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinHandledScreen.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinMinecraftClient.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/ComponentUtils.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/SkyHanniRenderPipeline.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/render/SkyHanniRenderPipelines.kt
  versions/1.21.5/src/main/resources/skyhanni.accesswidener
  versions/mapping-1.21.5-1.16.5-fabric.txt
Labels: Bug Fix

#3795 Feature + Fix: Hide co-op members from collections and fix Collection Api not detecting Co-op contributions
  src/main/java/at/hannibal2/skyhanni/api/CollectionApi.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/HideExCoopMembers.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
Labels: Soon, Bug Fix

#4131 Improvement: Visual Words on 1.21
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/ModifyVisualWords.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/AccessorMixinGuiNewChat.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinChatHud.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinTextHandler.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinTextRenderer.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/compat/OrdereredTextUtils.kt
  versions/1.21.5/src/main/resources/skyhanni.accesswidener
Labels: Soon

#4110 Fix + Backend: Farming Contest + EliteDevApi
  src/main/java/at/hannibal2/skyhanni/config/features/garden/NextJacobContestConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/local/JacobContestsJson.java
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/local/JacobContestsJson.kt
  src/main/java/at/hannibal2/skyhanni/events/WidgetUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/EliteDevApi.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/DialogUtils.kt
Labels: Soon, Bug Fix, Backend

#4146 Fix: Visitor Shopping List and potentially fix deadlock
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  versions/pattern-mappings-1.16.5-forge-1.8.9.txt
Labels: Soon, Bug Fix

#4079 Backend: CircularRenderable
  src/main/java/at/hannibal2/skyhanni/shader/CircleShader.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/CircularRenderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/shader/ShaderManager.kt
  src/main/resources/assets/skyhanni/shaders/circle.fsh
  src/main/resources/assets/skyhanni/shaders/circle.vsh
Labels: Soon, Backend

#4147 Fix: keybind migration having a seperate popup for every missing keybind
  src/main/java/at/hannibal2/skyhanni/config/UpdateKeybinds.kt
Labels: Bug Fix

#3956 Feature: Display current powder in HOTM perk tooltip
  src/main/java/at/hannibal2/skyhanni/config/features/mining/HotmConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/hotx/HotmData.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/CurrentPowderOnHotmPerk.kt
Labels: Soon

#3997 Fix: Incorrect Ability Detection for Wither Blades
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbility.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbilityCooldown.kt
Labels: Bug Fix

#4149 Fix: Carnival Zombie Shootout lamps not highlighting in 1.21.5
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalZombieShootout.kt
Labels: Bug Fix

#4086 Fix: Trapper Solver detecting dying mobs
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorSolver.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/trevor/TrevorTracker.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Bug Fix

#4150 Fix: Pet Data (For real real real real real real real this time)
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
Labels: Bug Fix

#4153 Fix: Add back message
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
Labels: Bug Fix

#4162 Fix: Keybind migration causing crashes
  src/main/java/at/hannibal2/skyhanni/config/UpdateKeybinds.kt
Labels: Soon, Bug Fix

#4166 Fix: Fixed Hide Armor in 1.21
  src/main/java/at/hannibal2/skyhanni/features/misc/HideArmor.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinRenderManager.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinArmorFeatureRenderer.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinHeadFeatureRenderer.java
Labels: Bug Fix

#4160 Fix: Another lot of 1.21 stuff
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/ItemResolutionQuery.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/EstimatedItemValueConfig.java
  src/main/java/at/hannibal2/skyhanni/data/title/TitleContext.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiContainerHook.kt
  src/main/java/at/hannibal2/skyhanni/test/PacketTest.kt
  src/main/java/at/hannibal2/skyhanni/utils/HolographicEntities.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/render/LineDrawer.kt
  src/main/java/at/hannibal2/skyhanni/utils/render/QuadDrawer.kt
  versions/1.21.5/buildpaths-excluded.txt
  versions/mapping-1.16.5-forge-1.8.9.txt
Labels: Soon, Bug Fix

#4115 Improvement: Disable soul sand speed logic on modern
  src/main/java/at/hannibal2/skyhanni/config/features/garden/laneswitch/FarmingLaneConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/MovementSpeedDisplay.kt
Labels: Soon

#4155 Improvement: Add starborn tab widget + Put new widgets in tab widget display
  .idea/dictionaries/default_user.xml
  src/main/java/at/hannibal2/skyhanni/data/model/TabWidget.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/TabWidgetDisplay.kt
Labels: Soon

#2508 Improvement: Zombie Shootout QOL
  src/main/java/at/hannibal2/skyhanni/config/features/event/carnival/ZombieShootoutConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalZombieShootout.kt
Labels: Soon, Waiting on Hypixel

#4159 Fix: Aaron's Mod + Meowdding + Any mod that uses custom colors compat
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinTextVisitFactory.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/compat/OrdereredTextUtils.kt
Labels: Bug Fix

#3882 Backend: Fix + Improvement; Chat History Highlight + Mouse Postion fixed
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatHistoryGui.kt
Labels: Soon, Backend

#4152 Feature: Foraging Tracker
  src/main/java/at/hannibal2/skyhanni/config/features/foraging/ForagingConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/foraging/ForagingTrackerConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandTypeTag.kt
  src/main/java/at/hannibal2/skyhanni/features/foraging/ForagingTrackerLegacy.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/foraging/ForagingTracker.kt
Labels: Soon

#4167 move mixins to 1.21 folder
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinArmorFeatureRenderer.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinHeadFeatureRenderer.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/render/MixinArmorFeatureRenderer.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/render/MixinHeadFeatureRenderer.java
Labels: Soon

#4168 Fix: Fix rendered text width calculation to include custom colours
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/compat/OrdereredTextUtils.kt
Labels: Bug Fix

#4170 Fix: Signal Enhancer in Foraging Tracker
  src/main/java/at/hannibal2/skyhanni/features/foraging/ForagingTrackerLegacy.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/foraging/ForagingTracker.kt
Labels: Bug Fix

#4175 Fix: Packet Received Event not being able to be cancelled
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinClientConnection.java
Labels: Bug Fix

#4177 Fix: Foraging Tracker
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/foraging/ForagingTracker.kt
Labels: Bug Fix

#4174 Feature: Mute phantoms in galatea
  src/main/java/at/hannibal2/skyhanni/config/features/foraging/ForagingConfig.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinSoundSystem.java
Labels: Soon

#4176 Fix: Cleanup with item stack nullables
  src/main/java/at/hannibal2/skyhanni/data/CropAccessoryData.kt
  src/main/java/at/hannibal2/skyhanni/events/InventoryFullyOpenedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/EquipmentApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/BlockNotSpawnable.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
Labels: Bug Fix

#4179 Fix: Zoombie Shootout colored lines only working when having hitboxes enabled
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalZombieShootout.kt
Labels: Bug Fix

#4185 Fix: Not posting the glow event on 1.21
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/RenderLivingEntityHelper.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinWorldRenderer.java
Labels: Bug Fix

#4187 fix: scoreboard galatea
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardConfigFix.kt
Labels: Bug Fix, Wrong Title/Changelog

#4196 Fix: new slayer areas
  src/main/java/at/hannibal2/skyhanni/data/SlayerApi.kt
Labels: Bug Fix

#4190 Fix: Melons showing as melon bloc
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/ComponentUtils.kt
  versions/mapping-1.16.5-forge-1.8.9.txt
Labels: Bug Fix

#4211 Fix: Rare crash with highlighted entities
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/RenderLivingEntityHelper.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Bug Fix

#4208 Backend: Made /sendcoords be actually registered as a command
  src/main/java/at/hannibal2/skyhanni/features/commands/SendCoordinatedCommand.kt
Labels: Soon, Backend

#4194 Fix: duplicate enum entries in CS
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardConfigFix.kt
Labels: Soon, Bug Fix

#4216 Backend: Skip Detekt on GH Build Workflow
  .github/workflows/build.yml
Labels: Soon, Backend

#4205 Fix: Hide vanilla enchants applying outside of SkyBlock
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinItemStack.java
Labels: Soon, Bug Fix

#4222 Backend: Fix Newlines in Regex Tests
  detekt/src/main/kotlin/RepoPatternElement.kt
  detekt/src/main/kotlin/style/InSkyBlockEarlyReturn.kt
Labels: Backend

#4189 Fix: Textured progress bars not working on modern
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Soon, Bug Fix

#4202 Fix: Token Shop Reading
  src/main/java/at/hannibal2/skyhanni/features/inventory/CarnivalShopHelper.kt
Labels: Soon, Bug Fix

#4191 Feature: Tree progress display
  src/main/java/at/hannibal2/skyhanni/config/features/foraging/ForagingConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/foraging/TreeProgressConfig.kt
  src/main/java/at/hannibal2/skyhanni/utils/ModernPatterns.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/foraging/TreeProgressDisplay.kt
Labels: Soon

#4217 Fix: Incompatibilities with some other mods rendering
  src/main/java/at/hannibal2/skyhanni/data/RenderData.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinGuiIngameForge.java
  versions/1.21.5/buildpaths-excluded.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/api/minecraftevents/RenderEvents.kt
Labels: Soon, Bug Fix

#4183 Improvement: Foraging Tracker now stays for a few seconds after swapping off an axe
  src/main/java/at/hannibal2/skyhanni/config/features/foraging/ForagingTrackerConfig.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/features/foraging/ForagingTracker.kt
Labels: Soon

#4209 Improvement: Make hide fire particles and hide blaze particles work
  src/main/java/at/hannibal2/skyhanni/features/misc/ParticleHider.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/AccessorChatComponentText.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/AccessorFontRenderer.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinBlockFire.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntityBlaze.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinRenderManager.java
  versions/1.21.5/buildpaths-excluded.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinBlockFire.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntityBlaze.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinArmorFeatureRenderer.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinHeadFeatureRenderer.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinRendererLivingEntity.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/renderer/MixinVertexConsumerProvider.java
  versions/mapping-1.16.5-forge-1.8.9.txt
Labels: Soon

#4218 Backend: Setup exclusive content for gradle
  root.gradle.kts
  settings.gradle.kts
Labels: Soon, Backend

#4223 Fix: cs error outside galatea
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventGalatea.kt
Labels: Bug Fix

#4219 Improvement + Fix: Add Rei plugin
  build.gradle.kts
  gradle/libs.versions.toml
  root.gradle.kts
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/customwardrobe/CustomWardrobeConfig.java
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/compat/ConfigModMenuInterop.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/compat/SkyHanniReiPlugin.kt
  versions/1.21.5/src/main/resources/fabric.mod.json
Labels: Soon, Bug Fix

#4228 Fix: Pumpkins were not carved on 1.21
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/ComponentUtils.kt
  versions/mapping-1.16.5-forge-1.8.9.txt
Labels: Soon, Bug Fix
