Repository hannibal002/SkyHanni, pull requests merged in 2025-04, with the labels that each got.

#3699 Fix: Tps
  src/main/java/at/hannibal2/skyhanni/features/misc/TpsCounter.kt
Labels: Bug Fix

#3692 Fix: Title Width
  src/main/java/at/hannibal2/skyhanni/data/TitleManager.kt
Labels: Bug Fix

#3700 Fix: chimera values
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/FixChimeraDescription.kt
Labels: Bug Fix

#3697 Improvement: Double Hook Rare Sea Creature Announcer
  src/main/java/at/hannibal2/skyhanni/features/fishing/SeaCreatureFeatures.kt
Labels: Soon

#3690 Fix: Cs LobbyCode Roomid showing twice
  src/main/java/at/hannibal2/skyhanni/data/MiningApi.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementLobbyCode.kt
Labels: Bug Fix

#3691 Fix: `KeyDownEvent` (again)
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
Labels: Bug Fix

#3693 Fix: RenderUtils boxes again
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Bug Fix

#3331 Improvement: Filter Legacy Items Warning
  src/main/java/at/hannibal2/skyhanni/config/features/chat/FilterTypesConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
Labels: Soon

#3704 Fix: Dragon Profit tracker overwriting edit commands for other Trackers
  src/main/java/at/hannibal2/skyhanni/features/combat/end/DragonFightAPI.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/DragonProfitTracker.kt
Labels: Bug Fix

#3706 Fix Loom?????????????????????????????????????????????????????????????…
  root.gradle.kts
Labels: Soon, Bug Fix

#3639 Backend + Improvement: Add twilight and shuriken to damage indicator
  src/main/java/at/hannibal2/skyhanni/config/features/combat/damageindicator/DamageIndicatorConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobDetection.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
Labels: Soon, Backend

#3713 Backend: Replace Blossom with KSP
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProcessor.kt
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProvider.kt
  build.gradle.kts
  root.gradle.kts
  settings.gradle.kts
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/tweaker/ModLoadingTweaker.java
  src/main/java/at/hannibal2/skyhanni/utils/system/PlatformUtils.kt
  versions/1.21.4/buildpaths.txt
Labels: Soon, Backend

#3711 Fix: copy-paste from signs adding extra characters on macOS
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiEditSign.java
Labels: Bug Fix

#3717 fix order of CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Bug Fix

#3718 Improvement: Cooldown on Base Camp Hotkey
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
Labels: Soon

#3236 Improvement: Hoppity Egg Timer De-Fuckification
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/events/hoppity/EggSpawnedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggDisplayManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/hitman/HitmanApi.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockTime.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CollectionUtils.kt
Labels: Soon

#3502 Improvement: Decouple Abiphone Hotkey from Hoppity Warning
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityCallWarningConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCallWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/AbiphoneFeatures.kt
Labels: Soon

#3708 Fix: Crop Icons Round Two
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenBestCropTime.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
Labels: Bug Fix

#3064 Backend: Allow Parameterless Handling of SkyHanniEvent(s)
  .live-plugins/event/plugin.kts
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProcessor.kt
  src/main/java/at/hannibal2/skyhanni/api/event/EventListeners.kt
  src/main/java/at/hannibal2/skyhanni/api/event/HandleEvent.kt
  src/main/java/at/hannibal2/skyhanni/api/event/SkyHanniEvents.kt
Labels: Soon, Backend

#3719 Backend: Improved /shdebugprice
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemPriceUtils.kt
Labels: Soon, Backend

#3077 Feature: Hitman Claim All Compact
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityChatConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEggsConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityUnclaimedEggsConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityWaypointsConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ResettableStorageSet.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggDisplayManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocations.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocator.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsShared.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/hitman/HitmanApi.kt
Labels: Soon

#3145 Improvement: Option to show Change in Counts in HoppityEventSummary
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEventSummaryConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FortuneStats.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CollectionUtils.kt
Labels: Soon

#3722 Backend: Fix Zero Parameter Consumer
  .live-plugins/event/plugin.kts
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProcessor.kt
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/PrimaryFunction.kt
  src/main/java/at/hannibal2/skyhanni/api/event/EventListeners.kt
  src/main/java/at/hannibal2/skyhanni/api/event/SkyHanniEvent.kt
  src/main/java/at/hannibal2/skyhanni/api/event/SkyHanniEvents.kt
  src/main/java/at/hannibal2/skyhanni/events/IslandChangeEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/minecraft/SkyHanniTickEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/minecraft/WorldChangeEvent.kt
Labels: Soon, Backend

#3703 Fix + Backend: TitleManager Improvements
  src/main/java/at/hannibal2/skyhanni/data/GardenCropMilestones.kt
  src/main/java/at/hannibal2/skyhanni/data/TitleManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/BurrowWarpHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenBestCropTime.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropMilestoneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ServerRestartTitle.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CollectionUtils.kt
Labels: Bug Fix, Backend

#2815 Backend: Bits Event
  src/main/java/at/hannibal2/skyhanni/config/storage/PlayerSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/data/BitsApi.kt
  src/main/java/at/hannibal2/skyhanni/data/FameRanks.kt
  src/main/java/at/hannibal2/skyhanni/events/BitsUpdateEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/NoBitsWarning.kt
Labels: Soon, Backend

#3725 Fix: Migrate sea emperror
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/SeaCreatureTracker.kt
Labels: Soon, Bug Fix

#3724 Backend: Default Function "Jump to Event Declaration"
  .live-plugins/deffunjumpr/plugin.kts
Labels: Soon, Backend

#3728 Fix: some patterns not using their actual group
  src/main/java/at/hannibal2/skyhanni/features/nether/RescueMissionWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/stranded/HighlightPlaceableNpcs.kt
Labels: Bug Fix

#3727 Fix: Null Issues in HoppityEventSummary
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
Labels: Bug Fix

#3689 Fix: Erroring from addCrimsonPrestige
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Bug Fix, Wrong Title/Changelog

#3726 Fix: Wrong Rabbit Barn Full Highlight
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBarnManager.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryInventory.kt
Labels: Bug Fix

#3705 Improvement: Option to enable Voidgloom Tracker in Dragon's Nest and made Dragon Tracker always render everything
  src/main/java/at/hannibal2/skyhanni/config/features/slayer/SlayerProfitTrackerConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/SlayerApi.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/DragonProfitTracker.kt
Labels: Soon

#3607 Backend: Remove Deprecated Function `addAsSingletonList`
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobContestFFNeededDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenBestCropTime.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/CruxTalismanDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/motes/ShowMotesNpcSellPrice.kt
  src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillProgress.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/RenderableCollectionUtils.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#3731 Backend: remove unused RenderUtils functions
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
Labels: Soon, Backend

#3629 Backend: Block Stuff, openInventoryName()
  src/main/java/at/hannibal2/skyhanni/data/BlockData.kt
  src/main/java/at/hannibal2/skyhanni/data/GuiData.kt
  src/main/java/at/hannibal2/skyhanni/data/ItemTipHelper.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerNameFormatter.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingApi.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/ThunderSparksHighlight.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/AuctionsHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarOrderHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/OreBlock.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/utils/BlockUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/NeuItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/BlockCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/MiscCompat.kt
  versions/mapping-1.16.5-fabric-1.16.5-forge.txt
  versions/mapping-1.16.5-forge-1.12.2.txt
  versions/mapping-1.21.4-1.16.5-fabric.txt
  versions/pattern-mappings-1.16.5-forge-1.12.2.txt
Labels: Soon, Backend

#3242 Feature: All-Time Hoppity Stats
  src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEventSummaryLiveDisplayConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityApi.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/AtmosphericFilterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockTime.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyblockSeason.kt
Labels: Soon

#3730 Backend: Cache getSlayerTypeForCurrentArea
  src/main/java/at/hannibal2/skyhanni/data/SlayerApi.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerQuestWarning.kt
Labels: Soon, Backend

#3729 Fix: Bits chat message
  src/main/java/at/hannibal2/skyhanni/config/features/misc/BitsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/NoBitsWarning.kt
Labels: Bug Fix

#3720 Backend: command /shdebugrecentitemadds
  src/main/java/at/hannibal2/skyhanni/data/ItemAddManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CollectionUtils.kt
Labels: Soon, Backend

#3733 Fix: area detection in glacite tunnels
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
Labels: Bug Fix

#3702 Backend: Bump ModAPI Version
  gradle/libs.versions.toml
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinHypixelForgeModApi.java
Labels: Soon, Backend

#3740 Fix: Hitman Threshold
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsCompactChat.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/hitman/HitmanApi.kt
Labels: Bug Fix

#3746 Fix: Fixed Lobby Easter Egg Waypoints
  src/main/java/at/hannibal2/skyhanni/config/features/event/waypoints/EasterEggConfig.java
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/easter/EasterEgg.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/easter/EggEntrance.kt
Labels: Bug Fix

#3744 Fix: revenant slayer detection
  src/main/java/at/hannibal2/skyhanni/data/SlayerApi.kt
Labels: Bug Fix

#3743 Fix: Lane Switch Title Weights
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneFeatures.kt
Labels: Bug Fix

#3745 Fix: Attribute Overlay not respecting list with Highlight Good Rolls off
  src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/AttributeOverlay.kt
Labels: Bug Fix

#2593 Feature: Mayor Overlay
  src/main/java/at/hannibal2/skyhanni/config/enums/OutsideSBFeature.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/GUIConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/MayorOverlayConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/ElectionApi.kt
  src/main/java/at/hannibal2/skyhanni/data/MayorData.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/MayorOverlay.kt
Labels: Soon

#2541 Feature: Accept Last Party Invite
  src/main/java/at/hannibal2/skyhanni/config/features/commands/CommandsConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/AcceptLastPartyInvite.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
Labels: Soon

#2509 Feature: Bonus Pest Chance Display
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestsConfig.java
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/BonusPestChanceDisplay.kt
Labels: Soon

#3616 Feature: Added option to make tooltips from SkyHanni transparent
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
Labels: Soon

#3742 Backend: GUI -> Gui
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/Features.kt
  src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/FarmingFortuneConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/SensitivityReducerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/gui/GuiConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/TextBoxConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/rift/PunchcardConfig.java
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatPeek.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/SensitivityReducer.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/ToolTooltipTweaks.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFGuideGui.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FarmingItems.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FortuneStats.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CustomTextBox.kt
  src/main/java/at/hannibal2/skyhanni/utils/guide/GuideGui.kt
  src/main/java/at/hannibal2/skyhanni/utils/guide/GuideTab.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
Labels: Soon, Backend

#3675 Backend: Begin preparing for modern rendering
  CONTRIBUTING.md
  src/main/java/at/hannibal2/skyhanni/api/minecraftevents/RenderEvents.kt
  src/main/java/at/hannibal2/skyhanni/data/GuiEditManager.kt
  src/main/java/at/hannibal2/skyhanni/data/RenderData.kt
  src/main/java/at/hannibal2/skyhanni/events/DrawScreenAfterEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/GuiContainerEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/GuiRenderEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/GuiRenderItemEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/RenderGuiItemOverlayEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/minecraft/SkyHanniRenderWorldEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/render/gui/DrawBackgroundEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/render/gui/GameOverlayRenderPostEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/render/gui/GameOverlayRenderPreEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/render/gui/RenderingTickEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/render/gui/ScreenDrawnEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chroma/ChromaManager.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiContainerHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/RenderItemHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntityRenderer.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinRenderItem.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiContainer.java
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/DrawContext.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/MatrixStack.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/WorldRenderContext.kt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/utils/compat/DrawContext.kt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/utils/compat/MatrixStack.kt
  versions/1.21.4/src/main/java/at/hannibal2/skyhanni/utils/compat/WorldRenderContext.kt
  versions/mapping-1.16.5-forge-1.12.2.txt
  versions/mapping-1.21.4-1.16.5-fabric.txt
Labels: Soon, Backend

#3736 Backend: refractor some events
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
  src/main/java/at/hannibal2/skyhanni/data/FriendApi.kt
  src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
  src/main/java/at/hannibal2/skyhanni/data/ProfileStorageData.kt
  src/main/java/at/hannibal2/skyhanni/events/garden/GardenToolChangeEvent.kt
  src/main/java/at/hannibal2/skyhanni/events/hypixel/HypixelJoinEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingFortuneDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenOptimalSpeed.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenYawAndPitch.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/SensitivityReducer.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/DicerRngDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropSpeed.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/WrongFungiCutterWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/AutoJoinSkyblock.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/limbo/LimboTimeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/ModifyVisualWords.kt
Labels: Soon, Backend

#3750 Backend + Fix: Crash on wrong config link
  src/main/java/at/hannibal2/skyhanni/config/core/config/Position.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestsConfig.java
Labels: Soon, Bug Fix, Backend

#3749 Backend: Rename ChatFilterGui -> ChatHistoryGui
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatHistoryGui.kt
Labels: Soon, Backend

#3738 Improvement: Improve accuracy of estimated item value calculator and improve consistency of the display
  src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
Labels: Soon

#3752 Fix: Item NBT Data not saving in config (/ff or wardrobe)
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFGuideGui.kt
Labels: Bug Fix

#3758 Fix: Disable Fix Ghost Entities in Kuudra
  src/main/java/at/hannibal2/skyhanni/features/misc/FixGhostEntities.kt
Labels: Bug Fix

#2778 Feature: Block Strength
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/core/config/gui/GuiPositionEditor.kt
  src/main/java/at/hannibal2/skyhanni/data/MiningApi.kt
  src/main/java/at/hannibal2/skyhanni/data/OtherInventoryData.kt
  src/main/java/at/hannibal2/skyhanni/data/ScreenData.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/MiningJson.kt
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
  src/main/java/at/hannibal2/skyhanni/events/InventoryCloseEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/BlockStrengthGuide.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/OreBlock.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CollectionUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/RenderableUtils.kt
Labels: Soon

#3732 Backend: Wool Compat, String Utils, Inventory Name stuffs
  src/main/java/at/hannibal2/skyhanni/api/SkillApi.kt
  src/main/java/at/hannibal2/skyhanni/config/ConfigGuiManager.kt
  src/main/java/at/hannibal2/skyhanni/config/core/config/Position.kt
  src/main/java/at/hannibal2/skyhanni/data/hypixel/chat/PlayerNameFormatter.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/playerchat/PlayerChatModifier.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonLividFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonTeammateOutlines.kt
  src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalQuickStart.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityApi.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityRabbitTheFishChecker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/WarpMenuUniques.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/FarmingMilestoneCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/CarnivalShopHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/EssenceShopHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/hitman/HitmanSlots.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/UserLuckBreakdown.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/limbo/LimboPlaytime.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/BlockNotSpawnable.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiChatHook.kt
  src/main/java/at/hannibal2/skyhanni/utils/ComponentMatcherUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/BlockCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  versions/1.21.4/buildpaths.txt
  versions/mapping-1.16.5-fabric-1.16.5-forge.txt
  versions/mapping-1.16.5-forge-1.12.2.txt
Labels: Soon, Backend

#3760 Fix: Accept Last Invite making parties completely un-joinable
  src/main/java/at/hannibal2/skyhanni/features/commands/AcceptLastPartyInvite.kt
Labels: Bug Fix

#3759 Fix: Titles Stuck
  src/main/java/at/hannibal2/skyhanni/data/TitleManager.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/lane/FarmingLaneFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/ServerRestartTitle.kt
Labels: Bug Fix

#3343 Feature: Pest Spawn Cooldown Display and Warning
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestTimerConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/PestTimerConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestSpawn.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestSpawnTimer.kt
  src/main/java/at/hannibal2/skyhanni/utils/TimeUtils.kt
Labels: Soon

#3756 Improvement: Thunderstorm is never ever ready again
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonChatFilter.kt
Labels: Soon

#3748 Backend: Fix repo chat message format
  src/main/java/at/hannibal2/skyhanni/data/repo/RepoManager.kt
Labels: Soon, Backend

#3754 Fix: Highlight Fels Skull
  src/main/java/at/hannibal2/skyhanni/data/EntityMovementData.kt
  src/main/java/at/hannibal2/skyhanni/events/entity/EntityMoveEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHideItems.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonMobManager.kt
Labels: Soon, Bug Fix

#3415 Backend: More event debugging
  src/main/java/at/hannibal2/skyhanni/api/event/EventHandler.kt
  src/main/java/at/hannibal2/skyhanni/api/event/SkyHanniEvents.kt
Labels: Soon, Backend

#3753 Backend: renamed class name
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/CropType.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFGuideGui.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFInfos.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FFStats.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FarmingItemType.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/FortuneUpgrades.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/CropPage.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/OverviewPage.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/pages/UpgradePage.kt
Labels: Soon, Backend

#2149 Feature: Copy Chat
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatCopy.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatHistoryGui.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/CompactBestiaryChatMessage.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/ChatLineData.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiChatHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/AccessorMixinGuiNewChat.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinChatLine.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiNewChat.java
  src/main/java/at/hannibal2/skyhanni/utils/ChatUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
Labels: Soon

#3715 Improvement: Stereo Harmony Crop Icons
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/StereoHarmonyConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/StereoHarmonyConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestApi.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestType.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/stereo/StereoHarmonyDiscReplacer.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/stereo/StereoHarmonyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/stereo/VinylType.kt
Labels: Soon

#3678 Backend: Use DrawContext in GuiRenderUtils
  src/main/java/at/hannibal2/skyhanni/config/core/config/gui/GuiPositionEditor.kt
  src/main/java/at/hannibal2/skyhanni/data/ItemTipHelper.kt
  src/main/java/at/hannibal2/skyhanni/data/NotificationManager.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatHistoryGui.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/FlareDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCallWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/stray/CFStrayWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/TabListRenderer.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/massconfiguration/DefaultConfigOptionGui.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/VisualWordGui.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/guide/GuideGui.kt
Labels: Soon, Backend

#3340 Feature: Cake Counter features
  src/main/java/at/hannibal2/skyhanni/config/features/misc/CakeCounterConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/CakeCounterFeatures.kt
Labels: Soon

#3761 Backend: Cleanup CopyChat
  src/main/java/at/hannibal2/skyhanni/api/minecraftevents/RenderEvents.kt
  src/main/java/at/hannibal2/skyhanni/events/render/gui/GuiMouseInputEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/CopyChat.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/ChatLineData.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/GuiScreenUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/system/PlatformUtils.kt
Labels: Soon, Backend

#3679 Backend: Use DrawContext instead of GlStateManager
  src/main/java/at/hannibal2/skyhanni/data/HighlightOnHoverSlot.kt
  src/main/java/at/hannibal2/skyhanni/data/TitleManager.kt
  src/main/java/at/hannibal2/skyhanni/features/anvil/AnvilCombineHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardTips.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/CroesusChestTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCollectionStats.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityNpc.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityRabbitTheFishChecker.kt
  src/main/java/at/hannibal2/skyhanni/features/fame/CityProjectFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/GardenComposterInventoryFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobFarmingContestsInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenPlotMenuHighlighting.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorRewardWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/MovableHotBar.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/MovableXPBar.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ActiveBeaconEffect.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/AuctionsHighlighter.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/FavoritePowerStone.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HideNotClickableItems.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HighlightBonzoMasks.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/PowerStoneGuideFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/QuickCraftFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ReforgeHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/RngMeterInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SkyblockGuideHighlightFeature.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/StatsTuning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/bazaar/BazaarOrderHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/CFInventory.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/stray/CFStrayWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/ColdOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/HotmFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/solver/FossilSolverDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/AuctionHousePriceComparison.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/QuickModMenuSwitch.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/TabWidgetSettings.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/TabListRenderer.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/visualwords/VisualWordGui.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/westvillage/kloon/KloonHacking.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/EnigmaSoulWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/everywhere/HighlightRiftGuide.kt
  src/main/java/at/hannibal2/skyhanni/features/stranded/HighlightPlaceableNpcs.kt
  src/main/java/at/hannibal2/skyhanni/test/HighlightMissingRepoItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/guide/GuideGui.kt
  src/main/java/at/hannibal2/skyhanni/utils/guide/GuidePage.kt
  src/main/java/at/hannibal2/skyhanni/utils/guide/GuideRenderablePage.kt
Labels: Soon, Backend

#3762 Improvement: Keep trophy fish symbol in custom catch messages
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishMessages.kt
Labels: Soon

#2898 Feature: Custom Scoreboard Number Gain
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/DisplayConfig.java
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardConfigFix.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardNumberTrackingElement.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardUtils.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementBits.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementCopper.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementMotes.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementPurse.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementSoulflow.kt
Labels: Soon

#3024 Feature + Backend: EffectApi V2
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/CFConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/data/effect/EffectApi.kt
  src/main/java/at/hannibal2/skyhanni/data/effect/NonGodPotEffect.kt
  src/main/java/at/hannibal2/skyhanni/events/effects/EffectDurationChangeEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/CFBlockOpen.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/NonGodPotEffectDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/effects/NonGodPotEffectDisplay.kt
Labels: Soon, Backend

#3765 Fix: cs number tracking not using the config, crash when parsing Long
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboardNumberTrackingElement.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementCopper.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementMotes.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/elements/ScoreboardElementSoulflow.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/WardrobeApi.kt
Labels: Bug Fix

#3768 Fix: Title Watchdog
  src/main/java/at/hannibal2/skyhanni/api/event/EventListeners.kt
  src/main/java/at/hannibal2/skyhanni/data/TitleManager.kt
Labels: Bug Fix

#3764 Fix: NPE in SlotClickEvent
  src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobFarmingContestsInventory.kt
Labels: Bug Fix

#3767 Fix: Chatting Crash
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.kt
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/GuiChatHook.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinChatLine.java
Labels: Bug Fix

#3772 Backend: cleanup in HolographicEntities
  src/main/java/at/hannibal2/skyhanni/utils/HolographicEntities.kt
Labels: Soon, Backend

#3773 Fix: Reputation Helper faction missing
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
Labels: Bug Fix

#3771 Improvement: estimated armor value and custom wardrobe
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/CustomWardrobe.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/EstimatedWardrobePrice.kt
Labels: Soon

#3770 Fix: Dungeon Starred Fel always highlight
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonMobManager.kt
Labels: Bug Fix

#3779 Backend: Fix type in CONTRIBUTING
  CONTRIBUTING.md
Labels: Backend

#3784 Fix: Remove redundant space in ultra-rare discovery message
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsDryStreakDisplay.kt
Labels: Bug Fix

#3780 Backend: Better visitor config access
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorTimer.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/HighlightVisitorsOutsideOfGarden.kt
Labels: Backend

#3785 Fix: Titles
  src/main/java/at/hannibal2/skyhanni/data/TitleManager.kt
Labels: Bug Fix

#3769 Backend: Cleaner errors
  src/main/java/at/hannibal2/skyhanni/api/event/EventHandler.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
Labels: Soon, Backend

#3786 Improvement: Enable all trackers
  src/main/java/at/hannibal2/skyhanni/config/features/fishing/SeaCreatureTrackerConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/DicerRngDropTrackerConfig.java
  src/main/java/at/hannibal2/skyhanni/features/combat/end/DragonProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/end/endernodetracker/EnderNodeTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/ghosttracker/GhostTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/SeaCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/ArmorDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/DicerRngDropTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/stray/CFStrayTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/mountaintop/TimiteTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerProfitTracker.kt
Labels: Soon

#3778 Feature: Outside Sack Value
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/sacks/OutsideSackValueConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/SackApi.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/SackDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/sacks/OutsideSackValue.kt
  src/main/java/at/hannibal2/skyhanni/utils/NumberUtil.kt
  src/main/java/at/hannibal2/skyhanni/utils/collection/CollectionUtils.kt
Labels: Soon

#3794 Backend: Update changelog builder
  buildSrc/build.gradle.kts
Labels: Backend

#3796 Fix: Outdated Mixin + Typo
  src/main/java/at/hannibal2/skyhanni/data/effect/NonGodPotEffect.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/CFBlockOpen.kt
Labels: Bug Fix

#3798 Fix: Change tablist error time to 3 seconds
  src/main/java/at/hannibal2/skyhanni/data/ProfileStorageData.kt
Labels: Bug Fix

#3782 Backend: Create SlayerApi.config
  src/main/java/at/hannibal2/skyhanni/data/SlayerApi.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/BlockNotSpawnable.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/HideMobNames.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerBossSpawnSoon.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerItemsOnGround.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerMiniBossFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerQuestWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerRngMeterDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/VampireSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/BlazeSlayerClearView.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/BlazeSlayerDaggerHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/BlazeSlayerFirePitsWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/FirePillarDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/blaze/HellionShieldHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/enderman/EndermanSlayerFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/enderman/EndermanSlayerHideParticles.kt
Labels: Soon, Backend

#3777 Backend: Add detekt rule to stop messing with imports
  detekt/detekt.yml
  detekt/src/main/kotlin/imports/CustomImportOrdering.kt
  detekt/src/main/kotlin/imports/ImportOrdering.kt
  detekt/src/main/kotlin/imports/ImportRuleSetProvider.kt
  detekt/src/main/kotlin/imports/PreprocessingImportOrdering.kt
  src/main/java/at/hannibal2/skyhanni/utils/TabListData.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Backend

#3789 Backend: Various Todos
  src/main/java/at/hannibal2/skyhanni/data/TitleManager.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/DianaProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/event/diana/MythologicalCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/FishingProfitTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/FarmingWeightDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/MineshaftPityDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
  src/main/java/at/hannibal2/skyhanni/utils/RenderDisplayHelper.kt
Labels: Soon, Backend

#3774 Backend: Update to 1.21.5
  CONTRIBUTING.md
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  root.gradle.kts
  sharedVariables/src/MinecraftVersion.kt
  sharedVariables/src/ProjectTarget.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/EntityCompat.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/TextCompat.kt
  versions/1.21.5/buildpaths-test.txt
  versions/1.21.5/buildpaths.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/SkyHanniModLoader.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/TestingModFeatures.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/api/minecraftevents/ClientEvents.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/api/minecraftevents/EntityEvents.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/api/minecraftevents/RenderEvents.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/config/commands/SimpleCommand.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/init/BeforeForLoopInjectionPoint.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinClientConnection.java
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/test/hotswap/HotswapSupport.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/test/hotswap/HotswapSupportImpl.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/FakePlayer.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/NeuCalculator.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/compat/DrawContext.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/compat/MatrixStack.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/utils/compat/WorldRenderContext.kt
  versions/1.21.5/src/main/resources/fabric.mod.json
  versions/1.21.5/src/main/resources/mixins.skyhanni.json
  versions/1.21.5/src/main/resources/skyhanni.accesswidener
  versions/1.21.5/src/test/kotlin/TestLegacyColorFormat.kt
  versions/1.21.5/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
  versions/mapping-1.21.5-1.16.5-fabric.txt
  versions/pattern-mappings-1.21.5-1.16.5-fabric.txt
Labels: Soon, Backend

#3710 Backend + Improvement: Fruit Bowl + Visitor Drops
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/DropsStatisticsConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/DropsStatisticsConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorDropStatistics.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorReward.kt
Labels: Soon, Backend

#2514 Feature: Spirit leap overlay
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/DungeonConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/dungeon/SpiritLeapConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonApi.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonRankTabListColor.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonSpiritLeapOverlay.kt
Labels: Soon

#3681 Improvement: Bold perfect enchantments
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/EnchantParsingConfig.java
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/Enchant.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
Labels: Soon, Wrong Title/Changelog

#3816 Backend: re-allow backticks
  buildSrc/build.gradle.kts
Labels: Backend

#3817 Fix + Backend: shortened party commands
  src/main/java/at/hannibal2/skyhanni/data/PartyApi.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/PartyCommands.kt
Labels: Bug Fix, Backend

#3491 Feature: Current Chat Display
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/storage/PlayerSpecificStorage.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/BingoBoopParty.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/CurrentChatDisplay.kt
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinGuiChat.java
  src/main/java/at/hannibal2/skyhanni/utils/EnumUtils.kt
Labels: Soon

#3235 Feature: Compact Jacob Claim
  src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.kt
  src/main/java/at/hannibal2/skyhanni/events/garden/contests/rewards/ContestRewardsClaimedEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/CompactJacobClaim.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/AnitaMedalProfit.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/CropType.kt
Labels: Soon

#3797 Backend: format files in features
  src/main/java/at/hannibal2/skyhanni/features/bingo/BingoBoopParty.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/BestiaryData.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggLocations.kt
  src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/events/ScoreboardEventMining.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/HighlightMiningCommissionMobs.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsWalls.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/JoinCrystalHollows.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/NoBitsWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/update/UpdateManager.kt
Labels: Soon, Backend

#3814 Fix: Slayer features broken in End
  src/main/java/at/hannibal2/skyhanni/config/features/slayer/SlayerProfitTrackerConfig.kt
  src/main/java/at/hannibal2/skyhanni/data/SlayerApi.kt
Labels: Bug Fix

#3813 Backend: /shdebug warns for wrong graph data
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandType.kt
Labels: Soon, Backend

#3524 Feature: Shortened /warp command
  src/main/java/at/hannibal2/skyhanni/config/features/commands/CommandsConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/ShortenWarpCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/tabcomplete/WarpTabComplete.kt
Labels: Soon, Wrong Title/Changelog

#3808 Backend: Correct CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Soon, Backend

#3818 Fix: Composter empty warning!
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterDisplay.kt
Labels: Bug Fix

#3812 Improvement: Treasure Hook Detection
  src/main/java/at/hannibal2/skyhanni/features/fishing/FishingApi.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/tracker/SeaCreatureTracker.kt
  src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/TrophyFishDisplay.kt
Labels: Soon

#3807 Improvement: Ghost Leap Overlay
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonApi.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonSpiritLeapOverlay.kt
Labels: Soon

#3806 Improvement: Add Harvest Harbinger V to Visitor Rewards
  src/main/java/at/hannibal2/skyhanni/config/features/garden/visitor/DropsStatisticsConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/VisitorReward.kt
Labels: Soon

#3815 Improvement + Fix: Added pathfind support for lobby eastereggs
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/easter/EasterEggWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/halloween/HalloweenBasketWaypoints.kt
  versions/1.8.9/detekt/baseline.xml
Labels: Soon, Bug Fix

#3820 Improvement: Independent 6th visitor reminder
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorTimer.kt
Labels: Soon

#3821 Fix: ChromaColour Alpha
  src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
Labels: Bug Fix

#3348 Feature: Trade Value Overlay.
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/inventory/TradeConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/ChestValue.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/TradeValue.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Soon

#3823 Fix: Critical Bug with Trackers
  src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniItemTracker.kt
Labels: Soon, Bug Fix

#3827 Fix: Composter empty outside garden
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterDisplay.kt
Labels: Bug Fix

#3792 Backend: Added Server ticks alive to Entity Data
  src/main/java/at/hannibal2/skyhanni/data/MinecraftData.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/EntityData.kt
Labels: Soon, Backend

#3826 Backend: Cleanup Current Chat Display
  src/main/java/at/hannibal2/skyhanni/features/chat/CurrentChatDisplay.kt
Labels: Soon, Backend

#3822 Improvement: Block Strength Mining Speed Until Next Tick
  src/main/java/at/hannibal2/skyhanni/features/mining/BlockStrengthGuide.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/OreBlock.kt
Labels: Soon

#3412 Backend: Use more SimpleTimeMark
  src/main/java/at/hannibal2/skyhanni/data/MinecraftData.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/PlayerDeathMessages.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/FlareDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageCounter.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/EntityData.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/EntityResult.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/MobFinder.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/OldDamage.kt
  src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonHideItems.kt
  src/main/java/at/hannibal2/skyhanni/features/event/anniversary/Year300RaffleEvent.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/WrongFungiCutterWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/stray/CFStrayWarning.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbility.kt
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbilityCooldown.kt
  src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SimpleTimeMark.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockTime.kt
Labels: Backend

#3828 Fix: Golden Goblin Line
  src/main/java/at/hannibal2/skyhanni/data/mob/LineToMobHandler.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/GoldenGoblinHighlight.kt
Labels: Bug Fix

#3557 Backend: Fixed up searchable table Renderable
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
  src/main/java/at/hannibal2/skyhanni/utils/renderables/Searchable.kt
Labels: Soon, Backend

#3835 Backend: Make CleanupMappingFiles only modify changed files
  annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProcessor.kt
  buildSrc/src/main/kotlin/skyhannibuildsystem/CleanupMappingFiles.kt
  versions/mapping-1.16.5-forge-1.12.2.txt
Labels: Soon, Backend

#3834 Fix: Ability Cooldown format
  src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbility.kt
  src/main/java/at/hannibal2/skyhanni/utils/NumberUtil.kt
Labels: Bug Fix

#3832 Fix: Composter Display update
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterDisplay.kt
Labels: Bug Fix

#3829 Fix: Computer Time Offset
  src/main/java/at/hannibal2/skyhanni/utils/ComputerTimeOffset.kt
  src/main/java/at/hannibal2/skyhanni/utils/EnumUtils.kt
Labels: Bug Fix

#3831 Fix: Composter upgrade flickering
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
Labels: Bug Fix

#3776 Backend: Nbt Compat for 1.21.5
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/compat/NbtCompat.kt
  versions/1.21.5/buildpaths.txt
  versions/pattern-mappings-1.21.5-1.16.5-fabric.txt
Labels: Soon, Backend

#3810 Backend: Closed inventory name
  src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
  src/main/java/at/hannibal2/skyhanni/config/core/config/gui/GuiPositionEditor.kt
  src/main/java/at/hannibal2/skyhanni/data/OtherInventoryData.kt
  src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
Labels: Soon, Backend

#3449 Feature: Frog Mask Warning
  src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
  src/main/java/at/hannibal2/skyhanni/config/features/misc/frogmask/FrogMaskFeaturesConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/misc/frogmask/FrogMaskWarningConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/FrogMaskDisplay.kt
  src/main/java/at/hannibal2/skyhanni/features/misc/FrogMaskFeatures.kt
Labels: Soon

#3802 Fix + Backend: `KeyDownEvent` (again)
  src/main/java/at/hannibal2/skyhanni/events/minecraft/KeyUpEvent.kt
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
Labels: Bug Fix, Backend

#3837 Fix: User Luck in wrong item lore + pet luck in breakdown
  src/main/java/at/hannibal2/skyhanni/features/misc/UserLuckBreakdown.kt
Labels: Soon, Bug Fix

#3838 Fix: Add pure quartz to flowstate helper
  src/main/java/at/hannibal2/skyhanni/features/mining/BlockStrengthGuide.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/OreBlock.kt
Labels: Bug Fix

#3468 Backend: Matrix class Cleanup
  src/main/java/at/hannibal2/skyhanni/utils/Matrix.kt
  src/main/java/at/hannibal2/skyhanni/utils/PolynomialFitter.kt
Labels: Soon, Backend

#3848 Fix: Typos in time offset
  src/main/java/at/hannibal2/skyhanni/utils/ComputerTimeOffset.kt
Labels: Bug Fix

#3855 Fix: 2 Custom Scoreboard Patterns
  src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardPattern.kt
Labels: Bug Fix

#3859 Backend: Post keyboard events on 1.21
  src/main/java/at/hannibal2/skyhanni/utils/KeyboardManager.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinKeyboard.java
Labels: Backend

#3860 Backend: Fill out ClientEvents in 1.21
  versions/1.21.5/buildpaths.txt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/api/minecraftevents/ClientEvents.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/hooks/MessageHandlerHook.kt
  versions/1.21.5/src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinMessageHandler.java
  versions/1.21.5/src/main/resources/skyhanni.accesswidener
Labels: Backend

#3840 Fix: Don't override /jerry on private island
  src/main/java/at/hannibal2/skyhanni/features/commands/ShortenWarpCommand.kt
Labels: Bug Fix

#3850 Fix: Fetch Quest Misdetection
  src/main/java/at/hannibal2/skyhanni/features/nether/reputationhelper/dailyquest/DailyQuestHelper.kt
Labels: Soon, Bug Fix

#3852 Backend: event execution time regression
  src/main/java/at/hannibal2/skyhanni/api/event/EventListeners.kt
  src/main/java/at/hannibal2/skyhanni/api/event/SkyHanniEvents.kt
  src/main/java/at/hannibal2/skyhanni/test/command/ErrorManager.kt
  src/main/java/at/hannibal2/skyhanni/utils/ReflectionUtils.kt
Labels: Soon, Backend

#3861 Fix: ChatHistoryGui
  src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/ChatHistoryGui.kt
Labels: Soon, Bug Fix

#3862 Fix: Composter overlay always showing
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
Labels: Soon, Bug Fix

#3858 Fix: ViewRecipe Command for certain items
  src/main/java/at/hannibal2/skyhanni/features/commands/ViewRecipeCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorFeatures.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorSupercraft.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/craft/CraftableItemList.kt
  src/main/java/at/hannibal2/skyhanni/utils/HypixelCommands.kt
  src/main/java/at/hannibal2/skyhanni/utils/NeuInternalName.kt
Labels: Soon, Bug Fix

#3853 Fix: Effects not being detected in "Active Effects" inventory
  src/main/java/at/hannibal2/skyhanni/data/effect/EffectApi.kt
Labels: Soon, Bug Fix
