Repository hannibal002/SkyHanni, pull requests merged in 2025-08, with the labels that each got.

#4527 Improvement: item performance boosts
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/ItemStackCachedData.java
  src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinItemStack.java
  src/main/java/at/hannibal2/skyhanni/utils/CachedItemData.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
Labels: Soon

#4540 Fix: Enchanted Book Drop Message Changer (On Alpha)
  src/main/java/at/hannibal2/skyhanni/config/features/chat/RareDropMessagesConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
Labels: Bug Fix

#4521 Fix: Slayer dropped books having both a Hypixel and SH message
  src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
Labels: Bug Fix

#4539 Improvement: less lags
  src/main/java/at/hannibal2/skyhanni/api/StorageApi.kt
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
Labels: Soon

#4529 Fix: Naga Charm Detection
  src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/AttributeShardsData.kt
Labels: Bug Fix

#4535 Fix: Wilted Berberis Helper ghost waypoints
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/RiftWiltedBerberisHelper.kt
Labels: Bug Fix

#4546 Fix: RenderLivingEntityHelper Concurrent Error
  src/main/java/at/hannibal2/skyhanni/mixins/hooks/RenderLivingEntityHelper.kt
Labels: Bug Fix

#4548 Fix: Cake Tracker cache error
  src/main/java/at/hannibal2/skyhanni/features/inventory/caketracker/CakeTracker.kt
Labels: Bug Fix

#4550 Backend: Fix pet lvl 0
  src/main/java/at/hannibal2/skyhanni/utils/PetUtils.kt
Labels: Soon, Backend

#4549 Backend: hypixel no sound sound info
  src/main/java/at/hannibal2/skyhanni/config/features/mining/FlowstateHelperConfig.kt
  src/main/java/at/hannibal2/skyhanni/config/features/mining/glacite/MineshaftPityDisplayConfig.kt
Labels: Soon, Backend

#4555 Fix: Sack display not working for rough on 1.21
  src/main/java/at/hannibal2/skyhanni/data/SackApi.kt
Labels: Soon, Bug Fix

#4561 Fix: Tree gift pattern
  src/main/java/at/hannibal2/skyhanni/features/foraging/ForagingTrackerLegacy.kt
Labels: Soon, Bug Fix

#4563 Backend + Fix: Not detecting bogged shard
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/ItemResolutionQuery.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/ItemsJson.kt
Labels: Soon, Bug Fix, Waiting on Dependency PR, Backend

#4553 Fix: Item Renderables Centering 1.21.7
  src/main/java/at/hannibal2/skyhanni/utils/GuiRenderUtils.kt
Labels: Bug Fix

#4559 Fix: Performance of chum bucket hider
  src/main/java/at/hannibal2/skyhanni/features/fishing/ChumBucketHider.kt
Labels: Bug Fix

#4558 Backend: Incremental Preprocessor
  gradle.properties
  root.gradle.kts
Labels: Backend, Fails Multi-Version

#4567 Backend: Bumped Preprocessor Version
  root.gradle.kts
Labels: Backend

#4566 Fix: Pet Drop Rarity with no Magic Find
  src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
Labels: Bug Fix

#4573 Improvement: Add more tab widgets
  src/main/java/at/hannibal2/skyhanni/features/gui/TabWidgetDisplay.kt
Labels: Soon

#4551 Backend: Fix RenderableTestSuit Command
  src/main/java/at/hannibal2/skyhanni/test/renderable/RenderableTestSuite.kt
Labels: Soon, Backend

#4533 Feature: Prevent picking up empty huntraps
  src/main/java/at/hannibal2/skyhanni/config/features/hunting/HuntingConfig.kt
  src/main/java/at/hannibal2/skyhanni/features/inventory/HuntrapMisclickPrevention.kt
Labels: Soon

#4554 Fix: Slayer Tier 5 Mob Detection
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFactories.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
Labels: Bug Fix

#4377 Fix + Backend: NEU JSON + String Cleanup
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/EnoughUpdatesManager.kt
  src/main/java/at/hannibal2/skyhanni/api/enoughupdates/ItemResolutionQuery.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/NeuItemJson.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/NeuPetNumsJson.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/recipe/NeuAbstractRecipe.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/recipe/NeuCraftingRecipeJson.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/recipe/NeuForgeRecipeJson.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/recipe/NeuKatUpgradeRecipeJson.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/recipe/NeuMobDropsRecipeJson.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/recipe/NeuNpcShopRecipeJson.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/recipe/NeuOverrideProvider.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/recipe/NeuRecipeComponent.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/recipe/NeuRecipeType.kt
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/neu/recipe/NeuTradeRecipeJson.kt
  src/main/java/at/hannibal2/skyhanni/data/model/Graph.kt
  src/main/java/at/hannibal2/skyhanni/features/bingo/MinionCraftHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/commands/ViewRecipeCommand.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/composter/ComposterOverlay.kt
  src/main/java/at/hannibal2/skyhanni/features/garden/farming/CropMoneyDisplay.kt
  src/main/java/at/hannibal2/skyhanni/test/DebugCommand.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemNameResolver.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/KSerializable.kt
  src/main/java/at/hannibal2/skyhanni/utils/NeuInternalName.kt
  src/main/java/at/hannibal2/skyhanni/utils/NeuItems.kt
  src/main/java/at/hannibal2/skyhanni/utils/PetUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/PrimitiveRecipe.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/BaseGsonBuilder.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/JsonUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/json/SkyHanniTypeAdapters.kt
Labels: Soon, Bug Fix, Backend

#4584 Backend: Bumped Preprocessor Version
  root.gradle.kts
Labels: Soon, Backend

#4581 Backend: Bumped loom version
  root.gradle.kts
Labels: Soon, Backend

#4587 Fix: Trophy Fish Chance color
  src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
Labels: Bug Fix

#4591 fix: detekt not noticing rules/rule paths with - in their names
  .github/scripts/process-detekt-output.kts
Labels: Bug Fix

#4588 Fix: Tier 5 slayer detection errors
  src/main/java/at/hannibal2/skyhanni/data/jsonobjects/elitedev/EliteItemResourceJson.kt
  src/main/java/at/hannibal2/skyhanni/features/slayer/SlayerType.kt
Labels: Soon, Bug Fix

#4600 Backend: Fix future issues with the graph Deserialization
  src/main/java/at/hannibal2/skyhanni/data/model/Graph.kt
Labels: Soon, Backend

#4607 Backend: graph cleanup
  src/main/java/at/hannibal2/skyhanni/data/IslandGraphs.kt
  src/main/java/at/hannibal2/skyhanni/data/model/Graph.kt
  src/main/java/at/hannibal2/skyhanni/features/event/lobby/waypoints/halloween/HalloweenBasketWaypoints.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/TunnelsMaps.kt
  src/main/java/at/hannibal2/skyhanni/features/nether/MatriarchHelper.kt
  src/main/java/at/hannibal2/skyhanni/features/rift/area/dreadfarm/WoodenButtonsHelper.kt
  src/main/java/at/hannibal2/skyhanni/test/graph/GraphParkour.kt
  src/main/java/at/hannibal2/skyhanni/utils/GraphUtils.kt
  src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
Labels: Soon, Backend

#4594 Fix: Item pickup log numbers being wrong
  src/main/java/at/hannibal2/skyhanni/features/inventory/ItemPickupLog.kt
Labels: Soon, Bug Fix

#4610 Fix: Enchanted Book Detection for Corpses and Excavator
  src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalNucleusApi.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/FossilExcavatorApi.kt
  src/main/java/at/hannibal2/skyhanni/features/mining/glacitemineshaft/CorpseApi.kt
  src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
Labels: Bug Fix

#4616 Backend: Updated Dictionary
  .idea/dictionaries/default_user.xml
Labels: Backend

#4612 Fix: Cancel Vacuum uses when particles are still being received
  src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestParticleWaypoint.kt
Labels: Bug Fix

#4604 Backend: Changed part of the foundation of the Damage Indicator to utilize the Mob Detection
  src/main/java/at/hannibal2/skyhanni/data/mob/IslandExceptions.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/Mob.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFactories.kt
  src/main/java/at/hannibal2/skyhanni/data/mob/MobFilter.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorEntityData.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/DamageIndicatorManager.kt
  src/main/java/at/hannibal2/skyhanni/features/combat/damageindicator/MobFinder.kt
Labels: Soon, Backend
